apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - cloud-init-secret.yaml
  - datavolume-rootdisk-rbd.yaml
  - virtualmachine.yaml
  - service-ssh.yaml
  - openclaw-vm-rbac.yaml
