---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-agents-shell-user
  namespace: keycloak
spec:
  encryptedData:
    AGENTS_SHELL_CHATGPT_PASSWORD: AgBEQs3AUD5HEnOZSvBqKR/WCCvrMut8kv4BzW3JxNLSLbstzydwASDzDPhA1sh1GZp6JvUUkh+l6SbNNpUsDxxS21hwsqXYAWNqGkGXkyZHx76YlUi7ftIYKFdIsrgQPOaEFnUVQv2ffH2d6SErkm3ObQhQQLE3HfVIOf2SRwEbWU4WWbsAo6zoqhzV258bBEpWQzPDgpRUAzHCgbgTrqtG1pskDkydG0uA5wLwSIP67dswWv1ssES5p32O8KdLeBEBmHXfZ2W1+WOQewcRQZSF0+aDqoD8uxqpl9ztwz8OkoDbTPeUR3UzX1wxSsdS9prHLl67BncDYHr303cJOOFeVNEsKCN+OE5lw/ZA4GU5+1dYzsAbmcb7qMX8qzqKBwmcEHrw8ij8EV+tGJUin7lbzOd81ETByJMwm2ZPC4k7XDqXzizH/7rDoRzPj/qpj7t7TVz/cifJTqrsc44EjYE/cOTCXiAGugAo2h7cBUB1HuKzRDox6t0rj4/0NhDbkqZgLpTAEMSXGdmNrfsf2puvsW8k0bDGVDUpsTpc+QrT4MtdFCIfIeUzZckSWJ+RZKICbtoz1CuUP2U527rNMqJydxdOJg5rut8xC0xXYtSgJ5E3g6p5lArnG0y2cU7LnYymiv42VoNp5pxVnWOYgJXDAwsahXhdW2CAuzmoCXre9WQhP4XyewNrWYsF0YbEGGphwtt7Vuie2hLXAcHgj6UfLYcJnPyfugHKWKLV/RdmOaqH1Onh2oIfRf4s
  template:
    metadata:
      name: keycloak-agents-shell-user
      namespace: keycloak
