---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-headlamp-client
  namespace: keycloak
spec:
  encryptedData:
    HEADLAMP_OIDC_CLIENT_ID: AgA5Z+4QvKTR88lSXAhi/fUw4UHOGkdoJgfXCE3xJQIz49CxMVDND3Vrv7FEJWSFY5X0/8Gl1AIZle/Gz5wjRB12VjAAaovxlzQDdBvH+vkPetCuW98IGcwGabmjH48s0DDpitzvC7NQ/tboBUEENvZNifxsmAUx3oB4+2tNjFLmbawjAcNJRAb6ikLZp+eEOPD6n0y9AI2CKu577/NKI0LOfDaAi1f7LTg+4SkWPWq/sGnmwx4pHhX3RX6mOYTBXkdZ/qjmk+nD8ah/dZ4O5qMrysFiazLlrdMYlMelAee0GT/4p3R3FHWU0XczpLEtlYySl29MDDm/Lv21ED4sMknY9f3ZgV04tj7FpZuL04XVbz+sFGCOIB9dg89GRANPAYaPrvT+BLWwcHrlj+IkJry2kPtuKlf+ey4JuDwwVcKN3xvHBbI/f98t+gbmfweEixBeQrh59VMMIM0vGkrwfIu5NzhOdZkeI9AU4v5fqrpL1J/rFq2e+dpdvmKsjQU9asNOqwlMQX99dwmH+8tikJNzBr/oKxmClml8qOWZGy5t35qR9dXFuLKIDIHU+qrz8pPuLat6ORyYPrAo/9yCqYGPvE8wTSm9DykHrwKqRMbXzRaL5p5IYyAC0QrCWOOVAaAX234y1icvlPulAfKPEHCu3dwsOi7MaY4AIZbGSohWOP8DnkiZEG/1033gZcewruj2oLs4KX8FzSAi
    HEADLAMP_OIDC_CLIENT_SECRET: AgBsje/OI2w2DpIL+8Q0JkR881wWI/DtfyJ/81M/S+kxEPwlAEIdv6rp6Lv7uM/OQSl6t0w/1GEUFOh8WzHy5kbhQYoU+Vqj28Y9pt9Nulz9wnbsx51qxYOo+QZSePeAvH4ZK2wpf+JQE9aVsrUo9SK4qTfyJB73umlOqJ4vtJ6xGCqokGcCqWPbXC0bMy4oQkJRECZe+Gx7fq/wzy0lV3XcuXMKAz2kTjVmbu1G4aqqc/4QY5f3L7Gu51pfEraoeuuaFQS2BrE3ox7nZRy55+XjXYMeJ2Vn6e2BJVgTG1gXAuxTnGu0WcWIhWnz6WiQ5dZMgSqd8qPb3+TirmTi/eTllhpeGnNQfGFKjkOAYRwznUkIxAnuWuPjrfS/NSJproqXhPbpXXDdo0SV7aEWa9j1hGhvmjLtDZiLqgqlObmt4ferR73wDBy1t1qOrgedYg0QPc01L5vNqclvPzsauQPokl1JAKUYAWdRn3A0CrktILTRDF+HN1CGcjmdAtx4cMaxpSWgJYm6XerPIO86QP4oTLPIV5bzrbKDexci5RSA/72c+PfOOt3GAQSlKJtETWjJMkearQ6K7zyv09Undu0bEgvuShqmu89MQ1rXxgR+NKOXIwtSPrwKpho+2MLL617wkKTiBBUgWeskpkP0yu4Zopp3NK2cntM5wkch86TnPFXlkcMOjv9f6mvjKMR0FON8R3a+x5+4THKBJmMOAl0icl5LxIURKiJ5ZnJukhxUdQ==
  template:
    metadata:
      name: keycloak-headlamp-client
      namespace: keycloak
