apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: keycloak-db-major-upgrade
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-db
    app.kubernetes.io/component: postgres-upgrade-backup
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  cluster:
    name: keycloak-db
  method: volumeSnapshot
  online: false
  target: primary
