apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: keycloak-server-26-7-3
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  cluster:
    name: keycloak-db
  method: volumeSnapshot
  online: true
  target: prefer-standby
