apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-cluster.yaml
  - objectbucketclaim.yaml
  - synthesis-env-sealedsecret.yaml
  - deployment.yaml
  - service.yaml
  - tailscale-service.yaml
  - networkpolicy.yaml
  - agents-domain
images:
  - name: registry.ide-newton.ts.net/lab/synthesis
    digest: sha256:84be557dee9a030423a2527a593d6016f7156ffe88f7bf7ffbb7ce817f30d895
    newName: registry.ide-newton.ts.net/lab/synthesis
