apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-cluster.yaml
  - objectbucketclaim.yaml
  - synthesis-env-sealedsecret.yaml
  - deployment.yaml
  - service.yaml
  - tailscale-service.yaml
  - networkpolicy.yaml
  - agents-domain
images:
  - name: registry.ide-newton.ts.net/lab/synthesis
    digest: sha256:6e51fddbb23f47933b16f84ee6d818a150395a839ff76810a2980472178e9d32
    newName: registry.ide-newton.ts.net/lab/synthesis
