apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-upgrade-backup.yaml
- postgres-cluster.yaml
- objectbucketclaim.yaml
- synthesis-env-sealedsecret.yaml
- deployment.yaml
- service.yaml
- tailscale-service.yaml
- networkpolicy.yaml
- agents-domain
images:
- name: registry.ide-newton.ts.net/lab/synthesis
  digest: sha256:00f1173a88c58653cf83bbcee2c53c2ae8f5964b307c4244c03337db8a71b6fc
