apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: synthesis-db
  namespace: synthesis
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: rook-ceph-block
    size: 5Gi
  bootstrap:
    initdb:
      database: synthesis
      owner: synthesis
      encoding: "UTF8"
      dataChecksums: true
  inheritedMetadata:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "pgadmin"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "pgadmin"
  monitoring:
    enablePodMonitor: true
# CNPG emits application credentials in the secret `synthesis-db-app`
