apiVersion: v2
name: tigresse
description: Production TigerBeetle Kubernetes operator
type: application
version: 0.1.6
appVersion: v0.1.6
home: https://github.com/proompteng/tigresse
sources:
  - https://github.com/proompteng/tigresse
maintainers:
  - name: proompteng
