replicaCount: 1

image:
  repository: ghcr.io/proompteng/tigresse
  tag: "v0.1.3"
  digest: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

metrics:
  bindAddress: ":8080"

healthProbe:
  bindAddress: ":8081"

leaderElection:
  enabled: true
