apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tengri-bff
  namespace: proompteng
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-infra
  target:
    name: tengri-bff
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tengri-runtime/BETTER_AUTH_SECRET
        metadataPolicy: None
        nullBytePolicy: Fail
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tengri-runtime/GITHUB_CLIENT_ID
        metadataPolicy: None
        nullBytePolicy: Fail
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tengri-runtime/GITHUB_CLIENT_SECRET
        metadataPolicy: None
        nullBytePolicy: Fail
    - secretKey: TENGRI_INTERNAL_HMAC_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tengri-runtime/TENGRI_INTERNAL_HMAC_SECRET
        metadataPolicy: None
        nullBytePolicy: Fail
