apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-secret.yaml
- network-policy.yaml
- deployment.yaml
- service.yaml
- ingressroute.yaml
images:
- name: registry.ide-newton.ts.net/lab/proompteng
  digest: sha256:c804aba89af2385c021429e315d2c4e8788e167bc87d211dbcc5ec5168c3ba7e
  newName: registry.ide-newton.ts.net/lab/proompteng
