apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealed-secret.yaml
- network-policy.yaml
- deployment.yaml
- service.yaml
- ingressroute.yaml
images:
- name: registry.ide-newton.ts.net/lab/proompteng
  digest: sha256:8299d046553d3d8e86ae359581ee0c8f2a1b05e6b8d36930f0a5112967521328
