apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealed-secret.yaml
- network-policy.yaml
- deployment.yaml
- service.yaml
- ingressroute.yaml
images:
- name: registry.ide-newton.ts.net/lab/proompteng
  digest: sha256:78e0a7f436c8100563785f2c5e94bef9bb1d411697b5de71456ed02e301feaf9
