apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-router
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-router-policy-preflight
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
automountServiceAccountToken: true
