apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-object-user-objectstore-loki
  namespace: rook-ceph
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "observability"
type: kubernetes.io/rook
