from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import hashlib
import json
import re
import time
from datetime import datetime, timezone
from http.client import HTTPConnection, HTTPSConnection
from pathlib import Path
from typing import Any, Literal, Mapping, Sequence, cast
from urllib.parse import quote, urlencode, unquote, urlsplit
from sqlalchemy import select
from sqlalchemy.orm import Session
from ....config import settings
from ....models import LLMDSPyWorkflowArtifact, coerce_json_payload
from .hashing import hash_payload
from .schemas import (
    DSPyArtifactBundle,
    DSPyCompileResult,
    DSPyEvalReport,
    DSPyPromotionRecord,
)

DSPyWorkflowLane: Any
DSPyWorkflowExecutionMode: Any
_DEFAULT_DSPY_AGENT_NAME: Any
_IMPLEMENTATION_SPEC_BY_LANE: dict[DSPyWorkflowLane, str]
_TERMINAL_PHASES: Any
_K8S_LABEL_VALUE_MAX_LENGTH: Any
_IDEMPOTENCY_HASH_HEX_LENGTH: Any
_PROMOTION_MIN_SCHEMA_VALID_RATE: Any
_PROMOTION_MAX_FALLBACK_RATE: Any
_PROMOTION_EVAL_REPORT_MAX_AGE_SECONDS: Any
_PROMOTION_EVIDENCE_OVERRIDE_KEYS: Any

def _normalize_local_path(*args: Any, **kwargs: Any) -> Any: ...
def _load_local_artifact_payload(*args: Any, **kwargs: Any) -> Any: ...
def _parse_iso_datetime(*args: Any, **kwargs: Any) -> Any: ...
def resolve_default_dspy_universe_ref(*args: Any, **kwargs: Any) -> Any: ...
def build_compile_result(*args: Any, **kwargs: Any) -> Any: ...
def build_eval_report(*args: Any, **kwargs: Any) -> Any: ...
def build_promotion_record(*args: Any, **kwargs: Any) -> Any: ...
def bundle_artifacts(*args: Any, **kwargs: Any) -> Any: ...
def write_artifact_bundle(*args: Any, **kwargs: Any) -> Any: ...
def upsert_workflow_artifact_record(*args: Any, **kwargs: Any) -> Any: ...
def build_dspy_agentrun_payload(*args: Any, **kwargs: Any) -> Any: ...
def _sanitize_idempotency_key(*args: Any, **kwargs: Any) -> Any: ...
def submit_agents_agentrun(*args: Any, **kwargs: Any) -> Any: ...
def get_agents_agentrun(*args: Any, **kwargs: Any) -> Any: ...
def wait_for_agents_agentrun_terminal_status(*args: Any, **kwargs: Any) -> Any: ...
def _extract_submitted_agentrun_id(*args: Any, **kwargs: Any) -> Any: ...
def _lane_overrides_with_defaults(*args: Any, **kwargs: Any) -> Any: ...
def _to_float(*args: Any, **kwargs: Any) -> Any: ...
def _to_bool(*args: Any, **kwargs: Any) -> Any: ...
def _json_copy(*args: Any, **kwargs: Any) -> Any: ...
def _load_eval_gate_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_promotion_gate_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def _load_eval_snapshot_for_promotion(*args: Any, **kwargs: Any) -> Any: ...
def _promotion_gate_failures(*args: Any, **kwargs: Any) -> Any: ...
def orchestrate_dspy_agentrun_workflow(*args: Any, **kwargs: Any) -> Any: ...
def _execute_local_dspy_lane(*args: Any, **kwargs: Any) -> Any: ...
def _load_compile_result_from_artifact_root(*args: Any, **kwargs: Any) -> Any: ...
def _load_eval_report_from_ref(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_optional_string(*args: Any, **kwargs: Any) -> Any: ...
def _coerce_optional_float(*args: Any, **kwargs: Any) -> Any: ...
def _coerce_optional_int(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_string_parameter(*args: Any, **kwargs: Any) -> Any: ...
def _http_json_request(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
