apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - postgres-cluster.yaml
  - secret.yaml
images:
  - name: registry.ide-newton.ts.net/lab/app
    digest: sha256:5be62419bcd1414551198b4de234408d0cfd231f46775d6b4b2fcda94683cd0a
    newName: registry.ide-newton.ts.net/lab/app
