apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-upgrade-backup.yaml
- deployment.yaml
- service.yaml
- ingressroute.yaml
- postgres-cluster.yaml
- secret.yaml
images:
- name: registry.ide-newton.ts.net/lab/app
  digest: sha256:73621d8c6e34a9c554c1085b55d4affd54f3f18158d3671591fda1173da7621f
