apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-upgrade-backup.yaml
- deployment.yaml
- service.yaml
- ingressroute.yaml
- postgres-cluster.yaml
- secret.yaml
images:
- name: registry.ide-newton.ts.net/lab/app
  digest: sha256:8a1d6ef4a3945e50b0b1593553eebc244d87a77f9a13231c71807f84be1a4833
