apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-cephfs-fuse-bench
  namespace: rook-ceph-benchmarks
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs-fuse
