image:
  repository: registry.ide-newton.ts.net/lab/tigresse
  tag: v0.1.7
  digest: sha256:b04308528a46291e2c65562d04c2ac7644c4e7f25f2c247dae282b70f8856e2c
  pullPolicy: IfNotPresent

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  seccompProfile:
    type: Unconfined
