image:
  repository: registry.ide-newton.ts.net/lab/tigresse
  tag: v0.1.5
  digest: sha256:b73cc34f3f82b21a28eeea6b480a634bdbe93ac91d1a5710d082d33a211521eb
  pullPolicy: IfNotPresent

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  seccompProfile:
    type: Unconfined
