apiVersion: apps/v1
kind: Deployment
metadata:
  name: torghut-notebooks-proxy
spec:
  template:
    spec:
      containers:
        - name: chp
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: torghut-notebook-hub
                  key: proxy-token
