---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: torghut-notebook-hub
  namespace: torghut
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  encryptedData:
    crypt-key: AgBT3SF2eA12IkV/2ljFhmtnbps791tuWNWakfIb8+ad1ogRCyWduJfhcFcwB7GPqmtAoVD35obR15IMGCINRhjfYcmsD5khWj3vYA7zUIj2u/jhflfWdNKcaKlfOW0Ullz7vP1jGOqLTScnS22naW24LHo4uhqEKVw0oUDsKmEYWlNBg+Weqj26VDzoIbjjzLd8KtsdqMeDLnlVSlAHtlPuLfy5AB8rVqzInEENa/aWlXXRuuANmskO8kNyp53nvXwiHc7n6AsUjGmyJB2rplkGRRKMYU+tRnU8NRSOFM7TuGzvezZqVdUVj20s6OhgHfhBS9uRbox9lFEKi9lXEk3VP+WeMfZacdl3bPNdPjihzaNG60C5AMXufMYCj0Ev6bCp7dvjU+s3LiTKybougH6eI1F0q70KJrMMZ1UodyaHB22bLv1damVHAQ0n+3z0kzgsuOqtxbMwtwqh7L0m+HnXOlyottL9cb9lVkRn/3PiKROPFFqDdez77uhvK5up2hRERofDvbz2qGvF/x14R+J357kVC5Y9Y9qiwba5zriBtQkua6zk9xLg6knS53VZTicnNwGHca/zHtTi2jZwTFETZBgaHu749Lz0ENhLTXCr8BzS/aTeEOLeFfy5rEURpoUv9lQgnR8EgAPHuvbgIqmjRGisWg7YzRuS0CgUQoPSkQTg1IjxHODMw2m5SPck1v1XBkK1+AkcHT9K5le7otPa8llPJD8kH+QM4pui7h22Un5rcum24kneo+37OhX7wLCC/t4vyBDyk7LT/ZcKB2Feqw==
    cookie-secret: AgBuMQY7FFt0Jv47yxRb/dIYVd+1fOXYo1kJ3Gy/5ZL8mDLH/kdj76EuHeAGNTB/1YcD96fbVAgTU+f1m9TwuSPIeQzhOdDZEnA2pE1lzM6PB+/4iTGYRyale6WKVheuqYAqWETnBsGWL/HhFhXZaX4iyhSx+smQQiveXwSQ8IjT9JXcOZraGFdxsOZAwkMMn/XDcueu2J1gKRkGjIomzm+jRYX/wJ6BJMIIw/djnAa2Xh+uYF4fhdO/uszS1CZkj5KCcUdg62ahTZ6hL8DrQ4fK9HBSHuJ4ptPdU9DIukpt5aT4yZLtjbSF/R4IqFiLO+RRBG0JbZt5qgGVj11N9KEEpIML/RdyZS+hi1XVZiZ+r/FJhwiraEoIcsv2Oo/4dEqCzcGpKFPCQxrKA23oHPqDNvD1fyRBFHuGnQyaQHnfTi3VSTBHusDyzjgNBXtC869w2CBXC20xkL0j3+V0Pjm8Dv/piz2TEdJs6gNZkJw821otKTF29hMpGILLcLjwugy41KLVwPaoXVnifWBMMLjGKVB9ERipjJI6xxfdX2xG+AGf+EnKbFBBaQ1enGlnep925hl+grMRxoiFdxo3R46douQGLGlJNHFzvFwc5QtHsWxf/rt9KWY2WW5fbY5soXPTOksEe1Vwg8PdZFeCN7YcYjFgFY96+6DMLEhrgDMK26K2iMVRMWBEi7GoZe0CwL+3UkRVdrJUZF2rJp5wMV+1BNjHg1UhQ+QxmkcScfB128qQ/uJ3N7Fn18oJBDZsjmNJR7tReWd30J3qLtgANmUi
    proxy-token: AgAwhc3IgdwtflJngiyfiLZVYSW3n6qcPLwGe/jojP/AAN2xpC8Wg+ax7AwCN3n0DL0NNRO9yEx5FAegfU+R6EnSP9bMnKcSknOy1Xl3ymEr7mChfEmCZDpfgMUF4UFt2zROP+fnsmdq/2Rd1nmDV7iTmrknaIamn7iuJsgFcZ0P8HDY28k6hgeR4E6iUpZm6iHkRw0tXVIYRzdi51IvMdo4oPCMApPcpQUrSaWH1ueXtBQNSgY0iDUsd8BIiD5oux1vnKPQAYFfRfR7qQ/4pjZcRfU2C2mPVGbJKmy1NIs00igzLwLu8HBdHRl3v6zn8qRKKtn2bZ562nCF18VH4KhpditkU8Kfj9Fm76ty+1Au/rJX5nV5VhaptkKTjQbNzgiojfAYMOLRAbZhIEYk7loBCSr2dBHIBcIs43g/MWDCsksspjKAzh4xTeGorXovpWUbfFEafY7Qk0uVXeqt1JvpouKixAGQaQwkx9d5YpqWzI83OsDrcv9uaf5H3B3oqlYSglkUqkX21UyEPVj2SRxY3XFFcI6MJFPAgXyEK37pLnjn5CtsCZtVo+iE7WAsv6IaG6XYG0oxgYz/s6gU3ZyQZ/c5wCz0WdIM9JEhXfXVhIVimIm/qAVeWRTEqjHDPTZcVn/qm5mt0UG+IHDAhaKhcNiCm4A9+HElvsQRkMbKljH2vHuIoI9/r8qNNzxvk1nIubZZk6ji4UfMbHq78xRCodEzVap8S46d0YkYfJI/MH0J3skU7CGyCcd3EVsQGbbryw+btFEOt052W4FMuxxM
  template:
    metadata:
      name: torghut-notebook-hub
      namespace: torghut
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: torghut-notebook-postgres
  namespace: torghut
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  encryptedData:
    password: AgBIBeuf5j7syc1r+oUocjAYIVaTyMU653TbtkDM+Bv6e48CYcvG0521iK1zQv58s9/I5jgEuk/pwyi1ZZ9kPesh6fnDX5IuP9UDVExPF7AHMkYReyocELh1PTgmpmlSe4HTsuICQX6Gj5WpV0skIkYC5fNgjpARxlcrMqaAzxiFd7T/m2hLZMrfX7ikYlYoivqAYmwWmdmAPwTsfKhLye0YhX41uheSJ0mliQdbEhPd2en0lLmJYnU/IrtGi3P6de87PuFkyoOP1N8u57OSIranwXmK/OwMOiq5KUbWGrkX+idy4IO3AstGZXLOl4sUYecKA6Z0vw6v8ETzFwa4kFxwvD0RD6ANQ6dZSq7m+icKG1vDEqDq6YJRBRuVoOHQhY6PiHFgYFGJ+3IFagnapDjLCcktCEPGbhBvM0JEwShktTsfuCAFLazG53TF2bBTxsfRUwaFyjTcYyIS5BlE1tX+9JSVgkvRx6+Fyq4lWeJJXR8m+92/JwaATyZhzMZ5IODnsbEOsX8knq2WbJJzWv26HA4dcdl5VQnPCUfyl2NHU0RZM7KISZrvI4xfGFWDpCcQKVSyslR9zBLKOpAiECm+zMJa0i//q3+2NnWjFBKgDTdxIZTcvqQF7YD7b0EMl1bitmG9QNNOMDHJuQnGN4ync+D5cZ6KUiv4phnnWfYJgfBhGKlkrkgBqAdBwzXbvRlBT1qjAETu4fPmJANZ0++Qm9ueanApMO47uhUh9u3+QgHQD+cHlsgG7oF8tSWerAQUyE1+oqgRd+MU7J0tWf2p
    username: AgCw2b6Xk+VK6Nhq3BYXQJm8fHFTXBKCQIXhDjmxW5Kc0pnmlRztuCnXofepNoLvMnciqNI0ozLup2kG2xovqd0FY7kWA7BaRbKwZKImL01JGg7rRVsAVlo9fO1Xq4uYRq/wc+vqXhI9PjlO0nZ1tww7Dvv7HrLXDLjmiUVnejzAWTtVU+nLhlpFAWvOH7ui8Lh5gCZcHs4ntNXFuXpdLw3myQ3BMJvCXPKG9Nqk6E2EAsS78xJ9ahR9vQkh7fGGrwkzoWiu7Zu3lec7UsTaQ5J4Hq9fEZUOpPBXMh236EzLSXUsL0Jf+TZf+azGvBlexoiGMYjiYHjyfUSNM6E5RsWustziPlofGhvEUL7FNoeKfnxf0jtSbXmqyY+6Sa3cXhHJs5HJIwuJnU9sGaB2AOZEUrojp85+FonrdO/evS/rYmwGN9boGccBDcqexOUw8oSjHb4E4PnlG+OsWoctqkLe/6QXHRBy88JJeyG28TsG0gwVkWHkylvAbQqaGrPOCd91xWE92vt/bYWL2WbQO7C0a9i0rIv//+/cjrEC2fOm1g77TCG090ohjxQGOaxkAAHADYX4TVCBIF1MURywyFZq/XLc781Z3hv1TSO45+twtDfV8tW1SAQCj95LEmStCrXhtmYgrpPNrb7hqAz4zkcgM4B7Ites6fisdV2Zi59rEFEOrNrmPRtZISlfeZ37YjUD/WPKkUcf7bEWJNnYxB39
  template:
    metadata:
      name: torghut-notebook-postgres
      namespace: torghut
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: torghut-notebook-clickhouse
  namespace: torghut
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  encryptedData:
    password: AgCOoulj+2DAvFzhtw9KLcTgZ3MpPeNr0IysIZ4z5lD2MM5rBytUpjiyWLaCD7gxZRAMS+T+T1RECAtoyVuvc0ssVVpYGWJcr/fqQUGtDXtHKRWYVZUhCNrRAOVQhQ6zao75F0++LmwAkUuEzsoQ2Qzz6+eK9JVCVUdZkwpNIcfXj4sG76w7PwP1bh8H1gs2iLVXWOL2s5b505zwMTfSaN0ianOKdXFdB/iZhhCXf8ex+0VuAlrfvlUH6/bnYTSdtIHhRpHRcXXZ9FGbnY0WSjs8wRAeLedWqLkk1Wwhw9OAE92lOeRqqrETiAnDICxiTBiJhmX5i2raCb7VBgAEA36+BIUB1I7xd4SsfYLiqIOXr8Q+27a7YEMbFnpBcqkVXcOPHLCFnln26J2C4Ghp1b33qtAJaLWlAcVu7jS2umkFMHXhMRQGCdLGdiX0u4a8zmKXP9JRCa2sxQmoYjT7ZUrA6KEj4dhKNKBJC9CjGdNep+XMdXlMQV7/r8IoOQqu4kwTM85V8M58tCYCF7OqSyySBpnJi1AtIEgI3kDKVP189UuSnseLPdmcArHKrJwk8JZ5c0HeiK02nBrJ6M135Ho1/TxkjywoBrawJUCYZ8vn62sGSSff6KqOZ58+1WajyNvNjzIaImc1xmLaa8g5JFJXc4gkPFOJpGwjquh3p9sPsIizJE+hASb+T0WvIgush+PTDFACcRHvT4LDVyR1xJj6cE+DBko8IYt7hgXN9o3+MpJYEiGsC22hUXHHMT+EqxZ6HUZB2e3e7N5u+4nTmeZW
  template:
    metadata:
      name: torghut-notebook-clickhouse
      namespace: torghut
