---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: codex-auth
  namespace: agents
spec:
  encryptedData:
    auth.json: AgCCBbRZl3S1ATV41x3Gh8P2+nrxtxRdOE/UiiYxI0XLDfh2B6/UIUdpeYLEQmzeDHeSySOvA1oDEXZOo6ZBrI0Qcd9jEgz0kVKsQDSrqZbVD1cFXO62Px4hJftgJAFk4opbAGP2xqatG9WHso2liROVIijRPqRcvpzfZlkmxSnkPNpS7PdAn/6eNonV6C4P2Ws0YzhR+JGvn7OJNFL8VCQ+5jubFsTLs0tB/auSKsVn7YUrcBMIdiEIbnciP7mSU8Np6r2B8IE6RK7CbLg2hMU4+SJLzNnMKgDItVsatCwsbrEJFVG1dCjhCALOjNmFTiAQZu1N7/gPUAIq0h3UJklIdbb2Nnut2H5KErW/ZJfkSS0tMZSLiTx8JWWDFlj7EP4fQ7G/1GXxItcAZhZKwlRbbUY+K7nwNrOcZUbl9dfh12mK/xee3PtmV0JDCw/1HoJiDA6yoGgEEr8Fi2w0TBzYCfIuR7xxZI5o++5R6WP+9wbB/lmACYWvcW0aWmTgCGSek0tVkLMA1mZ61yN+ZX32Ht33a9rr5NmuZTo5jTdFjiuDU5bx3hyoe4YJcx2PHX/E26Eq21yFA227MDwBFy8BSp73OckGfncIJr6EPCLw5VzGa1CL9qYZ62ksjE5MQrW2MNHwTXexC5JY+trqjVKiacgLukVgg4gkQydYCvpb+wghbKrCW6EBNiJU7UzFWOvgQlcCwqU1vVl6x6cYam6fmb5pNU5HREkidQNXOdFl4c9lnGTuUNmU3dd+0W9EcJKZNYgGwsGBKd7heKCjgE17cuhqcAGRfwXauF7sHXHPjf7Yh2oazIbcaOZ5Z5wASzu4tlhTj/0/HbS+5u+kXtezcRjDa91+m2BEJHEmESBJQw6PaaTATMIJ9EchVkriNgjblCn3AG++wrOXMVLn3geRjrgQncUczNW6X/DnW01qtI9/S8fhjXmpZvrBIiy2rgAWWqHykMr1BKMfvL8KYjzMLqziNmkzyTA=
  template:
    metadata:
      name: codex-auth
      namespace: agents
