---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hf-router-token
  namespace: agents
spec:
  encryptedData:
    HF_TOKEN: AgBHcFzQwM7JkxWgsjSP7AmEGDe28116HpQ1njgAuFdq9A3JSdg7/EB5MKLWkKarcpJoemmArIgHUXbbSfNm5yFzlJoSQpIM/VhBPfDAmDBxXAw6E7xmq6ndGKgCQ6eCsc29FR3+n/XbK5zDl7Hh3KaLVUHQ06fS4QSpo9K41lLAmFOgDyr/jDgoYWDthQixBR6T0/FaRJOmQb24EYsont+lO2ZwOBwPleiMP+IuU5Hzfnq5fQ7lK9XtteEwdMnqAQrbro9+wqjQF5PC6C3zixyE8yNs0qIdQKDNLD8tiyUvSk1ZQ3RodZ5mPQdv597c3tJwVDZXp8pCEPOzebstD+QiL0wIoaHrtGGurLR6cxMXQw6xm4NmzG+SyEpoEof/ac7Mcaz5ZmuWuNBHbUaABLsIj7Ijl1fQOr2on8FN6J8L07T9KiJoTXyqz74prDQnkf1TEUp+xV+q/bw8PaNS6nJhcgSUzAqgJ+jjXgsD3iO8lPew4whveB7Be1k1fQtbNTI805RDx6W4DZNHJOBks2llYO0MADjziNjk/pXAyfSArbji0Th4DSwn7NNrIWiXbXH8hsmLDGsewgMK9xKhNzeSzUIAyy89F7UtcLH6Ts1SWjiWHfRF3V8ytv9lmxVPe3C3uJBMxB3GKoDPJN+jFweTNLON3lSWng5a+j2b4qu2nY8iL3eVXLu0PoDGpsxmGb9HMok5hmHecgulhtma0hEMgHhOMxJ8EXYyPACWtikB90OHbkjQ
  template:
    metadata:
      name: hf-router-token
      namespace: agents
