---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: codex-auth-symphony-jangar
  namespace: jangar
spec:
  encryptedData:
    auth.json: AgCqazKbK8sa7w35HsWOtbm5SlG8v2bTTXuenGGa2L8KPke1MBIe2xQ/rNaN3tXty2EW0apnwZ0yrkc1VWqH9SKDspfSoJd35BW7aKDuw4/qqfilp5ZHu8HR+tloSyQcw+4+RBdgdyzh3y+8O6So2IQKP3PmAiiTBeAD9Kb/fOr2BbbBEjuDw9ytoAeqYmvtlEfrOefdU0ioPV68TFhP7reNPsxn5dfKThoyljrNgW7G0pZcao8+NSjsEt4+Y5RFowf7i0EYl3n4oy2g9tpb7nLvaVqyzzVOI9DUAvMpRGkAWqmJOkwfjbJ6jVJwpf7PXghSLyRNlws/pmHcrXSInvu7MXx6u+pkr5plmHQjHHe1AvJCwMqX3x1sBS83Wn/P0hTPKvsSt8WsDQhnQ6ITlS2riubGTwnHthn9oNJVHNnH1zUxGrBuv1DZXc381Droq63ZY80mbAScmF4dsqHKFHRMl2LqvygD1KxVpUJ6wX3DCVDZSuM6KQsPDCD7ROCt0bO/ZJ+KcSvfjhjuXdbkZKOP4nnMFYgAdek4U04tA8PfZ64qg3if0IrN7++3GjntJ4fP6ZcedYk73zhCbZebGy47cZ4UfoiFYnTvYtNoggPEu+MwLVTejMt2XNM+NpuNLJx5CYpdohdWFLYGqaG8yO1sijUFldnehqzZ9+lABc8nPTEbt2K3A1AqTEqcpnSbULQGWnomoeoF46fNX2dH0Dy4iPPr+qJGjuf3dNBbMzDwBA5BTqwsB4MX+znM5lz7TOIipF/cgWXpQPOBCUzPb8Wz3/TLiFmfbcHt1H0w16g6yAczrh7lyw4rMjHk8rcOlxR5rrcVL/110Zvo7nHsnpmCNwoNhGNCtuPeuoiyik9Ra5mekJ/wy74PPt8+JtHB/Cqy3SGTVtFsoDTxtRFP/5Hk3BphgwRTO/I91YlbS//6KJJVEn2IdEDEHFOxkbCpxoCNb9L/v/vWVqAVxsGOy9yN6+9yf87t+g==
  template:
    metadata:
      name: codex-auth-symphony-jangar
      namespace: jangar
