apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
nameSuffix: -jangar
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: symphony-jangar
      app.kubernetes.io/part-of: lab
configMapGenerator:
  - name: symphony-workflow
    files:
      - WORKFLOW.md
resources:
  - ../symphony-base
  - codex-auth-sealedsecret.yaml
  - linear-api-key-sealedsecret.yaml
  - target-argocd-role.yaml
  - target-argocd-rolebinding.yaml
patches:
  - path: deployment.patch.yaml
images:
  - name: registry.ide-newton.ts.net/lab/symphony
    newName: registry.ide-newton.ts.net/lab/symphony
    newTag: "f852e406"
    digest: sha256:6920ad38219eefd6d3852de078694840fbeb70d3153e9888edf2da9035f52737
