apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
nameSuffix: -jangar
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: symphony-jangar
      app.kubernetes.io/part-of: lab
configMapGenerator:
  - name: symphony-workflow
    files:
      - WORKFLOW.md
resources:
  - ../symphony-base
  - linear-api-key-sealedsecret.yaml
  - target-argocd-role.yaml
  - target-argocd-rolebinding.yaml
patches:
  - path: deployment.patch.yaml
images:
  - name: registry.ide-newton.ts.net/lab/symphony
    newName: registry.ide-newton.ts.net/lab/symphony
    newTag: kargo-sha-621002d9c9aba4548db0af5f469e3fed67170c7d
    digest: sha256:48c34dda24290f6daf7e8f01de39539faf0c1562946ecc7c0042401e0254cd9c
