apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
nameSuffix: -jangar
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: symphony-jangar
      app.kubernetes.io/part-of: lab
configMapGenerator:
  - name: symphony-workflow
    files:
      - WORKFLOW.md
resources:
  - ../symphony-base
  - linear-api-key-sealedsecret.yaml
  - target-argocd-role.yaml
  - target-argocd-rolebinding.yaml
patches:
  - path: deployment.patch.yaml
images:
  - name: registry.ide-newton.ts.net/lab/symphony
    newName: registry.ide-newton.ts.net/lab/symphony
    newTag: kargo-sha-8e50a2870716c8db51e3c8cb08b03679000ace9a
    digest: sha256:b6693cbee7daf09bb80a4f9f25a837a00d5a42e7b33efa30b1f52501598fb389
