---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: symphony-linear-api-key
  namespace: jangar
spec:
  encryptedData:
    LINEAR_API_KEY: AgBy0Cwxi02Go33AB72VlDcYJ4Tce4n/h/wVzhsZpuqigeZpLAFOzHlBLifQbIvJu9hPWrz2mVGRse/26NUU9bMHO+uAJVY6ioJpB18sydTxJaLV88ItcwWXlBpo20z+5eRRSNPK+yis9VrPGIjyxjJHYZAc3MUEaymuZmh0iPsIYCl979kMkYNGYnzuI+r5HKXOOgKIXuJYIsQvA+cqVTXSqT8DpcE01vXaz6XsgstNh4BA738IxJscHlhck/VZiEjd/wsP1pvjd6RzfPfKewa+JwTeQ0KoIm9LUG//tqZtrRvMsuI/HMVLmKZIOplIGr2gq9KJxwM5skV8zKCb842+4lcppHB0+NNt80zOCGXlZAp42Pp2mPYLz/8Uto2X4MKPPvpMjg57srfdye9snWwDHRCt2CIeUW2iWBRmLJgeVyn7QGjhRArXrpwdkU1Y04GiHTf0WyavnuNxLI8U1JRVQp2dfMVLeo81IlbPI5vTH70zFSJdBngMw1M6Q3y7gBHSNupvCPp8fO0dIkng6UeuD63BwahfuAiu1RV0JPdNzGxWfSUitX70wQHT/2kwty1wJeiytXtS6bku9Ci3uVQVuSGRTmbYTHADKqinbgD37RPIIadE1bmS+/QWyFXmkxdYRsIrvvIgy4C6G9ddCuN0d3+k0lcUGUuOi8RRSwSrSqj4y/rY89+VSt1lE/d2V30lQoCAXO6H9U+4WqUYB32C1pI8vYbl7urxiPwP0KN7R1YW3DtXC2s0eRw1IBS/lls=
  template:
    metadata:
      name: symphony-linear-api-key-jangar
      namespace: jangar
