apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: observability-alertmanager-email
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-infra
  target:
    name: observability-alertmanager-email
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: smtp-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: resend/password
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: smtp-from
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: resend/from
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: email-to
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: resend/to
        metadataPolicy: None
        nullBytePolicy: Ignore
