apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: observability-alertmanager-email
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-infra
  target:
    name: observability-alertmanager-email
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        smtp-password: '{{ .smtp_password }}'
        smtp-from: '{{ .smtp_from }}'
        email-to: '{{ .email_to }}'
        alertmanager_fallback_config.yaml: |
          global:
            resolve_timeout: 5m
            smtp_smarthost: smtp.resend.com:587
            smtp_from: "{{ .smtp_from }}"
            smtp_auth_username: resend
            smtp_auth_password_file: /configs/smtp-password
            smtp_require_tls: true
          route:
            receiver: default-receiver
            group_by: [alertname, namespace, service, severity]
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 4h
            routes:
              - receiver: critical-email
                matchers:
                  - severity = "critical"
                  - notify = "email"
                group_wait: 10s
                group_interval: 2m
                repeat_interval: 1h
                continue: false
          receivers:
            - name: default-receiver
            - name: critical-email
              email_configs:
                - to: "{{ .email_to }}"
                  send_resolved: true
                  headers:
                    subject: '[lab] {{ "{{" }} .CommonLabels.alertname {{ "}}" }}'
  data:
    - secretKey: smtp_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: resend/password
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: smtp_from
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: resend/from
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: email_to
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: resend/to
        metadataPolicy: None
        nullBytePolicy: Ignore
