// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proompteng/facteur/v1/contract.proto

package facteurpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	InteractionId string                 `protobuf:"bytes,2,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	CommandId     string                 `protobuf:"bytes,5,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Version       uint32                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Token         string                 `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	Options       map[string]string      `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GuildId       string                 `protobuf:"bytes,9,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,10,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	User          *DiscordUser           `protobuf:"bytes,11,opt,name=user,proto3" json:"user,omitempty"`
	Member        *DiscordMember         `protobuf:"bytes,12,opt,name=member,proto3" json:"member,omitempty"`
	Locale        string                 `protobuf:"bytes,13,opt,name=locale,proto3" json:"locale,omitempty"`
	GuildLocale   string                 `protobuf:"bytes,14,opt,name=guild_locale,json=guildLocale,proto3" json:"guild_locale,omitempty"`
	Response      *Response              `protobuf:"bytes,15,opt,name=response,proto3" json:"response,omitempty"`
	Timestamp     string                 `protobuf:"bytes,16,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CorrelationId string                 `protobuf:"bytes,17,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,18,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEvent) Reset() {
	*x = CommandEvent{}
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent) ProtoMessage() {}

func (x *CommandEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent.ProtoReflect.Descriptor instead.
func (*CommandEvent) Descriptor() ([]byte, []int) {
	return file_proompteng_facteur_v1_contract_proto_rawDescGZIP(), []int{0}
}

func (x *CommandEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CommandEvent) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *CommandEvent) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CommandEvent) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandEvent) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandEvent) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CommandEvent) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CommandEvent) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CommandEvent) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *CommandEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CommandEvent) GetUser() *DiscordUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CommandEvent) GetMember() *DiscordMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *CommandEvent) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *CommandEvent) GetGuildLocale() string {
	if x != nil {
		return x.GuildLocale
	}
	return ""
}

func (x *CommandEvent) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CommandEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *CommandEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommandEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type DiscordUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	GlobalName    string                 `protobuf:"bytes,3,opt,name=global_name,json=globalName,proto3" json:"global_name,omitempty"`
	Discriminator string                 `protobuf:"bytes,4,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordUser) Reset() {
	*x = DiscordUser{}
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordUser) ProtoMessage() {}

func (x *DiscordUser) ProtoReflect() protoreflect.Message {
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordUser.ProtoReflect.Descriptor instead.
func (*DiscordUser) Descriptor() ([]byte, []int) {
	return file_proompteng_facteur_v1_contract_proto_rawDescGZIP(), []int{1}
}

func (x *DiscordUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiscordUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DiscordUser) GetGlobalName() string {
	if x != nil {
		return x.GlobalName
	}
	return ""
}

func (x *DiscordUser) GetDiscriminator() string {
	if x != nil {
		return x.Discriminator
	}
	return ""
}

type DiscordMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordMember) Reset() {
	*x = DiscordMember{}
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordMember) ProtoMessage() {}

func (x *DiscordMember) ProtoReflect() protoreflect.Message {
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordMember.ProtoReflect.Descriptor instead.
func (*DiscordMember) Descriptor() ([]byte, []int) {
	return file_proompteng_facteur_v1_contract_proto_rawDescGZIP(), []int{2}
}

func (x *DiscordMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiscordMember) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Flags         *uint32                `protobuf:"varint,2,opt,name=flags,proto3,oneof" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proompteng_facteur_v1_contract_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Response) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

type DispatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResult) Reset() {
	*x = DispatchResult{}
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResult) ProtoMessage() {}

func (x *DispatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proompteng_facteur_v1_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResult.ProtoReflect.Descriptor instead.
func (*DispatchResult) Descriptor() ([]byte, []int) {
	return file_proompteng_facteur_v1_contract_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchResult) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DispatchResult) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *DispatchResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DispatchResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *DispatchResult) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_proompteng_facteur_v1_contract_proto protoreflect.FileDescriptor

const file_proompteng_facteur_v1_contract_proto_rawDesc = "" +
	"\n" +
	"$proompteng/facteur/v1/contract.proto\x12\x15proompteng.facteur.v1\"\xf1\x05\n" +
	"\fCommandEvent\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12%\n" +
	"\x0einteraction_id\x18\x02 \x01(\tR\rinteractionId\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x05 \x01(\tR\tcommandId\x12\x18\n" +
	"\aversion\x18\x06 \x01(\rR\aversion\x12\x14\n" +
	"\x05token\x18\a \x01(\tR\x05token\x12J\n" +
	"\aoptions\x18\b \x03(\v20.proompteng.facteur.v1.CommandEvent.OptionsEntryR\aoptions\x12\x19\n" +
	"\bguild_id\x18\t \x01(\tR\aguildId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\n" +
	" \x01(\tR\tchannelId\x126\n" +
	"\x04user\x18\v \x01(\v2\".proompteng.facteur.v1.DiscordUserR\x04user\x12<\n" +
	"\x06member\x18\f \x01(\v2$.proompteng.facteur.v1.DiscordMemberR\x06member\x12\x16\n" +
	"\x06locale\x18\r \x01(\tR\x06locale\x12!\n" +
	"\fguild_locale\x18\x0e \x01(\tR\vguildLocale\x12;\n" +
	"\bresponse\x18\x0f \x01(\v2\x1f.proompteng.facteur.v1.ResponseR\bresponse\x12\x1c\n" +
	"\ttimestamp\x18\x10 \x01(\tR\ttimestamp\x12%\n" +
	"\x0ecorrelation_id\x18\x11 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrace_id\x18\x12 \x01(\tR\atraceId\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\vDiscordUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\vglobal_name\x18\x03 \x01(\tR\n" +
	"globalName\x12$\n" +
	"\rdiscriminator\x18\x04 \x01(\tR\rdiscriminator\"5\n" +
	"\rDiscordMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"C\n" +
	"\bResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x19\n" +
	"\x05flags\x18\x02 \x01(\rH\x00R\x05flags\x88\x01\x01B\b\n" +
	"\x06_flags\"\xaf\x01\n" +
	"\x0eDispatchResult\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceIdB?Z=github.com/proompteng/lab/services/facteur/internal/facteurpbb\x06proto3"

var (
	file_proompteng_facteur_v1_contract_proto_rawDescOnce sync.Once
	file_proompteng_facteur_v1_contract_proto_rawDescData []byte
)

func file_proompteng_facteur_v1_contract_proto_rawDescGZIP() []byte {
	file_proompteng_facteur_v1_contract_proto_rawDescOnce.Do(func() {
		file_proompteng_facteur_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proompteng_facteur_v1_contract_proto_rawDesc), len(file_proompteng_facteur_v1_contract_proto_rawDesc)))
	})
	return file_proompteng_facteur_v1_contract_proto_rawDescData
}

var file_proompteng_facteur_v1_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proompteng_facteur_v1_contract_proto_goTypes = []any{
	(*CommandEvent)(nil),   // 0: proompteng.facteur.v1.CommandEvent
	(*DiscordUser)(nil),    // 1: proompteng.facteur.v1.DiscordUser
	(*DiscordMember)(nil),  // 2: proompteng.facteur.v1.DiscordMember
	(*Response)(nil),       // 3: proompteng.facteur.v1.Response
	(*DispatchResult)(nil), // 4: proompteng.facteur.v1.DispatchResult
	nil,                    // 5: proompteng.facteur.v1.CommandEvent.OptionsEntry
}
var file_proompteng_facteur_v1_contract_proto_depIdxs = []int32{
	5, // 0: proompteng.facteur.v1.CommandEvent.options:type_name -> proompteng.facteur.v1.CommandEvent.OptionsEntry
	1, // 1: proompteng.facteur.v1.CommandEvent.user:type_name -> proompteng.facteur.v1.DiscordUser
	2, // 2: proompteng.facteur.v1.CommandEvent.member:type_name -> proompteng.facteur.v1.DiscordMember
	3, // 3: proompteng.facteur.v1.CommandEvent.response:type_name -> proompteng.facteur.v1.Response
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proompteng_facteur_v1_contract_proto_init() }
func file_proompteng_facteur_v1_contract_proto_init() {
	if File_proompteng_facteur_v1_contract_proto != nil {
		return
	}
	file_proompteng_facteur_v1_contract_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proompteng_facteur_v1_contract_proto_rawDesc), len(file_proompteng_facteur_v1_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proompteng_facteur_v1_contract_proto_goTypes,
		DependencyIndexes: file_proompteng_facteur_v1_contract_proto_depIdxs,
		MessageInfos:      file_proompteng_facteur_v1_contract_proto_msgTypes,
	}.Build()
	File_proompteng_facteur_v1_contract_proto = out.File
	file_proompteng_facteur_v1_contract_proto_goTypes = nil
	file_proompteng_facteur_v1_contract_proto_depIdxs = nil
}
