/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminalsIndexRouteImport } from './routes/terminals/index'
import { Route as AtlasIndexRouteImport } from './routes/atlas/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as TorghutVisualsRouteImport } from './routes/torghut/visuals'
import { Route as TorghutSymbolsRouteImport } from './routes/torghut/symbols'
import { Route as TerminalsSessionIdRouteImport } from './routes/terminals/$sessionId'
import { Route as CodexRunsRouteImport } from './routes/codex/runs'
import { Route as CodexRunsAllRouteImport } from './routes/codex/runs/all'
import { Route as AtlasSearchRouteImport } from './routes/atlas/search'
import { Route as AtlasIndexedRouteImport } from './routes/atlas/indexed'
import { Route as AtlasEnrichRouteImport } from './routes/atlas/enrich'
import { Route as ApiTerminalsRouteImport } from './routes/api/terminals'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiMemoriesRouteImport } from './routes/api/memories'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiEnrichRouteImport } from './routes/api/enrich'
import { Route as AgentsGeneralRouteImport } from './routes/agents/general'
import { Route as AgentsRunIdRouteImport } from './routes/agents/$runId'
import { Route as OpenaiV1ModelsRouteImport } from './routes/openai/v1/models'
import { Route as ApiTorghutSymbolsRouteImport } from './routes/api/torghut/symbols'
import { Route as ApiTerminalsSessionIdRouteImport } from './routes/api/terminals/$sessionId'
import { Route as ApiCodexRunsRouteImport } from './routes/api/codex/runs'
import { Route as ApiCodexIssuesRouteImport } from './routes/api/codex/issues'
import { Route as ApiCodexRunCompleteRouteImport } from './routes/api/codex/run-complete'
import { Route as ApiCodexNotifyRouteImport } from './routes/api/codex/notify'
import { Route as ApiCodexGithubEventsRouteImport } from './routes/api/codex/github-events'
import { Route as ApiCodexRunsRecentRouteImport } from './routes/api/codex/runs/recent'
import { Route as ApiAtlasPathsRouteImport } from './routes/api/atlas/paths'
import { Route as ApiAtlasIndexedRouteImport } from './routes/api/atlas/indexed'
import { Route as ApiAtlasFileRouteImport } from './routes/api/atlas/file'
import { Route as ApiAtlasAstRouteImport } from './routes/api/atlas/ast'
import { Route as ApiAgentsEventsRouteImport } from './routes/api/agents/events'
import { Route as OpenaiV1ChatCompletionsRouteImport } from './routes/openai/v1/chat/completions'
import { Route as ApiTorghutTaSignalsRouteImport } from './routes/api/torghut/ta/signals'
import { Route as ApiTorghutTaLatestRouteImport } from './routes/api/torghut/ta/latest'
import { Route as ApiTorghutTaBarsRouteImport } from './routes/api/torghut/ta/bars'
import { Route as ApiTorghutSymbolsSymbolRouteImport } from './routes/api/torghut/symbols/$symbol'
import { Route as ApiTerminalsSessionIdStreamRouteImport } from './routes/api/terminals/$sessionId/stream'
import { Route as ApiTerminalsSessionIdWsRouteImport } from './routes/api/terminals/$sessionId/ws'
import { Route as ApiTerminalsSessionIdResizeRouteImport } from './routes/api/terminals/$sessionId/resize'
import { Route as ApiTerminalsSessionIdInputRouteImport } from './routes/api/terminals/$sessionId/input'
import { Route as ApiTerminalsSessionIdTerminateRouteImport } from './routes/api/terminals/$sessionId/terminate'
import { Route as ApiTerminalsSessionIdDeleteRouteImport } from './routes/api/terminals/$sessionId/delete'

const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsIndexRoute = TerminalsIndexRouteImport.update({
  id: '/terminals/',
  path: '/terminals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasIndexRoute = AtlasIndexRouteImport.update({
  id: '/atlas/',
  path: '/atlas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorghutVisualsRoute = TorghutVisualsRouteImport.update({
  id: '/torghut/visuals',
  path: '/torghut/visuals',
  getParentRoute: () => rootRouteImport,
} as any)
const TorghutSymbolsRoute = TorghutSymbolsRouteImport.update({
  id: '/torghut/symbols',
  path: '/torghut/symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsSessionIdRoute = TerminalsSessionIdRouteImport.update({
  id: '/terminals/$sessionId',
  path: '/terminals/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRunsRoute = CodexRunsRouteImport.update({
  id: '/codex/runs',
  path: '/codex/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRunsAllRoute = CodexRunsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => CodexRunsRoute,
} as any)
const AtlasSearchRoute = AtlasSearchRouteImport.update({
  id: '/atlas/search',
  path: '/atlas/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasIndexedRoute = AtlasIndexedRouteImport.update({
  id: '/atlas/indexed',
  path: '/atlas/indexed',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasEnrichRoute = AtlasEnrichRouteImport.update({
  id: '/atlas/enrich',
  path: '/atlas/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalsRoute = ApiTerminalsRouteImport.update({
  id: '/api/terminals',
  path: '/api/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesRoute = ApiMemoriesRouteImport.update({
  id: '/api/memories',
  path: '/api/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrichRoute = ApiEnrichRouteImport.update({
  id: '/api/enrich',
  path: '/api/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsGeneralRoute = AgentsGeneralRouteImport.update({
  id: '/agents/general',
  path: '/agents/general',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRunIdRoute = AgentsRunIdRouteImport.update({
  id: '/agents/$runId',
  path: '/agents/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenaiV1ModelsRoute = OpenaiV1ModelsRouteImport.update({
  id: '/openai/v1/models',
  path: '/openai/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorghutSymbolsRoute = ApiTorghutSymbolsRouteImport.update({
  id: '/api/torghut/symbols',
  path: '/api/torghut/symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalsSessionIdRoute = ApiTerminalsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ApiTerminalsRoute,
} as any)
const ApiCodexRunsRoute = ApiCodexRunsRouteImport.update({
  id: '/api/codex/runs',
  path: '/api/codex/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexIssuesRoute = ApiCodexIssuesRouteImport.update({
  id: '/api/codex/issues',
  path: '/api/codex/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexRunsRecentRoute = ApiCodexRunsRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => ApiCodexRunsRoute,
} as any)
const ApiCodexRunCompleteRoute = ApiCodexRunCompleteRouteImport.update({
  id: '/api/codex/run-complete',
  path: '/api/codex/run-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexNotifyRoute = ApiCodexNotifyRouteImport.update({
  id: '/api/codex/notify',
  path: '/api/codex/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexGithubEventsRoute = ApiCodexGithubEventsRouteImport.update({
  id: '/api/codex/github-events',
  path: '/api/codex/github-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtlasPathsRoute = ApiAtlasPathsRouteImport.update({
  id: '/api/atlas/paths',
  path: '/api/atlas/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtlasIndexedRoute = ApiAtlasIndexedRouteImport.update({
  id: '/api/atlas/indexed',
  path: '/api/atlas/indexed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtlasFileRoute = ApiAtlasFileRouteImport.update({
  id: '/api/atlas/file',
  path: '/api/atlas/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtlasAstRoute = ApiAtlasAstRouteImport.update({
  id: '/api/atlas/ast',
  path: '/api/atlas/ast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsEventsRoute = ApiAgentsEventsRouteImport.update({
  id: '/api/agents/events',
  path: '/api/agents/events',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenaiV1ChatCompletionsRoute = OpenaiV1ChatCompletionsRouteImport.update({
  id: '/openai/v1/chat/completions',
  path: '/openai/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorghutTaSignalsRoute = ApiTorghutTaSignalsRouteImport.update({
  id: '/api/torghut/ta/signals',
  path: '/api/torghut/ta/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorghutTaLatestRoute = ApiTorghutTaLatestRouteImport.update({
  id: '/api/torghut/ta/latest',
  path: '/api/torghut/ta/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorghutTaBarsRoute = ApiTorghutTaBarsRouteImport.update({
  id: '/api/torghut/ta/bars',
  path: '/api/torghut/ta/bars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorghutSymbolsSymbolRoute = ApiTorghutSymbolsSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => ApiTorghutSymbolsRoute,
} as any)
const ApiTerminalsSessionIdStreamRoute =
  ApiTerminalsSessionIdStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => ApiTerminalsSessionIdRoute,
  } as any)
const ApiTerminalsSessionIdWsRoute =
  ApiTerminalsSessionIdWsRouteImport.update({
    id: '/ws',
    path: '/ws',
    getParentRoute: () => ApiTerminalsSessionIdRoute,
  } as any)
const ApiTerminalsSessionIdResizeRoute =
  ApiTerminalsSessionIdResizeRouteImport.update({
    id: '/resize',
    path: '/resize',
    getParentRoute: () => ApiTerminalsSessionIdRoute,
  } as any)
const ApiTerminalsSessionIdInputRoute =
  ApiTerminalsSessionIdInputRouteImport.update({
    id: '/input',
    path: '/input',
    getParentRoute: () => ApiTerminalsSessionIdRoute,
  } as any)
const ApiTerminalsSessionIdTerminateRoute =
  ApiTerminalsSessionIdTerminateRouteImport.update({
    id: '/terminate',
    path: '/terminate',
    getParentRoute: () => ApiTerminalsSessionIdRoute,
  } as any)
const ApiTerminalsSessionIdDeleteRoute =
  ApiTerminalsSessionIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => ApiTerminalsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/memories': typeof MemoriesRoute
  '/agents/$runId': typeof AgentsRunIdRoute
  '/agents/general': typeof AgentsGeneralRoute
  '/api/enrich': typeof ApiEnrichRoute
  '/api/health': typeof ApiHealthRoute
  '/api/memories': typeof ApiMemoriesRoute
  '/api/models': typeof ApiModelsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/terminals': typeof ApiTerminalsRouteWithChildren
  '/atlas/enrich': typeof AtlasEnrichRoute
  '/atlas/indexed': typeof AtlasIndexedRoute
  '/atlas/search': typeof AtlasSearchRoute
  '/codex/runs': typeof CodexRunsRouteWithChildren
  '/codex/runs/all': typeof CodexRunsAllRoute
  '/terminals/$sessionId': typeof TerminalsSessionIdRoute
  '/torghut/symbols': typeof TorghutSymbolsRoute
  '/torghut/visuals': typeof TorghutVisualsRoute
  '/agents': typeof AgentsIndexRoute
  '/atlas': typeof AtlasIndexRoute
  '/terminals': typeof TerminalsIndexRoute
  '/api/agents/events': typeof ApiAgentsEventsRoute
  '/api/atlas/ast': typeof ApiAtlasAstRoute
  '/api/atlas/file': typeof ApiAtlasFileRoute
  '/api/atlas/indexed': typeof ApiAtlasIndexedRoute
  '/api/atlas/paths': typeof ApiAtlasPathsRoute
  '/api/codex/github-events': typeof ApiCodexGithubEventsRoute
  '/api/codex/issues': typeof ApiCodexIssuesRoute
  '/api/codex/notify': typeof ApiCodexNotifyRoute
  '/api/codex/run-complete': typeof ApiCodexRunCompleteRoute
  '/api/codex/runs': typeof ApiCodexRunsRouteWithChildren
  '/api/codex/runs/recent': typeof ApiCodexRunsRecentRoute
  '/api/terminals/$sessionId': typeof ApiTerminalsSessionIdRouteWithChildren
  '/api/torghut/symbols': typeof ApiTorghutSymbolsRouteWithChildren
  '/openai/v1/models': typeof OpenaiV1ModelsRoute
  '/api/terminals/$sessionId/input': typeof ApiTerminalsSessionIdInputRoute
  '/api/terminals/$sessionId/delete': typeof ApiTerminalsSessionIdDeleteRoute
  '/api/terminals/$sessionId/terminate': typeof ApiTerminalsSessionIdTerminateRoute
  '/api/terminals/$sessionId/resize': typeof ApiTerminalsSessionIdResizeRoute
  '/api/terminals/$sessionId/stream': typeof ApiTerminalsSessionIdStreamRoute
  '/api/terminals/$sessionId/ws': typeof ApiTerminalsSessionIdWsRoute
  '/api/torghut/symbols/$symbol': typeof ApiTorghutSymbolsSymbolRoute
  '/api/torghut/ta/bars': typeof ApiTorghutTaBarsRoute
  '/api/torghut/ta/latest': typeof ApiTorghutTaLatestRoute
  '/api/torghut/ta/signals': typeof ApiTorghutTaSignalsRoute
  '/openai/v1/chat/completions': typeof OpenaiV1ChatCompletionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/memories': typeof MemoriesRoute
  '/agents/$runId': typeof AgentsRunIdRoute
  '/agents/general': typeof AgentsGeneralRoute
  '/api/enrich': typeof ApiEnrichRoute
  '/api/health': typeof ApiHealthRoute
  '/api/memories': typeof ApiMemoriesRoute
  '/api/models': typeof ApiModelsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/terminals': typeof ApiTerminalsRouteWithChildren
  '/atlas/enrich': typeof AtlasEnrichRoute
  '/atlas/indexed': typeof AtlasIndexedRoute
  '/atlas/search': typeof AtlasSearchRoute
  '/codex/runs': typeof CodexRunsRouteWithChildren
  '/codex/runs/all': typeof CodexRunsAllRoute
  '/terminals/$sessionId': typeof TerminalsSessionIdRoute
  '/torghut/symbols': typeof TorghutSymbolsRoute
  '/torghut/visuals': typeof TorghutVisualsRoute
  '/agents': typeof AgentsIndexRoute
  '/atlas': typeof AtlasIndexRoute
  '/terminals': typeof TerminalsIndexRoute
  '/api/agents/events': typeof ApiAgentsEventsRoute
  '/api/atlas/ast': typeof ApiAtlasAstRoute
  '/api/atlas/file': typeof ApiAtlasFileRoute
  '/api/atlas/indexed': typeof ApiAtlasIndexedRoute
  '/api/atlas/paths': typeof ApiAtlasPathsRoute
  '/api/codex/github-events': typeof ApiCodexGithubEventsRoute
  '/api/codex/issues': typeof ApiCodexIssuesRoute
  '/api/codex/notify': typeof ApiCodexNotifyRoute
  '/api/codex/run-complete': typeof ApiCodexRunCompleteRoute
  '/api/codex/runs': typeof ApiCodexRunsRouteWithChildren
  '/api/codex/runs/recent': typeof ApiCodexRunsRecentRoute
  '/api/terminals/$sessionId': typeof ApiTerminalsSessionIdRouteWithChildren
  '/api/torghut/symbols': typeof ApiTorghutSymbolsRouteWithChildren
  '/openai/v1/models': typeof OpenaiV1ModelsRoute
  '/api/terminals/$sessionId/input': typeof ApiTerminalsSessionIdInputRoute
  '/api/terminals/$sessionId/delete': typeof ApiTerminalsSessionIdDeleteRoute
  '/api/terminals/$sessionId/terminate': typeof ApiTerminalsSessionIdTerminateRoute
  '/api/terminals/$sessionId/resize': typeof ApiTerminalsSessionIdResizeRoute
  '/api/terminals/$sessionId/stream': typeof ApiTerminalsSessionIdStreamRoute
  '/api/terminals/$sessionId/ws': typeof ApiTerminalsSessionIdWsRoute
  '/api/torghut/symbols/$symbol': typeof ApiTorghutSymbolsSymbolRoute
  '/api/torghut/ta/bars': typeof ApiTorghutTaBarsRoute
  '/api/torghut/ta/latest': typeof ApiTorghutTaLatestRoute
  '/api/torghut/ta/signals': typeof ApiTorghutTaSignalsRoute
  '/openai/v1/chat/completions': typeof OpenaiV1ChatCompletionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/memories': typeof MemoriesRoute
  '/agents/$runId': typeof AgentsRunIdRoute
  '/agents/general': typeof AgentsGeneralRoute
  '/api/enrich': typeof ApiEnrichRoute
  '/api/health': typeof ApiHealthRoute
  '/api/memories': typeof ApiMemoriesRoute
  '/api/models': typeof ApiModelsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/terminals': typeof ApiTerminalsRouteWithChildren
  '/atlas/enrich': typeof AtlasEnrichRoute
  '/atlas/indexed': typeof AtlasIndexedRoute
  '/atlas/search': typeof AtlasSearchRoute
  '/codex/runs': typeof CodexRunsRouteWithChildren
  '/codex/runs/all': typeof CodexRunsAllRoute
  '/terminals/$sessionId': typeof TerminalsSessionIdRoute
  '/torghut/symbols': typeof TorghutSymbolsRoute
  '/torghut/visuals': typeof TorghutVisualsRoute
  '/agents/': typeof AgentsIndexRoute
  '/atlas/': typeof AtlasIndexRoute
  '/terminals/': typeof TerminalsIndexRoute
  '/api/agents/events': typeof ApiAgentsEventsRoute
  '/api/atlas/ast': typeof ApiAtlasAstRoute
  '/api/atlas/file': typeof ApiAtlasFileRoute
  '/api/atlas/indexed': typeof ApiAtlasIndexedRoute
  '/api/atlas/paths': typeof ApiAtlasPathsRoute
  '/api/codex/github-events': typeof ApiCodexGithubEventsRoute
  '/api/codex/issues': typeof ApiCodexIssuesRoute
  '/api/codex/notify': typeof ApiCodexNotifyRoute
  '/api/codex/run-complete': typeof ApiCodexRunCompleteRoute
  '/api/codex/runs': typeof ApiCodexRunsRouteWithChildren
  '/api/codex/runs/recent': typeof ApiCodexRunsRecentRoute
  '/api/terminals/$sessionId': typeof ApiTerminalsSessionIdRouteWithChildren
  '/api/torghut/symbols': typeof ApiTorghutSymbolsRouteWithChildren
  '/openai/v1/models': typeof OpenaiV1ModelsRoute
  '/api/terminals/$sessionId/input': typeof ApiTerminalsSessionIdInputRoute
  '/api/terminals/$sessionId/delete': typeof ApiTerminalsSessionIdDeleteRoute
  '/api/terminals/$sessionId/terminate': typeof ApiTerminalsSessionIdTerminateRoute
  '/api/terminals/$sessionId/resize': typeof ApiTerminalsSessionIdResizeRoute
  '/api/terminals/$sessionId/stream': typeof ApiTerminalsSessionIdStreamRoute
  '/api/terminals/$sessionId/ws': typeof ApiTerminalsSessionIdWsRoute
  '/api/torghut/symbols/$symbol': typeof ApiTorghutSymbolsSymbolRoute
  '/api/torghut/ta/bars': typeof ApiTorghutTaBarsRoute
  '/api/torghut/ta/latest': typeof ApiTorghutTaLatestRoute
  '/api/torghut/ta/signals': typeof ApiTorghutTaSignalsRoute
  '/openai/v1/chat/completions': typeof OpenaiV1ChatCompletionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/mcp'
    | '/memories'
    | '/agents/$runId'
    | '/agents/general'
    | '/api/enrich'
    | '/api/health'
    | '/api/memories'
    | '/api/models'
    | '/api/search'
    | '/api/terminals'
    | '/atlas/enrich'
    | '/atlas/indexed'
    | '/atlas/search'
    | '/codex/runs'
    | '/codex/runs/all'
    | '/terminals/$sessionId'
    | '/torghut/symbols'
    | '/torghut/visuals'
    | '/agents'
    | '/atlas'
    | '/terminals'
    | '/api/agents/events'
    | '/api/atlas/ast'
    | '/api/atlas/file'
    | '/api/atlas/indexed'
    | '/api/atlas/paths'
    | '/api/codex/github-events'
    | '/api/codex/issues'
    | '/api/codex/notify'
    | '/api/codex/run-complete'
    | '/api/codex/runs'
    | '/api/codex/runs/recent'
    | '/api/terminals/$sessionId'
    | '/api/torghut/symbols'
    | '/openai/v1/models'
    | '/api/terminals/$sessionId/input'
    | '/api/terminals/$sessionId/delete'
    | '/api/terminals/$sessionId/terminate'
    | '/api/terminals/$sessionId/resize'
    | '/api/terminals/$sessionId/stream'
    | '/api/terminals/$sessionId/ws'
    | '/api/torghut/symbols/$symbol'
    | '/api/torghut/ta/bars'
    | '/api/torghut/ta/latest'
    | '/api/torghut/ta/signals'
    | '/openai/v1/chat/completions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/mcp'
    | '/memories'
    | '/agents/$runId'
    | '/agents/general'
    | '/api/enrich'
    | '/api/health'
    | '/api/memories'
    | '/api/models'
    | '/api/search'
    | '/api/terminals'
    | '/atlas/enrich'
    | '/atlas/indexed'
    | '/atlas/search'
    | '/codex/runs'
    | '/codex/runs/all'
    | '/terminals/$sessionId'
    | '/torghut/symbols'
    | '/torghut/visuals'
    | '/agents'
    | '/atlas'
    | '/terminals'
    | '/api/agents/events'
    | '/api/atlas/ast'
    | '/api/atlas/file'
    | '/api/atlas/indexed'
    | '/api/atlas/paths'
    | '/api/codex/github-events'
    | '/api/codex/issues'
    | '/api/codex/notify'
    | '/api/codex/run-complete'
    | '/api/codex/runs'
    | '/api/codex/runs/recent'
    | '/api/terminals/$sessionId'
    | '/api/torghut/symbols'
    | '/openai/v1/models'
    | '/api/terminals/$sessionId/input'
    | '/api/terminals/$sessionId/delete'
    | '/api/terminals/$sessionId/terminate'
    | '/api/terminals/$sessionId/resize'
    | '/api/terminals/$sessionId/stream'
    | '/api/terminals/$sessionId/ws'
    | '/api/torghut/symbols/$symbol'
    | '/api/torghut/ta/bars'
    | '/api/torghut/ta/latest'
    | '/api/torghut/ta/signals'
    | '/openai/v1/chat/completions'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/mcp'
    | '/memories'
    | '/agents/$runId'
    | '/agents/general'
    | '/api/enrich'
    | '/api/health'
    | '/api/memories'
    | '/api/models'
    | '/api/search'
    | '/api/terminals'
    | '/atlas/enrich'
    | '/atlas/indexed'
    | '/atlas/search'
    | '/codex/runs'
    | '/codex/runs/all'
    | '/terminals/$sessionId'
    | '/torghut/symbols'
    | '/torghut/visuals'
    | '/agents/'
    | '/atlas/'
    | '/terminals/'
    | '/api/agents/events'
    | '/api/atlas/ast'
    | '/api/atlas/file'
    | '/api/atlas/indexed'
    | '/api/atlas/paths'
    | '/api/codex/github-events'
    | '/api/codex/issues'
    | '/api/codex/notify'
    | '/api/codex/run-complete'
    | '/api/codex/runs'
    | '/api/codex/runs/recent'
    | '/api/terminals/$sessionId'
    | '/api/torghut/symbols'
    | '/openai/v1/models'
    | '/api/terminals/$sessionId/input'
    | '/api/terminals/$sessionId/delete'
    | '/api/terminals/$sessionId/terminate'
    | '/api/terminals/$sessionId/resize'
    | '/api/terminals/$sessionId/stream'
    | '/api/terminals/$sessionId/ws'
    | '/api/torghut/symbols/$symbol'
    | '/api/torghut/ta/bars'
    | '/api/torghut/ta/latest'
    | '/api/torghut/ta/signals'
    | '/openai/v1/chat/completions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  McpRoute: typeof McpRoute
  MemoriesRoute: typeof MemoriesRoute
  AgentsRunIdRoute: typeof AgentsRunIdRoute
  AgentsGeneralRoute: typeof AgentsGeneralRoute
  ApiEnrichRoute: typeof ApiEnrichRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMemoriesRoute: typeof ApiMemoriesRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiTerminalsRoute: typeof ApiTerminalsRouteWithChildren
  AtlasEnrichRoute: typeof AtlasEnrichRoute
  AtlasIndexedRoute: typeof AtlasIndexedRoute
  AtlasSearchRoute: typeof AtlasSearchRoute
  CodexRunsRoute: typeof CodexRunsRouteWithChildren
  TerminalsSessionIdRoute: typeof TerminalsSessionIdRoute
  TorghutSymbolsRoute: typeof TorghutSymbolsRoute
  TorghutVisualsRoute: typeof TorghutVisualsRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AtlasIndexRoute: typeof AtlasIndexRoute
  TerminalsIndexRoute: typeof TerminalsIndexRoute
  ApiAgentsEventsRoute: typeof ApiAgentsEventsRoute
  ApiAtlasAstRoute: typeof ApiAtlasAstRoute
  ApiAtlasFileRoute: typeof ApiAtlasFileRoute
  ApiAtlasIndexedRoute: typeof ApiAtlasIndexedRoute
  ApiAtlasPathsRoute: typeof ApiAtlasPathsRoute
  ApiCodexGithubEventsRoute: typeof ApiCodexGithubEventsRoute
  ApiCodexIssuesRoute: typeof ApiCodexIssuesRoute
  ApiCodexNotifyRoute: typeof ApiCodexNotifyRoute
  ApiCodexRunCompleteRoute: typeof ApiCodexRunCompleteRoute
  ApiCodexRunsRoute: typeof ApiCodexRunsRouteWithChildren
  ApiTorghutSymbolsRoute: typeof ApiTorghutSymbolsRouteWithChildren
  OpenaiV1ModelsRoute: typeof OpenaiV1ModelsRoute
  ApiTorghutTaBarsRoute: typeof ApiTorghutTaBarsRoute
  ApiTorghutTaLatestRoute: typeof ApiTorghutTaLatestRoute
  ApiTorghutTaSignalsRoute: typeof ApiTorghutTaSignalsRoute
  OpenaiV1ChatCompletionsRoute: typeof OpenaiV1ChatCompletionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals/': {
      id: '/terminals/'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/': {
      id: '/atlas/'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torghut/visuals': {
      id: '/torghut/visuals'
      path: '/torghut/visuals'
      fullPath: '/torghut/visuals'
      preLoaderRoute: typeof TorghutVisualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torghut/symbols': {
      id: '/torghut/symbols'
      path: '/torghut/symbols'
      fullPath: '/torghut/symbols'
      preLoaderRoute: typeof TorghutSymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals/$sessionId': {
      id: '/terminals/$sessionId'
      path: '/terminals/$sessionId'
      fullPath: '/terminals/$sessionId'
      preLoaderRoute: typeof TerminalsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/runs': {
      id: '/codex/runs'
      path: '/codex/runs'
      fullPath: '/codex/runs'
      preLoaderRoute: typeof CodexRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/runs/all': {
      id: '/codex/runs/all'
      path: '/all'
      fullPath: '/codex/runs/all'
      preLoaderRoute: typeof CodexRunsAllRouteImport
      parentRoute: typeof CodexRunsRoute
    }
    '/atlas/search': {
      id: '/atlas/search'
      path: '/atlas/search'
      fullPath: '/atlas/search'
      preLoaderRoute: typeof AtlasSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/indexed': {
      id: '/atlas/indexed'
      path: '/atlas/indexed'
      fullPath: '/atlas/indexed'
      preLoaderRoute: typeof AtlasIndexedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/enrich': {
      id: '/atlas/enrich'
      path: '/atlas/enrich'
      fullPath: '/atlas/enrich'
      preLoaderRoute: typeof AtlasEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminals': {
      id: '/api/terminals'
      path: '/api/terminals'
      fullPath: '/api/terminals'
      preLoaderRoute: typeof ApiTerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories': {
      id: '/api/memories'
      path: '/api/memories'
      fullPath: '/api/memories'
      preLoaderRoute: typeof ApiMemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrich': {
      id: '/api/enrich'
      path: '/api/enrich'
      fullPath: '/api/enrich'
      preLoaderRoute: typeof ApiEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/general': {
      id: '/agents/general'
      path: '/agents/general'
      fullPath: '/agents/general'
      preLoaderRoute: typeof AgentsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$runId': {
      id: '/agents/$runId'
      path: '/agents/$runId'
      fullPath: '/agents/$runId'
      preLoaderRoute: typeof AgentsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openai/v1/models': {
      id: '/openai/v1/models'
      path: '/openai/v1/models'
      fullPath: '/openai/v1/models'
      preLoaderRoute: typeof OpenaiV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torghut/symbols': {
      id: '/api/torghut/symbols'
      path: '/api/torghut/symbols'
      fullPath: '/api/torghut/symbols'
      preLoaderRoute: typeof ApiTorghutSymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminals/$sessionId': {
      id: '/api/terminals/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/terminals/$sessionId'
      preLoaderRoute: typeof ApiTerminalsSessionIdRouteImport
      parentRoute: typeof ApiTerminalsRoute
    }
    '/api/codex/runs': {
      id: '/api/codex/runs'
      path: '/api/codex/runs'
      fullPath: '/api/codex/runs'
      preLoaderRoute: typeof ApiCodexRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/issues': {
      id: '/api/codex/issues'
      path: '/api/codex/issues'
      fullPath: '/api/codex/issues'
      preLoaderRoute: typeof ApiCodexIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/runs/recent': {
      id: '/api/codex/runs/recent'
      path: '/recent'
      fullPath: '/api/codex/runs/recent'
      preLoaderRoute: typeof ApiCodexRunsRecentRouteImport
      parentRoute: typeof ApiCodexRunsRoute
    }
    '/api/codex/run-complete': {
      id: '/api/codex/run-complete'
      path: '/api/codex/run-complete'
      fullPath: '/api/codex/run-complete'
      preLoaderRoute: typeof ApiCodexRunCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/notify': {
      id: '/api/codex/notify'
      path: '/api/codex/notify'
      fullPath: '/api/codex/notify'
      preLoaderRoute: typeof ApiCodexNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/github-events': {
      id: '/api/codex/github-events'
      path: '/api/codex/github-events'
      fullPath: '/api/codex/github-events'
      preLoaderRoute: typeof ApiCodexGithubEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atlas/paths': {
      id: '/api/atlas/paths'
      path: '/api/atlas/paths'
      fullPath: '/api/atlas/paths'
      preLoaderRoute: typeof ApiAtlasPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atlas/indexed': {
      id: '/api/atlas/indexed'
      path: '/api/atlas/indexed'
      fullPath: '/api/atlas/indexed'
      preLoaderRoute: typeof ApiAtlasIndexedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atlas/file': {
      id: '/api/atlas/file'
      path: '/api/atlas/file'
      fullPath: '/api/atlas/file'
      preLoaderRoute: typeof ApiAtlasFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atlas/ast': {
      id: '/api/atlas/ast'
      path: '/api/atlas/ast'
      fullPath: '/api/atlas/ast'
      preLoaderRoute: typeof ApiAtlasAstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/events': {
      id: '/api/agents/events'
      path: '/api/agents/events'
      fullPath: '/api/agents/events'
      preLoaderRoute: typeof ApiAgentsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openai/v1/chat/completions': {
      id: '/openai/v1/chat/completions'
      path: '/openai/v1/chat/completions'
      fullPath: '/openai/v1/chat/completions'
      preLoaderRoute: typeof OpenaiV1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torghut/ta/signals': {
      id: '/api/torghut/ta/signals'
      path: '/api/torghut/ta/signals'
      fullPath: '/api/torghut/ta/signals'
      preLoaderRoute: typeof ApiTorghutTaSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torghut/ta/latest': {
      id: '/api/torghut/ta/latest'
      path: '/api/torghut/ta/latest'
      fullPath: '/api/torghut/ta/latest'
      preLoaderRoute: typeof ApiTorghutTaLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torghut/ta/bars': {
      id: '/api/torghut/ta/bars'
      path: '/api/torghut/ta/bars'
      fullPath: '/api/torghut/ta/bars'
      preLoaderRoute: typeof ApiTorghutTaBarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torghut/symbols/$symbol': {
      id: '/api/torghut/symbols/$symbol'
      path: '/$symbol'
      fullPath: '/api/torghut/symbols/$symbol'
      preLoaderRoute: typeof ApiTorghutSymbolsSymbolRouteImport
      parentRoute: typeof ApiTorghutSymbolsRoute
    }
    '/api/terminals/$sessionId/stream': {
      id: '/api/terminals/$sessionId/stream'
      path: '/stream'
      fullPath: '/api/terminals/$sessionId/stream'
      preLoaderRoute: typeof ApiTerminalsSessionIdStreamRouteImport
      parentRoute: typeof ApiTerminalsSessionIdRoute
    }
    '/api/terminals/$sessionId/ws': {
      id: '/api/terminals/$sessionId/ws'
      path: '/ws'
      fullPath: '/api/terminals/$sessionId/ws'
      preLoaderRoute: typeof ApiTerminalsSessionIdWsRouteImport
      parentRoute: typeof ApiTerminalsSessionIdRoute
    }
    '/api/terminals/$sessionId/resize': {
      id: '/api/terminals/$sessionId/resize'
      path: '/resize'
      fullPath: '/api/terminals/$sessionId/resize'
      preLoaderRoute: typeof ApiTerminalsSessionIdResizeRouteImport
      parentRoute: typeof ApiTerminalsSessionIdRoute
    }
    '/api/terminals/$sessionId/input': {
      id: '/api/terminals/$sessionId/input'
      path: '/input'
      fullPath: '/api/terminals/$sessionId/input'
      preLoaderRoute: typeof ApiTerminalsSessionIdInputRouteImport
      parentRoute: typeof ApiTerminalsSessionIdRoute
    }
    '/api/terminals/$sessionId/delete': {
      id: '/api/terminals/$sessionId/delete'
      path: '/delete'
      fullPath: '/api/terminals/$sessionId/delete'
      preLoaderRoute: typeof ApiTerminalsSessionIdDeleteRouteImport
      parentRoute: typeof ApiTerminalsSessionIdRoute
    }
    '/api/terminals/$sessionId/terminate': {
      id: '/api/terminals/$sessionId/terminate'
      path: '/terminate'
      fullPath: '/api/terminals/$sessionId/terminate'
      preLoaderRoute: typeof ApiTerminalsSessionIdTerminateRouteImport
      parentRoute: typeof ApiTerminalsSessionIdRoute
    }
  }
}

interface CodexRunsRouteChildren {
  CodexRunsAllRoute: typeof CodexRunsAllRoute
}

const CodexRunsRouteChildren: CodexRunsRouteChildren = {
  CodexRunsAllRoute: CodexRunsAllRoute,
}

const CodexRunsRouteWithChildren = CodexRunsRoute._addFileChildren(
  CodexRunsRouteChildren,
)

interface ApiCodexRunsRouteChildren {
  ApiCodexRunsRecentRoute: typeof ApiCodexRunsRecentRoute
}

const ApiCodexRunsRouteChildren: ApiCodexRunsRouteChildren = {
  ApiCodexRunsRecentRoute: ApiCodexRunsRecentRoute,
}

const ApiCodexRunsRouteWithChildren = ApiCodexRunsRoute._addFileChildren(
  ApiCodexRunsRouteChildren,
)

interface ApiTerminalsSessionIdRouteChildren {
  ApiTerminalsSessionIdInputRoute: typeof ApiTerminalsSessionIdInputRoute
  ApiTerminalsSessionIdDeleteRoute: typeof ApiTerminalsSessionIdDeleteRoute
  ApiTerminalsSessionIdTerminateRoute: typeof ApiTerminalsSessionIdTerminateRoute
  ApiTerminalsSessionIdResizeRoute: typeof ApiTerminalsSessionIdResizeRoute
  ApiTerminalsSessionIdStreamRoute: typeof ApiTerminalsSessionIdStreamRoute
  ApiTerminalsSessionIdWsRoute: typeof ApiTerminalsSessionIdWsRoute
}

const ApiTerminalsSessionIdRouteChildren: ApiTerminalsSessionIdRouteChildren = {
  ApiTerminalsSessionIdInputRoute: ApiTerminalsSessionIdInputRoute,
  ApiTerminalsSessionIdDeleteRoute: ApiTerminalsSessionIdDeleteRoute,
  ApiTerminalsSessionIdTerminateRoute: ApiTerminalsSessionIdTerminateRoute,
  ApiTerminalsSessionIdResizeRoute: ApiTerminalsSessionIdResizeRoute,
  ApiTerminalsSessionIdStreamRoute: ApiTerminalsSessionIdStreamRoute,
  ApiTerminalsSessionIdWsRoute: ApiTerminalsSessionIdWsRoute,
}

const ApiTerminalsSessionIdRouteWithChildren =
  ApiTerminalsSessionIdRoute._addFileChildren(
    ApiTerminalsSessionIdRouteChildren,
  )

interface ApiTerminalsRouteChildren {
  ApiTerminalsSessionIdRoute: typeof ApiTerminalsSessionIdRouteWithChildren
}

const ApiTerminalsRouteChildren: ApiTerminalsRouteChildren = {
  ApiTerminalsSessionIdRoute: ApiTerminalsSessionIdRouteWithChildren,
}

const ApiTerminalsRouteWithChildren = ApiTerminalsRoute._addFileChildren(
  ApiTerminalsRouteChildren,
)

interface ApiTorghutSymbolsRouteChildren {
  ApiTorghutSymbolsSymbolRoute: typeof ApiTorghutSymbolsSymbolRoute
}

const ApiTorghutSymbolsRouteChildren: ApiTorghutSymbolsRouteChildren = {
  ApiTorghutSymbolsSymbolRoute: ApiTorghutSymbolsSymbolRoute,
}

const ApiTorghutSymbolsRouteWithChildren =
  ApiTorghutSymbolsRoute._addFileChildren(ApiTorghutSymbolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  McpRoute: McpRoute,
  MemoriesRoute: MemoriesRoute,
  AgentsRunIdRoute: AgentsRunIdRoute,
  AgentsGeneralRoute: AgentsGeneralRoute,
  ApiEnrichRoute: ApiEnrichRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMemoriesRoute: ApiMemoriesRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiTerminalsRoute: ApiTerminalsRouteWithChildren,
  AtlasEnrichRoute: AtlasEnrichRoute,
  AtlasIndexedRoute: AtlasIndexedRoute,
  AtlasSearchRoute: AtlasSearchRoute,
  CodexRunsRoute: CodexRunsRouteWithChildren,
  TerminalsSessionIdRoute: TerminalsSessionIdRoute,
  TorghutSymbolsRoute: TorghutSymbolsRoute,
  TorghutVisualsRoute: TorghutVisualsRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AtlasIndexRoute: AtlasIndexRoute,
  TerminalsIndexRoute: TerminalsIndexRoute,
  ApiAgentsEventsRoute: ApiAgentsEventsRoute,
  ApiAtlasAstRoute: ApiAtlasAstRoute,
  ApiAtlasFileRoute: ApiAtlasFileRoute,
  ApiAtlasIndexedRoute: ApiAtlasIndexedRoute,
  ApiAtlasPathsRoute: ApiAtlasPathsRoute,
  ApiCodexGithubEventsRoute: ApiCodexGithubEventsRoute,
  ApiCodexIssuesRoute: ApiCodexIssuesRoute,
  ApiCodexNotifyRoute: ApiCodexNotifyRoute,
  ApiCodexRunCompleteRoute: ApiCodexRunCompleteRoute,
  ApiCodexRunsRoute: ApiCodexRunsRouteWithChildren,
  ApiTorghutSymbolsRoute: ApiTorghutSymbolsRouteWithChildren,
  OpenaiV1ModelsRoute: OpenaiV1ModelsRoute,
  ApiTorghutTaBarsRoute: ApiTorghutTaBarsRoute,
  ApiTorghutTaLatestRoute: ApiTorghutTaLatestRoute,
  ApiTorghutTaSignalsRoute: ApiTorghutTaSignalsRoute,
  OpenaiV1ChatCompletionsRoute: OpenaiV1ChatCompletionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
