"""Aggregated execution profiles for candidate-spec compilation."""

from __future__ import annotations

from .candidate_spec_base_profiles_primary import (
    BASE_FAMILY_EXECUTION_PROFILES_PRIMARY,
)
from .candidate_spec_base_profiles_secondary import (
    BASE_FAMILY_EXECUTION_PROFILES_SECONDARY,
)
from .candidate_spec_feedback_profiles import (
    REJECTED_SIGNAL_FALSE_NEGATIVE_RESCUE_EXECUTION_PROFILES,
)
from .candidate_spec_hpairs_profiles import (
    H_PAIRS_REPLAY_LEDGER_BREADTH_EXECUTION_PROFILES,
)
from .candidate_spec_portfolio_profiles_primary import (
    PORTFOLIO_ORACLE_COVERAGE_EXECUTION_PROFILES_PRIMARY,
)
from .candidate_spec_portfolio_profiles_secondary import (
    PORTFOLIO_ORACLE_COVERAGE_EXECUTION_PROFILES_SECONDARY,
)
from .candidate_spec_profile_constants import (
    LIVE_SIGNAL_COVERED_SEMICONDUCTOR_UNIVERSE,
    RESEARCHED_SEMICONDUCTOR_TECH_UNIVERSE,
    FAMILY_RUNTIME,
    FAMILY_TIEBREAK,
    MAX_FAMILIES_PER_HYPOTHESIS,
    PORTFOLIO_TARGET_NET_PNL_PER_DAY,
    PORTFOLIO_SLEEVE_FAMILY_TARGET,
    PORTFOLIO_SLEEVE_FAMILY_ORDER,
    DEFAULT_PROFILE_COUNT,
    RESEARCHED_SEMICONDUCTOR_TECH_UNIVERSE_PROFILE,
    AI_ACCELERATOR_UNIVERSE_PROFILE,
    LIQUID_TECH_PLATFORM_UNIVERSE_PROFILE,
    BROAD_SEMICONDUCTOR_UNIVERSE_PROFILE,
    PORTFOLIO_COVERAGE_UNIVERSE_PROFILE,
    PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE,
    PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE,
    LARGE_CAP_UNIVERSE_PROFILES,
    BREAKOUT_UNIVERSE_PROFILES,
    REVERSAL_UNIVERSE_PROFILES,
    TSMOM_UNIVERSE_PROFILES,
)

FAMILY_EXECUTION_PROFILES = {
    **BASE_FAMILY_EXECUTION_PROFILES_PRIMARY,
    **BASE_FAMILY_EXECUTION_PROFILES_SECONDARY,
}
BASE_FAMILY_EXECUTION_PROFILES = FAMILY_EXECUTION_PROFILES
PORTFOLIO_ORACLE_COVERAGE_EXECUTION_PROFILES = {
    **PORTFOLIO_ORACLE_COVERAGE_EXECUTION_PROFILES_PRIMARY,
    **PORTFOLIO_ORACLE_COVERAGE_EXECUTION_PROFILES_SECONDARY,
}

__all__ = (
    "LIVE_SIGNAL_COVERED_SEMICONDUCTOR_UNIVERSE",
    "RESEARCHED_SEMICONDUCTOR_TECH_UNIVERSE",
    "FAMILY_RUNTIME",
    "FAMILY_TIEBREAK",
    "MAX_FAMILIES_PER_HYPOTHESIS",
    "PORTFOLIO_TARGET_NET_PNL_PER_DAY",
    "PORTFOLIO_SLEEVE_FAMILY_TARGET",
    "PORTFOLIO_SLEEVE_FAMILY_ORDER",
    "DEFAULT_PROFILE_COUNT",
    "RESEARCHED_SEMICONDUCTOR_TECH_UNIVERSE_PROFILE",
    "AI_ACCELERATOR_UNIVERSE_PROFILE",
    "LIQUID_TECH_PLATFORM_UNIVERSE_PROFILE",
    "BROAD_SEMICONDUCTOR_UNIVERSE_PROFILE",
    "PORTFOLIO_COVERAGE_UNIVERSE_PROFILE",
    "PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE",
    "PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE",
    "LARGE_CAP_UNIVERSE_PROFILES",
    "BREAKOUT_UNIVERSE_PROFILES",
    "REVERSAL_UNIVERSE_PROFILES",
    "TSMOM_UNIVERSE_PROFILES",
    "FAMILY_EXECUTION_PROFILES",
    "BASE_FAMILY_EXECUTION_PROFILES",
    "REJECTED_SIGNAL_FALSE_NEGATIVE_RESCUE_EXECUTION_PROFILES",
    "PORTFOLIO_ORACLE_COVERAGE_EXECUTION_PROFILES",
    "H_PAIRS_REPLAY_LEDGER_BREADTH_EXECUTION_PROFILES",
)
