"""Primary portfolio-oracle coverage profiles for candidate specs."""

from __future__ import annotations

from typing import Any

from .candidate_spec_profile_constants import (
    PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE as _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE,
    PORTFOLIO_COVERAGE_UNIVERSE_PROFILE as _PORTFOLIO_COVERAGE_UNIVERSE_PROFILE,
    PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE as _PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE,
)

PORTFOLIO_ORACLE_COVERAGE_EXECUTION_PROFILES_PRIMARY: dict[
    str, tuple[dict[str, Any], ...]
] = {
    "microbar_cross_sectional_pairs_v1": (
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "3.0",
            "max_notional_per_trade": "94770",
            "params": {
                "entry_minute_after_open": "45",
                "exit_minute_after_open": "close",
                "signal_motif": "open_window_continuation",
                "rank_feature": "cross_section_session_open_rank",
                "selection_mode": "continuation",
                "top_n": "3",
                "min_cross_section_continuation_rank": "0.50",
                "max_pair_legs": "4",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "300",
                "long_stop_loss_bps": "4",
                "long_trailing_stop_activation_profit_bps": "4",
                "long_trailing_stop_drawdown_bps": "2",
                "max_hold_seconds": "5400",
                "max_session_negative_exit_bps": "3",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "1200",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "2.5",
            "max_notional_per_trade": "78975",
            "params": {
                "entry_minute_after_open": "95",
                "exit_minute_after_open": "close",
                "signal_motif": "late_session_continuation",
                "rank_feature": "cross_section_session_open_rank",
                "selection_mode": "continuation",
                "top_n": "2",
                "min_cross_section_continuation_rank": "0.58",
                "max_pair_legs": "3",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "600",
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
                "max_hold_seconds": "3600",
                "max_session_negative_exit_bps": "3",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "1800",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "entry_minute_after_open": "35",
                "exit_minute_after_open": "close",
                "signal_motif": "open_window_reversal",
                "rank_feature": "cross_section_session_open_rank",
                "selection_mode": "reversal",
                "top_n": "2",
                "min_cross_section_continuation_rank": "0.40",
                "max_pair_legs": "3",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "600",
                "long_stop_loss_bps": "4",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
                "max_hold_seconds": "2700",
                "max_session_negative_exit_bps": "3",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "1800",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "entry_minute_after_open": "20",
                "entry_window_minutes": "25",
                "exit_minute_after_open": "150",
                "signal_motif": "overnight_gap_reversal",
                "rank_feature": "cross_section_prev_session_close_rank",
                "selection_mode": "reversal",
                "top_n": "2",
                "gate_feature": "cross_section_positive_opening_window_return_from_prev_close_ratio",
                "gate_min": "0.20",
                "gate_max": "0.80",
                "max_pair_legs": "3",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "900",
                "long_stop_loss_bps": "4",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
                "max_hold_seconds": "2700",
                "max_session_negative_exit_bps": "3",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "1800",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "entry_minute_after_open": "35",
                "entry_window_minutes": "25",
                "exit_minute_after_open": "180",
                "signal_motif": "opening_window_prev_close_reversal",
                "rank_feature": "cross_section_opening_window_return_from_prev_close_rank",
                "selection_mode": "reversal",
                "top_n": "2",
                "gate_feature": "cross_section_positive_opening_window_return_from_prev_close_ratio",
                "gate_min": "0.20",
                "gate_max": "0.85",
                "max_pair_legs": "3",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "900",
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
                "max_hold_seconds": "3000",
                "max_session_negative_exit_bps": "3",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "1800",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "1.75",
            "max_notional_per_trade": "55283",
            "params": {
                "entry_minute_after_open": "120",
                "entry_window_minutes": "30",
                "exit_minute_after_open": "close",
                "signal_motif": "intraday_tug_of_war_reversal",
                "rank_feature": "cross_section_prev_session_close_rank",
                "selection_mode": "reversal",
                "top_n": "2",
                "gate_feature": "cross_section_positive_opening_window_return_from_prev_close_ratio",
                "gate_min": "0.15",
                "gate_max": "0.85",
                "max_pair_legs": "3",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "1800",
                "long_stop_loss_bps": "4",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
                "max_hold_seconds": "3600",
                "max_session_negative_exit_bps": "3",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "2400",
            },
        },
    ),
    "microstructure_continuation_matched_filter_v1": (
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "3.0",
            "max_notional_per_trade": "94770",
            "params": {
                "min_cross_section_continuation_rank": "0.48",
                "min_cross_section_opening_window_return_rank": "0.40",
                "max_gross_exposure_pct_equity": "5.0",
                "entry_notional_max_multiplier": "0.70",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "300",
                "leader_reclaim_start_minutes_since_open": "20",
                "leader_reclaim_min_recent_imbalance_pressure": "0.04",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.08",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.50",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.50",
                "max_session_negative_exit_bps": "4",
                "long_stop_loss_bps": "6",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "max_position_pct_equity": "2.5",
            "max_notional_per_trade": "78975",
            "params": {
                "min_cross_section_continuation_rank": "0.58",
                "min_cross_section_opening_window_return_rank": "0.52",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_notional_max_multiplier": "0.60",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "600",
                "leader_reclaim_start_minutes_since_open": "40",
                "leader_reclaim_min_recent_imbalance_pressure": "0.06",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.10",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.55",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.55",
                "max_session_negative_exit_bps": "3",
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "signal_motif": "ofi_lob_response_continuation",
                "min_cross_section_continuation_rank": "0.42",
                "min_cross_section_opening_window_return_rank": "0.34",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_notional_max_multiplier": "0.50",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "600",
                "leader_reclaim_start_minutes_since_open": "30",
                "leader_reclaim_min_recent_imbalance_pressure": "0.02",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.04",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.48",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.48",
                "max_session_negative_exit_bps": "3",
                "long_stop_loss_bps": "4",
                "long_trailing_stop_activation_profit_bps": "4",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "signal_motif": "ofi_lob_response_continuation",
                "min_cross_section_continuation_rank": "0.50",
                "min_cross_section_opening_window_return_rank": "0.40",
                "min_recent_imbalance_pressure": "0.03",
                "min_recent_microprice_bias_bps": "0.08",
                "min_recent_above_opening_window_close_ratio": "0.48",
                "min_recent_above_vwap_w5m_ratio": "0.48",
                "max_gross_exposure_pct_equity": "3.0",
                "entry_notional_max_multiplier": "0.50",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "300",
                "max_hold_seconds": "900",
                "max_session_negative_exit_bps": "3",
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
    ),
    "opening_drive_leader_reclaim_v1": (
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "3.0",
            "max_notional_per_trade": "94770",
            "params": {
                "min_cross_section_continuation_rank": "0.48",
                "min_cross_section_opening_window_return_rank": "0.44",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_notional_max_multiplier": "0.70",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "300",
                "leader_reclaim_start_minutes_since_open": "15",
                "leader_reclaim_min_recent_imbalance_pressure": "0.03",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.06",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.48",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.46",
                "max_session_negative_exit_bps": "3",
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "4",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "max_position_pct_equity": "2.5",
            "max_notional_per_trade": "78975",
            "params": {
                "min_cross_section_continuation_rank": "0.56",
                "min_cross_section_opening_window_return_rank": "0.52",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_notional_max_multiplier": "0.60",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "600",
                "leader_reclaim_start_minutes_since_open": "25",
                "leader_reclaim_min_recent_imbalance_pressure": "0.05",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.10",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.54",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.52",
                "max_session_negative_exit_bps": "3",
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "signal_motif": "opening_ofi_leader_reclaim_continuation",
                "min_cross_section_continuation_rank": "0.42",
                "min_cross_section_opening_window_return_rank": "0.38",
                "max_gross_exposure_pct_equity": "3.0",
                "entry_notional_max_multiplier": "0.50",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "600",
                "leader_reclaim_start_minutes_since_open": "15",
                "leader_reclaim_min_recent_imbalance_pressure": "0.02",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.04",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.46",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.44",
                "max_session_negative_exit_bps": "3",
                "long_stop_loss_bps": "4",
                "long_trailing_stop_activation_profit_bps": "4",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "signal_motif": "opening_ofi_leader_reclaim_continuation",
                "min_cross_section_continuation_rank": "0.50",
                "min_cross_section_opening_window_return_rank": "0.40",
                "max_gross_exposure_pct_equity": "3.0",
                "entry_notional_max_multiplier": "0.50",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "300",
                "leader_reclaim_start_minutes_since_open": "10",
                "leader_reclaim_min_recent_imbalance_pressure": "0.03",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.06",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.48",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.46",
                "min_recent_imbalance_pressure": "0.02",
                "min_recent_microprice_bias_bps": "0.05",
                "max_session_negative_exit_bps": "3",
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
    ),
    "intraday_tsmom_v2": (
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "max_notional_per_trade": "94770",
            "max_position_pct_equity": "3.0",
            "params": {
                "long_stop_loss_bps": "6",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
                "max_session_negative_exit_bps": "4",
                "min_cross_section_continuation_rank": "0.50",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "300",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "max_notional_per_trade": "78975",
            "max_position_pct_equity": "2.5",
            "params": {
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
                "max_session_negative_exit_bps": "3",
                "min_cross_section_continuation_rank": "0.58",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "600",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_notional_per_trade": "63180",
            "max_position_pct_equity": "2.0",
            "params": {
                "long_stop_loss_bps": "4",
                "long_trailing_stop_activation_profit_bps": "4",
                "long_trailing_stop_drawdown_bps": "2",
                "max_session_negative_exit_bps": "3",
                "min_cross_section_continuation_rank": "0.42",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "600",
            },
        },
    ),
    "mean_reversion_rebound_v1": (
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "3.0",
            "max_notional_per_trade": "94770",
            "params": {
                "min_bull_rsi": "36",
                "max_bull_rsi": "52",
                "min_price_below_vwap_bps": "6",
                "max_price_below_vwap_bps": "65",
                "max_price_vs_session_open_bps": "-12",
                "max_opening_window_return_bps": "0",
                "max_cross_section_continuation_rank": "0.58",
                "min_cross_section_reversal_rank": "0.58",
                "min_recent_imbalance_pressure": "0.00",
                "entry_start_minute_utc": "810",
                "entry_end_minute_utc": "1140",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_cooldown_seconds": "450",
                "long_stop_loss_bps": "8",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "3",
                "max_session_negative_exit_bps": "5",
                "max_hold_seconds": "3600",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "max_position_pct_equity": "2.5",
            "max_notional_per_trade": "78975",
            "params": {
                "min_bull_rsi": "34",
                "max_bull_rsi": "50",
                "min_price_below_vwap_bps": "8",
                "max_price_below_vwap_bps": "80",
                "max_price_vs_session_open_bps": "-16",
                "max_opening_window_return_bps": "-2",
                "max_cross_section_continuation_rank": "0.52",
                "min_cross_section_reversal_rank": "0.62",
                "min_recent_imbalance_pressure": "-0.02",
                "entry_start_minute_utc": "825",
                "entry_end_minute_utc": "1110",
                "max_gross_exposure_pct_equity": "3.5",
                "entry_cooldown_seconds": "900",
                "long_stop_loss_bps": "7",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "3",
                "max_session_negative_exit_bps": "4",
                "max_hold_seconds": "3000",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "min_bull_rsi": "38",
                "max_bull_rsi": "54",
                "min_price_below_vwap_bps": "4",
                "max_price_below_vwap_bps": "50",
                "max_price_vs_session_open_bps": "-8",
                "max_opening_window_return_bps": "4",
                "max_cross_section_continuation_rank": "0.62",
                "min_cross_section_reversal_rank": "0.52",
                "min_recent_imbalance_pressure": "-0.04",
                "entry_start_minute_utc": "810",
                "entry_end_minute_utc": "1080",
                "max_gross_exposure_pct_equity": "3.0",
                "entry_cooldown_seconds": "900",
                "long_stop_loss_bps": "6",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
                "max_session_negative_exit_bps": "3",
                "max_hold_seconds": "2400",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "drive_reference_basis": "prev_close",
                "opening_window_reference_basis": "prev_close",
                "opening_window_rank_reference_basis": "prev_close",
                "min_bull_rsi": "34",
                "max_bull_rsi": "54",
                "min_price_below_vwap_bps": "4",
                "max_price_below_vwap_bps": "72",
                "max_price_vs_session_open_bps": "-18",
                "max_opening_window_return_bps": "-4",
                "max_cross_section_continuation_rank": "0.50",
                "min_cross_section_reversal_rank": "0.60",
                "min_recent_imbalance_pressure": "-0.03",
                "entry_start_minute_utc": "840",
                "entry_end_minute_utc": "1020",
                "max_gross_exposure_pct_equity": "3.0",
                "entry_cooldown_seconds": "1200",
                "long_stop_loss_bps": "6",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "2",
                "max_session_negative_exit_bps": "3",
                "max_hold_seconds": "2700",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "max_position_pct_equity": "1.75",
            "max_notional_per_trade": "55283",
            "params": {
                "drive_reference_basis": "prev_close",
                "opening_window_reference_basis": "prev_close",
                "opening_window_rank_reference_basis": "prev_close",
                "min_bull_rsi": "32",
                "max_bull_rsi": "50",
                "min_price_below_vwap_bps": "8",
                "max_price_below_vwap_bps": "90",
                "max_price_vs_session_open_bps": "-24",
                "max_opening_window_return_bps": "-8",
                "max_cross_section_continuation_rank": "0.45",
                "min_cross_section_reversal_rank": "0.66",
                "min_recent_imbalance_pressure": "-0.04",
                "entry_start_minute_utc": "855",
                "entry_end_minute_utc": "1050",
                "max_gross_exposure_pct_equity": "2.75",
                "entry_cooldown_seconds": "1800",
                "long_stop_loss_bps": "6",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "2",
                "max_session_negative_exit_bps": "3",
                "max_hold_seconds": "2400",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "1.5",
            "max_notional_per_trade": "47385",
            "params": {
                "drive_reference_basis": "prev_close",
                "opening_window_reference_basis": "prev_close",
                "opening_window_rank_reference_basis": "prev_close",
                "min_bull_rsi": "38",
                "max_bull_rsi": "56",
                "min_price_below_vwap_bps": "3",
                "max_price_below_vwap_bps": "55",
                "max_price_vs_session_open_bps": "-12",
                "max_opening_window_return_bps": "0",
                "max_cross_section_continuation_rank": "0.55",
                "min_cross_section_reversal_rank": "0.55",
                "min_recent_imbalance_pressure": "-0.05",
                "entry_start_minute_utc": "870",
                "entry_end_minute_utc": "1080",
                "max_gross_exposure_pct_equity": "2.5",
                "entry_cooldown_seconds": "1800",
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
                "max_session_negative_exit_bps": "3",
                "max_hold_seconds": "2400",
            },
        },
    ),
    "breakout_reclaim_v2": (
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "4.0",
            "max_notional_per_trade": "126360",
            "params": {
                "min_cross_section_continuation_rank": "0.50",
                "min_cross_section_opening_window_return_rank": "0.45",
                "max_gross_exposure_pct_equity": "6.0",
                "entry_notional_max_multiplier": "0.80",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "300",
                "max_session_negative_exit_bps": "5",
                "leader_reclaim_start_minutes_since_open": "25",
                "leader_reclaim_min_recent_imbalance_pressure": "0.05",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.12",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.54",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.52",
                "long_stop_loss_bps": "6",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "max_position_pct_equity": "2.5",
            "max_notional_per_trade": "78975",
            "params": {
                "min_cross_section_continuation_rank": "0.62",
                "min_cross_section_opening_window_return_rank": "0.58",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_notional_max_multiplier": "0.60",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "600",
                "max_session_negative_exit_bps": "3",
                "leader_reclaim_start_minutes_since_open": "40",
                "leader_reclaim_min_recent_imbalance_pressure": "0.08",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.14",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.58",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.56",
                "long_stop_loss_bps": "5",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "min_cross_section_continuation_rank": "0.42",
                "min_cross_section_opening_window_return_rank": "0.36",
                "max_gross_exposure_pct_equity": "3.5",
                "entry_notional_max_multiplier": "0.50",
                "max_entries_per_session": "4",
                "entry_cooldown_seconds": "600",
                "max_session_negative_exit_bps": "3",
                "leader_reclaim_start_minutes_since_open": "30",
                "leader_reclaim_min_recent_imbalance_pressure": "0.02",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.04",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.48",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.48",
                "long_stop_loss_bps": "4",
                "long_trailing_stop_activation_profit_bps": "4",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
    ),
    "washout_rebound_v2": (
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "max_notional_per_trade": "94770",
            "max_position_pct_equity": "3.0",
            "params": {
                "min_session_open_selloff_bps": "12",
                "max_price_vs_session_low_bps": "48",
                "min_recent_microprice_bias_bps": "0.00",
                "min_cross_section_reversal_rank": "0.55",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "max_notional_per_trade": "78975",
            "max_position_pct_equity": "2.5",
            "params": {
                "min_session_open_selloff_bps": "18",
                "max_price_vs_session_low_bps": "55",
                "min_recent_microprice_bias_bps": "0.02",
                "min_cross_section_reversal_rank": "0.62",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_notional_per_trade": "63180",
            "max_position_pct_equity": "2.0",
            "params": {
                "min_session_open_selloff_bps": "8",
                "max_price_vs_session_low_bps": "40",
                "min_recent_microprice_bias_bps": "-0.02",
                "min_cross_section_reversal_rank": "0.50",
            },
        },
    ),
}

__all__ = ("PORTFOLIO_ORACLE_COVERAGE_EXECUTION_PROFILES_PRIMARY",)
