from __future__ import annotations

# pyright: reportMissingImports=false, reportMissingTypeStubs=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportUnnecessaryComparison=false, reportUnnecessaryCast=false
# ruff: noqa: F401, F811
from typing import Any
import hashlib
import json
from dataclasses import dataclass
from decimal import Decimal
from typing import Any, Literal, Mapping, Sequence, cast
from app.trading.discovery.capital_budget import estimate_capital_pressure
from app.trading.discovery.factor_acceptance import build_factor_acceptance_artifact
from app.trading.discovery.hypothesis_cards import HypothesisCard
from app.trading.discovery.replay_tape import (
    HPAIRS_REPLAY_TAPE_FEATURE_SCHEMA_VERSION,
    build_hpairs_replay_tape_feature_schema_hash,
    hpairs_replay_tape_feature_versions,
)
from app.trading.semiconductor_universe import (
    LIVE_SIGNAL_COVERED_SEMICONDUCTOR_UNIVERSE as LIVE_SIGNAL_COVERED_SEMICONDUCTOR_UNIVERSE,
    RESEARCHED_SEMICONDUCTOR_TECH_UNIVERSE,
)

CANDIDATE_SPEC_SCHEMA_VERSION: Any
_FAMILY_RUNTIME: Any
_FAMILY_TIEBREAK: Any
_MAX_FAMILIES_PER_HYPOTHESIS: Any
_PORTFOLIO_TARGET_NET_PNL_PER_DAY: Any
_PORTFOLIO_SLEEVE_FAMILY_TARGET: Any
_PORTFOLIO_SLEEVE_FAMILY_ORDER: Any
_DEFAULT_PROFILE_COUNT: Any
_RESEARCHED_SEMICONDUCTOR_TECH_UNIVERSE: Any
_AI_ACCELERATOR_UNIVERSE_PROFILE: tuple[str, ...]
_LIQUID_TECH_PLATFORM_UNIVERSE_PROFILE: tuple[str, ...]
_BROAD_SEMICONDUCTOR_UNIVERSE_PROFILE: tuple[str, ...]
_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE: tuple[str, ...]
_PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE: Any
_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE: Any
_LARGE_CAP_UNIVERSE_PROFILES: tuple[tuple[str, ...], ...]
_BREAKOUT_UNIVERSE_PROFILES: tuple[tuple[str, ...], ...]
_REVERSAL_UNIVERSE_PROFILES: tuple[tuple[str, ...], ...]
_TSMOM_UNIVERSE_PROFILES: tuple[tuple[str, ...], ...]
_FAMILY_EXECUTION_PROFILES: dict[str, tuple[dict[str, Any], ...]]
_BASE_FAMILY_EXECUTION_PROFILES: Any
_REJECTED_SIGNAL_FALSE_NEGATIVE_RESCUE_EXECUTION_PROFILES: dict[
    str, tuple[dict[str, Any], ...]
]
_PORTFOLIO_ORACLE_COVERAGE_EXECUTION_PROFILES: dict[str, tuple[dict[str, Any], ...]]
_H_PAIRS_REPLAY_LEDGER_BREADTH_EXECUTION_PROFILES: tuple[dict[str, Any], ...]

def _stable_hash(*args: Any, **kwargs: Any) -> Any: ...
def _stable_int(*args: Any, **kwargs: Any) -> Any: ...
def _string(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _string_sequence(*args: Any, **kwargs: Any) -> Any: ...
def _format_profile_budget(*args: Any, **kwargs: Any) -> Any: ...
def _profile_rank_count_floor(*args: Any, **kwargs: Any) -> Any: ...
def _capital_limited_profile_values(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_profile_param(*args: Any, **kwargs: Any) -> Any: ...
def _int_profile_param(*args: Any, **kwargs: Any) -> Any: ...
def _clamped_profile_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _cash_constrain_profile(*args: Any, **kwargs: Any) -> Any: ...
def _drop_fragile_prev_close_positive_gate(*args: Any, **kwargs: Any) -> Any: ...
def _daily_coverage_feedback_escape_profile(*args: Any, **kwargs: Any) -> Any: ...
def _consistency_guard_feedback_escape_profile(*args: Any, **kwargs: Any) -> Any: ...
def _turnover_coverage_feedback_escape_profile(*args: Any, **kwargs: Any) -> Any: ...
def _notional_throughput_feedback_escape_profile(*args: Any, **kwargs: Any) -> Any: ...
def _adverse_selection_feedback_escape_profile(*args: Any, **kwargs: Any) -> Any: ...
def _symbol_diversification_feedback_escape_profile(
    *args: Any, **kwargs: Any
) -> Any: ...
def _portfolio_feedback_escape_execution_profiles(*args: Any, **kwargs: Any) -> Any: ...
def _capital_constrained_execution_profiles(*args: Any, **kwargs: Any) -> Any: ...
def _universe_symbol_override(*args: Any, **kwargs: Any) -> Any: ...
def _list_of_mappings(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_haystack(*args: Any, **kwargs: Any) -> Any: ...
def _has_rejected_signal_outcome_calibration(*args: Any, **kwargs: Any) -> Any: ...
def _normalization_candidates_for_card(*args: Any, **kwargs: Any) -> Any: ...
def _requires_synthetic_validation_only_policy(*args: Any, **kwargs: Any) -> Any: ...
def _is_validation_or_execution_constraint_only(*args: Any, **kwargs: Any) -> Any: ...
def _paper_mechanism_haystack(*args: Any, **kwargs: Any) -> Any: ...
def _requires_factor_acceptance_harness(*args: Any, **kwargs: Any) -> Any: ...
def _factor_acceptance_dependencies(*args: Any, **kwargs: Any) -> Any: ...
def _factor_acceptance_expression(*args: Any, **kwargs: Any) -> Any: ...
def _apply_factor_acceptance_harness(*args: Any, **kwargs: Any) -> Any: ...
def _mechanism_overlays_for_card(*args: Any, **kwargs: Any) -> Any: ...
def _apply_mechanism_overlay_strategy_params(*args: Any, **kwargs: Any) -> Any: ...
def _family_scores_for_hypothesis(*args: Any, **kwargs: Any) -> Any: ...
def _families_for_hypothesis(*args: Any, **kwargs: Any) -> Any: ...
def _execution_profile_index(*args: Any, **kwargs: Any) -> Any: ...
def _execution_profile_indexes(*args: Any, **kwargs: Any) -> Any: ...
def _execution_profile_id(*args: Any, **kwargs: Any) -> Any: ...
def _execution_profiles_for_target(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_overrides_for_profile(*args: Any, **kwargs: Any) -> Any: ...

class CandidateSpec:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    schema_version: Literal["torghut.candidate-spec.v1"]
    candidate_spec_id: str
    hypothesis_id: str
    family_template_id: str
    candidate_kind: Literal[
        "family", "sleeve", "portfolio", "algorithm", "configuration"
    ]
    runtime_family: str
    runtime_strategy_name: str
    feature_contract: Mapping[str, Any]
    parameter_space: Mapping[str, Any]
    strategy_overrides: Mapping[str, Any]
    objective: Mapping[str, Any]
    hard_vetoes: Mapping[str, Any]
    expected_failure_modes: tuple[str, ...]
    promotion_contract: Mapping[str, Any]
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...
    def to_vnext_experiment_payload(*args: Any, **kwargs: Any) -> Any: ...

def candidate_spec_id_for_payload(*args: Any, **kwargs: Any) -> Any: ...
def compile_candidate_specs(*args: Any, **kwargs: Any) -> Any: ...
def candidate_spec_from_payload(*args: Any, **kwargs: Any) -> Any: ...
