"""Primary base execution profiles for candidate specs."""

from __future__ import annotations

from typing import Any

from .candidate_spec_profile_constants import (
    BREAKOUT_UNIVERSE_PROFILES as _BREAKOUT_UNIVERSE_PROFILES,
    LARGE_CAP_UNIVERSE_PROFILES as _LARGE_CAP_UNIVERSE_PROFILES,
    PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE as _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE,
    PORTFOLIO_COVERAGE_UNIVERSE_PROFILE as _PORTFOLIO_COVERAGE_UNIVERSE_PROFILE,
    PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE as _PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE,
    REVERSAL_UNIVERSE_PROFILES as _REVERSAL_UNIVERSE_PROFILES,
    TSMOM_UNIVERSE_PROFILES as _TSMOM_UNIVERSE_PROFILES,
)

BASE_FAMILY_EXECUTION_PROFILES_PRIMARY: dict[str, tuple[dict[str, Any], ...]] = {
    "microbar_cross_sectional_pairs_v1": (
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[0]),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "6.0",
            "max_notional_per_trade": "157950.10",
            "params": {
                "entry_minute_after_open": "60",
                "exit_minute_after_open": "120",
                "signal_motif": "vwap_close_continuation",
                "rank_feature": "cross_section_vwap_w5m_rank",
                "selection_mode": "continuation",
                "top_n": "1",
                "min_cross_section_continuation_rank": "0.55",
                "max_pair_legs": "2",
                "max_entries_per_session": "1",
                "entry_cooldown_seconds": "600",
                "long_stop_loss_bps": "10",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
                "max_hold_seconds": "7200",
                "max_session_negative_exit_bps": "10",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "1800",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[1]),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "8.0",
            "max_notional_per_trade": "236925.15",
            "params": {
                "entry_minute_after_open": "75",
                "exit_minute_after_open": "close",
                "signal_motif": "open_window_continuation",
                "rank_feature": "cross_section_session_open_rank",
                "selection_mode": "continuation",
                "top_n": "2",
                "min_cross_section_continuation_rank": "0.65",
                "max_pair_legs": "3",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "900",
                "long_stop_loss_bps": "10",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
                "max_hold_seconds": "7200",
                "max_session_negative_exit_bps": "8",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "1800",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[2]),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "6.0",
            "max_notional_per_trade": "157950.10",
            "params": {
                "entry_minute_after_open": "75",
                "exit_minute_after_open": "120",
                "signal_motif": "vwap_close_continuation",
                "rank_feature": "cross_section_session_open_rank",
                "selection_mode": "continuation",
                "top_n": "1",
                "min_cross_section_continuation_rank": "0.60",
                "max_pair_legs": "2",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "600",
                "long_stop_loss_bps": "8",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "3",
                "max_hold_seconds": "5400",
                "max_session_negative_exit_bps": "8",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "1800",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[2]),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "4.0",
            "max_notional_per_trade": "126360",
            "params": {
                "entry_minute_after_open": "45",
                "exit_minute_after_open": "150",
                "signal_motif": "open_window_reversal",
                "rank_feature": "cross_section_session_open_rank",
                "selection_mode": "reversal",
                "top_n": "2",
                "max_cross_section_continuation_rank": "0.45",
                "min_cross_section_reversal_rank": "0.70",
                "max_pair_legs": "4",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "1200",
                "long_stop_loss_bps": "8",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "3",
                "max_hold_seconds": "5400",
                "max_session_negative_exit_bps": "6",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "2700",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[0]),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "4.0",
            "max_notional_per_trade": "94770",
            "params": {
                "entry_minute_after_open": "90",
                "exit_minute_after_open": "close",
                "signal_motif": "vwap_close_reversal",
                "rank_feature": "cross_section_vwap_w5m_rank",
                "selection_mode": "reversal",
                "top_n": "1",
                "max_cross_section_continuation_rank": "0.40",
                "min_cross_section_reversal_rank": "0.78",
                "max_pair_legs": "2",
                "max_entries_per_session": "1",
                "entry_cooldown_seconds": "1800",
                "long_stop_loss_bps": "6",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "3",
                "max_hold_seconds": "3600",
                "max_session_negative_exit_bps": "5",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "3600",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[0]),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "4.0",
            "max_notional_per_trade": "94770",
            "params": {
                "entry_minute_after_open": "60",
                "exit_minute_after_open": "150",
                "signal_motif": "factor_neutral_residual_continuation",
                "rank_feature": "cross_section_factor_neutral_residual_rank",
                "selection_mode": "continuation",
                "top_n": "1",
                "min_cross_section_continuation_rank": "0.65",
                "max_pair_legs": "2",
                "max_entries_per_session": "1",
                "entry_cooldown_seconds": "900",
                "long_stop_loss_bps": "8",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "3",
                "max_hold_seconds": "5400",
                "max_session_negative_exit_bps": "6",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "2700",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[2]),
            "normalization_regime": "market_neutral_gross_scaled",
            "max_position_pct_equity": "3.0",
            "max_notional_per_trade": "63180",
            "params": {
                "entry_minute_after_open": "75",
                "exit_minute_after_open": "150",
                "signal_motif": "residual_spread_reversion",
                "rank_feature": "cross_section_residual_spread_zscore_rank",
                "selection_mode": "reversal",
                "top_n": "1",
                "max_cross_section_continuation_rank": "0.35",
                "min_cross_section_reversal_rank": "0.75",
                "max_pair_legs": "2",
                "max_entries_per_session": "1",
                "entry_cooldown_seconds": "1800",
                "long_stop_loss_bps": "6",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "3",
                "max_hold_seconds": "3600",
                "max_session_negative_exit_bps": "5",
                "max_stop_loss_exits_per_session": "1",
                "stop_loss_lockout_seconds": "3600",
            },
        },
    ),
    "microstructure_continuation_matched_filter_v1": (
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[0]),
            "max_position_pct_equity": "8.0",
            "max_notional_per_trade": "157950.10",
            "params": {
                "min_cross_section_continuation_rank": "0.55",
                "min_cross_section_opening_window_return_rank": "0.45",
                "max_gross_exposure_pct_equity": "8.0",
                "entry_notional_max_multiplier": "1.00",
                "max_entries_per_session": "1",
                "entry_cooldown_seconds": "600",
                "leader_reclaim_start_minutes_since_open": "30",
                "leader_reclaim_min_recent_imbalance_pressure": "0.08",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.15",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.55",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.55",
                "long_stop_loss_bps": "10",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "3",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[1]),
            "max_position_pct_equity": "10.0",
            "max_notional_per_trade": "236925.15",
            "params": {
                "min_cross_section_continuation_rank": "0.65",
                "min_cross_section_opening_window_return_rank": "0.55",
                "max_gross_exposure_pct_equity": "10.0",
                "entry_notional_max_multiplier": "1.25",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "900",
                "leader_reclaim_start_minutes_since_open": "45",
                "leader_reclaim_min_recent_imbalance_pressure": "0.12",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.25",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.65",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.65",
                "long_stop_loss_bps": "12",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[2]),
            "max_position_pct_equity": "8.0",
            "max_notional_per_trade": "236925.15",
            "params": {
                "min_cross_section_continuation_rank": "0.60",
                "min_cross_section_opening_window_return_rank": "0.50",
                "max_gross_exposure_pct_equity": "8.0",
                "entry_notional_max_multiplier": "1.25",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "600",
                "leader_reclaim_start_minutes_since_open": "45",
                "leader_reclaim_min_recent_imbalance_pressure": "0.10",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.20",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.60",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.60",
                "long_stop_loss_bps": "10",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "3",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[2]),
            "max_position_pct_equity": "4.0",
            "max_notional_per_trade": "126360",
            "params": {
                "min_cross_section_continuation_rank": "0.52",
                "min_cross_section_opening_window_return_rank": "0.45",
                "max_gross_exposure_pct_equity": "6.0",
                "entry_notional_max_multiplier": "0.80",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "450",
                "leader_reclaim_start_minutes_since_open": "30",
                "leader_reclaim_min_recent_imbalance_pressure": "0.06",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.10",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.52",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.52",
                "max_session_negative_exit_bps": "6",
                "long_stop_loss_bps": "8",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "3",
            },
        },
        {
            "universe_symbols": list(_LARGE_CAP_UNIVERSE_PROFILES[1]),
            "max_position_pct_equity": "6.0",
            "max_notional_per_trade": "189540",
            "params": {
                "min_cross_section_continuation_rank": "0.70",
                "min_cross_section_opening_window_return_rank": "0.60",
                "max_gross_exposure_pct_equity": "8.0",
                "entry_notional_max_multiplier": "1.00",
                "max_entries_per_session": "1",
                "entry_cooldown_seconds": "1200",
                "leader_reclaim_start_minutes_since_open": "60",
                "leader_reclaim_min_recent_imbalance_pressure": "0.16",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.35",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.70",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.70",
                "max_session_negative_exit_bps": "8",
                "long_stop_loss_bps": "10",
                "long_trailing_stop_activation_profit_bps": "10",
                "long_trailing_stop_drawdown_bps": "4",
            },
        },
    ),
    "opening_drive_leader_reclaim_v1": (
        {
            "universe_symbols": list(_PORTFOLIO_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "6.0",
            "max_notional_per_trade": "189540",
            "params": {
                "min_cross_section_continuation_rank": "0.58",
                "min_cross_section_opening_window_return_rank": "0.54",
                "max_gross_exposure_pct_equity": "6.0",
                "entry_notional_max_multiplier": "1.00",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "600",
                "leader_reclaim_start_minutes_since_open": "20",
                "leader_reclaim_min_recent_imbalance_pressure": "0.06",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.12",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.54",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.52",
                "max_session_negative_exit_bps": "6",
                "long_stop_loss_bps": "8",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "3",
            },
        },
        {
            "universe_symbols": list(
                _PORTFOLIO_AI_ACCELERATOR_COVERAGE_UNIVERSE_PROFILE
            ),
            "max_position_pct_equity": "5.0",
            "max_notional_per_trade": "157950",
            "params": {
                "min_cross_section_continuation_rank": "0.64",
                "min_cross_section_opening_window_return_rank": "0.60",
                "max_gross_exposure_pct_equity": "5.0",
                "entry_notional_max_multiplier": "0.90",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "900",
                "leader_reclaim_start_minutes_since_open": "30",
                "leader_reclaim_min_recent_imbalance_pressure": "0.08",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.16",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.58",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.56",
                "max_session_negative_exit_bps": "5",
                "long_stop_loss_bps": "7",
                "long_trailing_stop_activation_profit_bps": "6",
                "long_trailing_stop_drawdown_bps": "3",
            },
        },
        {
            "universe_symbols": list(_PORTFOLIO_PLATFORM_COVERAGE_UNIVERSE_PROFILE),
            "max_position_pct_equity": "4.0",
            "max_notional_per_trade": "126360",
            "params": {
                "min_cross_section_continuation_rank": "0.52",
                "min_cross_section_opening_window_return_rank": "0.48",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_notional_max_multiplier": "0.80",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "600",
                "leader_reclaim_start_minutes_since_open": "15",
                "leader_reclaim_min_recent_imbalance_pressure": "0.04",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.08",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.50",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.48",
                "max_session_negative_exit_bps": "4",
                "long_stop_loss_bps": "6",
                "long_trailing_stop_activation_profit_bps": "5",
                "long_trailing_stop_drawdown_bps": "2",
            },
        },
    ),
    "intraday_tsmom_v2": (
        {
            "universe_symbols": list(_TSMOM_UNIVERSE_PROFILES[0]),
            "max_notional_per_trade": "15000",
            "max_position_pct_equity": "1.5",
            "params": {
                "long_stop_loss_bps": "12",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
                "max_session_negative_exit_bps": "8",
                "min_cross_section_continuation_rank": "0.60",
            },
        },
        {
            "universe_symbols": list(_TSMOM_UNIVERSE_PROFILES[1]),
            "max_notional_per_trade": "25000",
            "max_position_pct_equity": "2.0",
            "params": {
                "long_stop_loss_bps": "18",
                "long_trailing_stop_activation_profit_bps": "12",
                "long_trailing_stop_drawdown_bps": "6",
                "max_session_negative_exit_bps": "12",
                "min_cross_section_continuation_rank": "0.70",
            },
        },
        {
            "universe_symbols": list(_TSMOM_UNIVERSE_PROFILES[2]),
            "max_notional_per_trade": "35000",
            "max_position_pct_equity": "2.0",
            "params": {
                "long_stop_loss_bps": "12",
                "long_trailing_stop_activation_profit_bps": "12",
                "long_trailing_stop_drawdown_bps": "4",
                "max_session_negative_exit_bps": "8",
                "min_cross_section_continuation_rank": "0.65",
            },
        },
        {
            "universe_symbols": list(_TSMOM_UNIVERSE_PROFILES[1]),
            "max_notional_per_trade": "63180",
            "max_position_pct_equity": "3.0",
            "params": {
                "long_stop_loss_bps": "10",
                "long_trailing_stop_activation_profit_bps": "10",
                "long_trailing_stop_drawdown_bps": "4",
                "max_session_negative_exit_bps": "6",
                "min_cross_section_continuation_rank": "0.55",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "600",
            },
        },
        {
            "universe_symbols": list(_TSMOM_UNIVERSE_PROFILES[2]),
            "max_notional_per_trade": "126360",
            "max_position_pct_equity": "4.0",
            "params": {
                "long_stop_loss_bps": "14",
                "long_trailing_stop_activation_profit_bps": "10",
                "long_trailing_stop_drawdown_bps": "5",
                "max_session_negative_exit_bps": "8",
                "min_cross_section_continuation_rank": "0.62",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "900",
            },
        },
    ),
    "mean_reversion_rebound_v1": (
        {
            "universe_symbols": list(_REVERSAL_UNIVERSE_PROFILES[1]),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "min_bull_rsi": "40",
                "max_bull_rsi": "50",
                "min_price_below_vwap_bps": "8",
                "max_price_below_vwap_bps": "40",
                "max_price_vs_session_open_bps": "-20",
                "max_opening_window_return_bps": "-5",
                "max_cross_section_continuation_rank": "0.45",
                "min_cross_section_reversal_rank": "0.70",
                "min_recent_imbalance_pressure": "0.02",
                "entry_start_minute_utc": "840",
                "entry_end_minute_utc": "1080",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_cooldown_seconds": "900",
            },
        },
        {
            "universe_symbols": list(_REVERSAL_UNIVERSE_PROFILES[2]),
            "max_position_pct_equity": "4.0",
            "max_notional_per_trade": "126360",
            "params": {
                "min_bull_rsi": "43",
                "max_bull_rsi": "50",
                "min_price_below_vwap_bps": "12",
                "max_price_below_vwap_bps": "55",
                "max_price_vs_session_open_bps": "-30",
                "max_opening_window_return_bps": "-10",
                "max_cross_section_continuation_rank": "0.55",
                "min_cross_section_reversal_rank": "0.78",
                "min_recent_imbalance_pressure": "0.03",
                "entry_start_minute_utc": "840",
                "entry_end_minute_utc": "1080",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_cooldown_seconds": "1200",
            },
        },
        {
            "universe_symbols": list(_REVERSAL_UNIVERSE_PROFILES[2]),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "126360",
            "params": {
                "min_bull_rsi": "40",
                "max_bull_rsi": "50",
                "min_price_below_vwap_bps": "12",
                "max_price_below_vwap_bps": "40",
                "max_price_vs_session_open_bps": "-30",
                "max_opening_window_return_bps": "-5",
                "max_cross_section_continuation_rank": "0.45",
                "min_cross_section_reversal_rank": "0.78",
                "min_recent_imbalance_pressure": "0.02",
                "entry_start_minute_utc": "840",
                "entry_end_minute_utc": "1080",
                "max_gross_exposure_pct_equity": "4.0",
                "entry_cooldown_seconds": "900",
            },
        },
        {
            "universe_symbols": list(_REVERSAL_UNIVERSE_PROFILES[1]),
            "max_position_pct_equity": "2.0",
            "max_notional_per_trade": "63180",
            "params": {
                "min_bull_rsi": "36",
                "max_bull_rsi": "48",
                "min_price_below_vwap_bps": "10",
                "max_price_below_vwap_bps": "50",
                "max_price_vs_session_open_bps": "-25",
                "max_opening_window_return_bps": "-15",
                "max_cross_section_continuation_rank": "0.50",
                "min_cross_section_reversal_rank": "0.65",
                "min_recent_imbalance_pressure": "0.01",
                "entry_start_minute_utc": "870",
                "entry_end_minute_utc": "1110",
                "max_gross_exposure_pct_equity": "3.0",
                "entry_cooldown_seconds": "600",
                "long_stop_loss_bps": "10",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
                "max_session_negative_exit_bps": "8",
                "max_hold_seconds": "3600",
            },
        },
        {
            "universe_symbols": list(_REVERSAL_UNIVERSE_PROFILES[0]),
            "max_position_pct_equity": "3.0",
            "max_notional_per_trade": "94770",
            "params": {
                "min_bull_rsi": "42",
                "max_bull_rsi": "50",
                "min_price_below_vwap_bps": "18",
                "max_price_below_vwap_bps": "60",
                "max_price_vs_session_open_bps": "-35",
                "max_opening_window_return_bps": "-20",
                "max_cross_section_continuation_rank": "0.42",
                "min_cross_section_reversal_rank": "0.82",
                "min_recent_imbalance_pressure": "0.04",
                "entry_start_minute_utc": "900",
                "entry_end_minute_utc": "1140",
                "max_gross_exposure_pct_equity": "3.0",
                "entry_cooldown_seconds": "1800",
                "long_stop_loss_bps": "12",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
                "max_session_negative_exit_bps": "8",
                "max_hold_seconds": "2700",
            },
        },
    ),
    "breakout_reclaim_v2": (
        {
            "universe_symbols": list(_BREAKOUT_UNIVERSE_PROFILES[0]),
            "max_position_pct_equity": "10.0",
            "max_notional_per_trade": "315900.20",
            "params": {
                "min_cross_section_continuation_rank": "0.60",
                "min_cross_section_opening_window_return_rank": "0.50",
                "max_gross_exposure_pct_equity": "10.0",
                "entry_notional_max_multiplier": "1.50",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "600",
                "max_session_negative_exit_bps": "8",
                "leader_reclaim_start_minutes_since_open": "45",
                "leader_reclaim_min_recent_imbalance_pressure": "0.10",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.25",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.65",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.60",
                "long_stop_loss_bps": "12",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
            },
        },
        {
            "universe_symbols": list(_BREAKOUT_UNIVERSE_PROFILES[1]),
            "max_position_pct_equity": "10.0",
            "max_notional_per_trade": "315900.20",
            "params": {
                "min_cross_section_continuation_rank": "0.60",
                "min_cross_section_opening_window_return_rank": "0.50",
                "max_gross_exposure_pct_equity": "10.0",
                "entry_notional_max_multiplier": "1.50",
                "max_entries_per_session": "3",
                "entry_cooldown_seconds": "900",
                "max_session_negative_exit_bps": "8",
                "leader_reclaim_start_minutes_since_open": "60",
                "leader_reclaim_min_recent_imbalance_pressure": "0.10",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.35",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.65",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.60",
                "long_stop_loss_bps": "12",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
            },
        },
        {
            "universe_symbols": list(_BREAKOUT_UNIVERSE_PROFILES[2]),
            "max_position_pct_equity": "10.0",
            "max_notional_per_trade": "315900.20",
            "params": {
                "min_cross_section_continuation_rank": "0.60",
                "min_cross_section_opening_window_return_rank": "0.50",
                "max_gross_exposure_pct_equity": "10.0",
                "entry_notional_max_multiplier": "1.50",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "900",
                "max_session_negative_exit_bps": "8",
                "leader_reclaim_start_minutes_since_open": "60",
                "leader_reclaim_min_recent_imbalance_pressure": "0.10",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.25",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.65",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.60",
                "long_stop_loss_bps": "12",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
            },
        },
        {
            "universe_symbols": list(_BREAKOUT_UNIVERSE_PROFILES[2]),
            "max_position_pct_equity": "4.0",
            "max_notional_per_trade": "126360",
            "params": {
                "min_cross_section_continuation_rank": "0.68",
                "min_cross_section_opening_window_return_rank": "0.58",
                "max_gross_exposure_pct_equity": "6.0",
                "entry_notional_max_multiplier": "0.80",
                "max_entries_per_session": "1",
                "entry_cooldown_seconds": "1200",
                "max_session_negative_exit_bps": "6",
                "leader_reclaim_start_minutes_since_open": "45",
                "leader_reclaim_min_recent_imbalance_pressure": "0.14",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.30",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.70",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.68",
                "long_stop_loss_bps": "8",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "3",
            },
        },
        {
            "universe_symbols": list(_BREAKOUT_UNIVERSE_PROFILES[1]),
            "max_position_pct_equity": "6.0",
            "max_notional_per_trade": "189540",
            "params": {
                "min_cross_section_continuation_rank": "0.62",
                "min_cross_section_opening_window_return_rank": "0.52",
                "max_gross_exposure_pct_equity": "8.0",
                "entry_notional_max_multiplier": "1.00",
                "max_entries_per_session": "2",
                "entry_cooldown_seconds": "600",
                "max_session_negative_exit_bps": "8",
                "leader_reclaim_start_minutes_since_open": "30",
                "leader_reclaim_min_recent_imbalance_pressure": "0.08",
                "leader_reclaim_min_recent_microprice_bias_bps": "0.20",
                "leader_reclaim_min_recent_above_opening_window_close_ratio": "0.60",
                "leader_reclaim_min_recent_above_vwap_w5m_ratio": "0.58",
                "long_stop_loss_bps": "10",
                "long_trailing_stop_activation_profit_bps": "8",
                "long_trailing_stop_drawdown_bps": "4",
            },
        },
    ),
    "washout_rebound_v2": (
        {
            "universe_symbols": list(_REVERSAL_UNIVERSE_PROFILES[0]),
            "max_notional_per_trade": "47385",
            "max_position_pct_equity": "1.5",
            "params": {
                "min_session_open_selloff_bps": "20",
                "max_price_vs_session_low_bps": "24",
                "min_recent_microprice_bias_bps": "0.05",
                "min_cross_section_reversal_rank": "0.65",
            },
        },
        {
            "universe_symbols": list(_REVERSAL_UNIVERSE_PROFILES[1]),
            "max_notional_per_trade": "63180",
            "max_position_pct_equity": "2.0",
            "params": {
                "min_session_open_selloff_bps": "28",
                "max_price_vs_session_low_bps": "36",
                "min_recent_microprice_bias_bps": "0.15",
                "min_cross_section_reversal_rank": "0.75",
            },
        },
        {
            "universe_symbols": list(_REVERSAL_UNIVERSE_PROFILES[2]),
            "max_notional_per_trade": "63180",
            "max_position_pct_equity": "1.5",
            "params": {
                "min_session_open_selloff_bps": "28",
                "max_price_vs_session_low_bps": "24",
                "min_recent_microprice_bias_bps": "0.10",
                "min_cross_section_reversal_rank": "0.70",
            },
        },
    ),
}

__all__ = ("BASE_FAMILY_EXECUTION_PROFILES_PRIMARY",)
