from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import hashlib
import importlib
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any, Mapping, Sequence, cast
from app.trading.discovery.candidate_specs import CandidateSpec
from app.trading.discovery.capital_budget import estimate_capital_budget
from app.trading.discovery.evidence_bundles import CandidateEvidenceBundle
from app.trading.discovery.objectives import (
    deployable_lower_bound_missing_count,
    deployable_lower_bound_net_pnl_per_day,
    deployable_proof_failed_gate_count,
)

MLX_RANKER_SCHEMA_VERSION: Any
_MECHANISM_OVERLAY_IDS: Any
_MECHANISM_OVERLAY_FEATURE_NAMES: Any
_PAPER_CONTRACT_FEATURE_NAMES: Any

def _stable_hash(*args: Any, **kwargs: Any) -> Any: ...

class _TorchArrayBackend:
    float32: Any
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def array(*args: Any, **kwargs: Any) -> Any: ...
    def zeros(*args: Any, **kwargs: Any) -> Any: ...

def _import_torch_array_backend(*args: Any, **kwargs: Any) -> Any: ...
def _import_array_backend(*args: Any, **kwargs: Any) -> Any: ...

class MlxTrainingRow:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    candidate_spec_id: str
    feature_names: tuple[str, ...]
    feature_values: tuple[float, ...]
    target: float
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class MlxRankerModel:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    schema_version: str
    model_id: str
    backend: str
    feature_names: tuple[str, ...]
    feature_means: tuple[float, ...]
    feature_scales: tuple[float, ...]
    target_mean: float
    target_scale: float
    weights: tuple[float, ...]
    bias: float
    row_count: int
    training_loss: float
    trained_at: str
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class MlxRankedCandidate:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    candidate_spec_id: str
    score: float
    rank: int
    model_id: str
    backend: str
    feature_hash: str
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class MlxRankBucketLift:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    metric_name: str
    top_bucket_mean: float
    bottom_bucket_mean: float
    lift: float
    status: str
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class MlxRankedRowsPolicyResult:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    ranked_rows: tuple[MlxRankedCandidate, ...]
    rank_bucket_lift: MlxRankBucketLift
    model_status: str
    selection_reason: str

def _float(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _mapping_sequence(*args: Any, **kwargs: Any) -> Any: ...
def _positive_or_default(*args: Any, **kwargs: Any) -> Any: ...
def _sequence_length(*args: Any, **kwargs: Any) -> Any: ...
def _params(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_universe_size(*args: Any, **kwargs: Any) -> Any: ...
def _bool_feature(*args: Any, **kwargs: Any) -> Any: ...
def _truthy_feature(*args: Any, **kwargs: Any) -> Any: ...
def _artifact_present(*args: Any, **kwargs: Any) -> Any: ...
def _hard_veto_count(*args: Any, **kwargs: Any) -> Any: ...
def _daily_target_shortfall(*args: Any, **kwargs: Any) -> Any: ...
def _sequence_strings(*args: Any, **kwargs: Any) -> Any: ...
def _strings(*args: Any, **kwargs: Any) -> Any: ...
def _unique_string_count(*args: Any, **kwargs: Any) -> Any: ...
def _unique_strings(*args: Any, **kwargs: Any) -> Any: ...
def _claim_type_count(*args: Any, **kwargs: Any) -> Any: ...
def _average_claim_confidence(*args: Any, **kwargs: Any) -> Any: ...
def _truthy_contract_key_count(*args: Any, **kwargs: Any) -> Any: ...
def _requirement_present(*args: Any, **kwargs: Any) -> Any: ...
def _mechanism_overlay_ids(*args: Any, **kwargs: Any) -> Any: ...
def _paper_contract_feature_values(*args: Any, **kwargs: Any) -> Any: ...
def _capital_rank_count_floor(*args: Any, **kwargs: Any) -> Any: ...
def candidate_spec_capital_features(*args: Any, **kwargs: Any) -> Any: ...
def capital_budget_penalty(*args: Any, **kwargs: Any) -> Any: ...
def configured_daily_notional_capacity_penalty(*args: Any, **kwargs: Any) -> Any: ...
def observed_capital_penalty(*args: Any, **kwargs: Any) -> Any: ...
def _observed_replay_viability_penalty(*args: Any, **kwargs: Any) -> Any: ...
def _net_pnl_per_100k_filled_notional(*args: Any, **kwargs: Any) -> Any: ...
def _post_cost_efficiency_penalty(*args: Any, **kwargs: Any) -> Any: ...
def _proof_target_shortfall(*args: Any, **kwargs: Any) -> Any: ...
def _deployable_lower_bound_net_pnl_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _deployable_lower_bound_missing_count(*args: Any, **kwargs: Any) -> Any: ...
def _deployable_lower_bound_failed_gate_count(*args: Any, **kwargs: Any) -> Any: ...
def _deployable_lower_bound_target_shortfall(*args: Any, **kwargs: Any) -> Any: ...
def _deployable_lower_bound_proof_penalty(*args: Any, **kwargs: Any) -> Any: ...
def _historical_proof_penalty(*args: Any, **kwargs: Any) -> Any: ...
def _format_float(*args: Any, **kwargs: Any) -> Any: ...
def _family_code(*args: Any, **kwargs: Any) -> Any: ...
def _mean(*args: Any, **kwargs: Any) -> Any: ...
def _std(*args: Any, **kwargs: Any) -> Any: ...
def _scalar_float(*args: Any, **kwargs: Any) -> Any: ...
def build_mlx_training_rows(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_matrix(*args: Any, **kwargs: Any) -> Any: ...
def train_mlx_ranker(*args: Any, **kwargs: Any) -> Any: ...
def rank_training_rows(*args: Any, **kwargs: Any) -> Any: ...
def compute_rank_bucket_lift(*args: Any, **kwargs: Any) -> Any: ...
def rank_training_rows_with_lift_policy(*args: Any, **kwargs: Any) -> Any: ...
def mlx_ranker_model_from_payload(*args: Any, **kwargs: Any) -> Any: ...
