from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F811,F821
from typing import Any
from decimal import Decimal, ROUND_CEILING
from typing import Any, Mapping, Sequence, cast
from app.trading.discovery.evidence_bundles import (
    CandidateEvidenceBundle,
    evidence_bundle_blockers,
    evidence_bundle_is_valid,
)
from app.trading.discovery.portfolio_candidates import (
    PORTFOLIO_CANDIDATE_SCHEMA_VERSION,
    PortfolioCandidateSpec,
    portfolio_candidate_id_for_payload,
)
from app.trading.discovery.objectives import deployable_lower_bound_net_pnl_per_day
from app.trading.discovery.profit_target_oracle import evaluate_profit_target_oracle
from app.trading.discovery.profit_target_oracle import ProfitTargetOraclePolicy
from app.trading.runtime_ledger import POST_COST_PNL_BASIS

MAX_ALLOWED_PAIRWISE_CORRELATION: Any
CONFORMAL_TAIL_RISK_ALPHA: Any
PORTFOLIO_SEARCH_BEAM_WIDTH: Any
PORTFOLIO_WEIGHTING_EQUAL_COUNT: Any
PORTFOLIO_WEIGHTING_GROSS_EXPOSURE_BUDGET: Any
PORTFOLIO_WEIGHTING_EDGE_RISK_GROSS_EXPOSURE_BUDGET: Any
PORTFOLIO_RUNTIME_LEDGER_PNL_SOURCE: Any
_ACCEPTED_LEDGER_PNL_SOURCES: Any
PORTFOLIO_COMPOSABLE_SINGLE_SLEEVE_VETOES: Any

def _decimal(*args: Any, **kwargs: Any) -> Any: ...
def _string(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _boolish(*args: Any, **kwargs: Any) -> Any: ...
def _scorecard(*args: Any, **kwargs: Any) -> Any: ...
def _scorecard_runtime_params(*args: Any, **kwargs: Any) -> Any: ...
def _scorecard_universe_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _scorecard_primary_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _diversified_candidate_order(*args: Any, **kwargs: Any) -> Any: ...
def _scorecard_sleeve_runtime_limits(*args: Any, **kwargs: Any) -> Any: ...
def _scorecard_signal(*args: Any, **kwargs: Any) -> Any: ...
def _net_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _active_ratio(*args: Any, **kwargs: Any) -> Any: ...
def _positive_ratio(*args: Any, **kwargs: Any) -> Any: ...
def _best_day_share(*args: Any, **kwargs: Any) -> Any: ...
def _max_drawdown(*args: Any, **kwargs: Any) -> Any: ...
def _worst_day_loss(*args: Any, **kwargs: Any) -> Any: ...
def _max_gross_exposure_pct_equity(*args: Any, **kwargs: Any) -> Any: ...
def _min_cash(*args: Any, **kwargs: Any) -> Any: ...
def _negative_cash_observation_count(*args: Any, **kwargs: Any) -> Any: ...
def _hard_vetoes(*args: Any, **kwargs: Any) -> Any: ...
def _non_composable_hard_vetoes(*args: Any, **kwargs: Any) -> Any: ...
def _capital_safety_rejection(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_passes_minimums(*args: Any, **kwargs: Any) -> Any: ...
def _daily_net(*args: Any, **kwargs: Any) -> Any: ...
def _daily_filled_notional(*args: Any, **kwargs: Any) -> Any: ...
def _trading_day_count(*args: Any, **kwargs: Any) -> Any: ...
def _mean(*args: Any, **kwargs: Any) -> Any: ...
def _correlation(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_daily_net(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_daily_filled_notional(*args: Any, **kwargs: Any) -> Any: ...
def _executable_replay_passed(*args: Any, **kwargs: Any) -> Any: ...
def _executable_replay_order_count(*args: Any, **kwargs: Any) -> Any: ...
def _executable_replay_artifact_ref(*args: Any, **kwargs: Any) -> Any: ...
def _artifact_refs_from_scorecard(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_ledger_artifact_refs(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_ledger_row_count(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_ledger_fill_count(*args: Any, **kwargs: Any) -> Any: ...
def _first_normalized_scorecard_text(*args: Any, **kwargs: Any) -> Any: ...
def _ledger_pnl_basis(*args: Any, **kwargs: Any) -> Any: ...
def _ledger_pnl_source(*args: Any, **kwargs: Any) -> Any: ...
def _executable_replay_buying_power(*args: Any, **kwargs: Any) -> Any: ...
def _executable_replay_max_notional(*args: Any, **kwargs: Any) -> Any: ...
def _market_impact_stress_passed(*args: Any, **kwargs: Any) -> Any: ...
def _market_impact_stress_model(*args: Any, **kwargs: Any) -> Any: ...
def _market_impact_stress_components(*args: Any, **kwargs: Any) -> Any: ...
def _market_impact_stress_artifact_ref(*args: Any, **kwargs: Any) -> Any: ...
def _market_impact_stress_net_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _market_impact_stress_cost_bps(*args: Any, **kwargs: Any) -> Any: ...
def _market_impact_liquidity_evidence_present(*args: Any, **kwargs: Any) -> Any: ...
def _implementation_uncertainty_required(*args: Any, **kwargs: Any) -> Any: ...
def _implementation_uncertainty_stability_passed(*args: Any, **kwargs: Any) -> Any: ...
def _implementation_uncertainty_model_count(*args: Any, **kwargs: Any) -> Any: ...
def _implementation_uncertainty_lower_net_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _implementation_uncertainty_upper_net_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _implementation_uncertainty_interval_width_per_day(
    *args: Any, **kwargs: Any
) -> Any: ...
def _conformal_tail_risk_required(*args: Any, **kwargs: Any) -> Any: ...
def _conformal_tail_loss_buffer(*args: Any, **kwargs: Any) -> Any: ...
def _delay_adjusted_depth_stress_passed(*args: Any, **kwargs: Any) -> Any: ...
def _delay_adjusted_depth_liquidity_evidence_present(
    *args: Any, **kwargs: Any
) -> Any: ...
def _delay_adjusted_depth_liquidity_missing_day_count(
    *args: Any, **kwargs: Any
) -> Any: ...
def _delay_adjusted_depth_tail_coverage_passed(*args: Any, **kwargs: Any) -> Any: ...
def _fill_survival_evidence_present(*args: Any, **kwargs: Any) -> Any: ...
def _fill_survival_sample_count(*args: Any, **kwargs: Any) -> Any: ...
def _fill_survival_rate(*args: Any, **kwargs: Any) -> Any: ...
def _queue_position_survival_evidence_present(*args: Any, **kwargs: Any) -> Any: ...
def _queue_position_survival_sample_count(*args: Any, **kwargs: Any) -> Any: ...
def _queue_position_survival_fill_rate(*args: Any, **kwargs: Any) -> Any: ...
def _queue_position_survival_queue_ratio_p95(*args: Any, **kwargs: Any) -> Any: ...
def _queue_ahead_depletion_evidence_present(*args: Any, **kwargs: Any) -> Any: ...
def _queue_ahead_depletion_sample_count(*args: Any, **kwargs: Any) -> Any: ...
def _queue_position_survival_stress_net_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _delay_adjusted_depth_stress_artifact_ref(*args: Any, **kwargs: Any) -> Any: ...
def _delay_adjusted_depth_stress_net_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _delay_adjusted_depth_stress_ms(*args: Any, **kwargs: Any) -> Any: ...
def _delay_adjusted_depth_fillable_notional_per_day(
    *args: Any, **kwargs: Any
) -> Any: ...
def _delay_adjusted_depth_worst_active_day_fillable_notional(
    *args: Any, **kwargs: Any
) -> Any: ...
def _delay_adjusted_depth_p10_active_day_fillable_notional(
    *args: Any, **kwargs: Any
) -> Any: ...
def _double_oos_fold_metrics(*args: Any, **kwargs: Any) -> Any: ...
def _fold_passed(*args: Any, **kwargs: Any) -> Any: ...
def _double_oos_independent_window_count(*args: Any, **kwargs: Any) -> Any: ...
def _double_oos_pass_rate(*args: Any, **kwargs: Any) -> Any: ...
def _double_oos_passed(*args: Any, **kwargs: Any) -> Any: ...
def _double_oos_net_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _double_oos_cost_shock_net_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _double_oos_artifact_ref(*args: Any, **kwargs: Any) -> Any: ...
def _positive_net_contribution(*args: Any, **kwargs: Any) -> Any: ...
def _cluster_id(*args: Any, **kwargs: Any) -> Any: ...
def _contribution_shares(*args: Any, **kwargs: Any) -> Any: ...
def _cluster_contribution_shares(*args: Any, **kwargs: Any) -> Any: ...
def _bundle_symbol_shares(*args: Any, **kwargs: Any) -> Any: ...
def _symbol_contribution_shares(*args: Any, **kwargs: Any) -> Any: ...
def _max_pairwise_correlation(*args: Any, **kwargs: Any) -> Any: ...
def _max_share(*args: Any, **kwargs: Any) -> Any: ...
def _max_drawdown_from_daily(*args: Any, **kwargs: Any) -> Any: ...
def _equal_weights(*args: Any, **kwargs: Any) -> Any: ...
def _gross_exposure_allocation_edge_net_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _gross_exposure_allocation_priority(*args: Any, **kwargs: Any) -> Any: ...
def _edge_risk_gross_exposure_budget_weights(*args: Any, **kwargs: Any) -> Any: ...
def _gross_exposure_budget_weights(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_weights(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_weighting_mode(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_max_gross_exposure_pct_equity(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_min_cash(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_negative_cash_observation_count(*args: Any, **kwargs: Any) -> Any: ...
def _missing_sleeve_daily_net_count(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_trading_day_count(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_scorecard(*args: Any, **kwargs: Any) -> Any: ...
def _sleeve_score(*args: Any, **kwargs: Any) -> Any: ...
def _scorecard_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _oracle_blocker_count(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_selection_key(*args: Any, **kwargs: Any) -> Any: ...
def _empty_selection_key(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_addition_rejection(*args: Any, **kwargs: Any) -> Any: ...
def _record_unique_rejection(*args: Any, **kwargs: Any) -> Any: ...
def _selected_from_state(*args: Any, **kwargs: Any) -> Any: ...
def _select_portfolio_bundles(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_candidate_id(*args: Any, **kwargs: Any) -> Any: ...
def optimize_portfolio_candidate(*args: Any, **kwargs: Any) -> Any: ...
