from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import hashlib
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from math import exp, isfinite, log1p
from typing import Any, cast
from app.trading.models import SignalEnvelope

QUEUE_SURVIVAL_FILL_STRESS_SCHEMA_VERSION: Any
QUEUE_SURVIVAL_FILL_STRESS_CONTRACT_SCHEMA_VERSION: Any
QUEUE_SURVIVAL_FILL_STRESS_PROOF_SEMANTICS_LABEL: Any
QUEUE_SURVIVAL_FILL_STRESS_PRIMARY_SOURCES: tuple[Mapping[str, str], ...]
_PRICE_FIELDS: Any
_SPREAD_FIELDS: Any
_VOLUME_FIELDS: Any
_BID_SIZE_FIELDS: Any
_ASK_SIZE_FIELDS: Any
_QUEUE_POSITION_FIELDS: Any
_QUEUE_RATIO_FIELDS: Any
_FILL_FIELDS: Any
_STATUS_FIELDS: Any
_EVENT_FIELDS: Any
_SIDE_FIELDS: Any
_ORDER_BOOK_IMBALANCE_FIELDS: Any
_FILL_TOKENS: Any
_CANCEL_TOKENS: Any
_REJECT_TOKENS: Any
_ADD_TOKENS: Any
_QUEUE_REACTIVE_EVENT_KINDS: Any

class QueueSurvivalFillStressSummary:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    row_count: int
    observed_queue_position_count: int
    observed_depth_count: int
    observed_fill_count: int
    observed_cancel_or_reject_count: int
    median_queue_ahead_ratio: float
    median_visible_executable_depth_notional: float
    visible_depth_notional_shortfall_share: float
    execution_turnover_ratio: float
    cancellation_or_reject_share: float
    queue_reactive_event_mix_l1: float
    order_size_distribution_wasserstein_proxy: float
    queue_reactive_replay_parity_penalty_bps: float
    time_priority_edge_concentration_score: float
    randomized_priority_fill_gap_proxy_bps: float
    queue_allocation_rule_sensitivity_penalty_bps: float
    fill_before_move_trial_count: int
    observed_opportunity_midprice_move_count: int
    opportunity_midprice_move_before_fill_share: float
    state_dependent_fill_before_move_probability: float
    state_dependent_order_flow_gap_score: float
    state_dependent_fill_risk_penalty_bps: float
    observed_order_book_imbalance_count: int
    median_directional_order_book_imbalance: float
    contrarian_reversal_support_score: float
    maker_fill_return_tradeoff_penalty_bps: float
    group_normalized_downside_reward_penalty_bps: float
    estimated_limit_fill_probability: float
    nonfill_opportunity_cost_bps: float
    adverse_selection_after_touch_bps: float
    queue_delay_penalty_bps: float
    replay_rank_penalty_bps: float
    warnings: tuple[str, ...]
    feature_schema_hash: str
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class _FillBeforeMoveStats:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    trial_count: int
    observed_move_count: int
    fill_before_move_share: float
    opportunity_move_before_fill_share: float

def queue_survival_fill_stress_contract(*args: Any, **kwargs: Any) -> Any: ...
def build_queue_survival_fill_stress_schema_hash(*args: Any, **kwargs: Any) -> Any: ...
def extract_queue_survival_fill_stress(*args: Any, **kwargs: Any) -> Any: ...
def _executable_side_depth(*args: Any, **kwargs: Any) -> Any: ...
def _queue_ahead_ratio(*args: Any, **kwargs: Any) -> Any: ...
def _estimated_fill_probability(*args: Any, **kwargs: Any) -> Any: ...
def _time_priority_edge_concentration_score(*args: Any, **kwargs: Any) -> Any: ...
def _randomized_priority_fill_gap_proxy_bps(*args: Any, **kwargs: Any) -> Any: ...
def _fill_before_opportunity_move_stats(*args: Any, **kwargs: Any) -> Any: ...
def _state_dependent_fill_before_move_probability(*args: Any, **kwargs: Any) -> Any: ...
def _state_dependent_order_flow_gap_score(*args: Any, **kwargs: Any) -> Any: ...
def _state_dependent_fill_risk_penalty_bps(*args: Any, **kwargs: Any) -> Any: ...
def _queue_reactive_event_mix_l1(*args: Any, **kwargs: Any) -> Any: ...
def _order_size_distribution_wasserstein_proxy(*args: Any, **kwargs: Any) -> Any: ...
def _nonfill_opportunity_cost_bps(*args: Any, **kwargs: Any) -> Any: ...
def _adverse_selection_after_touch_bps(*args: Any, **kwargs: Any) -> Any: ...
def _order_book_imbalance(*args: Any, **kwargs: Any) -> Any: ...
def _contrarian_reversal_support_score(*args: Any, **kwargs: Any) -> Any: ...
def _maker_fill_return_tradeoff_penalty_bps(*args: Any, **kwargs: Any) -> Any: ...
def _group_normalized_downside_reward_penalty_bps(*args: Any, **kwargs: Any) -> Any: ...
def _event_label(*args: Any, **kwargs: Any) -> Any: ...
def _label_has_token(*args: Any, **kwargs: Any) -> Any: ...
def _queue_reactive_event_kind(*args: Any, **kwargs: Any) -> Any: ...
def _first_payload_value(*args: Any, **kwargs: Any) -> Any: ...
def _positive_float(*args: Any, **kwargs: Any) -> Any: ...
def _nonnegative_float(*args: Any, **kwargs: Any) -> Any: ...
def _float_or_none(*args: Any, **kwargs: Any) -> Any: ...
def _median(*args: Any, **kwargs: Any) -> Any: ...
def _quantile(*args: Any, **kwargs: Any) -> Any: ...
def _log1p(*args: Any, **kwargs: Any) -> Any: ...
def _stable_float(*args: Any, **kwargs: Any) -> Any: ...
def _stable_hash(*args: Any, **kwargs: Any) -> Any: ...
