from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import gzip
import hashlib
import json
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, TextIO, cast
from app.trading.models import SignalEnvelope
from app.trading.session_context import (
    iter_regular_equities_session_dates,
    regular_session_close_utc_for,
    regular_session_open_utc_for,
)

REPLAY_TAPE_SCHEMA_VERSION: Any
REPLAY_TAPE_MANIFEST_SCHEMA_VERSION: Any
REPLAY_TAPE_CACHE_IDENTITY_SCHEMA_VERSION: Any
HPAIRS_REPLAY_TAPE_FEATURE_SCHEMA_VERSION: Any
HPAIRS_REPLAY_TAPE_FEATURE_CONTRACT_SCHEMA_VERSION: Any
HPAIRS_OFI_MEMORY_REGIME_SCHEMA_VERSION: Any
HPAIRS_CLUSTERLOB_FEATURE_VERSION: Any
HPAIRS_OFI_FEATURE_VERSION: Any
_DECIMAL_TAG: Any
_DATETIME_TAG: Any

def _empty_row_count_by_trading_day(*args: Any, **kwargs: Any) -> Any: ...
def _empty_row_count_by_symbol_trading_day(*args: Any, **kwargs: Any) -> Any: ...
def _empty_string_mapping(*args: Any, **kwargs: Any) -> Any: ...

class ReplayTapeCoverageError(ValueError):
    def __init__(*args: Any, **kwargs: Any) -> None: ...

class ReplayTapeManifest:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    schema_version: str
    dataset_snapshot_ref: str
    symbols: tuple[str, ...]
    row_symbols: tuple[str, ...]
    start_date: date
    end_date: date
    start_ts: datetime
    end_ts: datetime
    min_event_ts: datetime | None
    max_event_ts: datetime | None
    trading_day_count: int
    row_count: int
    source_query_digest: str
    content_sha256: str
    artifact_refs: Mapping[str, str]
    source_table_versions: Mapping[str, str]
    created_at: datetime
    feature_schema_hash: str
    cost_model_hash: str
    strategy_family: str
    replay_cache_key: str
    feature_versions: Mapping[str, str]
    requested_trading_days: tuple[date, ...]
    observed_trading_days: tuple[date, ...]
    missing_trading_days: tuple[date, ...]
    row_count_by_trading_day: Mapping[str, int]
    missing_symbol_trading_days: tuple[str, ...]
    row_count_by_symbol_trading_day: Mapping[str, Mapping[str, int]]
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...
    def cache_identity_diagnostics(*args: Any, **kwargs: Any) -> Any: ...
    def from_payload(*args: Any, **kwargs: Any) -> Any: ...

class ReplayTape:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    manifest: ReplayTapeManifest
    rows: tuple[SignalEnvelope, ...]

def default_manifest_path(*args: Any, **kwargs: Any) -> Any: ...
def build_source_query_digest(*args: Any, **kwargs: Any) -> Any: ...
def hpairs_replay_tape_feature_versions(*args: Any, **kwargs: Any) -> Any: ...
def hpairs_replay_tape_feature_contract(*args: Any, **kwargs: Any) -> Any: ...
def build_hpairs_replay_tape_feature_schema_hash(*args: Any, **kwargs: Any) -> Any: ...
def build_replay_tape_cache_key(*args: Any, **kwargs: Any) -> Any: ...
def build_replay_tape_cache_identity_diagnostics(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_replay_feature_versions(*args: Any, **kwargs: Any) -> Any: ...
def materialize_signal_tape(*args: Any, **kwargs: Any) -> Any: ...
def load_replay_tape(*args: Any, **kwargs: Any) -> Any: ...
def validate_tape_freshness(*args: Any, **kwargs: Any) -> Any: ...
def _replay_tape_cache_identity_mismatch_reasons(*args: Any, **kwargs: Any) -> Any: ...
def slice_tape_by_window(*args: Any, **kwargs: Any) -> Any: ...
def slice_tape_by_symbols(*args: Any, **kwargs: Any) -> Any: ...
def signal_to_tape_payload(*args: Any, **kwargs: Any) -> Any: ...
def signal_from_tape_payload(*args: Any, **kwargs: Any) -> Any: ...
def hpairs_replay_tape_features(*args: Any, **kwargs: Any) -> Any: ...
def _canonical_row_json(*args: Any, **kwargs: Any) -> Any: ...
def _signal_sort_key(*args: Any, **kwargs: Any) -> Any: ...
def _hpairs_ofi_horizons(*args: Any, **kwargs: Any) -> Any: ...
def _hpairs_ofi_decay_memory(*args: Any, **kwargs: Any) -> Any: ...
def _hpairs_cluster_lob_payload(*args: Any, **kwargs: Any) -> Any: ...
def _cluster_lob_behavior_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _quote_behavior_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _hpairs_ofi_memory_regime_slices(*args: Any, **kwargs: Any) -> Any: ...
def _ofi_regime_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _mean_decimal_for_keys(*args: Any, **kwargs: Any) -> Any: ...
def _mean_decimal_for_token(*args: Any, **kwargs: Any) -> Any: ...
def _horizon_key_matches_token(*args: Any, **kwargs: Any) -> Any: ...
def _mean_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _first_decimal_with_key(*args: Any, **kwargs: Any) -> Any: ...
def _hpairs_capacity_notional_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _stress_tag_tuple(*args: Any, **kwargs: Any) -> Any: ...
def _tag_tuple(*args: Any, **kwargs: Any) -> Any: ...
def _first_text(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_or_none(*args: Any, **kwargs: Any) -> Any: ...
def _open_text_writer(*args: Any, **kwargs: Any) -> Any: ...
def _open_text_reader(*args: Any, **kwargs: Any) -> Any: ...
def _parse_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _business_days(*args: Any, **kwargs: Any) -> Any: ...
def _row_count_by_symbol_trading_day(*args: Any, **kwargs: Any) -> Any: ...
def _missing_symbol_trading_days(*args: Any, **kwargs: Any) -> Any: ...
def _symbol_day_entry(*args: Any, **kwargs: Any) -> Any: ...
def _parse_symbol_day_entry(*args: Any, **kwargs: Any) -> Any: ...
def _symbol_day_entry_in_window(*args: Any, **kwargs: Any) -> Any: ...
def _coverage_status(*args: Any, **kwargs: Any) -> Any: ...
def _incomplete_coverage_reason(*args: Any, **kwargs: Any) -> Any: ...
def _coverage_error_diagnostics(*args: Any, **kwargs: Any) -> Any: ...
def _date_tuple(*args: Any, **kwargs: Any) -> Any: ...
def _string_tuple(*args: Any, **kwargs: Any) -> Any: ...
def _string_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _int_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _nested_int_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _encode_value(*args: Any, **kwargs: Any) -> Any: ...
def _decode_value(*args: Any, **kwargs: Any) -> Any: ...
def _json_ready(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
