from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F811,F821
from typing import Any
import json
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, cast
from app.trading.discovery.adaptive_market_limit_allocation_stress import (
    extract_adaptive_market_limit_allocation_stress,
)
from app.trading.discovery.cluster_lob_features import extract_cluster_lob_features
from app.trading.discovery.lob_reality_gap_stress import extract_lob_reality_gap_stress
from app.trading.discovery.order_book_observability_stress import (
    extract_order_book_observability_stress,
)
from app.trading.discovery.profit_target_oracle import ProfitTargetOraclePolicy
from app.trading.models import SignalEnvelope
from app.trading.runtime_ledger import RuntimeLedgerBucket, build_runtime_ledger_buckets

EXACT_REPLAY_LEDGER_RANKING_SCHEMA_VERSION: Any
EXECUTION_QUALITY_SCHEMA_VERSION: Any
EXACT_REPLAY_MICROSTRUCTURE_STRESS_SCHEMA_VERSION: Any
_LIVE_PROMOTION_AUTHORITIES: Any
_EXECUTION_QUALITY_SOURCE_PAPERS: Any
_ORDER_TYPE_FIELDS: Any
_FILL_STATUS_FIELDS: Any
_EXECUTION_SHORTFALL_FIELDS: Any
_PRICE_IMPROVEMENT_FIELDS: Any
_OPPORTUNITY_COST_FIELDS: Any
_QUEUE_POSITION_FIELDS: Any
_LIMIT_FILL_PROBABILITY_FIELDS: Any
_CLOSING_WINDOW_FIELDS: Any
_CLOSING_AUCTION_FIELDS: Any
_CLOSING_AUCTION_PROJECTION_FIELDS: Any
_CLOSING_AUCTION_CLEARING_PRICE_FIELDS: Any
_TERMINAL_INVENTORY_PATH_FIELDS: Any

class ReplayLedgerRankingPolicy:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    target_net_pnl_per_day: Decimal
    min_window_weekday_count: int
    min_avg_filled_notional_per_day: Decimal
    max_best_day_share: Decimal
    max_gross_exposure_pct_equity: Decimal
    start_equity: Decimal | None
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class ReplayLedgerCandidateRanking:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    artifact_ref: str
    candidate_id: str
    candidate_identity_hash: str
    cost_lineage_hash: str
    promotion_status: str
    promotion_blockers: tuple[str, ...]
    runtime_ledger_blockers: tuple[str, ...]
    window_start: datetime
    window_end: datetime
    window_weekday_count: int
    active_day_count: int
    positive_day_count: int
    negative_day_count: int
    fill_count: int
    decision_count: int
    submitted_order_count: int
    closed_trade_count: int
    open_position_count: int
    total_filled_notional: Decimal
    avg_filled_notional_per_window_weekday: Decimal
    avg_filled_notional_per_active_day: Decimal
    total_net_pnl_after_costs: Decimal
    window_net_pnl_per_day: Decimal
    active_net_pnl_per_day: Decimal
    gross_strategy_pnl: Decimal
    cost_amount: Decimal
    best_day_share: Decimal
    worst_day_net_pnl: Decimal
    max_drawdown: Decimal
    profit_factor: Decimal | None
    max_single_fill_notional: Decimal
    max_single_fill_notional_pct_equity: Decimal | None
    daily_net_pnl_after_costs: Mapping[str, Decimal]
    symbols: tuple[str, ...]
    stage: str
    source: str
    promotion_authority: str
    cost_basis_counts: Mapping[str, int]
    candidate_identity: Mapping[str, object]
    cost_lineage: Mapping[str, object]
    fills_with_adv_notional: int
    fills_with_participation_rate: int
    fills_with_capacity_warning_contract: int
    capacity_warning_counts: Mapping[str, int]
    execution_quality: Mapping[str, object]
    execution_quality_blockers: tuple[str, ...]
    execution_quality_penalty_bps: Decimal
    execution_quality_penalty_amount: Decimal
    execution_quality_adjusted_window_net_pnl_per_day: Decimal
    lob_reality_gap_stress: Mapping[str, object]
    lob_reality_gap_blockers: tuple[str, ...]
    lob_reality_gap_penalty_bps: Decimal
    lob_reality_gap_penalty_amount: Decimal
    microstructure_stress: Mapping[str, object]
    microstructure_stress_blockers: tuple[str, ...]
    microstructure_stress_penalty_bps: Decimal
    microstructure_stress_penalty_amount: Decimal
    replay_quality_adjusted_window_net_pnl_per_day: Decimal
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class ReplayLedgerRankingFailure:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    artifact_ref: str
    reason: str
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

def default_replay_ledger_ranking_policy(*args: Any, **kwargs: Any) -> Any: ...
def rank_replay_ledger_payload(*args: Any, **kwargs: Any) -> Any: ...
def rank_replay_ledger_files(*args: Any, **kwargs: Any) -> Any: ...
def build_replay_ledger_ranking_report(*args: Any, **kwargs: Any) -> Any: ...
def _ledger_window(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_rows_with_defaults(*args: Any, **kwargs: Any) -> Any: ...
def _full_window_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _promotion_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_id(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_identity_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _cost_lineage_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _capacity_lineage_summary(*args: Any, **kwargs: Any) -> Any: ...
def _execution_quality_summary(*args: Any, **kwargs: Any) -> Any: ...
def _lob_reality_gap_stress_summary(*args: Any, **kwargs: Any) -> Any: ...
def _microstructure_stress_summary(*args: Any, **kwargs: Any) -> Any: ...
def _stress_penalty_bps(*args: Any, **kwargs: Any) -> Any: ...
def _dedupe_source_papers(*args: Any, **kwargs: Any) -> Any: ...
def _lob_signal_rows(*args: Any, **kwargs: Any) -> Any: ...
def _row_event_ts(*args: Any, **kwargs: Any) -> Any: ...
def _row_ingest_ts(*args: Any, **kwargs: Any) -> Any: ...
def _daily_bucket_ranges(*args: Any, **kwargs: Any) -> Any: ...
def _parse_window_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _string_list(*args: Any, **kwargs: Any) -> Any: ...
def _payload_object(*args: Any, **kwargs: Any) -> Any: ...
def _first_text(*args: Any, **kwargs: Any) -> Any: ...
def _first_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _first_evidence(*args: Any, **kwargs: Any) -> Any: ...
def _evidence_present(*args: Any, **kwargs: Any) -> Any: ...
def _decimal(*args: Any, **kwargs: Any) -> Any: ...
def _average_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _normalized_order_type(*args: Any, **kwargs: Any) -> Any: ...
def _order_type_for_row(*args: Any, **kwargs: Any) -> Any: ...
def _count_texts(*args: Any, **kwargs: Any) -> Any: ...
def _row_has_fill_status(*args: Any, **kwargs: Any) -> Any: ...
def _text(*args: Any, **kwargs: Any) -> Any: ...
def _utc(*args: Any, **kwargs: Any) -> Any: ...
def _best_day_share(*args: Any, **kwargs: Any) -> Any: ...
def _max_drawdown(*args: Any, **kwargs: Any) -> Any: ...
def _profit_factor(*args: Any, **kwargs: Any) -> Any: ...
def _max_single_fill_notional(*args: Any, **kwargs: Any) -> Any: ...
def _fill_notional(*args: Any, **kwargs: Any) -> Any: ...
def _symbols(*args: Any, **kwargs: Any) -> Any: ...
def _event_type(*args: Any, **kwargs: Any) -> Any: ...
def _positive_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _safe_divide(*args: Any, **kwargs: Any) -> Any: ...
def _dedupe(*args: Any, **kwargs: Any) -> Any: ...
def _ranking_sort_key(*args: Any, **kwargs: Any) -> Any: ...
