from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import hashlib
import json
import subprocess
from dataclasses import dataclass
from datetime import UTC, date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any, Mapping, Sequence, cast
import yaml
from app.trading.autonomy.policy_checks import (
    evaluate_promotion_prerequisites,
    evaluate_rollback_readiness,
)
from app.trading.discovery.autoresearch import (
    StrategyAutoresearchProgram,
    candidate_meets_objective,
)
from app.trading.discovery.decomposition import (
    build_replay_decomposition,
    max_family_contribution_share,
    max_symbol_concentration_share,
    regime_slice_pass_rate,
)
from app.trading.discovery.mlx_snapshot import MlxSnapshotManifest
from app.trading.discovery.objectives import (
    ObjectiveVetoPolicy,
    build_scorecard,
    evaluate_vetoes,
)
from app.trading.discovery.portfolio_candidates import PortfolioCandidateSpec
from app.trading.evidence_receipts import build_portfolio_proof_receipt
from app.trading.costs import BPS_SCALE, CostModelConfig, participation_power
from app.trading.hypotheses import (
    hypothesis_registry_requires_dependency_capability,
    load_hypothesis_registry,
)
from app.trading.reporting import summarize_replay_profitability
import scripts.local_intraday_tsmom_replay as replay_mod
from scripts.search_consistent_profitability_frontier import (
    apply_candidate_to_configmap_with_overrides,
)

def _discover_runtime_root(*args: Any, **kwargs: Any) -> Any: ...

_REPO_ROOT: Any
_MIN_SIMULATION_PARITY_SAMPLE_COUNT: Any
_MAX_SIMULATION_LIVE_FILL_ERROR_BPS: Any
_MAX_ADVERSE_SELECTION_ERROR_BPS: Any
_EXECUTION_REALISM_PASS_STATUSES: Any

def _string(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _list_of_mappings(*args: Any, **kwargs: Any) -> Any: ...
def _list_of_strings(*args: Any, **kwargs: Any) -> Any: ...
def _int(*args: Any, **kwargs: Any) -> Any: ...
def _float(*args: Any, **kwargs: Any) -> Any: ...
def _decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_string(*args: Any, **kwargs: Any) -> Any: ...
def _optional_decimal_string(*args: Any, **kwargs: Any) -> Any: ...
def _p10(*args: Any, **kwargs: Any) -> Any: ...

_MICROBAR_PORTFOLIO_SIGNAL_SETTINGS: dict[str, dict[str, str]]
_MICROBAR_PORTFOLIO_RUNTIME_PARAM_KEYS: tuple[str, ...]
_PORTFOLIO_POLICY_REF_PREFIX: Any

def _json_dumps(*args: Any, **kwargs: Any) -> Any: ...
def _write_json(*args: Any, **kwargs: Any) -> Any: ...
def _sha256_path(*args: Any, **kwargs: Any) -> Any: ...
def _sha256_json(*args: Any, **kwargs: Any) -> Any: ...
def _now_iso(*args: Any, **kwargs: Any) -> Any: ...
def _git_output(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_run_context(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_closure_policy(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_proof_receipt_payload(*args: Any, **kwargs: Any) -> Any: ...

class RuntimeClosureExecutionContext:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    strategy_configmap_path: Path
    clickhouse_http_url: str
    clickhouse_username: str | None
    clickhouse_password: str | None
    start_equity: Decimal
    chunk_minutes: int
    symbols: tuple[str, ...]
    progress_log_interval_seconds: int
    shadow_validation_artifact_path: Path | None
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

def _date_from_iso(*args: Any, **kwargs: Any) -> Any: ...
def _daily_filled_notional(*args: Any, **kwargs: Any) -> Any: ...
def _daily_liquidity_notional(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_execution_realism_summary(*args: Any, **kwargs: Any) -> Any: ...
def _execution_realism_missing_evidence(*args: Any, **kwargs: Any) -> Any: ...
def _max_drawdown_from_daily_net(*args: Any, **kwargs: Any) -> Any: ...
def _rolling_lower_bound(*args: Any, **kwargs: Any) -> Any: ...
def _max_best_day_share_of_total_pnl(*args: Any, **kwargs: Any) -> Any: ...
def _objective_veto_policy(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_family(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_strategy_name(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_params(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_strategy_overrides(*args: Any, **kwargs: Any) -> Any: ...
def _disable_other_strategies(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_payload(*args: Any, **kwargs: Any) -> Any: ...
def _text_tuple(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_candidate_runtime_payload(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_best_candidate_payload(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_optimizer_evidence(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _is_microbar_portfolio_candidate(*args: Any, **kwargs: Any) -> Any: ...
def _microbar_portfolio_strategy_name(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_runtime_strategy_names(*args: Any, **kwargs: Any) -> Any: ...
def _policy_ref_slug(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_policy_refs(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_promotion_v2(*args: Any, **kwargs: Any) -> Any: ...
def _materialized_microbar_portfolio_runtime_strategies(
    *args: Any, **kwargs: Any
) -> Any: ...
def _materialized_generic_portfolio_runtime_strategies(
    *args: Any, **kwargs: Any
) -> Any: ...
def _candidate_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _window_bounds(*args: Any, **kwargs: Any) -> Any: ...
def _load_strategy_configmap_payload(*args: Any, **kwargs: Any) -> Any: ...
def _materialize_candidate_configmap(*args: Any, **kwargs: Any) -> Any: ...
def _default_replay_executor(*args: Any, **kwargs: Any) -> Any: ...
def _run_runtime_replay(*args: Any, **kwargs: Any) -> Any: ...
def _replay_analysis(*args: Any, **kwargs: Any) -> Any: ...
def _shadow_validation_artifact(*args: Any, **kwargs: Any) -> Any: ...
def _summary_status_and_next_steps(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_spec(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_generation_manifest(*args: Any, **kwargs: Any) -> Any: ...
def _gate_report(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_state(*args: Any, **kwargs: Any) -> Any: ...
def _backtest_summary(*args: Any, **kwargs: Any) -> Any: ...
def _market_impact_stress_report(*args: Any, **kwargs: Any) -> Any: ...
def _delay_adjusted_depth_stress_report(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_replay_net_pnl_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _double_oos_window_row(*args: Any, **kwargs: Any) -> Any: ...
def _double_oos_cost_shock_net_pnl_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _double_oos_walkforward_report(*args: Any, **kwargs: Any) -> Any: ...
def _stress_metrics_payload(*args: Any, **kwargs: Any) -> Any: ...
def _profitability_stage_manifest(*args: Any, **kwargs: Any) -> Any: ...

class RuntimeClosureBundleSummary:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    status: str
    candidate_id: str
    root: str
    candidate_spec_path: str
    candidate_generation_manifest_path: str
    candidate_configmap_path: str
    gate_report_path: str
    parity_replay_path: str
    parity_report_path: str
    approval_replay_path: str
    approval_report_path: str
    shadow_validation_path: str
    candidate_state_path: str
    rollback_readiness_artifact_path: str
    rollback_readiness_evaluation_path: str
    policy_path: str
    portfolio_optimizer_evidence_path: str
    portfolio_proof_receipt_path: str
    market_impact_stress_report_path: str
    delay_adjusted_depth_stress_report_path: str
    double_oos_report_path: str
    stress_metrics_path: str
    profitability_stage_manifest_path: str
    promotion_prerequisites_path: str
    replay_plan_path: str
    next_required_steps: tuple[str, ...]
    promotion_prerequisites: Mapping[str, Any]
    rollback_readiness: Mapping[str, Any]
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

def write_runtime_closure_bundle(*args: Any, **kwargs: Any) -> Any: ...
