// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=ts"
// @generated from file temporal/api/operatorservice/v1/request_response.proto (package temporal.api.operatorservice.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from '@bufbuild/protobuf'
import { Duration, Message, proto3, protoInt64 } from '@bufbuild/protobuf'
import { IndexedValueType } from '../../enums/v1/common_pbts'
import { Endpoint, EndpointSpec } from '../../nexus/v1/message_pbts'

/**
 * @generated from message temporal.api.operatorservice.v1.AddSearchAttributesRequest
 */
export class AddSearchAttributesRequest extends Message<AddSearchAttributesRequest> {
  /**
   * Mapping between search attribute name and its IndexedValueType.
   *
   * @generated from field: map<string, temporal.api.enums.v1.IndexedValueType> search_attributes = 1;
   */
  searchAttributes: { [key: string]: IndexedValueType } = {}

  /**
   * @generated from field: string namespace = 2;
   */
  namespace = ''

  constructor(data?: PartialMessage<AddSearchAttributesRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.AddSearchAttributesRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'search_attributes',
      kind: 'map',
      K: 9 /* ScalarType.STRING */,
      V: { kind: 'enum', T: proto3.getEnumType(IndexedValueType) },
    },
    { no: 2, name: 'namespace', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddSearchAttributesRequest {
    return new AddSearchAttributesRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddSearchAttributesRequest {
    return new AddSearchAttributesRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddSearchAttributesRequest {
    return new AddSearchAttributesRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: AddSearchAttributesRequest | PlainMessage<AddSearchAttributesRequest> | undefined,
    b: AddSearchAttributesRequest | PlainMessage<AddSearchAttributesRequest> | undefined,
  ): boolean {
    return proto3.util.equals(AddSearchAttributesRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.AddSearchAttributesResponse
 */
export class AddSearchAttributesResponse extends Message<AddSearchAttributesResponse> {
  constructor(data?: PartialMessage<AddSearchAttributesResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.AddSearchAttributesResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddSearchAttributesResponse {
    return new AddSearchAttributesResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddSearchAttributesResponse {
    return new AddSearchAttributesResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddSearchAttributesResponse {
    return new AddSearchAttributesResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: AddSearchAttributesResponse | PlainMessage<AddSearchAttributesResponse> | undefined,
    b: AddSearchAttributesResponse | PlainMessage<AddSearchAttributesResponse> | undefined,
  ): boolean {
    return proto3.util.equals(AddSearchAttributesResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.RemoveSearchAttributesRequest
 */
export class RemoveSearchAttributesRequest extends Message<RemoveSearchAttributesRequest> {
  /**
   * Search attribute names to delete.
   *
   * @generated from field: repeated string search_attributes = 1;
   */
  searchAttributes: string[] = []

  /**
   * @generated from field: string namespace = 2;
   */
  namespace = ''

  constructor(data?: PartialMessage<RemoveSearchAttributesRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.RemoveSearchAttributesRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'search_attributes', kind: 'scalar', T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: 'namespace', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveSearchAttributesRequest {
    return new RemoveSearchAttributesRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveSearchAttributesRequest {
    return new RemoveSearchAttributesRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveSearchAttributesRequest {
    return new RemoveSearchAttributesRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: RemoveSearchAttributesRequest | PlainMessage<RemoveSearchAttributesRequest> | undefined,
    b: RemoveSearchAttributesRequest | PlainMessage<RemoveSearchAttributesRequest> | undefined,
  ): boolean {
    return proto3.util.equals(RemoveSearchAttributesRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.RemoveSearchAttributesResponse
 */
export class RemoveSearchAttributesResponse extends Message<RemoveSearchAttributesResponse> {
  constructor(data?: PartialMessage<RemoveSearchAttributesResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.RemoveSearchAttributesResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveSearchAttributesResponse {
    return new RemoveSearchAttributesResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveSearchAttributesResponse {
    return new RemoveSearchAttributesResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveSearchAttributesResponse {
    return new RemoveSearchAttributesResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: RemoveSearchAttributesResponse | PlainMessage<RemoveSearchAttributesResponse> | undefined,
    b: RemoveSearchAttributesResponse | PlainMessage<RemoveSearchAttributesResponse> | undefined,
  ): boolean {
    return proto3.util.equals(RemoveSearchAttributesResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.ListSearchAttributesRequest
 */
export class ListSearchAttributesRequest extends Message<ListSearchAttributesRequest> {
  /**
   * @generated from field: string namespace = 1;
   */
  namespace = ''

  constructor(data?: PartialMessage<ListSearchAttributesRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.ListSearchAttributesRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'namespace', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSearchAttributesRequest {
    return new ListSearchAttributesRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSearchAttributesRequest {
    return new ListSearchAttributesRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSearchAttributesRequest {
    return new ListSearchAttributesRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: ListSearchAttributesRequest | PlainMessage<ListSearchAttributesRequest> | undefined,
    b: ListSearchAttributesRequest | PlainMessage<ListSearchAttributesRequest> | undefined,
  ): boolean {
    return proto3.util.equals(ListSearchAttributesRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.ListSearchAttributesResponse
 */
export class ListSearchAttributesResponse extends Message<ListSearchAttributesResponse> {
  /**
   * Mapping between custom (user-registered) search attribute name to its IndexedValueType.
   *
   * @generated from field: map<string, temporal.api.enums.v1.IndexedValueType> custom_attributes = 1;
   */
  customAttributes: { [key: string]: IndexedValueType } = {}

  /**
   * Mapping between system (predefined) search attribute name to its IndexedValueType.
   *
   * @generated from field: map<string, temporal.api.enums.v1.IndexedValueType> system_attributes = 2;
   */
  systemAttributes: { [key: string]: IndexedValueType } = {}

  /**
   * Mapping from the attribute name to the visibility storage native type.
   *
   * @generated from field: map<string, string> storage_schema = 3;
   */
  storageSchema: { [key: string]: string } = {}

  constructor(data?: PartialMessage<ListSearchAttributesResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.ListSearchAttributesResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'custom_attributes',
      kind: 'map',
      K: 9 /* ScalarType.STRING */,
      V: { kind: 'enum', T: proto3.getEnumType(IndexedValueType) },
    },
    {
      no: 2,
      name: 'system_attributes',
      kind: 'map',
      K: 9 /* ScalarType.STRING */,
      V: { kind: 'enum', T: proto3.getEnumType(IndexedValueType) },
    },
    {
      no: 3,
      name: 'storage_schema',
      kind: 'map',
      K: 9 /* ScalarType.STRING */,
      V: { kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSearchAttributesResponse {
    return new ListSearchAttributesResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSearchAttributesResponse {
    return new ListSearchAttributesResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSearchAttributesResponse {
    return new ListSearchAttributesResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: ListSearchAttributesResponse | PlainMessage<ListSearchAttributesResponse> | undefined,
    b: ListSearchAttributesResponse | PlainMessage<ListSearchAttributesResponse> | undefined,
  ): boolean {
    return proto3.util.equals(ListSearchAttributesResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.DeleteNamespaceRequest
 */
export class DeleteNamespaceRequest extends Message<DeleteNamespaceRequest> {
  /**
   * Only one of namespace or namespace_id must be specified to identify namespace.
   *
   * @generated from field: string namespace = 1;
   */
  namespace = ''

  /**
   * @generated from field: string namespace_id = 2;
   */
  namespaceId = ''

  /**
   * If provided, the deletion of namespace info will be delayed for the given duration (0 means no delay).
   * If not provided, the default delay configured in the cluster will be used.
   *
   * @generated from field: google.protobuf.Duration namespace_delete_delay = 3;
   */
  namespaceDeleteDelay?: Duration

  constructor(data?: PartialMessage<DeleteNamespaceRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.DeleteNamespaceRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'namespace', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'namespace_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'namespace_delete_delay', kind: 'message', T: Duration },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteNamespaceRequest {
    return new DeleteNamespaceRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteNamespaceRequest {
    return new DeleteNamespaceRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteNamespaceRequest {
    return new DeleteNamespaceRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: DeleteNamespaceRequest | PlainMessage<DeleteNamespaceRequest> | undefined,
    b: DeleteNamespaceRequest | PlainMessage<DeleteNamespaceRequest> | undefined,
  ): boolean {
    return proto3.util.equals(DeleteNamespaceRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.DeleteNamespaceResponse
 */
export class DeleteNamespaceResponse extends Message<DeleteNamespaceResponse> {
  /**
   * Temporary namespace name that is used during reclaim resources step.
   *
   * @generated from field: string deleted_namespace = 1;
   */
  deletedNamespace = ''

  constructor(data?: PartialMessage<DeleteNamespaceResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.DeleteNamespaceResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'deleted_namespace', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteNamespaceResponse {
    return new DeleteNamespaceResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteNamespaceResponse {
    return new DeleteNamespaceResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteNamespaceResponse {
    return new DeleteNamespaceResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: DeleteNamespaceResponse | PlainMessage<DeleteNamespaceResponse> | undefined,
    b: DeleteNamespaceResponse | PlainMessage<DeleteNamespaceResponse> | undefined,
  ): boolean {
    return proto3.util.equals(DeleteNamespaceResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.AddOrUpdateRemoteClusterRequest
 */
export class AddOrUpdateRemoteClusterRequest extends Message<AddOrUpdateRemoteClusterRequest> {
  /**
   * Frontend Address is a cross cluster accessible address for gRPC traffic. This field is required.
   *
   * @generated from field: string frontend_address = 1;
   */
  frontendAddress = ''

  /**
   * Flag to enable / disable the cross cluster connection.
   *
   * @generated from field: bool enable_remote_cluster_connection = 2;
   */
  enableRemoteClusterConnection = false

  /**
   * Frontend HTTP Address is a cross cluster accessible address for HTTP traffic. This field is optional. If not provided
   *  on update, the existing HTTP address will be removed.
   *
   * @generated from field: string frontend_http_address = 3;
   */
  frontendHttpAddress = ''

  constructor(data?: PartialMessage<AddOrUpdateRemoteClusterRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.AddOrUpdateRemoteClusterRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'frontend_address', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'enable_remote_cluster_connection', kind: 'scalar', T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: 'frontend_http_address', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddOrUpdateRemoteClusterRequest {
    return new AddOrUpdateRemoteClusterRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddOrUpdateRemoteClusterRequest {
    return new AddOrUpdateRemoteClusterRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddOrUpdateRemoteClusterRequest {
    return new AddOrUpdateRemoteClusterRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: AddOrUpdateRemoteClusterRequest | PlainMessage<AddOrUpdateRemoteClusterRequest> | undefined,
    b: AddOrUpdateRemoteClusterRequest | PlainMessage<AddOrUpdateRemoteClusterRequest> | undefined,
  ): boolean {
    return proto3.util.equals(AddOrUpdateRemoteClusterRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.AddOrUpdateRemoteClusterResponse
 */
export class AddOrUpdateRemoteClusterResponse extends Message<AddOrUpdateRemoteClusterResponse> {
  constructor(data?: PartialMessage<AddOrUpdateRemoteClusterResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.AddOrUpdateRemoteClusterResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddOrUpdateRemoteClusterResponse {
    return new AddOrUpdateRemoteClusterResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddOrUpdateRemoteClusterResponse {
    return new AddOrUpdateRemoteClusterResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddOrUpdateRemoteClusterResponse {
    return new AddOrUpdateRemoteClusterResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: AddOrUpdateRemoteClusterResponse | PlainMessage<AddOrUpdateRemoteClusterResponse> | undefined,
    b: AddOrUpdateRemoteClusterResponse | PlainMessage<AddOrUpdateRemoteClusterResponse> | undefined,
  ): boolean {
    return proto3.util.equals(AddOrUpdateRemoteClusterResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.RemoveRemoteClusterRequest
 */
export class RemoveRemoteClusterRequest extends Message<RemoveRemoteClusterRequest> {
  /**
   * Remote cluster name to be removed.
   *
   * @generated from field: string cluster_name = 1;
   */
  clusterName = ''

  constructor(data?: PartialMessage<RemoveRemoteClusterRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.RemoveRemoteClusterRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'cluster_name', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveRemoteClusterRequest {
    return new RemoveRemoteClusterRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveRemoteClusterRequest {
    return new RemoveRemoteClusterRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveRemoteClusterRequest {
    return new RemoveRemoteClusterRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: RemoveRemoteClusterRequest | PlainMessage<RemoveRemoteClusterRequest> | undefined,
    b: RemoveRemoteClusterRequest | PlainMessage<RemoveRemoteClusterRequest> | undefined,
  ): boolean {
    return proto3.util.equals(RemoveRemoteClusterRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.RemoveRemoteClusterResponse
 */
export class RemoveRemoteClusterResponse extends Message<RemoveRemoteClusterResponse> {
  constructor(data?: PartialMessage<RemoveRemoteClusterResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.RemoveRemoteClusterResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveRemoteClusterResponse {
    return new RemoveRemoteClusterResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveRemoteClusterResponse {
    return new RemoveRemoteClusterResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveRemoteClusterResponse {
    return new RemoveRemoteClusterResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: RemoveRemoteClusterResponse | PlainMessage<RemoveRemoteClusterResponse> | undefined,
    b: RemoveRemoteClusterResponse | PlainMessage<RemoveRemoteClusterResponse> | undefined,
  ): boolean {
    return proto3.util.equals(RemoveRemoteClusterResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.ListClustersRequest
 */
export class ListClustersRequest extends Message<ListClustersRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0

  /**
   * @generated from field: bytes next_page_token = 2;
   */
  nextPageToken = new Uint8Array(0)

  constructor(data?: PartialMessage<ListClustersRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.ListClustersRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'page_size', kind: 'scalar', T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: 'next_page_token', kind: 'scalar', T: 12 /* ScalarType.BYTES */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListClustersRequest {
    return new ListClustersRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListClustersRequest {
    return new ListClustersRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListClustersRequest {
    return new ListClustersRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: ListClustersRequest | PlainMessage<ListClustersRequest> | undefined,
    b: ListClustersRequest | PlainMessage<ListClustersRequest> | undefined,
  ): boolean {
    return proto3.util.equals(ListClustersRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.ListClustersResponse
 */
export class ListClustersResponse extends Message<ListClustersResponse> {
  /**
   * List of all cluster information
   *
   * @generated from field: repeated temporal.api.operatorservice.v1.ClusterMetadata clusters = 1;
   */
  clusters: ClusterMetadata[] = []

  /**
   * @generated from field: bytes next_page_token = 4;
   */
  nextPageToken = new Uint8Array(0)

  constructor(data?: PartialMessage<ListClustersResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.ListClustersResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'clusters', kind: 'message', T: ClusterMetadata, repeated: true },
    { no: 4, name: 'next_page_token', kind: 'scalar', T: 12 /* ScalarType.BYTES */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListClustersResponse {
    return new ListClustersResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListClustersResponse {
    return new ListClustersResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListClustersResponse {
    return new ListClustersResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: ListClustersResponse | PlainMessage<ListClustersResponse> | undefined,
    b: ListClustersResponse | PlainMessage<ListClustersResponse> | undefined,
  ): boolean {
    return proto3.util.equals(ListClustersResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.ClusterMetadata
 */
export class ClusterMetadata extends Message<ClusterMetadata> {
  /**
   * Name of the cluster name.
   *
   * @generated from field: string cluster_name = 1;
   */
  clusterName = ''

  /**
   * Id of the cluster.
   *
   * @generated from field: string cluster_id = 2;
   */
  clusterId = ''

  /**
   * gRPC address.
   *
   * @generated from field: string address = 3;
   */
  address = ''

  /**
   * HTTP address, if one exists.
   *
   * @generated from field: string http_address = 7;
   */
  httpAddress = ''

  /**
   * A unique failover version across all connected clusters.
   *
   * @generated from field: int64 initial_failover_version = 4;
   */
  initialFailoverVersion = protoInt64.zero

  /**
   * History service shard number.
   *
   * @generated from field: int32 history_shard_count = 5;
   */
  historyShardCount = 0

  /**
   * A flag to indicate if a connection is active.
   *
   * @generated from field: bool is_connection_enabled = 6;
   */
  isConnectionEnabled = false

  constructor(data?: PartialMessage<ClusterMetadata>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.ClusterMetadata'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'cluster_name', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'cluster_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'address', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 7, name: 'http_address', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 4, name: 'initial_failover_version', kind: 'scalar', T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: 'history_shard_count', kind: 'scalar', T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: 'is_connection_enabled', kind: 'scalar', T: 8 /* ScalarType.BOOL */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterMetadata {
    return new ClusterMetadata().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterMetadata {
    return new ClusterMetadata().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterMetadata {
    return new ClusterMetadata().fromJsonString(jsonString, options)
  }

  static equals(
    a: ClusterMetadata | PlainMessage<ClusterMetadata> | undefined,
    b: ClusterMetadata | PlainMessage<ClusterMetadata> | undefined,
  ): boolean {
    return proto3.util.equals(ClusterMetadata, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.GetNexusEndpointRequest
 */
export class GetNexusEndpointRequest extends Message<GetNexusEndpointRequest> {
  /**
   * Server-generated unique endpoint ID.
   *
   * @generated from field: string id = 1;
   */
  id = ''

  constructor(data?: PartialMessage<GetNexusEndpointRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.GetNexusEndpointRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetNexusEndpointRequest {
    return new GetNexusEndpointRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetNexusEndpointRequest {
    return new GetNexusEndpointRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetNexusEndpointRequest {
    return new GetNexusEndpointRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetNexusEndpointRequest | PlainMessage<GetNexusEndpointRequest> | undefined,
    b: GetNexusEndpointRequest | PlainMessage<GetNexusEndpointRequest> | undefined,
  ): boolean {
    return proto3.util.equals(GetNexusEndpointRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.GetNexusEndpointResponse
 */
export class GetNexusEndpointResponse extends Message<GetNexusEndpointResponse> {
  /**
   * @generated from field: temporal.api.nexus.v1.Endpoint endpoint = 1;
   */
  endpoint?: Endpoint

  constructor(data?: PartialMessage<GetNexusEndpointResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.GetNexusEndpointResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'endpoint', kind: 'message', T: Endpoint },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetNexusEndpointResponse {
    return new GetNexusEndpointResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetNexusEndpointResponse {
    return new GetNexusEndpointResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetNexusEndpointResponse {
    return new GetNexusEndpointResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetNexusEndpointResponse | PlainMessage<GetNexusEndpointResponse> | undefined,
    b: GetNexusEndpointResponse | PlainMessage<GetNexusEndpointResponse> | undefined,
  ): boolean {
    return proto3.util.equals(GetNexusEndpointResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.CreateNexusEndpointRequest
 */
export class CreateNexusEndpointRequest extends Message<CreateNexusEndpointRequest> {
  /**
   * Endpoint definition to create.
   *
   * @generated from field: temporal.api.nexus.v1.EndpointSpec spec = 1;
   */
  spec?: EndpointSpec

  constructor(data?: PartialMessage<CreateNexusEndpointRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.CreateNexusEndpointRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'spec', kind: 'message', T: EndpointSpec },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateNexusEndpointRequest {
    return new CreateNexusEndpointRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateNexusEndpointRequest {
    return new CreateNexusEndpointRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateNexusEndpointRequest {
    return new CreateNexusEndpointRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: CreateNexusEndpointRequest | PlainMessage<CreateNexusEndpointRequest> | undefined,
    b: CreateNexusEndpointRequest | PlainMessage<CreateNexusEndpointRequest> | undefined,
  ): boolean {
    return proto3.util.equals(CreateNexusEndpointRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.CreateNexusEndpointResponse
 */
export class CreateNexusEndpointResponse extends Message<CreateNexusEndpointResponse> {
  /**
   * Data post acceptance. Can be used to issue additional updates to this record.
   *
   * @generated from field: temporal.api.nexus.v1.Endpoint endpoint = 1;
   */
  endpoint?: Endpoint

  constructor(data?: PartialMessage<CreateNexusEndpointResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.CreateNexusEndpointResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'endpoint', kind: 'message', T: Endpoint },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateNexusEndpointResponse {
    return new CreateNexusEndpointResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateNexusEndpointResponse {
    return new CreateNexusEndpointResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateNexusEndpointResponse {
    return new CreateNexusEndpointResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: CreateNexusEndpointResponse | PlainMessage<CreateNexusEndpointResponse> | undefined,
    b: CreateNexusEndpointResponse | PlainMessage<CreateNexusEndpointResponse> | undefined,
  ): boolean {
    return proto3.util.equals(CreateNexusEndpointResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.UpdateNexusEndpointRequest
 */
export class UpdateNexusEndpointRequest extends Message<UpdateNexusEndpointRequest> {
  /**
   * Server-generated unique endpoint ID.
   *
   * @generated from field: string id = 1;
   */
  id = ''

  /**
   * Data version for this endpoint. Must match current version.
   *
   * @generated from field: int64 version = 2;
   */
  version = protoInt64.zero

  /**
   * @generated from field: temporal.api.nexus.v1.EndpointSpec spec = 3;
   */
  spec?: EndpointSpec

  constructor(data?: PartialMessage<UpdateNexusEndpointRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.UpdateNexusEndpointRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'version', kind: 'scalar', T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: 'spec', kind: 'message', T: EndpointSpec },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateNexusEndpointRequest {
    return new UpdateNexusEndpointRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateNexusEndpointRequest {
    return new UpdateNexusEndpointRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateNexusEndpointRequest {
    return new UpdateNexusEndpointRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: UpdateNexusEndpointRequest | PlainMessage<UpdateNexusEndpointRequest> | undefined,
    b: UpdateNexusEndpointRequest | PlainMessage<UpdateNexusEndpointRequest> | undefined,
  ): boolean {
    return proto3.util.equals(UpdateNexusEndpointRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.UpdateNexusEndpointResponse
 */
export class UpdateNexusEndpointResponse extends Message<UpdateNexusEndpointResponse> {
  /**
   * Data post acceptance. Can be used to issue additional updates to this record.
   *
   * @generated from field: temporal.api.nexus.v1.Endpoint endpoint = 1;
   */
  endpoint?: Endpoint

  constructor(data?: PartialMessage<UpdateNexusEndpointResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.UpdateNexusEndpointResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'endpoint', kind: 'message', T: Endpoint },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateNexusEndpointResponse {
    return new UpdateNexusEndpointResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateNexusEndpointResponse {
    return new UpdateNexusEndpointResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateNexusEndpointResponse {
    return new UpdateNexusEndpointResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: UpdateNexusEndpointResponse | PlainMessage<UpdateNexusEndpointResponse> | undefined,
    b: UpdateNexusEndpointResponse | PlainMessage<UpdateNexusEndpointResponse> | undefined,
  ): boolean {
    return proto3.util.equals(UpdateNexusEndpointResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.DeleteNexusEndpointRequest
 */
export class DeleteNexusEndpointRequest extends Message<DeleteNexusEndpointRequest> {
  /**
   * Server-generated unique endpoint ID.
   *
   * @generated from field: string id = 1;
   */
  id = ''

  /**
   * Data version for this endpoint. Must match current version.
   *
   * @generated from field: int64 version = 2;
   */
  version = protoInt64.zero

  constructor(data?: PartialMessage<DeleteNexusEndpointRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.DeleteNexusEndpointRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'version', kind: 'scalar', T: 3 /* ScalarType.INT64 */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteNexusEndpointRequest {
    return new DeleteNexusEndpointRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteNexusEndpointRequest {
    return new DeleteNexusEndpointRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteNexusEndpointRequest {
    return new DeleteNexusEndpointRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: DeleteNexusEndpointRequest | PlainMessage<DeleteNexusEndpointRequest> | undefined,
    b: DeleteNexusEndpointRequest | PlainMessage<DeleteNexusEndpointRequest> | undefined,
  ): boolean {
    return proto3.util.equals(DeleteNexusEndpointRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.DeleteNexusEndpointResponse
 */
export class DeleteNexusEndpointResponse extends Message<DeleteNexusEndpointResponse> {
  constructor(data?: PartialMessage<DeleteNexusEndpointResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.DeleteNexusEndpointResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteNexusEndpointResponse {
    return new DeleteNexusEndpointResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteNexusEndpointResponse {
    return new DeleteNexusEndpointResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteNexusEndpointResponse {
    return new DeleteNexusEndpointResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: DeleteNexusEndpointResponse | PlainMessage<DeleteNexusEndpointResponse> | undefined,
    b: DeleteNexusEndpointResponse | PlainMessage<DeleteNexusEndpointResponse> | undefined,
  ): boolean {
    return proto3.util.equals(DeleteNexusEndpointResponse, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.ListNexusEndpointsRequest
 */
export class ListNexusEndpointsRequest extends Message<ListNexusEndpointsRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0

  /**
   * To get the next page, pass in `ListNexusEndpointsResponse.next_page_token` from the previous page's
   * response, the token will be empty if there's no other page.
   * Note: the last page may be empty if the total number of endpoints registered is a multiple of the page size.
   *
   * @generated from field: bytes next_page_token = 2;
   */
  nextPageToken = new Uint8Array(0)

  /**
   * Name of the incoming endpoint to filter on - optional. Specifying this will result in zero or one results.
   * (-- api-linter: core::203::field-behavior-required=disabled
   *     aip.dev/not-precedent: Not following linter rules. --)
   *
   * @generated from field: string name = 3;
   */
  name = ''

  constructor(data?: PartialMessage<ListNexusEndpointsRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.ListNexusEndpointsRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'page_size', kind: 'scalar', T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: 'next_page_token', kind: 'scalar', T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: 'name', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListNexusEndpointsRequest {
    return new ListNexusEndpointsRequest().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListNexusEndpointsRequest {
    return new ListNexusEndpointsRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListNexusEndpointsRequest {
    return new ListNexusEndpointsRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: ListNexusEndpointsRequest | PlainMessage<ListNexusEndpointsRequest> | undefined,
    b: ListNexusEndpointsRequest | PlainMessage<ListNexusEndpointsRequest> | undefined,
  ): boolean {
    return proto3.util.equals(ListNexusEndpointsRequest, a, b)
  }
}

/**
 * @generated from message temporal.api.operatorservice.v1.ListNexusEndpointsResponse
 */
export class ListNexusEndpointsResponse extends Message<ListNexusEndpointsResponse> {
  /**
   * Token for getting the next page.
   *
   * @generated from field: bytes next_page_token = 1;
   */
  nextPageToken = new Uint8Array(0)

  /**
   * @generated from field: repeated temporal.api.nexus.v1.Endpoint endpoints = 2;
   */
  endpoints: Endpoint[] = []

  constructor(data?: PartialMessage<ListNexusEndpointsResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'temporal.api.operatorservice.v1.ListNexusEndpointsResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'next_page_token', kind: 'scalar', T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: 'endpoints', kind: 'message', T: Endpoint, repeated: true },
  ])

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListNexusEndpointsResponse {
    return new ListNexusEndpointsResponse().fromBinary(bytes, options)
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListNexusEndpointsResponse {
    return new ListNexusEndpointsResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListNexusEndpointsResponse {
    return new ListNexusEndpointsResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: ListNexusEndpointsResponse | PlainMessage<ListNexusEndpointsResponse> | undefined,
    b: ListNexusEndpointsResponse | PlainMessage<ListNexusEndpointsResponse> | undefined,
  ): boolean {
    return proto3.util.equals(ListNexusEndpointsResponse, a, b)
  }
}
