apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bayn
resources:
  - serviceaccount.yaml
  - clickhouse-secret.yaml
  - objectbucketclaim.yaml
  - postgres-objectstore.yaml
  - postgres-cluster.yaml
  - postgres-scheduled-backup.yaml
  - tigerbeetle-cluster.yaml
  - tigerbeetle-networkpolicy.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
images:
  - name: registry.ide-newton.ts.net/lab/bayn
    newName: registry.ide-newton.ts.net/lab/bayn
    newTag: "sha-2852775061c9614ba9d5474ea2fb9e0fa8f26c4c"
    digest: sha256:6608148f3576d4ada7ffcdf10329be241de1337de1ca696ea5ae0ed0ba98260a
