apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bayn
resources:
  - serviceaccount.yaml
  - clickhouse-secret.yaml
  - alpaca-sealedsecret.yaml
  - objectbucketclaim.yaml
  - postgres-objectstore.yaml
  - postgres-cluster.yaml
  - postgres-scheduled-backup.yaml
  - tigerbeetle-cluster.yaml
  - tigerbeetle-networkpolicy.yaml
  - egress-proxy.yaml
  - deployment.yaml
  - execution-bootstrap-sealedsecret.yaml
  - execution-controller.yaml
  - execution-controller-pdb.yaml
  - execution-controller-networkpolicy.yaml
  - execution-activation.yaml
  - service.yaml
  - status-pdb.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: bayn-egress-proxy
    files:
      - squid.conf
images:
  - name: bayn-main
    newName: registry.ide-newton.ts.net/lab/bayn
    newTag: "sha-8df8cb331c3e0f155ee80da52f4f3175a7a94e28"
    digest: sha256:9e2ff2a12b4c139cbd20c431ac3cb6ca75d32a7e338f32b4c755c0bdba443a18
