apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bayn
resources:
  - serviceaccount.yaml
  - clickhouse-secret.yaml
  - alpaca-sealedsecret.yaml
  - objectbucketclaim.yaml
  - postgres-objectstore.yaml
  - postgres-cluster.yaml
  - postgres-scheduled-backup.yaml
  - tigerbeetle-cluster.yaml
  - tigerbeetle-networkpolicy.yaml
  - egress-proxy.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: bayn-egress-proxy
    files:
      - squid.conf
images:
  - name: registry.ide-newton.ts.net/lab/bayn
    newName: registry.ide-newton.ts.net/lab/bayn
    newTag: "sha-12f006a961f89a2ae9a013253647cd2faf7ef0cd"
    digest: sha256:0e96a99a972c40f075c63b1684fdb1b2cb8e55ba90b358e1417e5cea2ec35357
