apiVersion: v1
kind: Secret
metadata:
  name: bayn-research-captures
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: rook-ceph/bayn-research-captures
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bayn-research-captures
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: rook-ceph/bayn-research-captures
