"""Extracted Torghut API route and support functions."""

from __future__ import annotations

from ..health_checks import (
    build_api_live_submission_gate_payload as _build_live_submission_gate_payload,
    build_control_plane_contract as _build_control_plane_contract,
    build_hypothesis_runtime_payload as _build_hypothesis_runtime_payload,
    build_shadow_first_runtime_payload as _build_shadow_first_runtime_payload,
    build_simple_lane_status_payload as _build_simple_lane_status_payload,
    empirical_jobs_status as _empirical_jobs_status,
    forecast_service_status as _forecast_service_status,
    lean_authority_status as _lean_authority_status,
    load_clickhouse_ta_status as _load_clickhouse_ta_status,
    load_options_catalog_freshness_summary as _load_options_catalog_freshness_summary,
    load_tca_summary as _load_tca_summary,
    route_claim_symbols as _route_claim_symbols,
)
from ..proof_floor_payloads import (
    build_capital_reentry_cohort_ledger_payload as _build_capital_reentry_cohort_ledger_payload,
    build_capital_replay_projection_payload as _build_capital_replay_projection_payload,
    build_clock_settlement_payload as _build_clock_settlement_payload,
    build_evidence_clock_payloads as _build_evidence_clock_payloads,
    build_freshness_carry_ledger_payload as _build_freshness_carry_ledger_payload,
    build_profit_carry_passport_ledger_payload as _build_profit_carry_passport_ledger_payload,
    build_profit_freshness_frontier_payload as _build_profit_freshness_frontier_payload,
    build_profit_repair_settlement_ledger_payload as _build_profit_repair_settlement_ledger_payload,
    build_profit_signal_quorum_payload as _build_profit_signal_quorum_payload,
    build_profitability_proof_floor_payload as _build_profitability_proof_floor_payload,
    build_quality_adjusted_profit_frontier_payload as _build_quality_adjusted_profit_frontier_payload,
    build_repair_bid_settlement_payload as _build_repair_bid_settlement_payload,
    build_repair_outcome_dividend_ledger_payload as _build_repair_outcome_dividend_ledger_payload,
    build_repair_receipt_frontier_payload as _build_repair_receipt_frontier_payload,
    build_route_evidence_clearinghouse_payload as _build_route_evidence_clearinghouse_payload,
    build_route_image_proof_summary as _build_route_image_proof_summary,
    build_route_warrant_exchange_payload as _build_route_warrant_exchange_payload,
    build_routeability_repair_acceptance_ledger_payload as _build_routeability_repair_acceptance_ledger_payload,
    build_source_serving_repair_receipt_payload as _build_source_serving_repair_receipt_payload,
    consumer_evidence_jangar_continuity_packet as _consumer_evidence_jangar_continuity_packet,
)
from fastapi import APIRouter
from typing import Any, TYPE_CHECKING


if TYPE_CHECKING:
    pass

from ..common import (
    BLOCKER_RECONCILIATION_STALE,
    BUILD_ARGO_HEALTH,
    BUILD_ARGO_SYNC_REVISION,
    BUILD_COMMIT,
    BUILD_IMAGE_DIGEST,
    BUILD_MANIFEST_COMMIT,
    BUILD_MANIFEST_IMAGE_DIGEST,
    BUILD_SOURCE_CI_REF,
    BUILD_VERSION,
    Body,
    CONSUMER_EVIDENCE_CONTROL_PLANE_DEPENDENCY_MESSAGE,
    ClickHouseSignalIngestor,
    DEFAULT_PAPER_ROUTE_EVIDENCE_TARGET_LIMIT,
    Decimal,
    Depends,
    EvidenceEpoch,
    EvidenceReceipt,
    Execution,
    ExecutionTCAMetric,
    FastAPI,
    FeatureQualityThresholds,
    Future,
    HTTPConnection,
    HTTPException,
    HTTPSConnection,
    JSONResponse,
    JangarDependencyQuorumStatus,
    LEAN_LANE_MANAGER,
    LeanLaneManager,
    Lock,
    MAX_PAPER_ROUTE_EVIDENCE_TARGET_LIMIT,
    Mapping,
    OperationalError,
    PAPER_ROUTE_RUNTIME_ACCOUNT_LABEL,
    PROFITABILITY_PROOF_FLOOR_TCA_MAX_AGE_SECONDS,
    Path,
    ProofKind,
    ProofWindowSelector,
    Query,
    RUNTIME_PROFITABILITY_LOOKBACK_HOURS,
    RUNTIME_PROFITABILITY_SCHEMA_VERSION,
    RejectedSignalOutcomeEvent,
    Request,
    Response,
    SQLAlchemyError,
    Sequence,
    Session,
    SessionLocal,
    SignalEnvelope,
    Strategy,
    StrategyRuntimeLedgerBucket,
    ThreadPoolExecutor,
    TimeoutError,
    TorghutAlpacaClient,
    TradeDecision,
    TradingScheduler,
    VNextDatasetSnapshot,
    VNextExperimentRun,
    VNextExperimentSpec,
    VNextFeatureViewSpec,
    VNextModelArtifact,
    VNextPromotionDecision,
    VNextShadowLiveDeviation,
    VNextSimulationCalibration,
    WHITEPAPER_WORKFLOW,
    WhitepaperAnalysisRun,
    WhitepaperCodexAgentRun,
    WhitepaperDesignPullRequest,
    WhitepaperEngineeringTrigger,
    WhitepaperKafkaWorker,
    WhitepaperRolloutTransition,
    WhitepaperWorkflowService,
    ACCOUNT_SCOPE_STATEMENT_TIMEOUT_MS as ACCOUNT_SCOPE_STATEMENT_TIMEOUT_MS,
    ALPACA_HEALTH_CACHE_LOCK as ALPACA_HEALTH_CACHE_LOCK,
    ALPACA_HEALTH_STATE as ALPACA_HEALTH_STATE,
    OPTIONS_CATALOG_FRESHNESS_CACHE as OPTIONS_CATALOG_FRESHNESS_CACHE,
    OPTIONS_CATALOG_FRESHNESS_CACHE_LOCK as OPTIONS_CATALOG_FRESHNESS_CACHE_LOCK,
    PAPER_ROUTE_BOUNDED_COLLECTION_ACCOUNT_LABEL as PAPER_ROUTE_BOUNDED_COLLECTION_ACCOUNT_LABEL,
    PAPER_ROUTE_TARGET_PLAN_STALE_SUCCESS_SECONDS as PAPER_ROUTE_TARGET_PLAN_STALE_SUCCESS_SECONDS,
    PAPER_ROUTE_TARGET_PLAN_SUCCESS_CACHE_LOCK as PAPER_ROUTE_TARGET_PLAN_SUCCESS_CACHE_LOCK,
    READINESS_PROMOTION_AUTHORITY_KEYS as READINESS_PROMOTION_AUTHORITY_KEYS,
    RETRYABLE_TCA_RECOMPUTE_SQLSTATES as RETRYABLE_TCA_RECOMPUTE_SQLSTATES,
    SIMPLE_LANE_ALLOWED_REJECT_REASONS as SIMPLE_LANE_ALLOWED_REJECT_REASONS,
    TRADING_DEPENDENCY_HEALTH_CACHE as TRADING_DEPENDENCY_HEALTH_CACHE,
    TRADING_DEPENDENCY_HEALTH_CACHE_LOCK as TRADING_DEPENDENCY_HEALTH_CACHE_LOCK,
    TRADING_HEALTH_SURFACE_EVALUATIONS as TRADING_HEALTH_SURFACE_EVALUATIONS,
    TRADING_HEALTH_SURFACE_EVALUATION_EXECUTOR as TRADING_HEALTH_SURFACE_EVALUATION_EXECUTOR,
    TRADING_HEALTH_SURFACE_EVALUATION_LOCK as TRADING_HEALTH_SURFACE_EVALUATION_LOCK,
    TRADING_HEALTH_SURFACE_PAYLOAD_CACHE as TRADING_HEALTH_SURFACE_PAYLOAD_CACHE,
    TRADING_HEALTH_SURFACE_TIMEOUT_SECONDS as TRADING_HEALTH_SURFACE_TIMEOUT_SECONDS,
    TRADING_STATUS_READ_BUDGET_SECONDS as TRADING_STATUS_READ_BUDGET_SECONDS,
    ZERO_NOTIONAL_TCA_RECOMPUTE_MAX_ATTEMPTS as ZERO_NOTIONAL_TCA_RECOMPUTE_MAX_ATTEMPTS,
    paper_route_target_plan_success_cache as paper_route_target_plan_success_cache,
    retryable_tca_recompute_error as retryable_tca_recompute_error,
    shared_mapping_items as shared_mapping_items,
    shared_paper_route_target_plan_from_payload as shared_paper_route_target_plan_from_payload,
    active_simulation_runtime_context,
    assert_runtime_gate_policy_contract,
    asynccontextmanager,
    autoresearch_router,
    bindparam,
    build_alpha_closure_dividend_slo,
    build_artifact_parity_receipt,
    build_capital_reentry_cohort_ledger,
    build_capital_replay_projection,
    build_clock_settlement_receipt,
    build_data_freshness_receipt,
    build_doc29_completion_status,
    build_empirical_jobs_receipt,
    build_empirical_jobs_status,
    build_evidence_clock_arbiter_and_exchange,
    build_freshness_carry_ledger,
    build_hypothesis_runtime_summary,
    build_jangar_authority_receipt,
    build_live_submission_gate_payload,
    build_llm_evaluation_metrics,
    build_portfolio_proof_receipt,
    build_profit_carry_passport_ledger,
    build_profit_freshness_frontier,
    build_profit_repair_settlement_ledger,
    build_profit_signal_quorum,
    build_profitability_proof_floor_receipt,
    build_proofs_payload,
    build_quality_adjusted_profit_frontier,
    build_renewal_bond_profit_escrow,
    build_repair_bid_settlement_ledger,
    build_repair_outcome_dividend_ledger,
    build_repair_receipt_frontier,
    build_revenue_repair_digest,
    build_route_evidence_clearinghouse_packet,
    build_route_proven_profit_receipt,
    build_route_reacquisition_board,
    build_route_warrant_exchange,
    build_routeability_repair_acceptance_ledger,
    build_runtime_ledger_profit_distance_readback,
    build_schema_receipt,
    build_service_health_receipt,
    build_shadow_first_toggle_parity,
    build_source_serving_repair_receipt_ledger,
    build_tca_gate_inputs,
    build_torghut_consumer_evidence_receipt,
    capture_posthog_event,
    cast,
    check_schema_current,
    check_tigerbeetle_health,
    compact_alpha_evidence_foundry,
    compact_alpha_readiness_settlement_conveyor,
    compact_alpha_repair_closure_board,
    compact_alpha_repair_dividend_ledger,
    compact_executable_alpha_settlement_slots,
    compact_jangar_controller_ingestion_carry,
    compact_no_delta_repair_reentry_auction,
    compile_evidence_epoch,
    cost_basis_counts_have_non_promotion_grade_costs,
    datetime,
    deepcopy,
    ensure_schema,
    evaluate_evidence_continuity,
    evaluate_feature_batch_quality,
    forecast_status_from_empirical_jobs,
    func,
    get_session,
    hypothesis_registry_requires_dependency_capability,
    inngest,
    inngest_fastapi_serve,
    json,
    jsonable_encoder,
    latest_tigerbeetle_reconciliation_payload,
    latest_tigerbeetle_reconciliation_status_payload,
    lean_authority_status,
    load_evidence_epoch_payload,
    load_hypothesis_registry,
    load_jangar_dependency_quorum,
    load_jangar_route_continuity_packet,
    load_latest_evidence_epoch_payload,
    load_quant_evidence_status,
    logger,
    logging,
    os,
    persist_evidence_epoch,
    ping,
    refresh_execution_tca_metrics,
    render_trading_metrics,
    resolve_active_capital_stage,
    resolve_hypothesis_dependency_quorum,
    run_zero_notional_repair,
    runtime_ledger_promotion_source_authority_blockers,
    select,
    settings,
    shutdown_posthog_telemetry,
    simulation_progress_snapshot,
    sys,
    text,
    tigerbeetle_ref_counts,
    time,
    timedelta,
    timezone,
    trading_time_status,
    urlencode,
    urlsplit,
    validate_hypothesis_registry_from_settings,
    whitepaper_inngest_enabled,
    whitepaper_kafka_enabled,
    whitepaper_semantic_indexing_enabled,
    whitepaper_workflow_enabled,
)

from ..common import main_runtime_value

from ..trading_scheduler_state import get_trading_scheduler
from .consumer_evidence_payload import (
    build_consumer_evidence_receipt_projection,
    build_trading_consumer_evidence_payload,
    consumer_evidence_dependency_quorum,
    consumer_evidence_summary_view,
    readiness_dependency_snapshot as _readiness_dependency_snapshot,
    revenue_repair_topline_fields,
)

router = APIRouter()


@router.get("/trading/consumer-evidence")
def trading_consumer_evidence(
    view: str | None = Query(default=None),
) -> dict[str, object]:
    """Return Jangar-facing Torghut evidence without recursive Jangar status fetches."""

    return build_trading_consumer_evidence_payload(
        summary=consumer_evidence_summary_view(view)
    )


@router.get("/trading/metrics")
def trading_metrics(session: Session = Depends(get_session)) -> dict[str, object]:
    """Expose trading metrics counters."""

    scheduler = get_trading_scheduler()
    metrics = scheduler.state.metrics
    market_context_status = scheduler.market_context_status()
    tca_summary = _load_tca_summary(session, scheduler=scheduler)
    _hypothesis_payload, hypothesis_summary, hypothesis_dependency_quorum = (
        _build_hypothesis_runtime_payload(
            scheduler,
            tca_summary=tca_summary,
            market_context_status=market_context_status,
        )
    )
    shadow_first_runtime = _build_shadow_first_runtime_payload(
        state=scheduler.state,
        hypothesis_summary=hypothesis_summary,
    )
    return {
        "metrics": metrics.to_payload(),
        "build": {
            "version": BUILD_VERSION,
            "commit": main_runtime_value("BUILD_COMMIT"),
            "image_digest": BUILD_IMAGE_DIGEST,
            "active_revision": shadow_first_runtime["active_revision"],
        },
        "shadow_first": shadow_first_runtime,
        "tca": tca_summary,
        "control_plane_contract": _build_control_plane_contract(
            scheduler.state,
            hypothesis_summary=hypothesis_summary,
            dependency_quorum=hypothesis_dependency_quorum,
        ),
    }


@router.get("/trading/simulation/progress")
def trading_simulation_progress(
    run_id: str | None = Query(default=None),
    session: Session = Depends(get_session),
) -> dict[str, object]:
    """Expose durable simulation progress for the current or requested run."""

    snapshot = simulation_progress_snapshot(session, run_id=run_id)
    active_runtime_context = active_simulation_runtime_context(session)
    snapshot["requested_run_id"] = run_id
    snapshot["active_run_id"] = (active_runtime_context or {}).get(
        "run_id"
    ) or settings.trading_simulation_run_id
    snapshot["simulation_enabled"] = settings.trading_simulation_enabled
    return cast(dict[str, object], snapshot)


@router.post("/trading/lean/backtests")
def submit_lean_backtest(
    payload: dict[str, object] = Body(default={}),
    requested_by: str | None = Query(default=None),
    session: Session = Depends(get_session),
) -> dict[str, object]:
    """Submit an asynchronous LEAN backtest and persist metadata for governance."""

    if settings.trading_lean_lane_disable_switch:
        raise HTTPException(status_code=409, detail="lean_lane_disabled")
    if not settings.trading_lean_backtest_enabled:
        raise HTTPException(status_code=409, detail="lean_backtest_lane_disabled")
    lane = str(payload.get("lane") or "research").strip() or "research"
    config_payload = payload.get("config")
    if not isinstance(config_payload, dict):
        raise HTTPException(status_code=400, detail="config_must_be_object")
    config = {
        str(key): value
        for key, value in cast(dict[object, Any], config_payload).items()
    }
    try:
        row = LEAN_LANE_MANAGER.submit_backtest(
            session,
            config=config,
            lane=lane,
            requested_by=requested_by,
            correlation_id=f"torghut-backtest-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc
    return {
        "backtest_id": row.backtest_id,
        "status": row.status,
        "lane": row.lane,
        "reproducibility_hash": row.reproducibility_hash,
        "requested_by": row.requested_by,
        "created_at": row.created_at,
    }


@router.get("/trading/lean/backtests/{backtest_id}")
def get_lean_backtest(
    backtest_id: str, session: Session = Depends(get_session)
) -> dict[str, object]:
    """Refresh and return LEAN backtest lifecycle state and reproducibility evidence."""

    try:
        row = LEAN_LANE_MANAGER.refresh_backtest(session, backtest_id=backtest_id)
    except RuntimeError as exc:
        detail = str(exc)
        status = 404 if detail == "lean_backtest_not_found" else 502
        raise HTTPException(status_code=status, detail=detail) from exc
    return {
        "backtest_id": row.backtest_id,
        "status": row.status,
        "lane": row.lane,
        "result": row.result_json,
        "artifacts": row.artifacts_json,
        "reproducibility_hash": row.reproducibility_hash,
        "replay_hash": row.replay_hash,
        "deterministic_replay_passed": row.deterministic_replay_passed,
        "failure_taxonomy": row.failure_taxonomy,
        "completed_at": row.completed_at,
    }


@router.get("/trading/lean/shadow/parity")
def get_lean_shadow_parity(
    lookback_hours: int = Query(default=24, ge=1, le=168),
    session: Session = Depends(get_session),
) -> dict[str, object]:
    """Return LEAN shadow execution parity summary for drift detection and governance."""

    summary = LEAN_LANE_MANAGER.parity_summary(
        session,
        lookback_hours=lookback_hours,
    )
    return summary


# Explicit barrel exports; keeps re-export imports intentional without file-level Ruff ignores.
__all__: tuple[str, ...] = (
    "ACCOUNT_SCOPE_STATEMENT_TIMEOUT_MS",
    "ALPACA_HEALTH_CACHE_LOCK",
    "ALPACA_HEALTH_STATE",
    "APIRouter",
    "Any",
    "BLOCKER_RECONCILIATION_STALE",
    "BUILD_ARGO_HEALTH",
    "BUILD_ARGO_SYNC_REVISION",
    "BUILD_COMMIT",
    "BUILD_IMAGE_DIGEST",
    "BUILD_MANIFEST_COMMIT",
    "BUILD_MANIFEST_IMAGE_DIGEST",
    "BUILD_SOURCE_CI_REF",
    "BUILD_VERSION",
    "Body",
    "CONSUMER_EVIDENCE_CONTROL_PLANE_DEPENDENCY_MESSAGE",
    "ClickHouseSignalIngestor",
    "DEFAULT_PAPER_ROUTE_EVIDENCE_TARGET_LIMIT",
    "Decimal",
    "Depends",
    "EvidenceEpoch",
    "EvidenceReceipt",
    "Execution",
    "ExecutionTCAMetric",
    "FastAPI",
    "FeatureQualityThresholds",
    "Future",
    "HTTPConnection",
    "HTTPException",
    "HTTPSConnection",
    "JSONResponse",
    "JangarDependencyQuorumStatus",
    "LEAN_LANE_MANAGER",
    "LeanLaneManager",
    "Lock",
    "MAX_PAPER_ROUTE_EVIDENCE_TARGET_LIMIT",
    "Mapping",
    "OPTIONS_CATALOG_FRESHNESS_CACHE",
    "OPTIONS_CATALOG_FRESHNESS_CACHE_LOCK",
    "OperationalError",
    "PAPER_ROUTE_BOUNDED_COLLECTION_ACCOUNT_LABEL",
    "PAPER_ROUTE_RUNTIME_ACCOUNT_LABEL",
    "PAPER_ROUTE_TARGET_PLAN_STALE_SUCCESS_SECONDS",
    "PAPER_ROUTE_TARGET_PLAN_SUCCESS_CACHE_LOCK",
    "PROFITABILITY_PROOF_FLOOR_TCA_MAX_AGE_SECONDS",
    "Path",
    "ProofKind",
    "ProofWindowSelector",
    "Query",
    "READINESS_PROMOTION_AUTHORITY_KEYS",
    "RETRYABLE_TCA_RECOMPUTE_SQLSTATES",
    "RUNTIME_PROFITABILITY_LOOKBACK_HOURS",
    "RUNTIME_PROFITABILITY_SCHEMA_VERSION",
    "RejectedSignalOutcomeEvent",
    "Request",
    "Response",
    "SIMPLE_LANE_ALLOWED_REJECT_REASONS",
    "SQLAlchemyError",
    "Sequence",
    "Session",
    "SessionLocal",
    "SignalEnvelope",
    "Strategy",
    "StrategyRuntimeLedgerBucket",
    "TRADING_DEPENDENCY_HEALTH_CACHE",
    "TRADING_DEPENDENCY_HEALTH_CACHE_LOCK",
    "TRADING_HEALTH_SURFACE_EVALUATIONS",
    "TRADING_HEALTH_SURFACE_EVALUATION_EXECUTOR",
    "TRADING_HEALTH_SURFACE_EVALUATION_LOCK",
    "TRADING_HEALTH_SURFACE_PAYLOAD_CACHE",
    "TRADING_HEALTH_SURFACE_TIMEOUT_SECONDS",
    "TRADING_STATUS_READ_BUDGET_SECONDS",
    "TYPE_CHECKING",
    "ThreadPoolExecutor",
    "TimeoutError",
    "TorghutAlpacaClient",
    "TradeDecision",
    "TradingScheduler",
    "VNextDatasetSnapshot",
    "VNextExperimentRun",
    "VNextExperimentSpec",
    "VNextFeatureViewSpec",
    "VNextModelArtifact",
    "VNextPromotionDecision",
    "VNextShadowLiveDeviation",
    "VNextSimulationCalibration",
    "WHITEPAPER_WORKFLOW",
    "WhitepaperAnalysisRun",
    "WhitepaperCodexAgentRun",
    "WhitepaperDesignPullRequest",
    "WhitepaperEngineeringTrigger",
    "WhitepaperKafkaWorker",
    "WhitepaperRolloutTransition",
    "WhitepaperWorkflowService",
    "ZERO_NOTIONAL_TCA_RECOMPUTE_MAX_ATTEMPTS",
    "ACCOUNT_SCOPE_STATEMENT_TIMEOUT_MS",
    "ALPACA_HEALTH_CACHE_LOCK",
    "ALPACA_HEALTH_STATE",
    "OPTIONS_CATALOG_FRESHNESS_CACHE",
    "OPTIONS_CATALOG_FRESHNESS_CACHE_LOCK",
    "PAPER_ROUTE_BOUNDED_COLLECTION_ACCOUNT_LABEL",
    "PAPER_ROUTE_TARGET_PLAN_STALE_SUCCESS_SECONDS",
    "PAPER_ROUTE_TARGET_PLAN_SUCCESS_CACHE_LOCK",
    "READINESS_PROMOTION_AUTHORITY_KEYS",
    "RETRYABLE_TCA_RECOMPUTE_SQLSTATES",
    "SIMPLE_LANE_ALLOWED_REJECT_REASONS",
    "TRADING_DEPENDENCY_HEALTH_CACHE",
    "TRADING_DEPENDENCY_HEALTH_CACHE_LOCK",
    "TRADING_HEALTH_SURFACE_EVALUATIONS",
    "TRADING_HEALTH_SURFACE_EVALUATION_EXECUTOR",
    "TRADING_HEALTH_SURFACE_EVALUATION_LOCK",
    "TRADING_HEALTH_SURFACE_PAYLOAD_CACHE",
    "TRADING_HEALTH_SURFACE_TIMEOUT_SECONDS",
    "TRADING_STATUS_READ_BUDGET_SECONDS",
    "ZERO_NOTIONAL_TCA_RECOMPUTE_MAX_ATTEMPTS",
    "_build_capital_reentry_cohort_ledger_payload",
    "_build_capital_replay_projection_payload",
    "_build_clock_settlement_payload",
    "build_consumer_evidence_receipt_projection",
    "_build_control_plane_contract",
    "_build_evidence_clock_payloads",
    "_build_freshness_carry_ledger_payload",
    "_build_hypothesis_runtime_payload",
    "_build_live_submission_gate_payload",
    "_build_profit_carry_passport_ledger_payload",
    "_build_profit_freshness_frontier_payload",
    "_build_profit_repair_settlement_ledger_payload",
    "_build_profit_signal_quorum_payload",
    "_build_profitability_proof_floor_payload",
    "_build_quality_adjusted_profit_frontier_payload",
    "_build_repair_bid_settlement_payload",
    "_build_repair_outcome_dividend_ledger_payload",
    "_build_repair_receipt_frontier_payload",
    "_build_route_evidence_clearinghouse_payload",
    "_build_route_image_proof_summary",
    "_build_route_warrant_exchange_payload",
    "_build_routeability_repair_acceptance_ledger_payload",
    "_build_shadow_first_runtime_payload",
    "_build_simple_lane_status_payload",
    "_build_source_serving_repair_receipt_payload",
    "build_trading_consumer_evidence_payload",
    "consumer_evidence_dependency_quorum",
    "_consumer_evidence_jangar_continuity_packet",
    "consumer_evidence_summary_view",
    "_empirical_jobs_status",
    "_forecast_service_status",
    "_lean_authority_status",
    "_load_clickhouse_ta_status",
    "_load_options_catalog_freshness_summary",
    "_load_tca_summary",
    "paper_route_target_plan_success_cache",
    "_readiness_dependency_snapshot",
    "retryable_tca_recompute_error",
    "revenue_repair_topline_fields",
    "_route_claim_symbols",
    "shared_mapping_items",
    "shared_paper_route_target_plan_from_payload",
    "active_simulation_runtime_context",
    "annotations",
    "assert_runtime_gate_policy_contract",
    "asynccontextmanager",
    "autoresearch_router",
    "bindparam",
    "build_alpha_closure_dividend_slo",
    "build_artifact_parity_receipt",
    "build_capital_reentry_cohort_ledger",
    "build_capital_replay_projection",
    "build_clock_settlement_receipt",
    "build_consumer_evidence_receipt_projection",
    "build_data_freshness_receipt",
    "build_doc29_completion_status",
    "build_empirical_jobs_receipt",
    "build_empirical_jobs_status",
    "build_evidence_clock_arbiter_and_exchange",
    "build_freshness_carry_ledger",
    "build_hypothesis_runtime_summary",
    "build_jangar_authority_receipt",
    "build_live_submission_gate_payload",
    "build_llm_evaluation_metrics",
    "build_portfolio_proof_receipt",
    "build_profit_carry_passport_ledger",
    "build_profit_freshness_frontier",
    "build_profit_repair_settlement_ledger",
    "build_profit_signal_quorum",
    "build_profitability_proof_floor_receipt",
    "build_proofs_payload",
    "build_quality_adjusted_profit_frontier",
    "build_renewal_bond_profit_escrow",
    "build_repair_bid_settlement_ledger",
    "build_repair_outcome_dividend_ledger",
    "build_repair_receipt_frontier",
    "build_revenue_repair_digest",
    "build_route_evidence_clearinghouse_packet",
    "build_route_proven_profit_receipt",
    "build_route_reacquisition_board",
    "build_route_warrant_exchange",
    "build_routeability_repair_acceptance_ledger",
    "build_runtime_ledger_profit_distance_readback",
    "build_schema_receipt",
    "build_service_health_receipt",
    "build_shadow_first_toggle_parity",
    "build_source_serving_repair_receipt_ledger",
    "build_tca_gate_inputs",
    "build_torghut_consumer_evidence_receipt",
    "build_trading_consumer_evidence_payload",
    "capture_posthog_event",
    "cast",
    "check_schema_current",
    "check_tigerbeetle_health",
    "compact_alpha_evidence_foundry",
    "compact_alpha_readiness_settlement_conveyor",
    "compact_alpha_repair_closure_board",
    "compact_alpha_repair_dividend_ledger",
    "compact_executable_alpha_settlement_slots",
    "compact_jangar_controller_ingestion_carry",
    "compact_no_delta_repair_reentry_auction",
    "compile_evidence_epoch",
    "consumer_evidence_dependency_quorum",
    "consumer_evidence_summary_view",
    "cost_basis_counts_have_non_promotion_grade_costs",
    "datetime",
    "deepcopy",
    "ensure_schema",
    "evaluate_evidence_continuity",
    "evaluate_feature_batch_quality",
    "forecast_status_from_empirical_jobs",
    "func",
    "get_lean_backtest",
    "get_lean_shadow_parity",
    "get_session",
    "get_trading_scheduler",
    "hypothesis_registry_requires_dependency_capability",
    "inngest",
    "inngest_fastapi_serve",
    "json",
    "jsonable_encoder",
    "latest_tigerbeetle_reconciliation_payload",
    "latest_tigerbeetle_reconciliation_status_payload",
    "lean_authority_status",
    "load_evidence_epoch_payload",
    "load_hypothesis_registry",
    "load_jangar_dependency_quorum",
    "load_jangar_route_continuity_packet",
    "load_latest_evidence_epoch_payload",
    "load_quant_evidence_status",
    "logger",
    "logging",
    "main_runtime_value",
    "os",
    "paper_route_target_plan_success_cache",
    "persist_evidence_epoch",
    "ping",
    "refresh_execution_tca_metrics",
    "render_trading_metrics",
    "resolve_active_capital_stage",
    "resolve_hypothesis_dependency_quorum",
    "retryable_tca_recompute_error",
    "revenue_repair_topline_fields",
    "router",
    "run_zero_notional_repair",
    "runtime_ledger_promotion_source_authority_blockers",
    "select",
    "settings",
    "shared_mapping_items",
    "shared_paper_route_target_plan_from_payload",
    "shutdown_posthog_telemetry",
    "simulation_progress_snapshot",
    "submit_lean_backtest",
    "sys",
    "text",
    "tigerbeetle_ref_counts",
    "time",
    "timedelta",
    "timezone",
    "trading_consumer_evidence",
    "trading_metrics",
    "trading_simulation_progress",
    "trading_time_status",
    "urlencode",
    "urlsplit",
    "validate_hypothesis_registry_from_settings",
    "whitepaper_inngest_enabled",
    "whitepaper_kafka_enabled",
    "whitepaper_semantic_indexing_enabled",
    "whitepaper_workflow_enabled",
)
