apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: torghut-command-auth
  namespace: torghut
  labels:
    app.kubernetes.io/name: torghut
    app.kubernetes.io/component: command-auth
spec:
  encryptedData:
    token: AgBQhg1gKg5SL/zmDZJb8JAAvwpHKfU+50H0/DZ6pK78KUpTayhvIlPLpkoTMuB9UPRjQayjXwFu1E5qirzrjXbxCl7YiRPskOw/YbOP0Z5T2t8TVGst4VdTHjXnDX263lXMhu4ZK1XRlHUkhDdsoUGQt6LZqw46gxE9oEuxHsAleQt69sW0be7NcQpAZr8LWKSMuBjuhXxvrqLur3G/93ZzWes+toopzur94j3YMCSO1YpMqNB+yhQd0V+W9Jj2P/hvTbakZL/K8yq7JBnsVsvZIQd4pn+6sxNqwX8/usoGNcs6025o8LnL15xV7uvuWsk5y6VaSUU2Hwdb2thl4oW6egkMafz3wtRuJR56NNhIHdYu9mGPQ8ezUNuNLr6hGRT86WZ+ee67q4eYzc7yoZW7/l4nrbYlkaTGW/hqy1C/5tRABF3a/CwHR3sna0fN0wYOA7THflDAVlaNJW1clYrKKtUGhKjX7c7uH2Dy0wffrErz7vYfmVTBrc8m15YCsdryq/CrOT2cwgBkZQQW5+tf3j7DdYvF7sKtrDx/unFR6bCIRpyV8zCGD94gqnFdXTu0T5LU1Gcf17OHcFpKGqqsZu4zyAjarzy2GpQAGnt2fPYV68ehsk5qnXDZt1j9BZmxOw8Iqg7KY+5xH8kYLFOBeJNn4c5qhHAeOIGnUp/6TkSycJmR/IPGsbKoDwQiwZeR9j56tGbhwWIyHJEEgCsaRfWm7urO5wl1OVUHSL0BDkgBv2EX2xXdXHiCh6gbVQqB4wH52vtTQl/CxKhMsyI+
  template:
    metadata:
      name: torghut-command-auth
      namespace: torghut
      labels:
        app.kubernetes.io/name: torghut
        app.kubernetes.io/component: command-auth
