apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- kustomizeconfig.yaml
resources:
- codex-auth-externalsecret.yaml
- postgres-upgrade-final-backup.yaml
- cnpg-torghut-db-objectbucketclaim.yaml
- ingressroute-flink-k8s-private.yaml
- sealed-secrets.yaml
- rook-ceph-rgw-argo-workflows-sealedsecret.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- alloy-rbac.yaml
- alloy-configmap.yaml
- alloy-deployment.yaml
- whitepapers-objectbucketclaim.yaml
- clickhouse
- ws
- ta
- market-data-archive
- notebooks
images:
- name: registry.ide-newton.ts.net/lab/signal-publisher
  digest: sha256:e3e67b9afeea6471533eef8d5b7fc3f08d911eed762265762f98bcb966dae120
- name: registry.ide-newton.ts.net/lab/torghut
  digest: sha256:3aa084ee0056d75a678106bc5420ca291998c45d4264aab569888f17fd96d33c
- name: registry.ide-newton.ts.net/lab/torghut-ta
  digest: sha256:ff1997a6b1b6b08b14b9b29a03ca6d3fd107ce4656ee5fa7101365b60f5a3546
- name: registry.ide-newton.ts.net/lab/torghut-ws
  digest: sha256:e3cf0761273995ebd4f983e4f20408fa2ad37eab3c7105542f795da7f1aba3a5
