apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- kustomizeconfig.yaml
resources:
- codex-auth-externalsecret.yaml
- postgres-upgrade-final-backup.yaml
- cnpg-torghut-db-objectbucketclaim.yaml
- ingressroute-flink-k8s-private.yaml
- sealed-secrets.yaml
- rook-ceph-rgw-argo-workflows-sealedsecret.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- alloy-rbac.yaml
- alloy-configmap.yaml
- alloy-deployment.yaml
- whitepapers-objectbucketclaim.yaml
- clickhouse
- ws
- ta
- market-data-archive
- notebooks
images:
- name: registry.ide-newton.ts.net/lab/signal-publisher
  digest: sha256:e1742bbab993dab528b5a12841cb45b27c7c12822ffdbce42d9249038541d0ec
- name: registry.ide-newton.ts.net/lab/torghut
  digest: sha256:12a0f0ba11f8c6eb8e69f490a0f77fae1f1f8b2dab9a6d6b6c2d0cfb6307672b
- name: registry.ide-newton.ts.net/lab/torghut-ta
  digest: sha256:b3cea19d97ed9229cf57be0507750be41c51562503ea9a8d7af12ba63427f46e
- name: registry.ide-newton.ts.net/lab/torghut-ws
  digest: sha256:d20902ea9f189cc9118d2bdd11f1ab80945111f92900d9d7830d43c471db087c
