---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rook-ceph-rgw-argo-workflows
  namespace: torghut
spec:
  encryptedData:
    accessKey: AgCF2GEGIiDWVRKCi+w1crufdaAaYsMePQ13oXjGd8WhJFgz4afWzZXavn5E2ns5gQoT8d9NrEJcHMnkS9FQbErHbF+89TJKq6Zzjyo3LoM+klkNlkyleAqn7dxGbsJAC8YXGp0/FqvvjuqfH6+bdYAaSIQezuwK80TTycWixA63auOHYabT6V9lb7/fa9iXWTjsUaJt5TBGPXNCV43r/CZDyUvDLV+P2DjDjUAlwkwVmt+1fyJMpZlVdQPWBqCSiYOXN3KtQvMwIFQX7QaETc3n7HTwKP5zitXlZRv5bdoT9LiGQ5pBxl8kVQ0OaXYlTWLWB0rGQ3/iUtkbLcIg2I4adezF7qc/WRX6W9MDjIlgSIj72+o7fzGEE+Ox/GAF38fVCYjKCa921yd37yVr7Y2coHBSZ2tNA8fVseUvoSzpvApB0j2ElVNI5708+JyQrERmuHatL00UWJlorSCS1/Fd/JcYHF2bOoOHWHcUhwLaMtVKM1QmTlMmB22zMeMKgBuXV00+1hWF6zO9onlMVV9jJi+toWLf04QNFw4naBIjtRVmQIhl3P2La+f2E1gtC0u7CUoAitZKx4epvqvIIiYJbeP7FPe33LkZ42WnWgYBo/YaJmE37YwMOgM91/2Mpx+t9g9M3IyCdAz1VZtcaDU7AKRG60plv4Zm4HDGuB81IUiiFqRqLuDTNJjCktN7qcB4FoDjJAY6vUksRJGAm1p2ZUzBIw==
    secretKey: AgCKNQ4JLxc4k6mart3kOcu+hoaG8S/85ZTdaFAcj2uBHTRwLl5TYOjJwA+OhnFaE+6ljFNFWvZFtEk2G7ZR0pVH9MEH+B7ylmps8Tnuyo6pzDcBs5MButyorDD9snSJGlWenkQ7uLF3UBJw8ZBKzOxSZy/m4XnVOH+5wkGzMNos7puY90cxBB0k68NQayU15NEPZy2ffeeYj/YNJIoegRZQ+0U4Y80RlEs0cvy1/H+PWgD+h2UMJQx9lYBAaWf/U2q1AAFLR4Md1WpzOW68akOe5RII7svu8YeG4liCGNvazoqbsMuN1N1CmeGGSSweuzFO6u1vslmDz9ZrAHSHzTS3GsMlJWAB9RdGwvpv5jD0XbKnZ/biGTi9sdGe/WIQqjyGYZyGw/+N+ldgz8QkZ7Bg/B/w//BAVtRbgLfNHC/EZ7m3LL+N999IKI1PlLuUG9ywQdNGk6SBpdzmvXIULsKdeeNHR1wAQ4XEAcTobPLMcX3OfnVfC8ehTHoQapNfs+5htblgqdHw4A9kzUI5GWrvK/sOPrEdXhBcMYl0pUgQEpcEDe9qaqxdxCIV54IIdW5OejCwZCJasRDqX1WN27o/h1btEFE7DK4CTUWX9CZYxWh2+/nCGmAoPJI7yqNEEPb4R1w2mi//CkwQO7vU9QdfVGH4aPjUgI1NCAWaP05eAja6TV8vXbrZFjstNF+iKTEulh+QfBb/WmQYnidsEjzGLoI4fVLWYskdwAoTpR7B9DPM5PrnXS08
  template:
    metadata:
      name: rook-ceph-rgw-argo-workflows
      namespace: torghut
    type: Opaque
