apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rune
resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- network-policy.yaml
images:
- name: registry.ide-newton.ts.net/lab/rune
  newName: registry.ide-newton.ts.net/lab/rune
  digest: sha256:062197d79aea16fce56c36cd76088ebea055171907993fbde77dd2d303d7738e
