apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: torghut
resources:
  - clickhouse-keeper.yaml
  - keeper-pdb.yaml
  - sealed-secret.yaml
  - bayn-sealed-secret.yaml
  - signal-publisher-sealed-secret.yaml
  - clickhouse-guardrails-exporter-configmap.yaml
  - clickhouse-guardrails-exporter.yaml
  - clickhouse-cluster.yaml
  - clickhouse-service.yaml
  - ta-replicated-table-migration-job.yaml
  - signal-schema-job.yaml
  - intraday-bars-schema-job.yaml
  - bayn-universe-v2-configmap.yaml
  - signal-publisher-cronjob.yaml
images:
  - name: registry.ide-newton.ts.net/lab/signal-publisher
    newName: registry.ide-newton.ts.net/lab/signal-publisher
    newTag: kargo-sha-e6240b280a7e35c4f178c482b0e027d39216e883
    digest: sha256:4522b02f0a09b260ec562bc5571e865c170301b3acfd1a0070654166a23922bb
