apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codex-auth
  namespace: sag
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-infra
  target:
    name: codex-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: auth.json
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: codex-auth/auth.json
        metadataPolicy: None
        nullBytePolicy: Ignore
