apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sag
resources:
  - serviceaccount.yaml
  - rbac.yaml
  - codex-auth-externalsecret.yaml
  - postgres-cluster.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
images:
  - name: registry.ide-newton.ts.net/lab/sag
    newName: registry.ide-newton.ts.net/lab/sag
    digest: sha256:a9c4dfb17a5bc8544f259cb633d087c0dcc122bbc8431bfa485425236e0a79cc
