apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sag
resources:
  - serviceaccount.yaml
  - rbac.yaml
  - codex-auth-externalsecret.yaml
  - postgres-cluster.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
images:
  - name: registry.ide-newton.ts.net/lab/sag
    newName: registry.ide-newton.ts.net/lab/sag
    digest: sha256:da99a22b2eca5ca1264abfbf048204659768ac53d8987033880d92c5b0b75ab9
