// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file temporal/api/enums/v1/batch_operation.proto (package temporal.api.enums.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file temporal/api/enums/v1/batch_operation.proto.
 */
export const file_temporal_api_enums_v1_batch_operation: GenFile = /*@__PURE__*/
  fileDesc("Cit0ZW1wb3JhbC9hcGkvZW51bXMvdjEvYmF0Y2hfb3BlcmF0aW9uLnByb3RvEhV0ZW1wb3JhbC5hcGkuZW51bXMudjEqwwYKEkJhdGNoT3BlcmF0aW9uVHlwZRIkCiBCQVRDSF9PUEVSQVRJT05fVFlQRV9VTlNQRUNJRklFRBAAEiYKHkJBVENIX09QRVJBVElPTl9UWVBFX1RFUk1JTkFURRABGgIIARIrCidCQVRDSF9PUEVSQVRJT05fVFlQRV9URVJNSU5BVEVfV09SS0ZMT1cQDRIjChtCQVRDSF9PUEVSQVRJT05fVFlQRV9DQU5DRUwQAhoCCAESKAokQkFUQ0hfT1BFUkFUSU9OX1RZUEVfQ0FOQ0VMX1dPUktGTE9XEA4SIwobQkFUQ0hfT1BFUkFUSU9OX1RZUEVfU0lHTkFMEAMaAggBEigKJEJBVENIX09QRVJBVElPTl9UWVBFX1NJR05BTF9XT1JLRkxPVxAPEiMKG0JBVENIX09QRVJBVElPTl9UWVBFX0RFTEVURRAEGgIIARIoCiRCQVRDSF9PUEVSQVRJT05fVFlQRV9ERUxFVEVfV09SS0ZMT1cQEBIiChpCQVRDSF9PUEVSQVRJT05fVFlQRV9SRVNFVBAFGgIIARInCiNCQVRDSF9PUEVSQVRJT05fVFlQRV9SRVNFVF9XT1JLRkxPVxAREjUKLUJBVENIX09QRVJBVElPTl9UWVBFX1VQREFURV9FWEVDVVRJT05fT1BUSU9OUxAGGgIIARI6CjZCQVRDSF9PUEVSQVRJT05fVFlQRV9VUERBVEVfV09SS0ZMT1dfRVhFQ1VUSU9OX09QVElPTlMQEhIpCiVCQVRDSF9PUEVSQVRJT05fVFlQRV9VTlBBVVNFX0FDVElWSVRZEAcSMAosQkFUQ0hfT1BFUkFUSU9OX1RZUEVfVVBEQVRFX0FDVElWSVRZX09QVElPTlMQCBInCiNCQVRDSF9PUEVSQVRJT05fVFlQRV9SRVNFVF9BQ1RJVklUWRAJEisKJ0JBVENIX09QRVJBVElPTl9UWVBFX1RFUk1JTkFURV9BQ1RJVklUWRAKEigKJEJBVENIX09QRVJBVElPTl9UWVBFX0NBTkNFTF9BQ1RJVklUWRALEigKJEJBVENIX09QRVJBVElPTl9UWVBFX0RFTEVURV9BQ1RJVklUWRAMKqYBChNCYXRjaE9wZXJhdGlvblN0YXRlEiUKIUJBVENIX09QRVJBVElPTl9TVEFURV9VTlNQRUNJRklFRBAAEiEKHUJBVENIX09QRVJBVElPTl9TVEFURV9SVU5OSU5HEAESIwofQkFUQ0hfT1BFUkFUSU9OX1NUQVRFX0NPTVBMRVRFRBACEiAKHEJBVENIX09QRVJBVElPTl9TVEFURV9GQUlMRUQQA0KLAQoYaW8udGVtcG9yYWwuYXBpLmVudW1zLnYxQhNCYXRjaE9wZXJhdGlvblByb3RvUAFaIWdvLnRlbXBvcmFsLmlvL2FwaS9lbnVtcy92MTtlbnVtc6oCF1RlbXBvcmFsaW8uQXBpLkVudW1zLlYx6gIaVGVtcG9yYWxpbzo6QXBpOjpFbnVtczo6VjFiBnByb3RvMw");

/**
 * @generated from enum temporal.api.enums.v1.BatchOperationType
 */
export enum BatchOperationType {
  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * DEPRECATED: Use BATCH_OPERATION_TYPE_TERMINATE_WORKFLOW instead.
   *
   * @generated from enum value: BATCH_OPERATION_TYPE_TERMINATE = 1 [deprecated = true];
   * @deprecated
   */
  TERMINATE = 1,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_TERMINATE_WORKFLOW = 13;
   */
  TERMINATE_WORKFLOW = 13,

  /**
   * DEPRECATED: Use BATCH_OPERATION_TYPE_CANCEL_WORKFLOW instead.
   *
   * @generated from enum value: BATCH_OPERATION_TYPE_CANCEL = 2 [deprecated = true];
   * @deprecated
   */
  CANCEL = 2,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_CANCEL_WORKFLOW = 14;
   */
  CANCEL_WORKFLOW = 14,

  /**
   * DEPRECATED: Use BATCH_OPERATION_TYPE_SIGNAL_WORKFLOW instead.
   *
   * @generated from enum value: BATCH_OPERATION_TYPE_SIGNAL = 3 [deprecated = true];
   * @deprecated
   */
  SIGNAL = 3,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_SIGNAL_WORKFLOW = 15;
   */
  SIGNAL_WORKFLOW = 15,

  /**
   * DEPRECATED: Use BATCH_OPERATION_TYPE_DELETE_WORKFLOW instead.
   *
   * @generated from enum value: BATCH_OPERATION_TYPE_DELETE = 4 [deprecated = true];
   * @deprecated
   */
  DELETE = 4,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_DELETE_WORKFLOW = 16;
   */
  DELETE_WORKFLOW = 16,

  /**
   * DEPRECATED: Use BATCH_OPERATION_TYPE_RESET_WORKFLOW instead.
   *
   * @generated from enum value: BATCH_OPERATION_TYPE_RESET = 5 [deprecated = true];
   * @deprecated
   */
  RESET = 5,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_RESET_WORKFLOW = 17;
   */
  RESET_WORKFLOW = 17,

  /**
   * DEPRECATED: Use BATCH_OPERATION_TYPE_UPDATE_WORKFLOW_EXECUTION_OPTIONS instead.
   *
   * @generated from enum value: BATCH_OPERATION_TYPE_UPDATE_EXECUTION_OPTIONS = 6 [deprecated = true];
   * @deprecated
   */
  UPDATE_EXECUTION_OPTIONS = 6,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_UPDATE_WORKFLOW_EXECUTION_OPTIONS = 18;
   */
  UPDATE_WORKFLOW_EXECUTION_OPTIONS = 18,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_UNPAUSE_ACTIVITY = 7;
   */
  UNPAUSE_ACTIVITY = 7,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_UPDATE_ACTIVITY_OPTIONS = 8;
   */
  UPDATE_ACTIVITY_OPTIONS = 8,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_RESET_ACTIVITY = 9;
   */
  RESET_ACTIVITY = 9,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_TERMINATE_ACTIVITY = 10;
   */
  TERMINATE_ACTIVITY = 10,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_CANCEL_ACTIVITY = 11;
   */
  CANCEL_ACTIVITY = 11,

  /**
   * @generated from enum value: BATCH_OPERATION_TYPE_DELETE_ACTIVITY = 12;
   */
  DELETE_ACTIVITY = 12,
}

/**
 * Describes the enum temporal.api.enums.v1.BatchOperationType.
 */
export const BatchOperationTypeSchema: GenEnum<BatchOperationType> = /*@__PURE__*/
  enumDesc(file_temporal_api_enums_v1_batch_operation, 0);

/**
 * @generated from enum temporal.api.enums.v1.BatchOperationState
 */
export enum BatchOperationState {
  /**
   * @generated from enum value: BATCH_OPERATION_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BATCH_OPERATION_STATE_RUNNING = 1;
   */
  RUNNING = 1,

  /**
   * @generated from enum value: BATCH_OPERATION_STATE_COMPLETED = 2;
   */
  COMPLETED = 2,

  /**
   * @generated from enum value: BATCH_OPERATION_STATE_FAILED = 3;
   */
  FAILED = 3,
}

/**
 * Describes the enum temporal.api.enums.v1.BatchOperationState.
 */
export const BatchOperationStateSchema: GenEnum<BatchOperationState> = /*@__PURE__*/
  enumDesc(file_temporal_api_enums_v1_batch_operation, 1);
