// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=ts"
// @generated from file temporal/api/enums/v1/nexus.proto (package temporal.api.enums.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from '@bufbuild/protobuf'

/**
 * NexusHandlerErrorRetryBehavior allows nexus handlers to explicity set the retry behavior of a HandlerError. If not
 * specified, retry behavior is determined from the error type. For example internal errors are not retryable by default
 * unless specified otherwise.
 *
 * @generated from enum temporal.api.enums.v1.NexusHandlerErrorRetryBehavior
 */
export enum NexusHandlerErrorRetryBehavior {
  /**
   * @generated from enum value: NEXUS_HANDLER_ERROR_RETRY_BEHAVIOR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * A handler error is explicitly marked as retryable.
   *
   * @generated from enum value: NEXUS_HANDLER_ERROR_RETRY_BEHAVIOR_RETRYABLE = 1;
   */
  RETRYABLE = 1,

  /**
   * A handler error is explicitly marked as non-retryable.
   *
   * @generated from enum value: NEXUS_HANDLER_ERROR_RETRY_BEHAVIOR_NON_RETRYABLE = 2;
   */
  NON_RETRYABLE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(NexusHandlerErrorRetryBehavior)
proto3.util.setEnumType(NexusHandlerErrorRetryBehavior, 'temporal.api.enums.v1.NexusHandlerErrorRetryBehavior', [
  { no: 0, name: 'NEXUS_HANDLER_ERROR_RETRY_BEHAVIOR_UNSPECIFIED' },
  { no: 1, name: 'NEXUS_HANDLER_ERROR_RETRY_BEHAVIOR_RETRYABLE' },
  { no: 2, name: 'NEXUS_HANDLER_ERROR_RETRY_BEHAVIOR_NON_RETRYABLE' },
])
