---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: codex-auth-symphony
  namespace: jangar
spec:
  encryptedData:
    auth.json: AgDQmU7S02S2/rd+3f+s+ViU/ETWJRzzfO3utoAY6I57SlPmgeMalWjarS3DA2ieN/Ru91dizXnO9AsTO6WIX5S0N+ktkwsuyyUgJtfY64wA4O/n7m9Wv8bQObCKm3HR28UFP5fnFrKOYA/QlTunA9ivXyqdvyjTnBUxlEGIGJIo9w86JwOnNU9jYN4qvU6fyyrUnNnhvdFakjJfy4ng/cA8DVSPhFSUaCy4sVH1eEbKt/BraGWvYixbyPudaS95lzDpbFPHAEnkjN5pGIxQ/6HGrjb/mOvwsEP9rsOIpYrf6/v2Rcd2uD+KP7xjYaUmzVKma0hk7ukPZlQIYtx2Z7YtOf4EqhQhiPsdlnKt5v7oIQF31k64H56ftBK21xZy+0Z5Lv1Lv7hiofuwTwmB0qQFcU65rcse10Pvb5+sFPPSyqwm1HIVKD2Z8TDiJ4k7MByqtjfETDUEGNdYnhhU45ZgeXwIldsr/m7K3CeZ6wVwUWeGlmvZ6cKnpTD7yHWSv6dV1Cc2WdrMkKI5ihrf4INE4dEvZB807soSyE+QCvnp/MTv3zBj7EOLH1H+4OlIpBgi3CS8hkbjky1Sez/klI7Kx14Tq6a1T3nddbD7vrf5g3ToKRPSebf4gzR/FwvqUiadaoG8T4n7npI4srCHTpYmQ+cjhFvKPmfQYhHIBvdq0sjfguPufpmQvqEkVYlFxcQEPzcB7KHbF+vp4GgiKyOA2tF9y7stwFx5+f6DZjIJZEvXzHkcdb/ONzOb7/CX3f2ac5YrfQw2a92XY/8HoicmR89/HkhfPFaqOr3vaOevIgTfBoBGyBt1avSpARbU0HxucO6Lsu/3Ww7updBSpNlLslNdxsi/FcMDIwE4vH62Rz6A/qfNM4EWyMdv5HKlvqiUs69lPSCCReZhNOi46uj37vZjaPy/JY6+TEHMU2v6cjSufkN9hz7tYg2rC/we5WSYs4+w4kofXEqLL3ZYUt888oYXHKMMrA==
  template:
    metadata:
      name: codex-auth-symphony
      namespace: jangar
