apiVersion: apps/v1
kind: Deployment
metadata:
  name: symphony
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-03-19T07:51:47Z"
    spec:
      volumes:
        - name: codex-auth
          secret:
            secretName: codex-auth-symphony
