apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
configMapGenerator:
  - name: symphony-workflow
    files:
      - WORKFLOW.md
resources:
  - ../symphony-base
  - codex-auth-sealedsecret.yaml
  - linear-api-key-sealedsecret.yaml
  - posthog-sealedsecret.yaml
  - target-argocd-role.yaml
  - target-argocd-rolebinding.yaml
patches:
  - path: deployment.patch.yaml
  - path: pvc.patch.yaml
images:
  - name: registry.ide-newton.ts.net/lab/symphony
    newName: registry.ide-newton.ts.net/lab/symphony
    newTag: "2ea968af"
    digest: sha256:dcd024f0abcb0615f698211df530056b196f0e050cedd19c118ac566eb415243
