apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
configMapGenerator:
  - name: symphony-workflow
    files:
      - WORKFLOW.md
resources:
  - ../symphony-base
  - linear-api-key-sealedsecret.yaml
  - posthog-sealedsecret.yaml
  - target-argocd-role.yaml
  - target-argocd-rolebinding.yaml
patches:
  - path: deployment.patch.yaml
  - path: pvc.patch.yaml
images:
  - name: registry.ide-newton.ts.net/lab/symphony
    newName: registry.ide-newton.ts.net/lab/symphony
    newTag: "fc28d2c3"
    digest: sha256:03a144f0e6b093ec45a8e84af34bfdc8b1629a37c336e57b0bcf581952d378ed
