apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
configMapGenerator:
  - name: symphony-workflow
    files:
      - WORKFLOW.md
resources:
  - ../symphony-base
  - codex-auth-sealedsecret.yaml
  - linear-api-key-sealedsecret.yaml
  - posthog-sealedsecret.yaml
  - target-argocd-role.yaml
  - target-argocd-rolebinding.yaml
patches:
  - path: deployment.patch.yaml
  - path: pvc.patch.yaml
images:
  - name: registry.ide-newton.ts.net/lab/symphony
    newName: registry.ide-newton.ts.net/lab/symphony
    newTag: "b7213469"
    digest: sha256:de8506f18cc9af496bb4355c9dfbec6798b3a1238429f671981e4f52ce3b14bd
