---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: symphony-linear-api-key
  namespace: jangar
spec:
  encryptedData:
    LINEAR_API_KEY: AgAiR38NxSBhv40/Yg4JNoKgJ6yWP/W8IpD0V/8+5Q9MnUyNR5472z/plWhifpSo48TyxrfDUjjFikBDGlNcTZlOFaXkdNRhvAYNho77tvC6qXfleE8pH6+tfZtryT4P0YOTSRVusNgbx2UIgK1nn6TAbYjjlghUElJWQ2P/DCF3P3eFDDMPel6ebCOfw7bTP0LAH5Tu7CChvnWJ5FLLOv3JeJAiGd5lS2tSYyBWa7FemrNkkMFxM3yjXHJvZqmcGoaHTePBarulPW7MNRcdBg9rPs/I+pw+YVCmCJYZSuQg5azfJb6TRAbSA5GM/FPcF+Qsv7a48JT5+Y4rctWYsZrVRjyQjZhY1jqsX2DxDLTZSUJNioX4f3ucz5IQXrtWCfnvCx/9OvavWWavTAYASasZgDTOv987tJdu8gd2Dnz4SBjhp4R30Yly3xuW5+AZ4SkW9aYz+IPC0v+VX2SeLokRaZ3eE9T4rIDq4UNWYClSJBjRR2dSeFK0t4HAtlwIsO0ssYdnFxmS/N0LCPsPgGGmsWFbjUwt0yJu4Zsx+Fb6uwxj5/Ue6NJt3afraMf3PvQcdyjJDv44kJZRH1OauvLz+AuH/Xofig71oyVIFvf1VbFbeNFTYMx9AsUpdWOg9J6RYmW4c/9aZWvnXLs3qMgPCRw1NESCkNmba/+bYiTcfWHcKcdgro1dANftWHxv1oeJ1S+5e+oF30OgLpxxCyc2s09iFQjLbEC0Hhej9bwVY3NygG6dCR4qxejURgRlVMw=
  template:
    metadata:
      name: symphony-linear-api-key
      namespace: jangar
