// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file temporal/api/nexusservices/workerservice/v1/request_response.proto (package temporal.api.nexusservices.workerservice.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { WorkerCommand, WorkerCommandResult } from "../../../worker/v1/message_pb.js";
import { file_temporal_api_worker_v1_message } from "../../../worker/v1/message_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file temporal/api/nexusservices/workerservice/v1/request_response.proto.
 */
export const file_temporal_api_nexusservices_workerservice_v1_request_response: GenFile = /*@__PURE__*/
  fileDesc("CkJ0ZW1wb3JhbC9hcGkvbmV4dXNzZXJ2aWNlcy93b3JrZXJzZXJ2aWNlL3YxL3JlcXVlc3RfcmVzcG9uc2UucHJvdG8SK3RlbXBvcmFsLmFwaS5uZXh1c3NlcnZpY2VzLndvcmtlcnNlcnZpY2UudjEiUQoWRXhlY3V0ZUNvbW1hbmRzUmVxdWVzdBI3Cghjb21tYW5kcxgBIAMoCzIlLnRlbXBvcmFsLmFwaS53b3JrZXIudjEuV29ya2VyQ29tbWFuZCJXChdFeGVjdXRlQ29tbWFuZHNSZXNwb25zZRI8CgdyZXN1bHRzGAEgAygLMisudGVtcG9yYWwuYXBpLndvcmtlci52MS5Xb3JrZXJDb21tYW5kUmVzdWx0Qu0BCi5pby50ZW1wb3JhbC5hcGkubmV4dXNzZXJ2aWNlcy53b3JrZXJzZXJ2aWNlLnYxQhRSZXF1ZXN0UmVzcG9uc2VQcm90b1ABWj9nby50ZW1wb3JhbC5pby9hcGkvbmV4dXNzZXJ2aWNlcy93b3JrZXJzZXJ2aWNlL3YxO3dvcmtlcnNlcnZpY2WqAi1UZW1wb3JhbGlvLkFwaS5OZXh1c3NlcnZpY2VzLldvcmtlcnNlcnZpY2UuVjHqAjFUZW1wb3JhbGlvOjpBcGk6Ok5leHVzc2VydmljZXM6OldvcmtlcnNlcnZpY2U6OlYxYgZwcm90bzM", [file_temporal_api_worker_v1_message]);

/**
 * Request payload for the "ExecuteCommands" Nexus operation.
 *
 * @generated from message temporal.api.nexusservices.workerservice.v1.ExecuteCommandsRequest
 */
export type ExecuteCommandsRequest = Message<"temporal.api.nexusservices.workerservice.v1.ExecuteCommandsRequest"> & {
  /**
   * @generated from field: repeated temporal.api.worker.v1.WorkerCommand commands = 1;
   */
  commands: WorkerCommand[];
};

/**
 * Describes the message temporal.api.nexusservices.workerservice.v1.ExecuteCommandsRequest.
 * Use `create(ExecuteCommandsRequestSchema)` to create a new message.
 */
export const ExecuteCommandsRequestSchema: GenMessage<ExecuteCommandsRequest> = /*@__PURE__*/
  messageDesc(file_temporal_api_nexusservices_workerservice_v1_request_response, 0);

/**
 * Response payload for the "ExecuteCommands" Nexus operation.
 * The results list must be 1:1 with the commands list in the request (same size and order).
 *
 * @generated from message temporal.api.nexusservices.workerservice.v1.ExecuteCommandsResponse
 */
export type ExecuteCommandsResponse = Message<"temporal.api.nexusservices.workerservice.v1.ExecuteCommandsResponse"> & {
  /**
   * @generated from field: repeated temporal.api.worker.v1.WorkerCommandResult results = 1;
   */
  results: WorkerCommandResult[];
};

/**
 * Describes the message temporal.api.nexusservices.workerservice.v1.ExecuteCommandsResponse.
 * Use `create(ExecuteCommandsResponseSchema)` to create a new message.
 */
export const ExecuteCommandsResponseSchema: GenMessage<ExecuteCommandsResponse> = /*@__PURE__*/
  messageDesc(file_temporal_api_nexusservices_workerservice_v1_request_response, 1);

