"""Shared health-cache state for Torghut API readiness surfaces."""

from datetime import datetime
from threading import Lock

TRADING_DEPENDENCY_HEALTH_CACHE_LOCK = Lock()
TRADING_DEPENDENCY_HEALTH_CACHE: dict[str, dict[str, object]] = {}
OPTIONS_CATALOG_FRESHNESS_CACHE_LOCK = Lock()
OPTIONS_CATALOG_FRESHNESS_CACHE: dict[
    tuple[str, ...], tuple[datetime, dict[str, object]]
] = {}
TRADING_STATUS_READ_BUDGET_SECONDS = 12.0
ALPACA_HEALTH_CACHE_LOCK = Lock()
ALPACA_HEALTH_STATE: dict[str, object] = {}
ACCOUNT_SCOPE_STATEMENT_TIMEOUT_MS = 150

__all__ = (
    "TRADING_DEPENDENCY_HEALTH_CACHE_LOCK",
    "TRADING_DEPENDENCY_HEALTH_CACHE",
    "OPTIONS_CATALOG_FRESHNESS_CACHE_LOCK",
    "OPTIONS_CATALOG_FRESHNESS_CACHE",
    "TRADING_STATUS_READ_BUDGET_SECONDS",
    "ALPACA_HEALTH_CACHE_LOCK",
    "ALPACA_HEALTH_STATE",
    "ACCOUNT_SCOPE_STATEMENT_TIMEOUT_MS",
)
