from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
from fastapi import APIRouter
from typing import Any, TYPE_CHECKING
from .common import *
from .proxy import capture_module_exports

def _check_postgres(*args: Any, **kwargs: Any) -> Any: ...
def _check_tigerbeetle_protocol_health(*args: Any, **kwargs: Any) -> Any: ...
def _tigerbeetle_status_int(*args: Any, **kwargs: Any) -> Any: ...
def _empty_tigerbeetle_ref_counts(*args: Any, **kwargs: Any) -> Any: ...
def _latest_reconciliation_ref_counts(*args: Any, **kwargs: Any) -> Any: ...
def _unavailable_tigerbeetle_reconciliation_payload(
    *args: Any, **kwargs: Any
) -> Any: ...
def _build_tigerbeetle_ledger_status(*args: Any, **kwargs: Any) -> Any: ...
def _build_control_plane_contract(*args: Any, **kwargs: Any) -> Any: ...
def _active_runtime_revision(*args: Any, **kwargs: Any) -> Any: ...
def _build_shadow_first_toggle_parity(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_active_capital_stage(*args: Any, **kwargs: Any) -> Any: ...
def _build_shadow_first_runtime_payload(*args: Any, **kwargs: Any) -> Any: ...
def _check_clickhouse(*args: Any, **kwargs: Any) -> Any: ...
def _forecast_service_status(*args: Any, **kwargs: Any) -> Any: ...
def _lean_authority_status(*args: Any, **kwargs: Any) -> Any: ...
def _empirical_jobs_status(*args: Any, **kwargs: Any) -> Any: ...
def _alpaca_endpoint_class(*args: Any, **kwargs: Any) -> Any: ...
def _alpaca_failure_status(*args: Any, **kwargs: Any) -> Any: ...
def _alpaca_probe_account(*args: Any, **kwargs: Any) -> Any: ...
def _remember_alpaca_success(*args: Any, **kwargs: Any) -> Any: ...
def _alpaca_cached_last_good(*args: Any, **kwargs: Any) -> Any: ...
def _check_alpaca(*args: Any, **kwargs: Any) -> Any: ...
def _tca_row_payload(*args: Any, **kwargs: Any) -> Any: ...
def _load_tca_summary(*args: Any, **kwargs: Any) -> Any: ...
def _load_clickhouse_ta_status(*args: Any, **kwargs: Any) -> Any: ...
def _budget_exhausted_live_submission_gate_payload(
    *args: Any, **kwargs: Any
) -> Any: ...
def _budget_exhausted_options_catalog_freshness_payload(
    *args: Any, **kwargs: Any
) -> Any: ...
def _route_claim_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _load_cached_options_catalog_freshness_summary(
    *args: Any, **kwargs: Any
) -> Any: ...
def _store_options_catalog_freshness_summary(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_or_none(*args: Any, **kwargs: Any) -> Any: ...
def _sqlalchemy_error_indicates_statement_timeout(*args: Any, **kwargs: Any) -> Any: ...
def _load_bounded_options_catalog_freshness_summary(
    *args: Any, **kwargs: Any
) -> Any: ...
def _load_options_catalog_freshness_summary(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_tca_scope_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_utc_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _load_last_decision_at(*args: Any, **kwargs: Any) -> Any: ...
def _build_hypothesis_runtime_payload(*args: Any, **kwargs: Any) -> Any: ...
def _build_live_submission_gate_payload(*args: Any, **kwargs: Any) -> Any: ...
def _build_simple_lane_status_payload(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
