from __future__ import annotations

from typing import Any

def _readiness_dependency_cache_key(*args: Any, **kwargs: Any) -> Any: ...
def _readiness_dependency_checks(*args: Any, **kwargs: Any) -> Any: ...
def _readiness_dependency_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def _readiness_authority_truthy(*args: Any, **kwargs: Any) -> Any: ...
def _append_unique_reason(*args: Any, **kwargs: Any) -> Any: ...
def _readiness_dependency_degradation_reason_codes(
    *args: Any, **kwargs: Any
) -> Any: ...
def _guard_live_submission_gate_for_readiness(*args: Any, **kwargs: Any) -> Any: ...
def _strip_promotion_authority_claims_for_readiness(
    *args: Any, **kwargs: Any
) -> Any: ...
def _core_readiness_live_submission_gate(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_core_readiness_payload(*args: Any, **kwargs: Any) -> Any: ...
def _trading_health_surface_cache_key(*args: Any, **kwargs: Any) -> Any: ...
def _cache_completed_trading_health_surface_payload(
    *args: Any, **kwargs: Any
) -> Any: ...
def _record_trading_health_surface_completion(*args: Any, **kwargs: Any) -> Any: ...
def _cached_trading_health_surface_payload(*args: Any, **kwargs: Any) -> Any: ...
def _cached_readiness_dependencies_for_health_surface(
    *args: Any, **kwargs: Any
) -> Any: ...
def _fail_closed_health_evaluation_gate(*args: Any, **kwargs: Any) -> Any: ...
def _health_surface_timeout_dependency_placeholder(
    *args: Any, **kwargs: Any
) -> Any: ...
def _minimal_health_surface_timeout_live_submission_gate(
    *args: Any, **kwargs: Any
) -> Any: ...
def _minimal_health_surface_timeout_proof_floor(*args: Any, **kwargs: Any) -> Any: ...
def _minimal_health_surface_timeout_payload(*args: Any, **kwargs: Any) -> Any: ...
def _health_surface_timeout_fallback_payload(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_trading_health_payload_bounded(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_trading_health_payload(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_universe_dependency(*args: Any, **kwargs: Any) -> Any: ...
def _refresh_universe_state_for_readiness(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_universe_resolver_for_readiness(*args: Any, **kwargs: Any) -> Any: ...
def _execute_readiness_account_scope_query(*args: Any, **kwargs: Any) -> Any: ...
def _check_account_scope_invariants_bounded(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_database_contract(*args: Any, **kwargs: Any) -> Any: ...

__all__: tuple[str, ...]
