from __future__ import annotations

from typing import Any

router: Any

def _consumer_evidence_dependency_quorum(*args: Any, **kwargs: Any) -> Any: ...
def _build_consumer_evidence_receipt_projection(*args: Any, **kwargs: Any) -> Any: ...
def _consumer_evidence_summary_view(*args: Any, **kwargs: Any) -> Any: ...
def _revenue_repair_topline_fields(*args: Any, **kwargs: Any) -> Any: ...
def _build_trading_consumer_evidence_payload(*args: Any, **kwargs: Any) -> Any: ...
def trading_consumer_evidence(*args: Any, **kwargs: Any) -> Any: ...
def trading_metrics(*args: Any, **kwargs: Any) -> Any: ...
def trading_simulation_progress(*args: Any, **kwargs: Any) -> Any: ...
def submit_lean_backtest(*args: Any, **kwargs: Any) -> Any: ...
def get_lean_backtest(*args: Any, **kwargs: Any) -> Any: ...
def get_lean_shadow_parity(*args: Any, **kwargs: Any) -> Any: ...
def trading_autonomy(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_evidence_grade(*args: Any, **kwargs: Any) -> Any: ...
def _daily_runtime_ledger_portfolio_summary(*args: Any, **kwargs: Any) -> Any: ...
def daily_runtime_ledger_portfolio_summary(*args: Any, **kwargs: Any) -> Any: ...
def _build_current_evidence_epoch(*args: Any, **kwargs: Any) -> Any: ...
def trading_evidence_epoch_latest(*args: Any, **kwargs: Any) -> Any: ...
def trading_evidence_epoch_detail(*args: Any, **kwargs: Any) -> Any: ...
def trading_empirical_jobs(*args: Any, **kwargs: Any) -> Any: ...
def trading_completion_doc29(*args: Any, **kwargs: Any) -> Any: ...
def trading_completion_doc29_gate(*args: Any, **kwargs: Any) -> Any: ...
def trading_autonomy_evidence_continuity(*args: Any, **kwargs: Any) -> Any: ...
def trading_llm_evaluation(*args: Any, **kwargs: Any) -> Any: ...
def prometheus_metrics(*args: Any, **kwargs: Any) -> Any: ...
def trading_decisions(*args: Any, **kwargs: Any) -> Any: ...
def trading_executions(*args: Any, **kwargs: Any) -> Any: ...

__all__: tuple[str, ...]
