//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Swarm) DeepCopyInto(out *Swarm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Swarm.
func (in *Swarm) DeepCopy() *Swarm {
	if in == nil {
		return nil
	}
	out := new(Swarm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Swarm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmCadence) DeepCopyInto(out *SwarmCadence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmCadence.
func (in *SwarmCadence) DeepCopy() *SwarmCadence {
	if in == nil {
		return nil
	}
	out := new(SwarmCadence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmDelivery) DeepCopyInto(out *SwarmDelivery) {
	*out = *in
	if in.RepoAllowlist != nil {
		in, out := &in.RepoAllowlist, &out.RepoAllowlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredChecks != nil {
		in, out := &in.RequiredChecks, &out.RequiredChecks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeploymentTargets != nil {
		in, out := &in.DeploymentTargets, &out.DeploymentTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(SwarmRollout)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmDelivery.
func (in *SwarmDelivery) DeepCopy() *SwarmDelivery {
	if in == nil {
		return nil
	}
	out := new(SwarmDelivery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmDiscovery) DeepCopyInto(out *SwarmDiscovery) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]SwarmDiscoverySource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmDiscovery.
func (in *SwarmDiscovery) DeepCopy() *SwarmDiscovery {
	if in == nil {
		return nil
	}
	out := new(SwarmDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmDiscoverySource) DeepCopyInto(out *SwarmDiscoverySource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmDiscoverySource.
func (in *SwarmDiscoverySource) DeepCopy() *SwarmDiscoverySource {
	if in == nil {
		return nil
	}
	out := new(SwarmDiscoverySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmExecution) DeepCopyInto(out *SwarmExecution) {
	*out = *in
	in.Discover.DeepCopyInto(&out.Discover)
	in.Plan.DeepCopyInto(&out.Plan)
	in.Implement.DeepCopyInto(&out.Implement)
	in.Verify.DeepCopyInto(&out.Verify)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmExecution.
func (in *SwarmExecution) DeepCopy() *SwarmExecution {
	if in == nil {
		return nil
	}
	out := new(SwarmExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmExecutionStage) DeepCopyInto(out *SwarmExecutionStage) {
	*out = *in
	if in.TargetRef != nil {
		in, out := &in.TargetRef, &out.TargetRef
		*out = new(SwarmTargetRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmExecutionStage.
func (in *SwarmExecutionStage) DeepCopy() *SwarmExecutionStage {
	if in == nil {
		return nil
	}
	out := new(SwarmExecutionStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmFreezeStatus) DeepCopyInto(out *SwarmFreezeStatus) {
	*out = *in
	if in.Until != nil {
		in, out := &in.Until, &out.Until
		*out = (*in).DeepCopy()
	}
	if in.EnteredAt != nil {
		in, out := &in.EnteredAt, &out.EnteredAt
		*out = (*in).DeepCopy()
	}
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make(map[string]v1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmFreezeStatus.
func (in *SwarmFreezeStatus) DeepCopy() *SwarmFreezeStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmFreezeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmIntegrations) DeepCopyInto(out *SwarmIntegrations) {
	*out = *in
	if in.NATS != nil {
		in, out := &in.NATS, &out.NATS
		*out = new(SwarmNATSIntegration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmIntegrations.
func (in *SwarmIntegrations) DeepCopy() *SwarmIntegrations {
	if in == nil {
		return nil
	}
	out := new(SwarmIntegrations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmList) DeepCopyInto(out *SwarmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Swarm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmList.
func (in *SwarmList) DeepCopy() *SwarmList {
	if in == nil {
		return nil
	}
	out := new(SwarmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmMission) DeepCopyInto(out *SwarmMission) {
	*out = *in
	if in.ValidationContract != nil {
		in, out := &in.ValidationContract, &out.ValidationContract
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValueGates != nil {
		in, out := &in.ValueGates, &out.ValueGates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HandoffRequiredFields != nil {
		in, out := &in.HandoffRequiredFields, &out.HandoffRequiredFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmMission.
func (in *SwarmMission) DeepCopy() *SwarmMission {
	if in == nil {
		return nil
	}
	out := new(SwarmMission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmNATSIntegration) DeepCopyInto(out *SwarmNATSIntegration) {
	*out = *in
	out.Personas = in.Personas
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmNATSIntegration.
func (in *SwarmNATSIntegration) DeepCopy() *SwarmNATSIntegration {
	if in == nil {
		return nil
	}
	out := new(SwarmNATSIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmNATSPersona) DeepCopyInto(out *SwarmNATSPersona) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmNATSPersona.
func (in *SwarmNATSPersona) DeepCopy() *SwarmNATSPersona {
	if in == nil {
		return nil
	}
	out := new(SwarmNATSPersona)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmNATSPersonas) DeepCopyInto(out *SwarmNATSPersonas) {
	*out = *in
	out.Architect = in.Architect
	out.Engineer = in.Engineer
	out.Deployer = in.Deployer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmNATSPersonas.
func (in *SwarmNATSPersonas) DeepCopy() *SwarmNATSPersonas {
	if in == nil {
		return nil
	}
	out := new(SwarmNATSPersonas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmOwner) DeepCopyInto(out *SwarmOwner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmOwner.
func (in *SwarmOwner) DeepCopy() *SwarmOwner {
	if in == nil {
		return nil
	}
	out := new(SwarmOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRequirementsStatus) DeepCopyInto(out *SwarmRequirementsStatus) {
	*out = *in
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = make(map[string]v1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.StageClearance != nil {
		in, out := &in.StageClearance, &out.StageClearance
		*out = make(map[string]v1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRequirementsStatus.
func (in *SwarmRequirementsStatus) DeepCopy() *SwarmRequirementsStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmRequirementsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRisk) DeepCopyInto(out *SwarmRisk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRisk.
func (in *SwarmRisk) DeepCopy() *SwarmRisk {
	if in == nil {
		return nil
	}
	out := new(SwarmRisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRollout) DeepCopyInto(out *SwarmRollout) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]SwarmRolloutStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRollout.
func (in *SwarmRollout) DeepCopy() *SwarmRollout {
	if in == nil {
		return nil
	}
	out := new(SwarmRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRolloutStep) DeepCopyInto(out *SwarmRolloutStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRolloutStep.
func (in *SwarmRolloutStep) DeepCopy() *SwarmRolloutStep {
	if in == nil {
		return nil
	}
	out := new(SwarmRolloutStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmSpec) DeepCopyInto(out *SwarmSpec) {
	*out = *in
	out.Owner = in.Owner
	if in.Integrations != nil {
		in, out := &in.Integrations, &out.Integrations
		*out = new(SwarmIntegrations)
		(*in).DeepCopyInto(*out)
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Objectives != nil {
		in, out := &in.Objectives, &out.Objectives
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Cadence != nil {
		in, out := &in.Cadence, &out.Cadence
		*out = new(SwarmCadence)
		**out = **in
	}
	in.Discovery.DeepCopyInto(&out.Discovery)
	in.Delivery.DeepCopyInto(&out.Delivery)
	if in.Risk != nil {
		in, out := &in.Risk, &out.Risk
		*out = new(SwarmRisk)
		**out = **in
	}
	if in.Mission != nil {
		in, out := &in.Mission, &out.Mission
		*out = new(SwarmMission)
		(*in).DeepCopyInto(*out)
	}
	in.Execution.DeepCopyInto(&out.Execution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmSpec.
func (in *SwarmSpec) DeepCopy() *SwarmSpec {
	if in == nil {
		return nil
	}
	out := new(SwarmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmStatus) DeepCopyInto(out *SwarmStatus) {
	*out = *in
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastDiscoverAt != nil {
		in, out := &in.LastDiscoverAt, &out.LastDiscoverAt
		*out = (*in).DeepCopy()
	}
	if in.LastPlanAt != nil {
		in, out := &in.LastPlanAt, &out.LastPlanAt
		*out = (*in).DeepCopy()
	}
	if in.LastImplementAt != nil {
		in, out := &in.LastImplementAt, &out.LastImplementAt
		*out = (*in).DeepCopy()
	}
	if in.LastVerifyAt != nil {
		in, out := &in.LastVerifyAt, &out.LastVerifyAt
		*out = (*in).DeepCopy()
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(SwarmRequirementsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Freeze != nil {
		in, out := &in.Freeze, &out.Freeze
		*out = new(SwarmFreezeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.StageStates != nil {
		in, out := &in.StageStates, &out.StageStates
		*out = make(map[string]v1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmStatus.
func (in *SwarmStatus) DeepCopy() *SwarmStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTargetRef) DeepCopyInto(out *SwarmTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTargetRef.
func (in *SwarmTargetRef) DeepCopy() *SwarmTargetRef {
	if in == nil {
		return nil
	}
	out := new(SwarmTargetRef)
	in.DeepCopyInto(out)
	return out
}
