apiVersion: v1
kind: Service
metadata:
  name: flamingo-tailscale
  namespace: flamingo
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
    tailscale.com/expose: "true"
    tailscale.com/hostname: flamingo
  labels:
    app.kubernetes.io/name: flamingo
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: flamingo
    app.kubernetes.io/component: model-server
  ports:
    - name: http
      port: 80
      targetPort: http
