apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ofz
resources:
  - postgres-backups.yaml
  - postgres-cluster.yaml
  - spicedb-preshared-key-sealedsecret.yaml
  - spicedb-cluster.yaml
  - playground.yaml
  - ingress.yaml
configMapGenerator:
  - name: ofz-playground-nginx
    files:
      - nginx.conf=playground-nginx.conf
