apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: posthog
  labels:
    app.kubernetes.io/name: posthog
    app.kubernetes.io/instance: posthog
  namespace: posthog
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      priority: 100
      match: Host(`posthog.proompteng.ai`) && (PathPrefix(`/batch`) || PathPrefix(`/e`) || PathPrefix(`/i/v0`) || PathPrefix(`/capture`))
      services:
        - name: posthog-capture
          port: 3000
    - kind: Rule
      match: Host(`posthog.proompteng.ai`)
      services:
        - name: posthog-web
          port: 8000
  tls: {}
