apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bilig-cert-tls.yaml
  - zero-admin-sealedsecret.yaml
  - web-runtime-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-ingressroute.yaml
  - zero-strip-prefix-middleware.yaml
  - sync-deployment.yaml
  - sync-service.yaml
  - sync-ingressroute.yaml
  - zero-pvc.yaml
  - zero-deployment.yaml
  - zero-service.yaml
  - zero-ingressroute.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - postgres-cluster.yaml
  - object-storage-configmap.yaml
  - alloy-configmap.yaml
  - alloy-deployment.yaml
  - alloy-rbac.yaml
images:
  - name: registry.ide-newton.ts.net/lab/bilig-web
    newName: registry.ide-newton.ts.net/lab/bilig-web
    newTag: bb27b4ccf6378ce5cdca2950a0a14d0090b44fb5
  - name: registry.ide-newton.ts.net/lab/bilig-sync
    newName: registry.ide-newton.ts.net/lab/bilig-sync
    newTag: bb27b4ccf6378ce5cdca2950a0a14d0090b44fb5
