apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bilig-cert-tls.yaml
  - zero-admin-sealedsecret.yaml
  - zero-strip-prefix-middleware.yaml
  - zero-data-migration-job.yaml
  - app-deployment.yaml
  - app-pdb.yaml
  - app-service.yaml
  - app-ingressroute.yaml
  - zero-pvc.yaml
  - zero-deployment.yaml
  - zero-service.yaml
  - zero-ingressroute.yaml
  - postgres-cluster.yaml
  - object-storage-configmap.yaml
  - alloy-configmap.yaml
  - alloy-deployment.yaml
  - alloy-rbac.yaml
images:
  - name: registry.ide-newton.ts.net/lab/bilig-app
    newName: registry.ide-newton.ts.net/lab/bilig-app
    newTag: e32d5fb1a7cfdc028cd8b1b72b366d91a0bf8782
