---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bilig-zero-admin
  namespace: bilig
spec:
  encryptedData:
    ZERO_ADMIN_PASSWORD: AgC3mJwlulzkXXLrYjBNNC9xGHj3Qt+lWjMMIKXlpijieAvlUhK4f7VrYFnMVOcqeaPltvVowKVvetZgO6u4aGr7AFxbj3oTo64zmV5EEY6ndJl7z3Qqqy0wVZhlnfwA8XJTJfYelwLtQA3Y0VMH51/hzsszA64V6H8kDxOxUk9PmAon92DMpzeNvUFSMitX+Wz1iyL37OsZpmdQo4id6qxDJSgdwgKpfi+jlHO9al08qs74fRr3W/rybA9qdDM/xHecwAwv1NHBHAr89uGhoI6zxzk8jh3dKxycifFo+o9LT6s8cTcCzOXD/LzVyEn4XKq90DhfDYLhPt+Pbhfo63VvV1nuiK4Xv2BItOnJi7N2C/QJp9xL+WO89rZ2L+EayaoYTtk720EgKMRkUoN2yYrkhYYmCOn52AaD+SG2g2hTF3M0jpHdfV/94N0tw7kXPn6FcyYElmmBVtUNS0XJ6Aagix7e0um/SV/jKzyGFh2HdVJHP9PcXh0G9r+rYpqCfhX7DH/9xj8nlAia2NJvb1YK9CoKo1E2VTnAp+Hr7c3oQdAqtiZLOSwpzvrhvmN1hGwXvRdATwn1aNZ+viBajLiqiKFvSOzVfTkDnGzfvOUzICCg265N+1MxOKiWyGJY4y09JuRIlmMzijzI21eYmu04fXzbUtBZt7jNWQRcbXGSDAkagqMNaPxBcYMBLTca61EKoqvk4i+RUS0UTPOsP6SOY21I6FHh34c2OAV0dRJ2wg==
  template:
    metadata:
      name: bilig-zero-admin
      namespace: bilig
