apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
resources:
- pvc-rwo.yaml
- deployment.yaml
images:
- name: registry.ide-newton.ts.net/lab/bumba
  digest: sha256:c7cd06bae0242144b631bd4be6a3e3a8501913fded590cfbfb49fa15d486a96b
