apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
resources:
  - pvc-rwo.yaml
  - deployment.yaml
images:
  - name: registry.ide-newton.ts.net/lab/bumba
    digest: sha256:e2841fc00fc42a53e8e4bffe84f63480c749112e6a5fbed0d8496ad0e0a48cc2
    newName: registry.ide-newton.ts.net/lab/bumba
