apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
resources:
  - pvc-rwo.yaml
  - deployment.yaml
images:
  - name: registry.ide-newton.ts.net/lab/bumba
    digest: sha256:2543efd2a9dc9b41dac6bcf51e347dd74b134e88aececed69bb568b1f5469306
    newName: registry.ide-newton.ts.net/lab/bumba
