// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file temporal/api/rules/v1/message.proto (package temporal.api.rules.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file temporal/api/rules/v1/message.proto.
 */
export const file_temporal_api_rules_v1_message: GenFile = /*@__PURE__*/
  fileDesc("CiN0ZW1wb3JhbC9hcGkvcnVsZXMvdjEvbWVzc2FnZS5wcm90bxIVdGVtcG9yYWwuYXBpLnJ1bGVzLnYxIo8BChJXb3JrZmxvd1J1bGVBY3Rpb24SVwoOYWN0aXZpdHlfcGF1c2UYASABKAsyPS50ZW1wb3JhbC5hcGkucnVsZXMudjEuV29ya2Zsb3dSdWxlQWN0aW9uLkFjdGlvbkFjdGl2aXR5UGF1c2VIABoVChNBY3Rpb25BY3Rpdml0eVBhdXNlQgkKB3ZhcmlhbnQivQIKEFdvcmtmbG93UnVsZVNwZWMSCgoCaWQYASABKAkSWQoOYWN0aXZpdHlfc3RhcnQYAiABKAsyPy50ZW1wb3JhbC5hcGkucnVsZXMudjEuV29ya2Zsb3dSdWxlU3BlYy5BY3Rpdml0eVN0YXJ0aW5nVHJpZ2dlckgAEhgKEHZpc2liaWxpdHlfcXVlcnkYAyABKAkSOgoHYWN0aW9ucxgEIAMoCzIpLnRlbXBvcmFsLmFwaS5ydWxlcy52MS5Xb3JrZmxvd1J1bGVBY3Rpb24SMwoPZXhwaXJhdGlvbl90aW1lGAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBosChdBY3Rpdml0eVN0YXJ0aW5nVHJpZ2dlchIRCglwcmVkaWNhdGUYASABKAlCCQoHdHJpZ2dlciKoAQoMV29ya2Zsb3dSdWxlEi8KC2NyZWF0ZV90aW1lGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI1CgRzcGVjGAIgASgLMicudGVtcG9yYWwuYXBpLnJ1bGVzLnYxLldvcmtmbG93UnVsZVNwZWMSGwoTY3JlYXRlZF9ieV9pZGVudGl0eRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCUKEAQoYaW8udGVtcG9yYWwuYXBpLnJ1bGVzLnYxQgxNZXNzYWdlUHJvdG9QAVohZ28udGVtcG9yYWwuaW8vYXBpL3J1bGVzL3YxO3J1bGVzqgIXVGVtcG9yYWxpby5BcGkuUnVsZXMuVjHqAhpUZW1wb3JhbGlvOjpBcGk6OlJ1bGVzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message temporal.api.rules.v1.WorkflowRuleAction
 */
export type WorkflowRuleAction = Message<"temporal.api.rules.v1.WorkflowRuleAction"> & {
  /**
   * Supported actions.
   *
   * @generated from oneof temporal.api.rules.v1.WorkflowRuleAction.variant
   */
  variant: {
    /**
     * @generated from field: temporal.api.rules.v1.WorkflowRuleAction.ActionActivityPause activity_pause = 1;
     */
    value: WorkflowRuleAction_ActionActivityPause;
    case: "activityPause";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message temporal.api.rules.v1.WorkflowRuleAction.
 * Use `create(WorkflowRuleActionSchema)` to create a new message.
 */
export const WorkflowRuleActionSchema: GenMessage<WorkflowRuleAction> = /*@__PURE__*/
  messageDesc(file_temporal_api_rules_v1_message, 0);

/**
 * @generated from message temporal.api.rules.v1.WorkflowRuleAction.ActionActivityPause
 */
export type WorkflowRuleAction_ActionActivityPause = Message<"temporal.api.rules.v1.WorkflowRuleAction.ActionActivityPause"> & {
};

/**
 * Describes the message temporal.api.rules.v1.WorkflowRuleAction.ActionActivityPause.
 * Use `create(WorkflowRuleAction_ActionActivityPauseSchema)` to create a new message.
 */
export const WorkflowRuleAction_ActionActivityPauseSchema: GenMessage<WorkflowRuleAction_ActionActivityPause> = /*@__PURE__*/
  messageDesc(file_temporal_api_rules_v1_message, 0, 0);

/**
 * @generated from message temporal.api.rules.v1.WorkflowRuleSpec
 */
export type WorkflowRuleSpec = Message<"temporal.api.rules.v1.WorkflowRuleSpec"> & {
  /**
   * The id of the new workflow rule. Must be unique within the namespace.
   * Can be set by the user, and can have business meaning.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Specifies how the rule should be triggered and evaluated.
   * Currently, only "activity start" type is supported.
   *
   * @generated from oneof temporal.api.rules.v1.WorkflowRuleSpec.trigger
   */
  trigger: {
    /**
     * @generated from field: temporal.api.rules.v1.WorkflowRuleSpec.ActivityStartingTrigger activity_start = 2;
     */
    value: WorkflowRuleSpec_ActivityStartingTrigger;
    case: "activityStart";
  } | { case: undefined; value?: undefined };

  /**
   * Restricted Visibility query.
   * This query is used to filter workflows in this namespace to which this rule should apply.
   * It is applied to any running workflow each time a triggering event occurs, before the trigger predicate is evaluated.
   * The following workflow attributes are supported:
   * - WorkflowType
   * - WorkflowId
   * - StartTime
   * - ExecutionStatus
   *
   * @generated from field: string visibility_query = 3;
   */
  visibilityQuery: string;

  /**
   * WorkflowRuleAction to be taken when the rule is triggered and predicate is matched.
   *
   * @generated from field: repeated temporal.api.rules.v1.WorkflowRuleAction actions = 4;
   */
  actions: WorkflowRuleAction[];

  /**
   * Expiration time of the rule. After this time, the rule will be deleted.
   * Can be empty if the rule should never expire.
   *
   * @generated from field: google.protobuf.Timestamp expiration_time = 5;
   */
  expirationTime?: Timestamp;
};

/**
 * Describes the message temporal.api.rules.v1.WorkflowRuleSpec.
 * Use `create(WorkflowRuleSpecSchema)` to create a new message.
 */
export const WorkflowRuleSpecSchema: GenMessage<WorkflowRuleSpec> = /*@__PURE__*/
  messageDesc(file_temporal_api_rules_v1_message, 1);

/**
 * Activity trigger will be triggered when an activity is about to start.
 *
 * @generated from message temporal.api.rules.v1.WorkflowRuleSpec.ActivityStartingTrigger
 */
export type WorkflowRuleSpec_ActivityStartingTrigger = Message<"temporal.api.rules.v1.WorkflowRuleSpec.ActivityStartingTrigger"> & {
  /**
   * Activity predicate is a SQL-like string filter parameter.
   * It is used to match against workflow data.
   * The following activity attributes are supported as part of the predicate:
   * - ActivityType: An Activity Type is the mapping of a name to an Activity Definition..
   * - ActivityId: The ID of the activity.
   * - ActivityAttempt: The number attempts of the activity.
   * - BackoffInterval: The current amount of time between scheduled attempts of the activity.
   * - ActivityStatus: The status of the activity. Can be one of "Scheduled", "Started", "Paused".
   * - TaskQueue: The name of the task queue the workflow specified that the activity should run on.
   * Activity predicate support the following operators:
   *  * =, !=, >, >=, <, <=
   *  * AND, OR, ()
   *  * BETWEEN ... AND
   *    STARTS_WITH
   *
   * @generated from field: string predicate = 1;
   */
  predicate: string;
};

/**
 * Describes the message temporal.api.rules.v1.WorkflowRuleSpec.ActivityStartingTrigger.
 * Use `create(WorkflowRuleSpec_ActivityStartingTriggerSchema)` to create a new message.
 */
export const WorkflowRuleSpec_ActivityStartingTriggerSchema: GenMessage<WorkflowRuleSpec_ActivityStartingTrigger> = /*@__PURE__*/
  messageDesc(file_temporal_api_rules_v1_message, 1, 0);

/**
 * WorkflowRule describes a rule that can be applied to any workflow in this namespace.
 *
 * @generated from message temporal.api.rules.v1.WorkflowRule
 */
export type WorkflowRule = Message<"temporal.api.rules.v1.WorkflowRule"> & {
  /**
   * Rule creation time.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 1;
   */
  createTime?: Timestamp;

  /**
   * Rule specification
   *
   * @generated from field: temporal.api.rules.v1.WorkflowRuleSpec spec = 2;
   */
  spec?: WorkflowRuleSpec;

  /**
   * Identity of the actor that created the rule
   * (-- api-linter: core::0140::prepositions=disabled
   *     aip.dev/not-precedent: It is better reflect the intent this way, we will also have updated_by. --)
   * (-- api-linter: core::0142::time-field-names=disabled
   *     aip.dev/not-precedent: Same as above. All other options sounds clumsy --)
   *
   * @generated from field: string created_by_identity = 3;
   */
  createdByIdentity: string;

  /**
   * Rule description.
   *
   * @generated from field: string description = 4;
   */
  description: string;
};

/**
 * Describes the message temporal.api.rules.v1.WorkflowRule.
 * Use `create(WorkflowRuleSchema)` to create a new message.
 */
export const WorkflowRuleSchema: GenMessage<WorkflowRule> = /*@__PURE__*/
  messageDesc(file_temporal_api_rules_v1_message, 2);

