// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=ts"
// @generated from file temporal/api/replication/v1/message.proto (package temporal.api.replication.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { ReplicationState } from "../../enums/v1/namespace_pbts";

/**
 * @generated from message temporal.api.replication.v1.ClusterReplicationConfig
 */
export class ClusterReplicationConfig extends Message<ClusterReplicationConfig> {
  /**
   * @generated from field: string cluster_name = 1;
   */
  clusterName = "";

  constructor(data?: PartialMessage<ClusterReplicationConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "temporal.api.replication.v1.ClusterReplicationConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cluster_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterReplicationConfig {
    return new ClusterReplicationConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterReplicationConfig {
    return new ClusterReplicationConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterReplicationConfig {
    return new ClusterReplicationConfig().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterReplicationConfig | PlainMessage<ClusterReplicationConfig> | undefined, b: ClusterReplicationConfig | PlainMessage<ClusterReplicationConfig> | undefined): boolean {
    return proto3.util.equals(ClusterReplicationConfig, a, b);
  }
}

/**
 * @generated from message temporal.api.replication.v1.NamespaceReplicationConfig
 */
export class NamespaceReplicationConfig extends Message<NamespaceReplicationConfig> {
  /**
   * @generated from field: string active_cluster_name = 1;
   */
  activeClusterName = "";

  /**
   * @generated from field: repeated temporal.api.replication.v1.ClusterReplicationConfig clusters = 2;
   */
  clusters: ClusterReplicationConfig[] = [];

  /**
   * @generated from field: temporal.api.enums.v1.ReplicationState state = 3;
   */
  state = ReplicationState.UNSPECIFIED;

  constructor(data?: PartialMessage<NamespaceReplicationConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "temporal.api.replication.v1.NamespaceReplicationConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "active_cluster_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "clusters", kind: "message", T: ClusterReplicationConfig, repeated: true },
    { no: 3, name: "state", kind: "enum", T: proto3.getEnumType(ReplicationState) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NamespaceReplicationConfig {
    return new NamespaceReplicationConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NamespaceReplicationConfig {
    return new NamespaceReplicationConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NamespaceReplicationConfig {
    return new NamespaceReplicationConfig().fromJsonString(jsonString, options);
  }

  static equals(a: NamespaceReplicationConfig | PlainMessage<NamespaceReplicationConfig> | undefined, b: NamespaceReplicationConfig | PlainMessage<NamespaceReplicationConfig> | undefined): boolean {
    return proto3.util.equals(NamespaceReplicationConfig, a, b);
  }
}

/**
 * Represents a historical replication status of a Namespace
 *
 * @generated from message temporal.api.replication.v1.FailoverStatus
 */
export class FailoverStatus extends Message<FailoverStatus> {
  /**
   * Timestamp when the Cluster switched to the following failover_version
   *
   * @generated from field: google.protobuf.Timestamp failover_time = 1;
   */
  failoverTime?: Timestamp;

  /**
   * @generated from field: int64 failover_version = 2;
   */
  failoverVersion = protoInt64.zero;

  constructor(data?: PartialMessage<FailoverStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "temporal.api.replication.v1.FailoverStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "failover_time", kind: "message", T: Timestamp },
    { no: 2, name: "failover_version", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FailoverStatus {
    return new FailoverStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FailoverStatus {
    return new FailoverStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FailoverStatus {
    return new FailoverStatus().fromJsonString(jsonString, options);
  }

  static equals(a: FailoverStatus | PlainMessage<FailoverStatus> | undefined, b: FailoverStatus | PlainMessage<FailoverStatus> | undefined): boolean {
    return proto3.util.equals(FailoverStatus, a, b);
  }
}

