// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file temporal/api/sdk/v1/external_storage.proto (package temporal.api.sdk.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file temporal/api/sdk/v1/external_storage.proto.
 */
export const file_temporal_api_sdk_v1_external_storage: GenFile = /*@__PURE__*/
  fileDesc("Cip0ZW1wb3JhbC9hcGkvc2RrL3YxL2V4dGVybmFsX3N0b3JhZ2UucHJvdG8SE3RlbXBvcmFsLmFwaS5zZGsudjEiswEKGEV4dGVybmFsU3RvcmFnZVJlZmVyZW5jZRITCgtkcml2ZXJfbmFtZRgBIAEoCRJQCgpjbGFpbV9kYXRhGAIgAygLMjwudGVtcG9yYWwuYXBpLnNkay52MS5FeHRlcm5hbFN0b3JhZ2VSZWZlcmVuY2UuQ2xhaW1EYXRhRW50cnkaMAoOQ2xhaW1EYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUKCAQoWaW8udGVtcG9yYWwuYXBpLnNkay52MUIURXh0ZXJuYWxTdG9yYWdlUHJvdG9QAVodZ28udGVtcG9yYWwuaW8vYXBpL3Nkay92MTtzZGuqAhVUZW1wb3JhbGlvLkFwaS5TZGsuVjHqAhhUZW1wb3JhbGlvOjpBcGk6OlNkazo6VjFiBnByb3RvMw");

/**
 * ExternalStorageReference identifies a payload stored in an external storage system.
 * It is used as a claim-check token, allowing the actual payload data to be retrieved
 * from the named driver using the provided claim data.
 *
 * @generated from message temporal.api.sdk.v1.ExternalStorageReference
 */
export type ExternalStorageReference = Message<"temporal.api.sdk.v1.ExternalStorageReference"> & {
  /**
   * The name of the storage driver responsible for retrieving the payload.
   *
   * @generated from field: string driver_name = 1;
   */
  driverName: string;

  /**
   * Driver-specific key-value pairs that identify and provide access to the stored payload.
   *
   * @generated from field: map<string, string> claim_data = 2;
   */
  claimData: { [key: string]: string };
};

/**
 * Describes the message temporal.api.sdk.v1.ExternalStorageReference.
 * Use `create(ExternalStorageReferenceSchema)` to create a new message.
 */
export const ExternalStorageReferenceSchema: GenMessage<ExternalStorageReference> = /*@__PURE__*/
  messageDesc(file_temporal_api_sdk_v1_external_storage, 0);

