apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - generated
images:
  - name: registry.ide-newton.ts.net/lab/analysis
    newName: registry.ide-newton.ts.net/lab/analysis
    newTag: ad95fd1764b7eb518c6eeb0794c4260f2c781708
