apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - tailscale-service.yaml
images:
  - name: registry.ide-newton.ts.net/lab/analysis
    newName: registry.ide-newton.ts.net/lab/analysis
    newTag: f885f9c9cdcfb143cdf709350ce21328ed7ae35d
