apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- generated
images:
- name: registry.ide-newton.ts.net/lab/analysis
  digest: sha256:9a3be15e849a8a6a31b8e4f21cbd6e3903a953462bde3f58183fbad64c857cea
