apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ofz-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ofz-api
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: proompteng
          podSelector:
            matchLabels:
              app: proompteng
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tengri
          podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: [tengri, tengri-kube-broker, tengri-connector-broker]
      ports:
        - protocol: TCP
          port: 9443
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: ofz-db
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: ofz-spicedb
      ports:
        - protocol: TCP
          port: 8443
    - to:
        - ipBlock:
            cidr: 100.100.244.181/32
      ports:
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8443
