/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {
    landing: Landing
  }
  globalsSelect: {
    landing: LandingSelect<false> | LandingSelect<true>
  }
  locale: null
  user: User & {
    collection: 'users'
  }
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: number
  hero: {
    announcement?: {
      label?: string | null
      href?: string | null
    }
    headline: string
    subheadline: string
    ctaLabel: string
    ctaHref: string
    secondaryCtaLabel: string
    secondaryCtaHref: string
    deRisk: string
    highlights?:
      | {
          title: string
          description: string
          id?: string | null
        }[]
      | null
  }
  benefits: {
    kicker: string
    heading: string
    description: string
    items?:
      | {
          icon?:
            | (
                | 'Layers'
                | 'Cloud'
                | 'Activity'
                | 'Boxes'
                | 'Eye'
                | 'Server'
                | 'Database'
                | 'ShieldCheck'
                | 'KeyRound'
                | 'Lock'
                | 'Network'
                | 'Brain'
              )
            | null
          title: string
          text: string
          id?: string | null
        }[]
      | null
  }
  controlPlane: {
    kicker: string
    heading: string
    description: string
    comparisonHeading: string
    comparisonNote: string
    points?:
      | {
          capability: string
          proompteng: string
          salesforceAgentforce: string
          googleGemini: string
          id?: string | null
        }[]
      | null
  }
  socialProof: {
    kicker: string
    heading: string
    description: string
    items?:
      | {
          name: string
          tagline: string
          id?: string | null
        }[]
      | null
  }
  metrics: {
    kicker: string
    heading: string
    description: string
    items?:
      | {
          value: string
          label: string
          sublabel: string
          id?: string | null
        }[]
      | null
  }
  showcase?: {
    sections?:
      | {
          id: string
          kicker: string
          heading: string
          description: string
          items?:
            | {
                icon?:
                  | (
                      | 'Layers'
                      | 'Cloud'
                      | 'Activity'
                      | 'Boxes'
                      | 'Eye'
                      | 'Server'
                      | 'Database'
                      | 'ShieldCheck'
                      | 'KeyRound'
                      | 'Lock'
                      | 'Network'
                      | 'Brain'
                    )
                  | null
                title: string
                text: string
                id?: string | null
              }[]
            | null
        }[]
      | null
  }
  useCases: {
    title: string
    items?:
      | {
          icon?:
            | (
                | 'Layers'
                | 'Cloud'
                | 'Activity'
                | 'Boxes'
                | 'Eye'
                | 'Server'
                | 'Database'
                | 'ShieldCheck'
                | 'KeyRound'
                | 'Lock'
                | 'Network'
                | 'Brain'
              )
            | null
          title: string
          text: string
          id?: string | null
        }[]
      | null
  }
  modelCatalog: {
    title: string
    items?:
      | {
          icon?:
            | (
                | 'Layers'
                | 'Cloud'
                | 'Activity'
                | 'Boxes'
                | 'Eye'
                | 'Server'
                | 'Database'
                | 'ShieldCheck'
                | 'KeyRound'
                | 'Lock'
                | 'Network'
                | 'Brain'
              )
            | null
          title: string
          text: string
          id?: string | null
        }[]
      | null
  }
  playbook: {
    kicker: string
    heading: string
    description: string
    steps?:
      | {
          title: string
          description: string
          timeframe: string
          result: string
          id?: string | null
        }[]
      | null
  }
  testimonial: {
    kicker: string
    quote: string
    author: string
    org: string
  }
  faq: {
    kicker: string
    heading: string
    description: string
    items?:
      | {
          question: string
          answer: string
          id?: string | null
        }[]
      | null
  }
  closingCta: {
    kicker: string
    heading: string
    description: string
    primaryCtaLabel: string
    primaryCtaHref: string
    secondaryCtaLabel: string
    secondaryCtaHref: string
    deRisk: string
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        announcement?:
          | T
          | {
              label?: T
              href?: T
            }
        headline?: T
        subheadline?: T
        ctaLabel?: T
        ctaHref?: T
        secondaryCtaLabel?: T
        secondaryCtaHref?: T
        deRisk?: T
        highlights?:
          | T
          | {
              title?: T
              description?: T
              id?: T
            }
      }
  benefits?:
    | T
    | {
        kicker?: T
        heading?: T
        description?: T
        items?:
          | T
          | {
              icon?: T
              title?: T
              text?: T
              id?: T
            }
      }
  controlPlane?:
    | T
    | {
        kicker?: T
        heading?: T
        description?: T
        comparisonHeading?: T
        comparisonNote?: T
        points?:
          | T
          | {
              capability?: T
              proompteng?: T
              salesforceAgentforce?: T
              googleGemini?: T
              id?: T
            }
      }
  socialProof?:
    | T
    | {
        kicker?: T
        heading?: T
        description?: T
        items?:
          | T
          | {
              name?: T
              tagline?: T
              id?: T
            }
      }
  metrics?:
    | T
    | {
        kicker?: T
        heading?: T
        description?: T
        items?:
          | T
          | {
              value?: T
              label?: T
              sublabel?: T
              id?: T
            }
      }
  showcase?:
    | T
    | {
        sections?:
          | T
          | {
              id?: T
              kicker?: T
              heading?: T
              description?: T
              items?:
                | T
                | {
                    icon?: T
                    title?: T
                    text?: T
                    id?: T
                  }
            }
      }
  useCases?:
    | T
    | {
        title?: T
        items?:
          | T
          | {
              icon?: T
              title?: T
              text?: T
              id?: T
            }
      }
  modelCatalog?:
    | T
    | {
        title?: T
        items?:
          | T
          | {
              icon?: T
              title?: T
              text?: T
              id?: T
            }
      }
  playbook?:
    | T
    | {
        kicker?: T
        heading?: T
        description?: T
        steps?:
          | T
          | {
              title?: T
              description?: T
              timeframe?: T
              result?: T
              id?: T
            }
      }
  testimonial?:
    | T
    | {
        kicker?: T
        quote?: T
        author?: T
        org?: T
      }
  faq?:
    | T
    | {
        kicker?: T
        heading?: T
        description?: T
        items?:
          | T
          | {
              question?: T
              answer?: T
              id?: T
            }
      }
  closingCta?:
    | T
    | {
        kicker?: T
        heading?: T
        description?: T
        primaryCtaLabel?: T
        primaryCtaHref?: T
        secondaryCtaLabel?: T
        secondaryCtaHref?: T
        deRisk?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
