// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file temporal/api/cloud/connectivityrule/v1/message.proto (package temporal.api.cloud.connectivityrule.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ResourceState } from "../../resource/v1/message_pb.js";
import { file_temporal_api_cloud_resource_v1_message } from "../../resource/v1/message_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file temporal/api/cloud/connectivityrule/v1/message.proto.
 */
export const file_temporal_api_cloud_connectivityrule_v1_message: GenFile = /*@__PURE__*/
  fileDesc("CjR0ZW1wb3JhbC9hcGkvY2xvdWQvY29ubmVjdGl2aXR5cnVsZS92MS9tZXNzYWdlLnByb3RvEiZ0ZW1wb3JhbC5hcGkuY2xvdWQuY29ubmVjdGl2aXR5cnVsZS52MSKWAgoQQ29ubmVjdGl2aXR5UnVsZRIKCgJpZBgBIAEoCRJKCgRzcGVjGAIgASgLMjwudGVtcG9yYWwuYXBpLmNsb3VkLmNvbm5lY3Rpdml0eXJ1bGUudjEuQ29ubmVjdGl2aXR5UnVsZVNwZWMSGAoQcmVzb3VyY2VfdmVyc2lvbhgEIAEoCRI8CgVzdGF0ZRgFIAEoDjItLnRlbXBvcmFsLmFwaS5jbG91ZC5yZXNvdXJjZS52MS5SZXNvdXJjZVN0YXRlEhoKEmFzeW5jX29wZXJhdGlvbl9pZBgGIAEoCRIwCgxjcmVhdGVkX3RpbWUYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSgQIAxAEItkBChRDb25uZWN0aXZpdHlSdWxlU3BlYxJVCgtwdWJsaWNfcnVsZRgBIAEoCzI+LnRlbXBvcmFsLmFwaS5jbG91ZC5jb25uZWN0aXZpdHlydWxlLnYxLlB1YmxpY0Nvbm5lY3Rpdml0eVJ1bGVIABJXCgxwcml2YXRlX3J1bGUYAiABKAsyPy50ZW1wb3JhbC5hcGkuY2xvdWQuY29ubmVjdGl2aXR5cnVsZS52MS5Qcml2YXRlQ29ubmVjdGl2aXR5UnVsZUgAQhEKD2Nvbm5lY3Rpb25fdHlwZSIYChZQdWJsaWNDb25uZWN0aXZpdHlSdWxlIl4KF1ByaXZhdGVDb25uZWN0aXZpdHlSdWxlEhUKDWNvbm5lY3Rpb25faWQYASABKAkSFgoOZ2NwX3Byb2plY3RfaWQYAiABKAkSDgoGcmVnaW9uGAMgASgJSgQIBBAFQtQBCilpby50ZW1wb3JhbC5hcGkuY2xvdWQuY29ubmVjdGl2aXR5cnVsZS52MUIMTWVzc2FnZVByb3RvUAFaPWdvLnRlbXBvcmFsLmlvL2FwaS9jbG91ZC9jb25uZWN0aXZpdHlydWxlL3YxO2Nvbm5lY3Rpdml0eXJ1bGWqAihUZW1wb3JhbGlvLkFwaS5DbG91ZC5Db25uZWN0aXZpdHlSdWxlLlYx6gIsVGVtcG9yYWxpbzo6QXBpOjpDbG91ZDo6Q29ubmVjdGl2aXR5UnVsZTo6VjFiBnByb3RvMw", [file_temporal_api_cloud_resource_v1_message, file_google_protobuf_timestamp]);

/**
 * @generated from message temporal.api.cloud.connectivityrule.v1.ConnectivityRule
 */
export type ConnectivityRule = Message<"temporal.api.cloud.connectivityrule.v1.ConnectivityRule"> & {
  /**
   * The id of the private connectivity rule.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The connectivity rule specification.
   *
   * @generated from field: temporal.api.cloud.connectivityrule.v1.ConnectivityRuleSpec spec = 2;
   */
  spec?: ConnectivityRuleSpec;

  /**
   * The current version of the connectivity rule specification.
   * The next update operation will have to include this version.
   *
   * @generated from field: string resource_version = 4;
   */
  resourceVersion: string;

  /**
   * @generated from field: temporal.api.cloud.resource.v1.ResourceState state = 5;
   */
  state: ResourceState;

  /**
   * The id of the async operation that is creating/updating/deleting the connectivity rule, if any.
   *
   * @generated from field: string async_operation_id = 6;
   */
  asyncOperationId: string;

  /**
   * The date and time when the connectivity rule was created.
   *
   * @generated from field: google.protobuf.Timestamp created_time = 7;
   */
  createdTime?: Timestamp;
};

/**
 * Describes the message temporal.api.cloud.connectivityrule.v1.ConnectivityRule.
 * Use `create(ConnectivityRuleSchema)` to create a new message.
 */
export const ConnectivityRuleSchema: GenMessage<ConnectivityRule> = /*@__PURE__*/
  messageDesc(file_temporal_api_cloud_connectivityrule_v1_message, 0);

/**
 * The connectivity rule specification passed in on create/update operations.
 *
 * @generated from message temporal.api.cloud.connectivityrule.v1.ConnectivityRuleSpec
 */
export type ConnectivityRuleSpec = Message<"temporal.api.cloud.connectivityrule.v1.ConnectivityRuleSpec"> & {
  /**
   * @generated from oneof temporal.api.cloud.connectivityrule.v1.ConnectivityRuleSpec.connection_type
   */
  connectionType: {
    /**
     * This allows access via public internet.
     *
     * @generated from field: temporal.api.cloud.connectivityrule.v1.PublicConnectivityRule public_rule = 1;
     */
    value: PublicConnectivityRule;
    case: "publicRule";
  } | {
    /**
     * This allows access via specific private vpc.
     *
     * @generated from field: temporal.api.cloud.connectivityrule.v1.PrivateConnectivityRule private_rule = 2;
     */
    value: PrivateConnectivityRule;
    case: "privateRule";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message temporal.api.cloud.connectivityrule.v1.ConnectivityRuleSpec.
 * Use `create(ConnectivityRuleSpecSchema)` to create a new message.
 */
export const ConnectivityRuleSpecSchema: GenMessage<ConnectivityRuleSpec> = /*@__PURE__*/
  messageDesc(file_temporal_api_cloud_connectivityrule_v1_message, 1);

/**
 * A public connectivity rule allows access to the namespace via the public internet.
 *
 * @generated from message temporal.api.cloud.connectivityrule.v1.PublicConnectivityRule
 */
export type PublicConnectivityRule = Message<"temporal.api.cloud.connectivityrule.v1.PublicConnectivityRule"> & {
};

/**
 * Describes the message temporal.api.cloud.connectivityrule.v1.PublicConnectivityRule.
 * Use `create(PublicConnectivityRuleSchema)` to create a new message.
 */
export const PublicConnectivityRuleSchema: GenMessage<PublicConnectivityRule> = /*@__PURE__*/
  messageDesc(file_temporal_api_cloud_connectivityrule_v1_message, 2);

/**
 * A private connectivity rule allows connections from a specific private vpc only.
 *
 * @generated from message temporal.api.cloud.connectivityrule.v1.PrivateConnectivityRule
 */
export type PrivateConnectivityRule = Message<"temporal.api.cloud.connectivityrule.v1.PrivateConnectivityRule"> & {
  /**
   * Connection id provided to enforce the private connectivity. This is required both by AWS and GCP.
   *
   * @generated from field: string connection_id = 1;
   */
  connectionId: string;

  /**
   * For GCP private connectivity service, GCP needs both GCP project id and the Private Service Connect Connection IDs
   * AWS only needs the connection_id
   *
   * @generated from field: string gcp_project_id = 2;
   */
  gcpProjectId: string;

  /**
   * The region of the connectivity rule. This should align with the namespace.
   * Example: "aws-us-west-2"
   *
   * @generated from field: string region = 3;
   */
  region: string;
};

/**
 * Describes the message temporal.api.cloud.connectivityrule.v1.PrivateConnectivityRule.
 * Use `create(PrivateConnectivityRuleSchema)` to create a new message.
 */
export const PrivateConnectivityRuleSchema: GenMessage<PrivateConnectivityRule> = /*@__PURE__*/
  messageDesc(file_temporal_api_cloud_connectivityrule_v1_message, 3);

