apiVersion: apps/v1
kind: Deployment
metadata:
  name: olden
  namespace: olden
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: olden
  template:
    metadata:
      labels:
        app: olden
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: olden
          image: registry.ide-newton.ts.net/lab/olden
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
