apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: registry.ide-newton.ts.net/lab/olden
    digest: sha256:c39ada7216c6d75950d88bdb69280d252002e29e9277fa4298d4c63f2b27afb0
    newName: registry.ide-newton.ts.net/lab/olden
