apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: registry.ide-newton.ts.net/lab/olden
    digest: sha256:2de252806508e7223e4a69f069a2999eeca794904f84c4583356b41f50af550c
    newName: registry.ide-newton.ts.net/lab/olden
