from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401, F811
from typing import Any
import argparse
import csv
import json
from collections import Counter, defaultdict, deque
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any, Mapping
import psycopg
from psycopg import rows
from scripts.start_historical_simulation import (
    ClickHouseRuntimeConfig,
    _as_mapping,
    _as_text,
    _build_clickhouse_runtime_config,
    _build_postgres_runtime_config,
    _build_resources,
    _default_simulation_postgres_db,
    _http_clickhouse_query,
    _load_manifest,
    _parse_rfc3339_timestamp,
    _resolve_window_bounds,
    _safe_float,
    _safe_int,
    _validate_window_policy,
)

REPORT_SCHEMA_VERSION: Any

def _parse_args(*args: Any, **kwargs: Any) -> Any: ...
def _to_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _to_list_of_strings(*args: Any, **kwargs: Any) -> Any: ...
def _as_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_to_str(*args: Any, **kwargs: Any) -> Any: ...
def _json_default(*args: Any, **kwargs: Any) -> Any: ...
def _percentile(*args: Any, **kwargs: Any) -> Any: ...
def _mean(*args: Any, **kwargs: Any) -> Any: ...
def _load_json(*args: Any, **kwargs: Any) -> Any: ...
def _parse_optional_ts(*args: Any, **kwargs: Any) -> Any: ...
def _query_rows(*args: Any, **kwargs: Any) -> Any: ...
def _extract_simulation_context(*args: Any, **kwargs: Any) -> Any: ...
def _extract_signal_event_ts(*args: Any, **kwargs: Any) -> Any: ...
def _extract_run_scope_decisions(*args: Any, **kwargs: Any) -> Any: ...
def _build_last_price_map(*args: Any, **kwargs: Any) -> Any: ...
def _fifo_trade_pnl(*args: Any, **kwargs: Any) -> Any: ...
def _csv_write(*args: Any, **kwargs: Any) -> Any: ...
def _collect_clickhouse_stats(*args: Any, **kwargs: Any) -> Any: ...
def _render_markdown(*args: Any, **kwargs: Any) -> Any: ...
def _build_report(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
