from __future__ import annotations

# pyright: reportMissingImports=false, reportMissingTypeStubs=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportUnnecessaryComparison=false, reportUnnecessaryCast=false
# ruff: noqa: F401,F811,F821
from typing import Any
import argparse
import hashlib
import json
import os
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Protocol, cast
from urllib.error import HTTPError, URLError
from urllib.parse import urljoin
from urllib.request import urlopen
from app.trading.runtime_ledger_proof_policy import (
    DEFAULT_RUNTIME_LEDGER_PROOF_MODE,
    RUNTIME_LEDGER_PROOF_MODES,
    normalize_runtime_ledger_proof_mode,
    runtime_ledger_proof_policy_from_env,
)

SCHEMA_VERSION: Any
DOC29_LIVE_SCALE_GATE: Any
DEFAULT_RUNTIME_LEDGER_PROOF_POLICY: Any
RUNTIME_LEDGER_PROOF_MODE_NOT_AUTHORITY_BLOCKER: Any
STATUS_ENDPOINT: Any
PAPER_ROUTE_EVIDENCE_ENDPOINT: Any
COMPLETION_DOC29_ENDPOINT: Any
ARTIFACT_SCHEMA_VERSION: Any
HPAIRS_SOURCE_PROOF_CENSUS_STATUS_SCHEMA_VERSION: Any
CAPITAL_PROMOTION_STATUS_BLOCKERS: Any
CAPITAL_PROMOTION_STATUS_BLOCKER_PREFIXES: Any
RUNTIME_IMPORT_MATERIALIZATION_PROMOTION_ONLY_BLOCKERS: Any
RUNTIME_IMPORT_MATERIALIZATION_STRUCTURAL_BLOCKERS: Any
DEFAULT_SERVICE_FETCH_TIMEOUT_SECONDS: Any

class _ObjectStoreClient(Protocol):
    def put_object(*args: Any, **kwargs: Any) -> Any: ...

def _utc_now(*args: Any, **kwargs: Any) -> Any: ...
def _text(*args: Any, **kwargs: Any) -> Any: ...
def _bool(*args: Any, **kwargs: Any) -> Any: ...
def _int(*args: Any, **kwargs: Any) -> Any: ...
def _decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _first_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _contains_tigerbeetle_claim(*args: Any, **kwargs: Any) -> Any: ...
def _sequence(*args: Any, **kwargs: Any) -> Any: ...
def _text_list(*args: Any, **kwargs: Any) -> Any: ...
def _hpairs_source_proof_census_status(*args: Any, **kwargs: Any) -> Any: ...
def _hpairs_source_proof_census_attachment_blockers(
    *args: Any, **kwargs: Any
) -> Any: ...
def _source_offsets(*args: Any, **kwargs: Any) -> Any: ...
def _extend_unique(*args: Any, **kwargs: Any) -> Any: ...
def _load_json_object(*args: Any, **kwargs: Any) -> Any: ...
def _load_json_url(*args: Any, **kwargs: Any) -> Any: ...
def _source_fetch_error_payload(*args: Any, **kwargs: Any) -> Any: ...
def _ceph_client_from_env(*args: Any, **kwargs: Any) -> Any: ...
def _safe_artifact_path_part(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_run_id(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_artifact_prefix(*args: Any, **kwargs: Any) -> Any: ...
def _artifact_key(*args: Any, **kwargs: Any) -> Any: ...
def _attach_and_upload_artifact(*args: Any, **kwargs: Any) -> Any: ...
def _artifact_upload_receipt_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _load_optional_json_object(*args: Any, **kwargs: Any) -> Any: ...
def _service_endpoint_url(*args: Any, **kwargs: Any) -> Any: ...
def _apply_service_base_url_defaults(*args: Any, **kwargs: Any) -> Any: ...
def _check(*args: Any, **kwargs: Any) -> Any: ...
def _completion_live_scale_gate(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_refs(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_trading_day_count(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_target_plan(*args: Any, **kwargs: Any) -> Any: ...
def _proofs_target_plan(*args: Any, **kwargs: Any) -> Any: ...
def _proof_identity_target(*args: Any, **kwargs: Any) -> Any: ...
def _proof_health_gate(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_import_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_targets(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_runtime_window_import_audit(*args: Any, **kwargs: Any) -> Any: ...
def _proofs_runtime_window_import_audit(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_runtime_window_import_audit_counts(
    *args: Any, **kwargs: Any
) -> Any: ...
def _paper_route_runtime_window_import_audit_blockers(
    *args: Any, **kwargs: Any
) -> Any: ...
def _paper_route_runtime_window_import_target_blockers(
    *args: Any, **kwargs: Any
) -> Any: ...
def _paper_route_source_activity_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _health_gate_bool(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_health_gate_summary(*args: Any, **kwargs: Any) -> Any: ...
def _missing_target_identity_count(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_payload(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_items(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_authoritative_observation_count(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_import_runtime_observations(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_target_materialization_ref(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_tigerbeetle_refs(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_target_blocker_codes(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_proof_blocker_codes(*args: Any, **kwargs: Any) -> Any: ...
def _is_runtime_import_materialization_blocker(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_materialization_blocker_codes(*args: Any, **kwargs: Any) -> Any: ...

_RUNTIME_LEDGER_PROMOTION_GRADE_SOURCE_MATERIALIZATIONS: Any
_RUNTIME_LEDGER_PROMOTION_GRADE_AUTHORITY_MARKERS: Any
_RUNTIME_LEDGER_NON_AUTHORITY_MATERIALIZATION_MARKERS: Any

def _runtime_ledger_non_authority_marker_present(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_readback_authority_markers_present(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_import_materialization_metadata_blockers(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_import_metadata_proof_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_readback_payload(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_readback_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_target_surface_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_import_materialization_summary(*args: Any, **kwargs: Any) -> Any: ...
def _first_identity(*args: Any, **kwargs: Any) -> Any: ...
def _first_env_text(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_image_digest(*args: Any, **kwargs: Any) -> Any: ...
def _commit_refs_match(*args: Any, **kwargs: Any) -> Any: ...
def _assembly_code_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _status_build_code_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_code_parity(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_immutable_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _status_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _is_capital_promotion_status_blocker(*args: Any, **kwargs: Any) -> Any: ...
def _status_gate_blocker_summary(*args: Any, **kwargs: Any) -> Any: ...
def _completion_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _required_actions(*args: Any, **kwargs: Any) -> Any: ...
def build_runtime_ledger_proof_packet(*args: Any, **kwargs: Any) -> Any: ...
def _parser(*args: Any, **kwargs: Any) -> Any: ...
def _required_source_args(*args: Any, **kwargs: Any) -> Any: ...
def _source_kind(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
