#!/usr/bin/env python
"""Assemble the Torghut runtime-ledger proof packet.

The packet is deliberately stricter than a research scorecard. It only grants
post-cost proof authority when paper-route runtime-window import output and
doc29 runtime-ledger completion evidence agree on ledger proof. Capital
promotion authority stays separate so disabled submit lanes or shadow promotion
certificates cannot make valid proof look absent. Discovery/replay artifacts can
be included as lineage, but they do not make the packet promotable by
themselves.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Protocol, cast
from urllib.error import HTTPError, URLError
from urllib.parse import urljoin
from urllib.request import urlopen

from app.trading.runtime_ledger_proof_policy import (
    DEFAULT_RUNTIME_LEDGER_PROOF_MODE,
    RUNTIME_LEDGER_PROOF_MODES,
    normalize_runtime_ledger_proof_mode,
    runtime_ledger_proof_policy_from_env,
)
from scripts.runtime_ledger_proof_packet.cli import (
    _parser,
    _required_source_args,
    _source_kind,
    main,
)
from scripts.runtime_ledger_proof_packet.common import (
    ARTIFACT_SCHEMA_VERSION,
    CAPITAL_PROMOTION_STATUS_BLOCKER_PREFIXES,
    CAPITAL_PROMOTION_STATUS_BLOCKERS,
    COMPLETION_DOC29_ENDPOINT,
    DEFAULT_RUNTIME_LEDGER_PROOF_POLICY,
    DEFAULT_SERVICE_FETCH_TIMEOUT_SECONDS,
    DOC29_LIVE_SCALE_GATE,
    HPAIRS_SOURCE_PROOF_CENSUS_STATUS_SCHEMA_VERSION,
    PAPER_ROUTE_EVIDENCE_ENDPOINT,
    RUNTIME_IMPORT_MATERIALIZATION_PROMOTION_ONLY_BLOCKERS,
    RUNTIME_IMPORT_MATERIALIZATION_STRUCTURAL_BLOCKERS,
    RUNTIME_LEDGER_PROOF_MODE_NOT_AUTHORITY_BLOCKER,
    SCHEMA_VERSION,
    STATUS_ENDPOINT,
    _ObjectStoreClient,
    _bool,
    _contains_tigerbeetle_claim,
    _decimal,
    _decimal_text,
    _first_decimal,
    _int,
    _mapping,
    _sequence,
    _text,
    _text_list,
    _utc_now,
)
from scripts.runtime_ledger_proof_packet.hpairs import (
    _extend_unique,
    _hpairs_source_proof_census_attachment_blockers,
    _hpairs_source_proof_census_status,
    _source_offsets,
)
from scripts.runtime_ledger_proof_packet.io_artifacts import (
    _apply_service_base_url_defaults,
    _artifact_key,
    _artifact_upload_receipt_blockers,
    _attach_and_upload_artifact,
    _ceph_client_from_env,
    _load_json_object,
    _load_json_url,
    _load_optional_json_object,
    _resolve_artifact_prefix,
    _runtime_window_import_run_id,
    _safe_artifact_path_part,
    _service_endpoint_url,
    _source_fetch_error_payload,
)
from scripts.runtime_ledger_proof_packet.lineage_verdict import (
    _assembly_code_lineage,
    _commit_refs_match,
    _first_env_text,
    _first_identity,
    _is_capital_promotion_status_blocker,
    _normalize_image_digest,
    _required_actions,
    _runtime_code_parity,
    _runtime_ledger_immutable_lineage,
    _status_blockers,
    _status_build_code_lineage,
    _status_gate_blocker_summary,
)
from scripts.runtime_ledger_proof_packet.packet_builder import (
    build_runtime_ledger_proof_packet,
)
from scripts.runtime_ledger_proof_packet.paper_route import (
    _check,
    _completion_live_scale_gate,
    _health_gate_bool,
    _missing_target_identity_count,
    _paper_route_import_blockers,
    _paper_route_runtime_window_import_audit,
    _paper_route_runtime_window_import_audit_blockers,
    _paper_route_runtime_window_import_audit_counts,
    _paper_route_runtime_window_import_target_blockers,
    _paper_route_source_activity_blockers,
    _paper_route_target_plan,
    _paper_route_targets,
    _proof_health_gate,
    _proof_identity_target,
    _proofs_runtime_window_import_audit,
    _proofs_target_plan,
    _runtime_ledger_refs,
    _runtime_ledger_trading_day_count,
    _runtime_window_import_health_gate_summary,
    _runtime_window_import_items,
    _runtime_window_import_lineage,
    _runtime_window_import_payload,
)
from scripts.runtime_ledger_proof_packet.runtime_import_materialization import (
    _RUNTIME_LEDGER_NON_AUTHORITY_MATERIALIZATION_MARKERS,
    _RUNTIME_LEDGER_PROMOTION_GRADE_AUTHORITY_MARKERS,
    _RUNTIME_LEDGER_PROMOTION_GRADE_SOURCE_MATERIALIZATIONS,
    _is_runtime_import_materialization_blocker,
    _runtime_import_authoritative_observation_count,
    _runtime_import_blockers,
    _runtime_import_materialization_blocker_codes,
    _runtime_import_materialization_metadata_blockers,
    _runtime_import_materialization_summary,
    _runtime_import_metadata_proof_blockers,
    _runtime_import_proof_blocker_codes,
    _runtime_import_readback_blockers,
    _runtime_import_readback_payload,
    _runtime_import_runtime_observations,
    _runtime_import_target_blocker_codes,
    _runtime_import_target_materialization_ref,
    _runtime_import_target_surface_blockers,
    _runtime_import_tigerbeetle_refs,
    _runtime_ledger_non_authority_marker_present,
    _runtime_ledger_readback_authority_markers_present,
)
from scripts.runtime_ledger_proof_packet.runtime_ledger_checks import (
    _completion_blockers,
)

if __name__ == "__main__":
    raise SystemExit(main())

__all__ = [
    "annotations",
    "argparse",
    "hashlib",
    "json",
    "os",
    "Mapping",
    "Sequence",
    "datetime",
    "timezone",
    "Decimal",
    "InvalidOperation",
    "Path",
    "Any",
    "Protocol",
    "cast",
    "HTTPError",
    "URLError",
    "urljoin",
    "urlopen",
    "DEFAULT_RUNTIME_LEDGER_PROOF_MODE",
    "RUNTIME_LEDGER_PROOF_MODES",
    "normalize_runtime_ledger_proof_mode",
    "runtime_ledger_proof_policy_from_env",
    "SCHEMA_VERSION",
    "DOC29_LIVE_SCALE_GATE",
    "DEFAULT_RUNTIME_LEDGER_PROOF_POLICY",
    "RUNTIME_LEDGER_PROOF_MODE_NOT_AUTHORITY_BLOCKER",
    "STATUS_ENDPOINT",
    "PAPER_ROUTE_EVIDENCE_ENDPOINT",
    "COMPLETION_DOC29_ENDPOINT",
    "ARTIFACT_SCHEMA_VERSION",
    "HPAIRS_SOURCE_PROOF_CENSUS_STATUS_SCHEMA_VERSION",
    "CAPITAL_PROMOTION_STATUS_BLOCKERS",
    "CAPITAL_PROMOTION_STATUS_BLOCKER_PREFIXES",
    "RUNTIME_IMPORT_MATERIALIZATION_PROMOTION_ONLY_BLOCKERS",
    "RUNTIME_IMPORT_MATERIALIZATION_STRUCTURAL_BLOCKERS",
    "DEFAULT_SERVICE_FETCH_TIMEOUT_SECONDS",
    "_ObjectStoreClient",
    "_utc_now",
    "_text",
    "_bool",
    "_int",
    "_decimal",
    "_decimal_text",
    "_first_decimal",
    "_mapping",
    "_contains_tigerbeetle_claim",
    "_sequence",
    "_text_list",
    "_hpairs_source_proof_census_status",
    "_hpairs_source_proof_census_attachment_blockers",
    "_source_offsets",
    "_extend_unique",
    "_load_json_object",
    "_load_json_url",
    "_source_fetch_error_payload",
    "_ceph_client_from_env",
    "_safe_artifact_path_part",
    "_runtime_window_import_run_id",
    "_resolve_artifact_prefix",
    "_artifact_key",
    "_attach_and_upload_artifact",
    "_artifact_upload_receipt_blockers",
    "_load_optional_json_object",
    "_service_endpoint_url",
    "_apply_service_base_url_defaults",
    "_check",
    "_completion_live_scale_gate",
    "_runtime_ledger_refs",
    "_runtime_ledger_trading_day_count",
    "_paper_route_target_plan",
    "_proofs_target_plan",
    "_proof_identity_target",
    "_proof_health_gate",
    "_paper_route_import_blockers",
    "_paper_route_targets",
    "_paper_route_runtime_window_import_audit",
    "_proofs_runtime_window_import_audit",
    "_paper_route_runtime_window_import_audit_counts",
    "_paper_route_runtime_window_import_audit_blockers",
    "_paper_route_runtime_window_import_target_blockers",
    "_paper_route_source_activity_blockers",
    "_health_gate_bool",
    "_runtime_window_import_health_gate_summary",
    "_missing_target_identity_count",
    "_runtime_window_import_payload",
    "_runtime_window_import_items",
    "_runtime_window_import_lineage",
    "_runtime_import_blockers",
    "_runtime_import_authoritative_observation_count",
    "_runtime_import_runtime_observations",
    "_runtime_import_target_materialization_ref",
    "_runtime_import_tigerbeetle_refs",
    "_runtime_import_target_blocker_codes",
    "_runtime_import_proof_blocker_codes",
    "_is_runtime_import_materialization_blocker",
    "_runtime_import_materialization_blocker_codes",
    "_RUNTIME_LEDGER_PROMOTION_GRADE_SOURCE_MATERIALIZATIONS",
    "_RUNTIME_LEDGER_PROMOTION_GRADE_AUTHORITY_MARKERS",
    "_RUNTIME_LEDGER_NON_AUTHORITY_MATERIALIZATION_MARKERS",
    "_runtime_ledger_non_authority_marker_present",
    "_runtime_ledger_readback_authority_markers_present",
    "_runtime_import_materialization_metadata_blockers",
    "_runtime_import_metadata_proof_blockers",
    "_runtime_import_readback_payload",
    "_runtime_import_readback_blockers",
    "_runtime_import_target_surface_blockers",
    "_runtime_import_materialization_summary",
    "_first_identity",
    "_first_env_text",
    "_normalize_image_digest",
    "_commit_refs_match",
    "_assembly_code_lineage",
    "_status_build_code_lineage",
    "_runtime_code_parity",
    "_runtime_ledger_immutable_lineage",
    "_status_blockers",
    "_is_capital_promotion_status_blocker",
    "_status_gate_blocker_summary",
    "_completion_blockers",
    "_required_actions",
    "build_runtime_ledger_proof_packet",
    "_parser",
    "_required_source_args",
    "_source_kind",
    "main",
]
