from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import argparse
import csv
import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any, Mapping
import yaml
from app.trading.evaluation import (
    build_profitability_evidence_v4,
    execute_profitability_benchmark_v4,
    validate_profitability_evidence_v4,
)

_SERVICE_ROOT: Any
_PROFITABILITY_PROOF_SCHEMA_VERSION: Any
_DEFAULT_BASELINE_ID: Any
_DEFAULT_TARGET_NET_PNL_PER_DAY: Any
_DEFAULT_MIN_SAMPLE_SIZE: Any
_DEFAULT_MIN_ACTIVE_DAY_RATIO: Any
_DEFAULT_MIN_POSITIVE_DAY_RATIO: Any
_DEFAULT_MAX_BEST_DAY_SHARE: Any
_DEFAULT_START_EQUITY: Any
_DEFAULT_MAX_DRAWDOWN_PCT_EQUITY: Any
_DEFAULT_EXTENDED_MAX_DRAWDOWN_PCT_EQUITY: Any
_DEFAULT_MIN_TOTAL_NET_PNL_TO_DRAWDOWN_RATIO: Any

class HistoricalRunSummary:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    run_id: str
    run_dir: Path
    trading_day: str
    candidate_id: str
    baseline_candidate_id: str
    strategy_spec_ref: str
    model_refs: list[str]
    runtime_version_refs: list[str]
    net_pnl: Decimal
    max_drawdown: Decimal
    cost_bps: Decimal
    trade_count: int
    decision_count: int
    execution_notional_total: Decimal
    estimated_cost_total: Decimal
    confidence_value: Decimal
    verdict_status: str
    signal_hash: str
    strategy_config_hash: str
    gate_policy_hash: str
    simulation_report_path: Path
    replay_report_path: Path | None
    trade_pnl_csv_path: Path | None

class ProfitabilityProofGatePolicy:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    target_net_pnl_per_day: Decimal
    min_sample_size: int
    min_active_day_ratio: Decimal
    min_positive_day_ratio: Decimal
    max_best_day_share: Decimal
    min_daily_notional: Decimal
    start_equity: Decimal
    max_drawdown_pct_equity: Decimal
    extended_max_drawdown_pct_equity: Decimal
    min_total_net_pnl_to_drawdown_ratio: Decimal

def _parse_args(*args: Any, **kwargs: Any) -> Any: ...
def _load_json(*args: Any, **kwargs: Any) -> Any: ...
def _load_yaml(*args: Any, **kwargs: Any) -> Any: ...
def _as_dict(*args: Any, **kwargs: Any) -> Any: ...
def _as_list(*args: Any, **kwargs: Any) -> Any: ...
def _as_text(*args: Any, **kwargs: Any) -> Any: ...
def _as_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _as_int(*args: Any, **kwargs: Any) -> Any: ...
def _clamp_confidence(*args: Any, **kwargs: Any) -> Any: ...
def _sha256_bytes(*args: Any, **kwargs: Any) -> Any: ...
def _sha256_json(*args: Any, **kwargs: Any) -> Any: ...
def _stable_hash_payload(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_manifest_path(*args: Any, **kwargs: Any) -> Any: ...
def _load_source_manifest(*args: Any, **kwargs: Any) -> Any: ...
def _lineage_text(*args: Any, **kwargs: Any) -> Any: ...
def _lineage_list(*args: Any, **kwargs: Any) -> Any: ...
def _load_trade_contributions(*args: Any, **kwargs: Any) -> Any: ...
def _estimate_day_drawdown(*args: Any, **kwargs: Any) -> Any: ...
def _best_signal_hash(*args: Any, **kwargs: Any) -> Any: ...
def _load_run_summary(*args: Any, **kwargs: Any) -> Any: ...
def _require_consistent_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _window_max_drawdown(*args: Any, **kwargs: Any) -> Any: ...
def _proof_gate_policy(*args: Any, **kwargs: Any) -> Any: ...
def _proof_gate_summary(*args: Any, **kwargs: Any) -> Any: ...
def _build_report_payload(*args: Any, **kwargs: Any) -> Any: ...
def _build_zero_baseline_payload(*args: Any, **kwargs: Any) -> Any: ...
def _effect_size(*args: Any, **kwargs: Any) -> Any: ...
def _artifact_refs(*args: Any, **kwargs: Any) -> Any: ...
def _proof_passed(*args: Any, **kwargs: Any) -> Any: ...
def build_historical_profitability_bundle(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
