from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F811,F821
from typing import Any
import argparse
import json
import os
import subprocess
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, cast
from sqlalchemy import create_engine, select
from sqlalchemy.orm import sessionmaker
from app.config import Settings
from app.models import (
    Execution,
    ExecutionOrderEvent,
    ExecutionTCAMetric,
    StrategyRuntimeLedgerBucket,
    TigerBeetleTransferRef,
)
from app.trading.tigerbeetle_journal import (
    SOURCE_TYPE_EXECUTION,
    SOURCE_TYPE_EXECUTION_ORDER_EVENT,
    SOURCE_TYPE_EXECUTION_TCA_METRIC,
    SOURCE_TYPE_RUNTIME_LEDGER_BUCKET,
    TIGERBEETLE_RUNTIME_LEDGER_JOURNAL_STATUS_PASS,
    TigerBeetleLedgerJournal,
    build_runtime_ledger_bucket_transfer_plan,
    build_order_event_transfer_plan,
    tigerbeetle_runtime_ledger_journal_payload,
)
from app.trading.tigerbeetle_client import TigerBeetleClientTimeoutError
from app.trading.tigerbeetle_ledger_model import (
    TRANSFER_KIND_EXECUTION_COST,
    TRANSFER_KIND_EXECUTION_FILL,
    TRANSFER_KIND_RUNTIME_NET_PNL,
)
from app.trading.tigerbeetle_reconcile import (
    latest_tigerbeetle_reconciliation_payload,
    reconcile_tigerbeetle_transfers,
)

DEFAULT_SOURCES: Any
INFRASTRUCTURE_RECONCILIATION_BLOCKERS: Any
SOURCE_ALIASES: Any
DEFAULT_JOURNAL_BATCH_CHUNK_SIZE: Any
MAX_JOURNAL_BATCH_CHUNK_SIZE: Any

class OrderEventSelection:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    rows: list[ExecutionOrderEvent]
    scan_failed: int

def _parse_args(*args: Any, **kwargs: Any) -> Any: ...
def _sqlalchemy_dsn(*args: Any, **kwargs: Any) -> Any: ...
def _parse_sources(*args: Any, **kwargs: Any) -> Any: ...
def _select_unlinked_events(*args: Any, **kwargs: Any) -> Any: ...
def _select_unlinked_executions(*args: Any, **kwargs: Any) -> Any: ...
def _select_unlinked_tca_metrics(*args: Any, **kwargs: Any) -> Any: ...
def _select_unlinked_runtime_buckets(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_bucket_has_signed_ref(*args: Any, **kwargs: Any) -> Any: ...
def _payload_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _payload_int_matches(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ref_matches_signed_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _journal_source_batch(*args: Any, **kwargs: Any) -> Any: ...
def _emit_progress(*args: Any, **kwargs: Any) -> Any: ...
def _batch_requested_stop(*args: Any, **kwargs: Any) -> Any: ...
def _attach_runtime_bucket_journal_payload(*args: Any, **kwargs: Any) -> Any: ...
def _error_summary(*args: Any, **kwargs: Any) -> Any: ...
def _reset_session_identity_map(*args: Any, **kwargs: Any) -> Any: ...
def _fresh_reconciliation_for_empty_selection(*args: Any, **kwargs: Any) -> Any: ...
def _payload(*args: Any, **kwargs: Any) -> Any: ...
def _reconciliation_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _hard_failure_reasons(*args: Any, **kwargs: Any) -> Any: ...
def _should_exit_nonzero(*args: Any, **kwargs: Any) -> Any: ...
def _supervised_timeout_payload(*args: Any, **kwargs: Any) -> Any: ...
def _without_arg(*args: Any, **kwargs: Any) -> Any: ...
def _with_source_arg(*args: Any, **kwargs: Any) -> Any: ...
def _args_for_source(*args: Any, **kwargs: Any) -> Any: ...
def _supervised_worker_argv(*args: Any, **kwargs: Any) -> Any: ...
def _write_supervised_output(*args: Any, **kwargs: Any) -> Any: ...
def _last_journal_payload(*args: Any, **kwargs: Any) -> Any: ...
def _journal_progress_events(*args: Any, **kwargs: Any) -> Any: ...
def _progress_int(*args: Any, **kwargs: Any) -> Any: ...
def _completed_progress_batch_from_timeout(*args: Any, **kwargs: Any) -> Any: ...
def _payload_from_completed_timeout_progress(*args: Any, **kwargs: Any) -> Any: ...
def _safe_payload_allows_success(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_supervised_returncode(*args: Any, **kwargs: Any) -> Any: ...
def _run_supervised_worker_once(*args: Any, **kwargs: Any) -> Any: ...
def _run_supervised_worker(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
