from __future__ import annotations

# pyright: reportMissingImports=false, reportMissingTypeStubs=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportUnnecessaryComparison=false, reportUnnecessaryCast=false
# ruff: noqa: F401,F811,F821
from typing import Any
import argparse
import csv
import hashlib
import http.client
import json
import logging
import os
import subprocess
import time as time_mod
import uuid
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any, Iterable, Mapping
from urllib import error, parse, request
import yaml
from unittest.mock import patch
from app.models import Strategy
from app.strategies.catalog import StrategyCatalogConfig, _compose_strategy_description
from app.config import settings
from app.trading.costs import CostModelInputs, OrderIntent, TransactionCostModel
from app.trading.decisions import DecisionEngine
from app.trading.discovery.replay_tape import (
    load_replay_tape,
    slice_tape_by_symbols,
    slice_tape_by_window,
    validate_tape_freshness,
)
from app.trading.evaluation_trace import (
    NearMissRecord,
    ReplayFunnelBucket,
    ReplayFunnelReport,
    ReplayTraceRecord,
    StrategyTrace,
)
from app.trading.execution_policy import (
    _near_touch_limit_price,
    _should_keep_market_order_for_high_conviction_entry,
)
from app.trading.models import SignalEnvelope, StrategyDecision
from app.trading.portfolio import allocator_from_settings, sizer_from_settings
from app.trading.quote_quality import (
    DEFAULT_MAX_EXECUTABLE_SPREAD_BPS,
    DEFAULT_MAX_JUMP_WITH_WIDE_SPREAD_BPS,
    DEFAULT_MAX_QUOTE_MID_JUMP_BPS,
    QuoteQualityPolicy,
    QuoteQualityStatus,
    SignalQuoteQualityTracker,
    assess_signal_quote_quality,
)
from app.trading.session_context import (
    SessionContextTracker,
    is_regular_equities_session_date,
    regular_session_close_utc_for,
    regular_session_open_utc_for,
)
from app.trading.strategy_runtime import StrategyRuntime

DEFAULT_CHUNK_MINUTES: Any
DEFAULT_START_EQUITY: Any
DEFAULT_CLICKHOUSE_QUERY_TIMEOUT_SECONDS: Any
DEFAULT_PROGRESS_LOG_INTERVAL_SECONDS: Any
logger: Any
_SHARED_POSITION_OWNER: Any
_FILL_LATENCY_BUCKETS_MS: Any
_FILL_LATENCY_THRESHOLDS_MS: Any
_EXACT_REPLAY_LEDGER_ROWS_SCHEMA_VERSION: Any
_REPLAY_LEDGER_ACCOUNT_LABEL: Any
_REPLAY_COST_BASIS: Any
_REPLAY_ADV_SOURCE: Any
_REPLAY_LEDGER_SOURCE: Any

def _resolve_repo_root(*args: Any, **kwargs: Any) -> Any: ...

_REPO_ROOT: Any

def default_strategy_configmap_path(*args: Any, **kwargs: Any) -> Any: ...
def _position_key(*args: Any, **kwargs: Any) -> Any: ...
def _stable_json_hash(*args: Any, **kwargs: Any) -> Any: ...
def _file_sha256(*args: Any, **kwargs: Any) -> Any: ...
def _utc_text(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text_or_none(*args: Any, **kwargs: Any) -> Any: ...

class ReplayConfig:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    strategy_configmap_path: Path
    clickhouse_http_url: str
    clickhouse_username: str | None
    clickhouse_password: str | None
    start_date: date
    end_date: date
    chunk_minutes: int
    flatten_eod: bool
    start_equity: Decimal
    symbols: tuple[str, ...]
    replay_tape_path: Path | None
    replay_tape_manifest_path: Path | None
    allow_stale_tape: bool
    progress_log_interval_seconds: int
    capture_traces: bool
    capture_trace_funnel: bool
    capture_exact_replay_ledger: bool
    force_position_isolation: bool
    max_executable_spread_bps: Decimal
    max_quote_mid_jump_bps: Decimal
    max_jump_with_wide_spread_bps: Decimal
    clickhouse_query_timeout_seconds: int

class PositionState:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    strategy_id: str
    qty: Decimal
    avg_entry_price: Decimal
    opened_at: datetime
    entry_cost_total: Decimal
    decision_at: datetime
    pending_entry: bool

class PendingOrder:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    decision: StrategyDecision
    created_at: datetime
    signal: SignalEnvelope

class ReplayLedgerContext:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    account_label: str
    candidate_id: str
    candidate_identity: dict[str, Any]
    candidate_identity_hash: str
    execution_policy_hash: str
    cost_model_hash: str
    cost_lineage: dict[str, Any]
    cost_lineage_hash: str
    lineage_hash: str
    replay_data_hash: str | None

class ReplayCostLineage:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    total_cost: Decimal
    notional: Decimal
    adv_notional: Decimal | None
    adv_source: str | None
    participation_rate: Decimal | None
    spread: Decimal | None
    volatility: Decimal | None
    spread_cost_bps: Decimal
    volatility_cost_bps: Decimal
    impact_cost_bps: Decimal
    commission_cost: Decimal
    commission_cost_bps: Decimal
    total_cost_bps: Decimal
    capacity_ok: bool
    warnings: tuple[str, ...]
    max_participation_rate: Decimal
    impact_bps_at_full_participation: Decimal
    impact_participation_exponent: Decimal

class ClosedTrade:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    symbol: str
    strategy_id: str
    decision_at: datetime
    opened_at: datetime
    closed_at: datetime
    qty: Decimal
    entry_price: Decimal
    exit_price: Decimal
    gross_pnl: Decimal
    net_pnl: Decimal
    exit_reason: str

def _ledger_identity(*args: Any, **kwargs: Any) -> Any: ...
def _build_replay_ledger_context(*args: Any, **kwargs: Any) -> Any: ...
def _base_ledger_row(*args: Any, **kwargs: Any) -> Any: ...
def _append_ledger_submission(*args: Any, **kwargs: Any) -> Any: ...
def _append_ledger_resolution(*args: Any, **kwargs: Any) -> Any: ...
def _ledger_resolution_event_type(*args: Any, **kwargs: Any) -> Any: ...
def _append_ledger_fill(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_ledger_payload(*args: Any, **kwargs: Any) -> Any: ...
def _parse_args(*args: Any, **kwargs: Any) -> Any: ...
def _load_strategies(*args: Any, **kwargs: Any) -> Any: ...
def _http_query(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_clickhouse_query(*args: Any, **kwargs: Any) -> Any: ...
def _b64(*args: Any, **kwargs: Any) -> Any: ...
def _iter_signal_rows(*args: Any, **kwargs: Any) -> Any: ...
def _iter_signal_rows_from_replay_tape(*args: Any, **kwargs: Any) -> Any: ...
def _fetch_chunk(*args: Any, **kwargs: Any) -> Any: ...
def _parse_signal_row(*args: Any, **kwargs: Any) -> Any: ...
def _parse_clickhouse_ts(*args: Any, **kwargs: Any) -> Any: ...
def _to_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _positions_payload(*args: Any, **kwargs: Any) -> Any: ...
def _position_equity(*args: Any, **kwargs: Any) -> Any: ...
def _position_exposure(*args: Any, **kwargs: Any) -> Any: ...
def _extract_spread(*args: Any, **kwargs: Any) -> Any: ...
def _extract_bid(*args: Any, **kwargs: Any) -> Any: ...
def _extract_ask(*args: Any, **kwargs: Any) -> Any: ...
def _extract_decimal_payload(*args: Any, **kwargs: Any) -> Any: ...
def _extract_price(*args: Any, **kwargs: Any) -> Any: ...
def _extract_volatility(*args: Any, **kwargs: Any) -> Any: ...
def _signal_spread_bps(*args: Any, **kwargs: Any) -> Any: ...
def _signal_mid_jump_bps(*args: Any, **kwargs: Any) -> Any: ...
def _quote_quality_status(*args: Any, **kwargs: Any) -> Any: ...
def _log_quote_skipped(*args: Any, **kwargs: Any) -> Any: ...
def _estimate_trade_cost(*args: Any, **kwargs: Any) -> Any: ...
def _estimate_trade_cost_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _positive_decimal_mapping_value(*args: Any, **kwargs: Any) -> Any: ...
def _observed_adv_notional(*args: Any, **kwargs: Any) -> Any: ...
def _observed_adv_notional_with_source(*args: Any, **kwargs: Any) -> Any: ...
def _record_decision(*args: Any, **kwargs: Any) -> Any: ...
def _record_fill_order_type(*args: Any, **kwargs: Any) -> Any: ...
def _order_age_ms(*args: Any, **kwargs: Any) -> Any: ...
def _latency_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _init_order_lifecycle_stats(*args: Any, **kwargs: Any) -> Any: ...
def _append_decimal_sample(*args: Any, **kwargs: Any) -> Any: ...
def _execution_proxy_payload(*args: Any, **kwargs: Any) -> Any: ...
def _record_order_lifecycle_outcome(*args: Any, **kwargs: Any) -> Any: ...
def _record_order_lifecycle(*args: Any, **kwargs: Any) -> Any: ...
def _pending_censor_time(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_average(*args: Any, **kwargs: Any) -> Any: ...
def _int_average(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_percentile(*args: Any, **kwargs: Any) -> Any: ...
def _int_percentile(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_or_none(*args: Any, **kwargs: Any) -> Any: ...
def _fill_probability_by_latency_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _fill_probability_by_latency_threshold(*args: Any, **kwargs: Any) -> Any: ...
def _order_lifecycle_summary(*args: Any, **kwargs: Any) -> Any: ...
def _post_cost_survivorship_summary(*args: Any, **kwargs: Any) -> Any: ...
def _decision_entry_order_type(*args: Any, **kwargs: Any) -> Any: ...
def _decision_market_order_spread_bps_max(*args: Any, **kwargs: Any) -> Any: ...
def _decision_spread_bps(*args: Any, **kwargs: Any) -> Any: ...
def _apply_order_preferences(*args: Any, **kwargs: Any) -> Any: ...
def _init_day_stats(*args: Any, **kwargs: Any) -> Any: ...
def _init_funnel_stats(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_replay_stats_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _record_liquidity_observation(*args: Any, **kwargs: Any) -> Any: ...
def _record_capital_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def _record_trace_for_funnel(*args: Any, **kwargs: Any) -> Any: ...
def _build_near_miss(*args: Any, **kwargs: Any) -> Any: ...
def _insert_near_miss(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _log_decision_queued(*args: Any, **kwargs: Any) -> Any: ...
def _log_trade_closed(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_pending_fill_price(*args: Any, **kwargs: Any) -> Any: ...
def _decision_exit_reason(*args: Any, **kwargs: Any) -> Any: ...
def _decision_position_owner(*args: Any, **kwargs: Any) -> Any: ...
def _first_reject_reason(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_passed_trace_block_reason(*args: Any, **kwargs: Any) -> Any: ...
def _pending_order_priority(*args: Any, **kwargs: Any) -> Any: ...
def _should_replace_pending_order(*args: Any, **kwargs: Any) -> Any: ...
def _reconcile_pending_order_before_immediate_fill(
    *args: Any, **kwargs: Any
) -> Any: ...
def _log_pending_order_replaced(*args: Any, **kwargs: Any) -> Any: ...
def _log_day_summary(*args: Any, **kwargs: Any) -> Any: ...
def _log_progress(*args: Any, **kwargs: Any) -> Any: ...
def _close_position(*args: Any, **kwargs: Any) -> Any: ...
def _apply_filled_decision(*args: Any, **kwargs: Any) -> Any: ...
def run_replay(*args: Any, **kwargs: Any) -> Any: ...
def _signal_regime_label(*args: Any, **kwargs: Any) -> Any: ...
def _flatten_positions(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
