from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F811,F821
from typing import Any
import argparse
import json
import os
import time
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from http.client import HTTPConnection, HTTPSConnection
from pathlib import Path
from typing import Any, cast
from urllib.parse import urlsplit
from sqlalchemy import create_engine, select
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool
from app.models import Base, Strategy
from app.trading.paper_route_target_plan import (
    PAPER_ROUTE_MATERIALIZATION_ACCOUNT_LABEL,
    PAPER_ROUTE_MATERIALIZATION_HPAIRS_HYPOTHESIS_ID,
    materialize_bounded_paper_route_target_plan,
    paper_route_target_execution_capacity_blockers,
    paper_route_target_plan_from_payload,
    paper_route_target_plan_targets,
)

SCHEMA_VERSION: Any
OPERATOR_CONFIRMATION: Any
DEFAULT_DYNAMIC_SELECTED_PLAN_SOURCE: Any
DEFAULT_DYNAMIC_SELECTED_PLAN_SOURCES: Any
PROMOTION_FLAG_FIELDS: Any
LIVE_LABEL_MARKERS: Any
TARGET_PLAN_RESPONSE_LIMIT_BYTES: Any
ACTIVE_TARGET_WINDOW_SKIP_REASON: Any
ACTIVE_TARGET_WINDOW_REQUIRED_BLOCKER: Any

def _json_default(*args: Any, **kwargs: Any) -> Any: ...
def _safe_text(*args: Any, **kwargs: Any) -> Any: ...
def _safe_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _truthy(*args: Any, **kwargs: Any) -> Any: ...
def _to_str_map(*args: Any, **kwargs: Any) -> Any: ...
def _target_symbol_actions(*args: Any, **kwargs: Any) -> Any: ...
def _target_symbol_quantities(*args: Any, **kwargs: Any) -> Any: ...
def _first_positive_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _target_notional(*args: Any, **kwargs: Any) -> Any: ...
def _target_quantity(*args: Any, **kwargs: Any) -> Any: ...
def _target_plan_ref(*args: Any, **kwargs: Any) -> Any: ...
def _target_window_start(*args: Any, **kwargs: Any) -> Any: ...
def _target_window_end(*args: Any, **kwargs: Any) -> Any: ...
def _parse_utc_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_now_utc(*args: Any, **kwargs: Any) -> Any: ...
def _load_json_file(*args: Any, **kwargs: Any) -> Any: ...
def _nested_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _target_bounded_materialization_authorized(*args: Any, **kwargs: Any) -> Any: ...
def _target_materialization_score(*args: Any, **kwargs: Any) -> Any: ...
def _plan_materialization_score(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_materialization_plans(*args: Any, **kwargs: Any) -> Any: ...
def _materialization_plan_from_payload(*args: Any, **kwargs: Any) -> Any: ...
def _fetch_plan_url_payload_once(*args: Any, **kwargs: Any) -> Any: ...
def _fetch_plan_url_payload(*args: Any, **kwargs: Any) -> Any: ...
def _load_plan(*args: Any, **kwargs: Any) -> Any: ...
def _unique_texts(*args: Any, **kwargs: Any) -> Any: ...
def _target_runtime_strategy_confirmation_names(*args: Any, **kwargs: Any) -> Any: ...
def _target_summaries(*args: Any, **kwargs: Any) -> Any: ...
def _active_target_window_check(*args: Any, **kwargs: Any) -> Any: ...
def _target_window_check_active_indexes(*args: Any, **kwargs: Any) -> Any: ...
def _plan_with_target_indexes(*args: Any, **kwargs: Any) -> Any: ...
def _confirmed_selected_plan_sources(*args: Any, **kwargs: Any) -> Any: ...
def _confirmed_dynamic_target_filters(*args: Any, **kwargs: Any) -> Any: ...
def _confirmed_dynamic_target_indexes(*args: Any, **kwargs: Any) -> Any: ...
def _plan_flag_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _confirmation_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _safety_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _session_factory(*args: Any, **kwargs: Any) -> Any: ...
def _sqlalchemy_dsn(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_names_from_summaries(*args: Any, **kwargs: Any) -> Any: ...
def _copy_preview_strategies(*args: Any, **kwargs: Any) -> Any: ...
def _run_dry_run_materialization(*args: Any, **kwargs: Any) -> Any: ...
def _run_materialization(*args: Any, **kwargs: Any) -> Any: ...
def build_report(*args: Any, **kwargs: Any) -> Any: ...
def _parse_args(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
