from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401, F811
from typing import Any
import argparse
import json
import os
from dataclasses import dataclass
from datetime import date
from decimal import Decimal, InvalidOperation, ROUND_DOWN
from pathlib import Path
from typing import Any, Mapping, cast
import yaml
from app.trading.discovery.autoresearch import (
    FamilyAutoresearchPlan,
    ProposalModelPolicy,
    StrategyAutoresearchProgram,
    apply_program_objective,
    build_mutated_sweep_config,
    candidate_meets_objective,
    load_strategy_autoresearch_program,
    run_id,
    stable_payload_hash,
)
from app.trading.discovery.autoresearch_notebooks import write_autoresearch_notebooks
from app.trading.discovery.evidence_bundles import (
    CandidateEvidenceBundle,
    evidence_bundle_from_frontier_candidate,
)
from app.trading.discovery.family_templates import family_template_dir
from app.trading.discovery.mlx_features import (
    MlxCandidateDescriptor,
    descriptor_from_candidate_payload,
    descriptor_from_sweep_config,
)
from app.trading.discovery.mlx_notebook_exports import write_mlx_notebook_exports
from app.trading.discovery.mlx_proposal_models import (
    ProposalDiagnostics,
    ProposalScore,
    ProposalSelectionEntry,
    build_proposal_diagnostics,
    rank_candidate_descriptors,
    select_proposal_batch,
)
from app.trading.discovery.mlx_snapshot import (
    MlxSignalBundleStats,
    MlxSnapshotManifest,
    build_mlx_snapshot_manifest,
    write_mlx_signal_bundle,
    write_mlx_snapshot_manifest,
)
from app.trading.discovery.objectives import (
    deployable_lower_bound_missing_count,
    deployable_lower_bound_net_pnl_per_day,
    deployable_proof_failed_gate_count,
)
from app.trading.discovery.promotion_contract import (
    blocked_research_candidate_promotion_readiness,
    summary_promotion_readiness,
)
from app.trading.discovery.portfolio_candidates import PortfolioCandidateSpec
from app.trading.discovery.portfolio_optimizer import optimize_portfolio_candidate
from app.trading.discovery.profit_target_oracle import ProfitTargetOraclePolicy
from app.trading.discovery.replay_ledger_ranker import (
    build_replay_ledger_ranking_report,
    default_replay_ledger_ranking_policy,
)
from app.trading.discovery.replay_ledger_guided_search import (
    apply_replay_ledger_remediation_guidance,
)
from app.trading.discovery.replay_ledger_remediation import (
    build_replay_ledger_remediation_report,
)
from app.trading.discovery.replay_tape import (
    ReplayTapeManifest,
    build_source_query_digest,
    default_manifest_path,
    materialize_signal_tape,
)
from app.trading.discovery.runtime_closure import write_runtime_closure_bundle
from app.trading.discovery.runtime_closure import RuntimeClosureExecutionContext
import scripts.local_intraday_tsmom_replay as replay_mod
from scripts.search_consistent_profitability_frontier import (
    run_consistent_profitability_frontier,
)
from scripts.materialize_replay_tape import (
    _DEFAULT_MAX_COVERAGE_SPREAD_BPS,
    _DEFAULT_MAX_EXECUTABLE_GAP_SECONDS,
    _DEFAULT_MIN_EXECUTABLE_ROWS_PER_SYMBOL_DAY,
    _DEFAULT_MIN_QUOTE_VALID_RATIO,
    _select_effective_window as _select_effective_replay_tape_window,
)

_REPO_ROOT: Any
_CAPITAL_LIMIT_SAFETY_MULTIPLIER: Any
_DEFAULT_CLICKHOUSE_HTTP_URL: Any

def _default_clickhouse_http_url(*args: Any, **kwargs: Any) -> Any: ...
def _default_clickhouse_password(*args: Any, **kwargs: Any) -> Any: ...
def _parse_args(*args: Any, **kwargs: Any) -> Any: ...

class WorkItem:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    family_plan: FamilyAutoresearchPlan
    iteration: int
    sweep_config: dict[str, Any]
    mutation_label: str
    parent_candidate_id: str | None

class LatestCompleteWindowRequirement:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    min_days: int
    source: str
    cli_min_days: int
    objective_min_days: int

def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _string(*args: Any, **kwargs: Any) -> Any: ...
def _float(*args: Any, **kwargs: Any) -> Any: ...
def _decimal(*args: Any, **kwargs: Any) -> Any: ...
def _maybe_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _json_clone(*args: Any, **kwargs: Any) -> Any: ...
def _as_grid_values(*args: Any, **kwargs: Any) -> Any: ...
def _format_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _positive_decimal_grid_values(*args: Any, **kwargs: Any) -> Any: ...
def _max_entry_count(*args: Any, **kwargs: Any) -> Any: ...
def _capped_numeric_grid(*args: Any, **kwargs: Any) -> Any: ...
def _apply_objective_capital_limits(*args: Any, **kwargs: Any) -> Any: ...
def _apply_exact_replay_guidance_to_next_sweep(*args: Any, **kwargs: Any) -> Any: ...
def _slug(*args: Any, **kwargs: Any) -> Any: ...
def _iter_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _snapshot_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _mlx_bundle_paths(*args: Any, **kwargs: Any) -> Any: ...
def _keep_candidate_limit(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_candidate_budget(*args: Any, **kwargs: Any) -> Any: ...
def _work_item_candidate_id(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_missing_candidate_payload(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_missing_frontier_payload(*args: Any, **kwargs: Any) -> Any: ...
def _promotion_readiness_payload(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_args(*args: Any, **kwargs: Any) -> Any: ...
def _load_yaml(*args: Any, **kwargs: Any) -> Any: ...
def _default_full_window_day_count(*args: Any, **kwargs: Any) -> Any: ...
def _iso_date(*args: Any, **kwargs: Any) -> Any: ...
def _full_window_signal_config(*args: Any, **kwargs: Any) -> Any: ...
def _replay_tape_source_query_digest(*args: Any, **kwargs: Any) -> Any: ...
def _replay_tape_receipt(*args: Any, **kwargs: Any) -> Any: ...
def _provided_replay_tape_receipt(*args: Any, **kwargs: Any) -> Any: ...
def _maybe_write_signal_bundle(*args: Any, **kwargs: Any) -> Any: ...
def _latest_complete_window_requirement(*args: Any, **kwargs: Any) -> Any: ...
def _maybe_materialize_run_replay_tape(*args: Any, **kwargs: Any) -> Any: ...
def _history_record(*args: Any, **kwargs: Any) -> Any: ...
def _write_history_jsonl(*args: Any, **kwargs: Any) -> Any: ...
def _sanitize_tsv_field(*args: Any, **kwargs: Any) -> Any: ...
def _write_results_tsv(*args: Any, **kwargs: Any) -> Any: ...
def _research_ranking_net_pnl_per_day(*args: Any, **kwargs: Any) -> Any: ...
def _best_history_record(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_name_from_strategy_id(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_manifest_rows(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_manifest_for_history_row(*args: Any, **kwargs: Any) -> Any: ...
def _dedupe_nonempty_strings(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_history_row(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_runtime_window_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_autoresearch_runtime_window_import_plan(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_closure_candidate(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_objective_scorecard(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_is_runtime_closure_candidate(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_closure_subject(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_closure_pending_promotion_steps(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_closure_promotion_prerequisite_blockers(
    *args: Any, **kwargs: Any
) -> Any: ...
def _portfolio_promotion_readiness(*args: Any, **kwargs: Any) -> Any: ...
def _summary_promotion_readiness_for_outputs(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_oracle_policy(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_spec_id_for_portfolio_payload(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_evidence_bundles_from_results(*args: Any, **kwargs: Any) -> Any: ...
def _write_portfolio_outputs(*args: Any, **kwargs: Any) -> Any: ...
def _proposal_diagnostics(*args: Any, **kwargs: Any) -> Any: ...
def _experiment_snapshot_from_payload(*args: Any, **kwargs: Any) -> Any: ...
def _load_experiment_snapshots(*args: Any, **kwargs: Any) -> Any: ...
def _best_experiment_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def _live_progress_payload(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_ledger_refs(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_run_artifact_ref(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_ledger_paths(*args: Any, **kwargs: Any) -> Any: ...
def _write_exact_replay_ledger_ranking(*args: Any, **kwargs: Any) -> Any: ...

_EXACT_REPLAY_EXECUTION_QUALITY_FIELDS: Any

def _exact_replay_ranking_by_candidate(*args: Any, **kwargs: Any) -> Any: ...
def _with_exact_replay_execution_quality(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_candidate_for_payload(*args: Any, **kwargs: Any) -> Any: ...
def _write_exact_replay_ledger_remediation(*args: Any, **kwargs: Any) -> Any: ...
def _persist_run_outputs(*args: Any, **kwargs: Any) -> Any: ...
def run_strategy_autoresearch_loop(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
