from __future__ import annotations

# pyright: reportMissingImports=false, reportMissingTypeStubs=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportUnnecessaryComparison=false, reportUnnecessaryCast=false
# ruff: noqa: F401, F811
from typing import Any
import argparse
import contextlib
import heapq
import hashlib
import itertools
import json
import os
import socket
import sys
import tempfile
from collections import Counter, deque
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta, timezone
from decimal import Decimal, InvalidOperation, ROUND_CEILING, ROUND_DOWN
from pathlib import Path
from typing import Any, Callable, Iterable, Iterator, Mapping, Sequence, cast
from urllib.parse import urlparse
from unittest.mock import patch
import yaml
from app.trading.discovery.dataset_snapshot import (
    DatasetSnapshotReceipt,
    DatasetWitness,
    build_dataset_snapshot_receipt,
    ensure_fresh_snapshot,
)
from app.trading.discovery.decomposition import (
    build_replay_decomposition,
    max_family_contribution_share,
    max_symbol_concentration_share,
    regime_slice_pass_rate,
)
from app.trading.discovery.family_templates import (
    derive_family_template_id,
    family_template_dir,
    load_family_template,
)
from app.trading.discovery.objectives import (
    ObjectiveVetoPolicy,
    build_scorecard,
    deployable_lower_bound_missing_count,
    deployable_lower_bound_net_pnl_per_day,
    deployable_proof_failed_gate_count,
    evaluate_vetoes,
    rank_scorecards,
)
from app.trading.discovery.replay_tape import (
    ReplayTape,
    load_replay_tape,
    slice_tape_by_symbols,
    slice_tape_by_window,
    validate_tape_freshness,
)
from app.trading.session_context import iter_regular_equities_session_dates
from app.trading.runtime_ledger import (
    POST_COST_PNL_BASIS,
    RuntimeLedgerBucket,
    build_runtime_ledger_buckets,
)
from app.trading.reporting import (
    ProfitabilityConstraintPolicy,
    score_replay_profitability_candidate,
    summarize_replay_profitability,
)
import scripts.local_intraday_tsmom_replay as replay_mod
from scripts.local_intraday_tsmom_replay import run_replay
from scripts.search_profitability_frontier import (
    _SWEEP_SCHEMA_VERSION,
    _build_replay_config,
    _load_sweep_config,
    _resolve_recent_trading_days,
    apply_candidate_to_configmap,
)

_LOCAL_ONLY_OVERRIDE_KEYS: Any
_SECOND_OOS_WINDOW_ID: Any
_SAFE_EXACT_REPLAY_CANDIDATE_CAP: Any
_SAFE_EXACT_REPLAY_EXPLOITATION_SLOTS: Any
_SAFE_EXACT_REPLAY_EXPLORATION_SLOTS: Any
_SAFE_LOCAL_EXACT_REPLAY_WORKERS: Any
_DEFAULT_STAGED_TRAIN_SCREEN_MULTIPLIER: Any
_LOSS_REPAIR_TRIGGER_REASONS: Any
_LOSS_REPAIR_TRIGGER_SUFFIXES: Any
_LOSS_REPAIR_BPS_FLOORS: Any
_LOSS_REPAIR_EXIT_LIMIT_KEYS: Any
_LOSS_REPAIR_LOCKOUT_KEYS: Any
_LOSS_REPAIR_PARAM_EXPOSURE_KEYS: Any
_LOSS_REPAIR_STRATEGY_EXPOSURE_KEYS: Any
_LOSS_REPAIR_DEFAULT_EXPOSURE_SCALE: Any
_LOSS_REPAIR_CAPITAL_SAFETY_BUFFER: Any
_LOSS_REPAIR_MIN_SCALE_QUANTUM: Any
_CONSISTENCY_REPAIR_TRIGGER_REASONS: Any
_CONSISTENCY_REPAIR_UNSAFE_REASONS: Any
_PAPER_PROBATION_CAPITAL_REPAIR_REASONS: Any
_PAPER_PROBATION_LOSS_REPAIR_REASONS: Any
_PAPER_PROBATION_ACTIVITY_REPAIR_REASONS: Any
_PAPER_PROBATION_TAIL_RISK_REASONS: Any
_PAPER_PROBATION_QUEUE_SURVIVAL_REASONS: Any
_PAPER_PROBATION_TARGET_SCALE_QUANTUM: Any
_PAPER_PROBATION_LIVE_PAPER_EVIDENCE_REQUIREMENTS: Any
_PAPER_PROBATION_SAFE_EVIDENCE_COLLECTION_PATH: Any
_CONSISTENCY_REPAIR_ENTRY_KEYS: Any
_CONSISTENCY_REPAIR_BREADTH_KEYS: Any
_CONSISTENCY_REPAIR_COOLDOWN_KEYS: Any
_CONSISTENCY_REPAIR_SIGNAL_THRESHOLD_KEYS: Any
_CONSISTENCY_REPAIR_RANK_STEP: Any
_CONSISTENCY_REPAIR_MIN_RANK_THRESHOLD: Any
_CONSISTENCY_REPAIR_THRESHOLD_SCALE: Any
_CONSISTENCY_REPAIR_MAX_SIGNAL_THRESHOLD_RELAXATIONS: Any

class _WorklistItem:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    params_candidate: dict[str, Any]
    strategy_overrides: dict[str, Any]
    candidate_record_seed: bool
    symbol_prune_iteration: int
    loss_repair_iteration: int
    consistency_repair_iteration: int
    pruned_symbol: str | None
    repair_reason: str | None
    parent_candidate_id: str | None
    deferred_candidate_index: int | None
    deferred_candidate_key: str | None
    deferred_train_payload: Mapping[str, Any] | None
    deferred_full_replay_selected: bool
    deferred_train_rank: int | None
    deferred_train_economic_rank: int | None
    deferred_full_replay_selection_reason: str | None
    def search_iteration(*args: Any, **kwargs: Any) -> Any: ...

class FullWindowConsistencyPolicy:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    target_net_per_day: Decimal
    min_daily_net_pnl: Decimal
    min_active_days: int
    min_active_ratio: Decimal
    min_positive_days: int
    max_worst_day_loss: Decimal
    max_negative_days: int
    max_drawdown: Decimal
    max_best_day_share_of_total_pnl: Decimal
    min_avg_filled_notional_per_day: Decimal
    min_avg_filled_notional_per_active_day: Decimal
    require_every_day_active: bool
    min_regime_slice_pass_rate: Decimal
    max_symbol_concentration_share: Decimal
    max_entry_family_contribution_share: Decimal
    max_gross_exposure_pct_equity: Decimal
    min_cash: Decimal
    min_window_weekday_count: int
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class OrderTypeAblationPolicy:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    enabled: bool
    max_candidates: int
    min_sample_count: int
    max_opportunity_cost_bps: Decimal
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class FrontierReplayWindows:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    train_days: tuple[date, ...]
    holdout_days: tuple[date, ...]
    second_oos_days: tuple[date, ...]
    def train_start(*args: Any, **kwargs: Any) -> Any: ...
    def train_end(*args: Any, **kwargs: Any) -> Any: ...
    def holdout_start(*args: Any, **kwargs: Any) -> Any: ...
    def holdout_end(*args: Any, **kwargs: Any) -> Any: ...
    def second_oos_start(*args: Any, **kwargs: Any) -> Any: ...
    def second_oos_end(*args: Any, **kwargs: Any) -> Any: ...
    def expected_days(*args: Any, **kwargs: Any) -> Any: ...

def _optional_int(*args: Any, **kwargs: Any) -> Any: ...
def _order_type_ablation_policy(*args: Any, **kwargs: Any) -> Any: ...
def _write_json_output(*args: Any, **kwargs: Any) -> Any: ...
def _safe_exact_replay_candidate_budget(*args: Any, **kwargs: Any) -> Any: ...
def _staged_search_budget_payload(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_error_payload(*args: Any, **kwargs: Any) -> Any: ...
def _clickhouse_host_requires_dns_preflight(*args: Any, **kwargs: Any) -> Any: ...
def _clickhouse_endpoint_preflight_failure(*args: Any, **kwargs: Any) -> Any: ...
def _stable_payload_hash(*args: Any, **kwargs: Any) -> Any: ...
def _replay_lineage_window_payload(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_replay_lineage_payload(*args: Any, **kwargs: Any) -> Any: ...
def _replay_window_coverage_payload(*args: Any, **kwargs: Any) -> Any: ...
def _parse_args(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_frontier_replay_windows(*args: Any, **kwargs: Any) -> Any: ...
def _business_days(*args: Any, **kwargs: Any) -> Any: ...
def _snapshot_expected_days(*args: Any, **kwargs: Any) -> Any: ...
def _rolling_lower_bound(*args: Any, **kwargs: Any) -> Any: ...
def _objective_veto_policy(*args: Any, **kwargs: Any) -> Any: ...
def _iter_strategy_override_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_record_seed(*args: Any, **kwargs: Any) -> Any: ...
def _load_candidate_record_seeds(*args: Any, **kwargs: Any) -> Any: ...
def _parameter_grid_items(*args: Any, **kwargs: Any) -> Any: ...
def _parameter_exploration_priority(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_payload_key(*args: Any, **kwargs: Any) -> Any: ...
def _iter_parameter_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _iter_initial_worklist_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_universe_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_universe_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_search_key(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_evaluation_key_payload(*args: Any, **kwargs: Any) -> Any: ...
def _replay_tape_selection_metadata(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_prefetch_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _prefetch_signal_rows(*args: Any, **kwargs: Any) -> Any: ...
def _cached_iter_signal_rows_factory(*args: Any, **kwargs: Any) -> Any: ...
def _cached_signal_rows_patch(*args: Any, **kwargs: Any) -> Any: ...
def _load_replay_tape_rows(*args: Any, **kwargs: Any) -> Any: ...
def _replay_tape_trading_days(*args: Any, **kwargs: Any) -> Any: ...
def _build_replay_tape_snapshot_receipt(*args: Any, **kwargs: Any) -> Any: ...
def _replay_tape_row_days(*args: Any, **kwargs: Any) -> Any: ...
def apply_candidate_to_configmap_with_overrides(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_full_window(*args: Any, **kwargs: Any) -> Any: ...
def _max_drawdown_from_daily_net(*args: Any, **kwargs: Any) -> Any: ...
def _daily_filled_notional(*args: Any, **kwargs: Any) -> Any: ...
def _daily_liquidity_notional(*args: Any, **kwargs: Any) -> Any: ...
def _daily_decimal_metric(*args: Any, **kwargs: Any) -> Any: ...
def _daily_int_metric(*args: Any, **kwargs: Any) -> Any: ...
def _int_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _optional_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _nonnegative_int_metric(*args: Any, **kwargs: Any) -> Any: ...
def _truthy_metric(*args: Any, **kwargs: Any) -> Any: ...
def _order_lifecycle_metrics(*args: Any, **kwargs: Any) -> Any: ...
def _order_type_execution_metrics(*args: Any, **kwargs: Any) -> Any: ...
def _normalized_order_type(*args: Any, **kwargs: Any) -> Any: ...
def _selected_entry_order_type(*args: Any, **kwargs: Any) -> Any: ...
def _forced_order_type_sample_count(*args: Any, **kwargs: Any) -> Any: ...
def _payload_digest(*args: Any, **kwargs: Any) -> Any: ...
def _artifact_run_dir_name(*args: Any, **kwargs: Any) -> Any: ...
def _order_type_ablation_artifact_dir(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_ledger_text(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_ledger_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_exact_replay_bucket_range(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_exact_replay_rows(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_exact_replay_bucket_has_authority(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_exact_replay_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _exact_replay_ledger_artifact_update(*args: Any, **kwargs: Any) -> Any: ...
def _order_type_replay_arm_summary(*args: Any, **kwargs: Any) -> Any: ...
def _order_type_ablation_payload(*args: Any, **kwargs: Any) -> Any: ...

DELAY_ADJUSTED_DEPTH_STRESS_GRID_MS: Any
CONFORMAL_TAIL_RISK_ALPHA: Any
BREAKEVEN_TRANSACTION_COST_BUFFER_MIN_BPS: Any
MARKET_IMPACT_STRESS_SOURCE_MARKERS: Any

def _p10(*args: Any, **kwargs: Any) -> Any: ...
def _conformal_tail_loss_buffer(*args: Any, **kwargs: Any) -> Any: ...
def _conformal_tail_risk_metrics(*args: Any, **kwargs: Any) -> Any: ...
def _breakeven_transaction_cost_buffer_metrics(*args: Any, **kwargs: Any) -> Any: ...
def _delay_depth_fillability(*args: Any, **kwargs: Any) -> Any: ...
def _implementation_uncertainty_metrics(*args: Any, **kwargs: Any) -> Any: ...
def _replay_stress_metrics(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_payload_metric(*args: Any, **kwargs: Any) -> Any: ...
def _max_best_day_share_of_total_pnl(*args: Any, **kwargs: Any) -> Any: ...
def _consistency_penalty(*args: Any, **kwargs: Any) -> Any: ...
def _second_oos_summary(*args: Any, **kwargs: Any) -> Any: ...
def _holdout_oos_passed(*args: Any, **kwargs: Any) -> Any: ...
def _empty_replay_payload(*args: Any, **kwargs: Any) -> Any: ...
def _train_screen_failures(*args: Any, **kwargs: Any) -> Any: ...
def _positive_train_screen_candidate(*args: Any, **kwargs: Any) -> Any: ...
def _train_screen_active_ratio(*args: Any, **kwargs: Any) -> Any: ...
def _train_screen_worst_day_loss(*args: Any, **kwargs: Any) -> Any: ...
def _rank_train_screen_survivors(*args: Any, **kwargs: Any) -> Any: ...
def _exploration_payload_signature(*args: Any, **kwargs: Any) -> Any: ...
def _exploration_distance(*args: Any, **kwargs: Any) -> Any: ...
def _exploration_diversity_key(*args: Any, **kwargs: Any) -> Any: ...
def _select_exact_replay_train_survivors(*args: Any, **kwargs: Any) -> Any: ...
def _enqueue_ranked_train_screen_survivors(*args: Any, **kwargs: Any) -> Any: ...
def _symbol_contributions_from_replay_payload(*args: Any, **kwargs: Any) -> Any: ...
def _top_counter_payload(*args: Any, **kwargs: Any) -> Any: ...
def _counter_from_payload(*args: Any, **kwargs: Any) -> Any: ...
def _near_miss_digest(*args: Any, **kwargs: Any) -> Any: ...
def _train_gate_diagnostics_from_replay_payload(*args: Any, **kwargs: Any) -> Any: ...
def _generate_symbol_prune_children(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_item_from_configmap(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_or_none(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_payload(*args: Any, **kwargs: Any) -> Any: ...
def _tightened_bps(*args: Any, **kwargs: Any) -> Any: ...
def _reduced_exposure(*args: Any, **kwargs: Any) -> Any: ...
def _capital_repair_exposure_scale(*args: Any, **kwargs: Any) -> Any: ...
def _loss_repair_trigger_reason(*args: Any, **kwargs: Any) -> Any: ...
def _apply_loss_control_tightening(*args: Any, **kwargs: Any) -> Any: ...
def _apply_exposure_clamp(*args: Any, **kwargs: Any) -> Any: ...
def _generate_loss_repair_children(*args: Any, **kwargs: Any) -> Any: ...
def _positive_capital_safe_summary(*args: Any, **kwargs: Any) -> Any: ...
def _consistency_repair_trigger_reason(*args: Any, **kwargs: Any) -> Any: ...
def _increment_integer_candidate_param(*args: Any, **kwargs: Any) -> Any: ...
def _halve_positive_integer_candidate_param(*args: Any, **kwargs: Any) -> Any: ...
def _relax_signal_threshold_candidate_param(*args: Any, **kwargs: Any) -> Any: ...
def _generate_consistency_repair_children(*args: Any, **kwargs: Any) -> Any: ...
def _rank_scored_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _safe_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_metric_value(*args: Any, **kwargs: Any) -> Any: ...
def _build_economic_shortlist(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_artifact_refs(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_exact_replay_ledger_artifact_refs(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_runtime_ledger_count(*args: Any, **kwargs: Any) -> Any: ...
def _paper_probation_required_actions(*args: Any, **kwargs: Any) -> Any: ...
def _paper_probation_notional_scale_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _paper_probation_notional_scale(*args: Any, **kwargs: Any) -> Any: ...
def _paper_probation_target_notional_scale(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_metric_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_source_lineage_ok(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_replay_tape_metadata_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_post_cost_proof_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_exact_replay_parity_ok(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_handoff_diagnostics(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_sim_handoff_metadata(*args: Any, **kwargs: Any) -> Any: ...
def _paper_probation_repair_actions(*args: Any, **kwargs: Any) -> Any: ...
def _paper_probation_target_progress(*args: Any, **kwargs: Any) -> Any: ...
def _paper_probation_repair_plan(*args: Any, **kwargs: Any) -> Any: ...
def _build_paper_probation_shortlist(*args: Any, **kwargs: Any) -> Any: ...
def _frontier_state_item(*args: Any, **kwargs: Any) -> Any: ...
def _build_frontier_workflow_states(*args: Any, **kwargs: Any) -> Any: ...
def _build_frontier_payload(*args: Any, **kwargs: Any) -> Any: ...
def _selected_normalization_regime(*args: Any, **kwargs: Any) -> Any: ...
def _resolved_clickhouse_password(*args: Any, **kwargs: Any) -> Any: ...
def run_consistent_profitability_frontier(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
def cli_main(*args: Any, **kwargs: Any) -> Any: ...
