from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import argparse
import base64
import gzip
import hashlib
import importlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import socket
import time
import uuid
from contextlib import contextmanager
from dataclasses import asdict, dataclass, replace
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence, cast
from urllib.parse import quote, quote_plus, unquote_plus, urlsplit
from http.client import HTTPConnection, HTTPSConnection
from zoneinfo import ZoneInfo
import psycopg
from psycopg import sql
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import yaml
from app.db import SessionLocal
from app.trading.autonomy.lane import run_autonomous_lane
from app.trading.completion import (
    DOC29_SIMULATION_FULL_DAY_GATE,
    DOC29_SIMULATION_SMOKE_GATE,
    TRACE_STATUS_BLOCKED,
    TRACE_STATUS_SATISFIED,
    build_completion_trace,
    persist_completion_trace,
)
from app.trading.evaluation import build_fill_price_error_budget_report_v1
from app.trading.simulation_progress import (
    COMPONENT_ARTIFACTS,
    COMPONENT_REPLAY,
    SIMULATION_PROGRESS_COMPONENTS,
    COMPONENT_TA,
    COMPONENT_TORGHUT,
)
from app.whitepapers.workflow import CephS3Client
from scripts import historical_simulation_verification as simulation_verification
from scripts.simulation_lane_contracts import (
    EQUITY_SIMULATION_LANE,
    simulation_clickhouse_table_names,
    simulation_lane_contract,
    simulation_lane_contract_for_manifest,
    simulation_schema_registry_subject_roles,
)

APPLY_CONFIRMATION_PHRASE: Any
DEFAULT_NAMESPACE: Any
DEFAULT_TA_CONFIGMAP: Any
DEFAULT_TA_DEPLOYMENT: Any
DEFAULT_TORGHUT_SERVICE: Any
DEFAULT_SIM_TA_CONFIGMAP: Any
DEFAULT_SIM_TA_DEPLOYMENT: Any
DEFAULT_SIM_TORGHUT_SERVICE: Any
DEFAULT_OUTPUT_ROOT: Any
DEFAULT_SIMULATION_CACHE_BUCKET: Any
DEFAULT_SIMULATION_CACHE_ENDPOINT: Any
DEFAULT_SIMULATION_CACHE_PREFIX: Any
SIMULATION_CACHE_KEY_SCHEMA_VERSION: Any
PRODUCTION_TOPIC_BY_ROLE: Any
SIMULATION_TOPIC_BY_ROLE: Any
TA_TOPIC_KEY_BY_ROLE: Any
TORGHUT_ENV_KEYS: Any
SIMULATION_TORGHUT_ENV_OVERRIDE_ALLOWLIST: Any
SIMULATION_TORGHUT_PATCH_ENV_KEYS: Any
SIMULATION_TORGHUT_RUNTIME_ENV_IGNORE_KEYS: Any
SIMULATION_TORGHUT_RUNTIME_ENV_IGNORE_JQ: Any
SIMULATION_FEATURE_STALENESS_MARGIN_MS: Any
SIMULATION_FEATURE_STALENESS_MIN_MS: Any
US_EQUITIES_REGULAR_PROFILE: Any
US_EQUITIES_REGULAR_TIMEZONE: Any
US_EQUITIES_REGULAR_MINUTES: Any
DEFAULT_COVERAGE_STRICT_RATIO: Any
DEFAULT_RUN_MONITOR_TIMEOUT_SECONDS: Any
DEFAULT_RUN_MONITOR_POLL_SECONDS: Any
DEFAULT_RUN_MONITOR_MIN_DECISIONS: Any
DEFAULT_RUN_MONITOR_MIN_EXECUTIONS: Any
DEFAULT_RUN_MONITOR_MIN_TCA: Any
DEFAULT_RUN_MONITOR_MIN_ORDER_EVENTS: Any
DEFAULT_RUN_MONITOR_CURSOR_GRACE_SECONDS: Any
DEFAULT_WARM_LANE_SIMULATION_DATABASE: Any
DEFAULT_SIMULATION_DUMP_FORMAT: Any
DEFAULT_SIMULATION_DUMP_SORT_MEMORY_LIMIT: Any
SUPPORTED_SIMULATION_DUMP_FORMATS: Any
DEFAULT_SIMULATION_REPLAY_PROFILE: Any
REPLAY_PROFILE_DEFAULTS: dict[str, dict[str, float | int | str]]
LEGACY_SIMULATION_STRATEGY_TOKENS: Any
DEFAULT_ARGOCD_APPSET_NAME: Any
DEFAULT_ARGOCD_NAMESPACE: Any
DEFAULT_ARGOCD_APP_NAME: Any
DEFAULT_ARGOCD_ROOT_APP_NAME: Any
DEFAULT_ARGOCD_RUN_MODE: Any
DEFAULT_ROLLOUTS_NAMESPACE: Any
DEFAULT_ROLLOUTS_RUNTIME_TEMPLATE: Any
DEFAULT_ROLLOUTS_ACTIVITY_TEMPLATE: Any
DEFAULT_ROLLOUTS_TEARDOWN_TEMPLATE: Any
DEFAULT_ROLLOUTS_ARTIFACT_TEMPLATE: Any
DEFAULT_ROLLOUTS_VERIFY_TIMEOUT_SECONDS: Any
DEFAULT_ROLLOUTS_VERIFY_POLL_SECONDS: Any
DEFAULT_SIMULATION_CACHE_CEPH_TIMEOUT_SECONDS: Any
SIMULATION_CACHE_UPLOAD_MIN_TIMEOUT_SECONDS: Any
SIMULATION_CACHE_UPLOAD_TIMEOUT_MAX_SECONDS: Any
SIMULATION_CACHE_UPLOAD_BYTES_PER_SECOND_FLOOR: Any
SIMULATION_CACHE_UPLOAD_TIMEOUT_SLACK_SECONDS: Any
SIMULATION_CACHE_UPLOAD_RETRY_ATTEMPTS: Any
SIMULATION_CACHE_UPLOAD_RETRY_SLEEP_SECONDS: Any
SIMULATION_RUNTIME_LOCK_NAME: Any
SIMULATION_CLICKHOUSE_SCHEMA_SOURCE_DATABASE: Any
SIMULATION_CLICKHOUSE_TABLE_VISIBILITY_ATTEMPTS: Any
SIMULATION_CLICKHOUSE_TABLE_VISIBILITY_SLEEP_SECONDS: Any
TRANSIENT_POSTGRES_ERROR_PATTERNS: Any
NON_TRANSIENT_POSTGRES_ERROR_PATTERNS: Any
VECTOR_EXTENSION_NAME: Any
POSTGRES_VECTOR_EXTENSION_PERMISSION_ERROR_MARKERS: Any
TRANSIENT_POSTGRES_RETRY_ATTEMPTS: Any
TRANSIENT_POSTGRES_RETRY_SLEEP_SECONDS: Any
SIMULATION_POSTGRES_RUNTIME_RESET_TABLES: Any
SIMULATION_POSTGRES_REQUIRED_METADATA_TABLES: Any
KAFKA_API_VERSION: Any
SCHEMA_REGISTRY_CONTENT_TYPE: Any
EMBEDDED_SCHEMA_REGISTRY_SCHEMA_BY_SUFFIX: Any
KAFKA_HOST_SUFFIX_FALLBACKS: Any
_ORIGINAL_GETADDRINFO: Any

def _cluster_service_host_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _kafka_host_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _getaddrinfo_with_kafka_fallback(*args: Any, **kwargs: Any) -> Any: ...

class KafkaRuntimeConfig:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    bootstrap_servers: str
    security_protocol: str | None
    sasl_mechanism: str | None
    sasl_username: str | None
    sasl_password: str | None
    runtime_bootstrap_servers: str | None
    runtime_security_protocol: str | None
    runtime_sasl_mechanism: str | None
    runtime_sasl_username: str | None
    runtime_sasl_password: str | None
    def runtime_bootstrap(*args: Any, **kwargs: Any) -> Any: ...
    def runtime_security(*args: Any, **kwargs: Any) -> Any: ...
    def runtime_sasl(*args: Any, **kwargs: Any) -> Any: ...
    def runtime_username(*args: Any, **kwargs: Any) -> Any: ...
    def runtime_password(*args: Any, **kwargs: Any) -> Any: ...
    def kafka_client_kwargs(*args: Any, **kwargs: Any) -> Any: ...
    def kafka_runtime_client_kwargs(*args: Any, **kwargs: Any) -> Any: ...

class ClickHouseRuntimeConfig:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    http_url: str
    username: str | None
    password: str | None

class PostgresRuntimeConfig:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    admin_dsn: str
    simulation_dsn: str
    simulation_db: str
    migrations_command: str
    runtime_simulation_dsn: str | None
    def torghut_runtime_dsn(*args: Any, **kwargs: Any) -> Any: ...
    def admin_simulation_dsn(*args: Any, **kwargs: Any) -> Any: ...

class SimulationResources:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    run_id: str
    run_token: str
    dataset_id: str
    lane: str
    target_mode: str
    namespace: str
    ta_configmap: str
    ta_deployment: str
    torghut_service: str
    output_root: Path
    source_topic_by_role: dict[str, str]
    simulation_topic_by_role: dict[str, str]
    replay_topic_by_source_topic: dict[str, str]
    ta_group_id: str
    order_feed_group_id: str
    clickhouse_db: str
    clickhouse_table_by_role: dict[str, str]
    clickhouse_signal_table: str
    clickhouse_price_table: str
    warm_lane_enabled: bool

class ArgocdAutomationConfig:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    manage_automation: bool
    applicationset_name: str
    applicationset_namespace: str
    app_name: str
    root_app_name: str
    desired_mode_during_run: str
    restore_mode_after_run: str
    verify_timeout_seconds: int

class RolloutsAnalysisConfig:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    enabled: bool
    namespace: str
    runtime_template: str
    activity_template: str
    teardown_template: str
    artifact_template: str
    verify_timeout_seconds: int
    verify_poll_seconds: int

class AutonomyLaneConfig:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    enabled: bool
    signals_path: Path | None
    strategy_config_path: Path | None
    gate_policy_path: Path | None
    output_dir: Path | None
    artifact_path: Path | None
    repository: str | None
    base: str | None
    head: str | None
    priority_id: str | None
    design_doc: str | None
    promotion_target: str
    strategy_configmap_path: Path | None
    approval_token: str | None
    persist_results: bool
    alpha_train_prices_path: Path | None
    alpha_test_prices_path: Path | None
    alpha_gate_policy_path: Path | None

def _parse_args(*args: Any, **kwargs: Any) -> Any: ...
def _load_manifest(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_run_token(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_kubernetes_name_token(*args: Any, **kwargs: Any) -> Any: ...
def _as_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _as_text(*args: Any, **kwargs: Any) -> Any: ...
def _as_string_list(*args: Any, **kwargs: Any) -> Any: ...
def _simulation_evidence_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _experimental_allow_legacy_strategy(*args: Any, **kwargs: Any) -> Any: ...
def _contains_legacy_strategy_reference(*args: Any, **kwargs: Any) -> Any: ...
def _validate_simulation_strategy_policy(*args: Any, **kwargs: Any) -> Any: ...
def _parse_rfc3339_timestamp(*args: Any, **kwargs: Any) -> Any: ...
def _parse_optional_rfc3339_timestamp(*args: Any, **kwargs: Any) -> Any: ...
def _safe_int(*args: Any, **kwargs: Any) -> Any: ...
def _safe_float(*args: Any, **kwargs: Any) -> Any: ...
def _truthy(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_manifest_relative_path(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_window_bounds(*args: Any, **kwargs: Any) -> Any: ...
def _window_min_coverage_minutes(*args: Any, **kwargs: Any) -> Any: ...
def _validate_us_equities_regular_profile(*args: Any, **kwargs: Any) -> Any: ...
def _validate_window_policy(*args: Any, **kwargs: Any) -> Any: ...
def _validate_dump_coverage(*args: Any, **kwargs: Any) -> Any: ...
def _build_kafka_runtime_config(*args: Any, **kwargs: Any) -> Any: ...
def _build_clickhouse_runtime_config(*args: Any, **kwargs: Any) -> Any: ...
def _derive_simulation_dsn(*args: Any, **kwargs: Any) -> Any: ...
def _database_name_from_dsn(*args: Any, **kwargs: Any) -> Any: ...
def _replace_database_in_dsn(*args: Any, **kwargs: Any) -> Any: ...
def _replace_password_in_dsn(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_dsn_password(*args: Any, **kwargs: Any) -> Any: ...
def _username_from_dsn(*args: Any, **kwargs: Any) -> Any: ...
def _redact_dsn_credentials(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_migrations_command(*args: Any, **kwargs: Any) -> Any: ...
def _find_vector_extension_blocking_revision(*args: Any, **kwargs: Any) -> Any: ...
def _replace_alembic_upgrade_target(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_command_args(*args: Any, **kwargs: Any) -> Any: ...
def _run_alembic_upgrade(*args: Any, **kwargs: Any) -> Any: ...
def _build_postgres_runtime_config(*args: Any, **kwargs: Any) -> Any: ...
def _merge_topics(*args: Any, **kwargs: Any) -> Any: ...
def _ta_topic_key_by_role(*args: Any, **kwargs: Any) -> Any: ...
def _ta_clickhouse_url_key(*args: Any, **kwargs: Any) -> Any: ...
def _ta_group_id_key(*args: Any, **kwargs: Any) -> Any: ...
def _ta_auto_offset_reset_key(*args: Any, **kwargs: Any) -> Any: ...
def _warm_lane_enabled(*args: Any, **kwargs: Any) -> Any: ...
def _default_simulation_postgres_db(*args: Any, **kwargs: Any) -> Any: ...
def _build_resources(*args: Any, **kwargs: Any) -> Any: ...
def _canonicalize_warm_lane_manifest(*args: Any, **kwargs: Any) -> Any: ...
def _build_argocd_automation_config(*args: Any, **kwargs: Any) -> Any: ...
def _build_rollouts_analysis_config(*args: Any, **kwargs: Any) -> Any: ...
def _build_autonomy_lane_config(*args: Any, **kwargs: Any) -> Any: ...
def _run_simulation_autonomy_lane(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_supported_binary(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_lz4_codec_available(*args: Any, **kwargs: Any) -> Any: ...
def _run_command(*args: Any, **kwargs: Any) -> Any: ...
def _is_transient_postgres_error(*args: Any, **kwargs: Any) -> Any: ...
def _is_vector_extension_create_permission_error(*args: Any, **kwargs: Any) -> Any: ...
def _postgres_extension_exists(*args: Any, **kwargs: Any) -> Any: ...
def _run_with_transient_postgres_retry(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_json(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_json_global(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_apply(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_delete(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_delete_if_exists(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_patch(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_patch_json(*args: Any, **kwargs: Any) -> Any: ...
def _json_pointer_escape(*args: Any, **kwargs: Any) -> Any: ...
def _json_pointer_unescape(*args: Any, **kwargs: Any) -> Any: ...
def _discover_applicationset_entry(*args: Any, **kwargs: Any) -> Any: ...
def _read_argocd_applicationset_entry(*args: Any, **kwargs: Any) -> Any: ...
def _json_pointer_get(*args: Any, **kwargs: Any) -> Any: ...
def _normalized_automation_mode(*args: Any, **kwargs: Any) -> Any: ...
def _clone_json_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _clone_json_list(*args: Any, **kwargs: Any) -> Any: ...
def _simulation_lock_payload(*args: Any, **kwargs: Any) -> Any: ...
def _read_simulation_runtime_lock(*args: Any, **kwargs: Any) -> Any: ...
def _acquire_simulation_runtime_lock(*args: Any, **kwargs: Any) -> Any: ...
def _release_simulation_runtime_lock(*args: Any, **kwargs: Any) -> Any: ...
def _read_argocd_automation_mode(*args: Any, **kwargs: Any) -> Any: ...
def _set_argocd_automation_mode(*args: Any, **kwargs: Any) -> Any: ...
def _argocd_application_mode_from_sync_policy(*args: Any, **kwargs: Any) -> Any: ...
def _read_named_argocd_application_sync_policy(*args: Any, **kwargs: Any) -> Any: ...
def _read_argocd_application_sync_policy(*args: Any, **kwargs: Any) -> Any: ...
def _manual_argocd_application_sync_policy(*args: Any, **kwargs: Any) -> Any: ...
def _set_argocd_application_sync_policy(*args: Any, **kwargs: Any) -> Any: ...
def _normalized_argocd_ignore_difference_rule(*args: Any, **kwargs: Any) -> Any: ...
def _normalized_argocd_ignore_differences(*args: Any, **kwargs: Any) -> Any: ...
def _simulation_runtime_argocd_ignore_differences(*args: Any, **kwargs: Any) -> Any: ...
def _merge_argocd_application_ignore_differences(*args: Any, **kwargs: Any) -> Any: ...
def _argocd_ignore_differences_cover_runtime_mutations(
    *args: Any, **kwargs: Any
) -> Any: ...
def _argocd_ignore_differences_cover_required_rules(
    *args: Any, **kwargs: Any
) -> Any: ...
def _set_argocd_application_ignore_differences(*args: Any, **kwargs: Any) -> Any: ...
def _wait_for_argocd_application_mode(*args: Any, **kwargs: Any) -> Any: ...
def _kservice_env(*args: Any, **kwargs: Any) -> Any: ...
def _kservice_container_with_env(*args: Any, **kwargs: Any) -> Any: ...
def _read_secret_key_ref(*args: Any, **kwargs: Any) -> Any: ...
def _read_configmap_key_ref(*args: Any, **kwargs: Any) -> Any: ...
def _expand_env_value_refs(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_kservice_env_values(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_warm_lane_runtime_postgres_config(*args: Any, **kwargs: Any) -> Any: ...
def _merge_env_entries(*args: Any, **kwargs: Any) -> Any: ...
def _recommended_simulation_feature_staleness_ms(*args: Any, **kwargs: Any) -> Any: ...
def _torghut_env_overrides_from_manifest(*args: Any, **kwargs: Any) -> Any: ...
def _simulation_account_label(*args: Any, **kwargs: Any) -> Any: ...
def _performance_config(*args: Any, **kwargs: Any) -> Any: ...
def _dump_suffix(*args: Any, **kwargs: Any) -> Any: ...
def _stable_json_for_hash(*args: Any, **kwargs: Any) -> Any: ...
def _stable_string_list(*args: Any, **kwargs: Any) -> Any: ...
def _cache_lineage_payload(*args: Any, **kwargs: Any) -> Any: ...
def _derived_simulation_cache_key(*args: Any, **kwargs: Any) -> Any: ...
def _derived_simulation_cache_paths(*args: Any, **kwargs: Any) -> Any: ...
def _cache_artifact_lineage_matches(*args: Any, **kwargs: Any) -> Any: ...
def _state_paths(*args: Any, **kwargs: Any) -> Any: ...
def _dump_artifact_manifest_path(*args: Any, **kwargs: Any) -> Any: ...
def _dump_sort_stage_path(*args: Any, **kwargs: Any) -> Any: ...
def _dump_sort_output_path(*args: Any, **kwargs: Any) -> Any: ...
def _dump_sort_key(*args: Any, **kwargs: Any) -> Any: ...
def _materialize_deterministic_dump(*args: Any, **kwargs: Any) -> Any: ...
def _run_state_path(*args: Any, **kwargs: Any) -> Any: ...
def _artifact_path(*args: Any, **kwargs: Any) -> Any: ...
def _ta_restore_policy(*args: Any, **kwargs: Any) -> Any: ...
def _ta_restore_paths(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_ta_restore_configuration(*args: Any, **kwargs: Any) -> Any: ...
def _update_run_state(*args: Any, **kwargs: Any) -> Any: ...
def _log_script_event(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_directory(*args: Any, **kwargs: Any) -> Any: ...
def _save_json(*args: Any, **kwargs: Any) -> Any: ...
def _write_dump_marker(*args: Any, **kwargs: Any) -> Any: ...
def _write_dump_marker_from_manifest(*args: Any, **kwargs: Any) -> Any: ...
def _simulation_cache_client_from_env(*args: Any, **kwargs: Any) -> Any: ...
def _simulation_cache_upload_timeout_seconds(*args: Any, **kwargs: Any) -> Any: ...
def _simulation_cache_upload_attempts(*args: Any, **kwargs: Any) -> Any: ...
def _is_transient_simulation_cache_upload_error(*args: Any, **kwargs: Any) -> Any: ...
def _cache_metadata(*args: Any, **kwargs: Any) -> Any: ...
def _s3_bucket_key(*args: Any, **kwargs: Any) -> Any: ...
def _restore_cached_dump_if_available(*args: Any, **kwargs: Any) -> Any: ...
def _upload_dump_to_cache(*args: Any, **kwargs: Any) -> Any: ...
def _utc_from_millis(*args: Any, **kwargs: Any) -> Any: ...
def _upsert_simulation_progress_row(*args: Any, **kwargs: Any) -> Any: ...
def _load_json(*args: Any, **kwargs: Any) -> Any: ...
def _load_optional_json(*args: Any, **kwargs: Any) -> Any: ...
def _file_sha256(*args: Any, **kwargs: Any) -> Any: ...
def _dump_marker_path(*args: Any, **kwargs: Any) -> Any: ...
def _parse_dump_timestamp_bounds(*args: Any, **kwargs: Any) -> Any: ...
def _scan_dump_timestamp_bounds(*args: Any, **kwargs: Any) -> Any: ...
def _reusable_dump_report(*args: Any, **kwargs: Any) -> Any: ...
def _build_plan_report(*args: Any, **kwargs: Any) -> Any: ...
def _http_clickhouse_query(*args: Any, **kwargs: Any) -> Any: ...
def _http_request(*args: Any, **kwargs: Any) -> Any: ...
def _clickhouse_query_configs(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_clickhouse_database(*args: Any, **kwargs: Any) -> Any: ...
def _show_create_clickhouse_table(*args: Any, **kwargs: Any) -> Any: ...
def _rewrite_clickhouse_table_ddl_for_simulation(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_clickhouse_runtime_tables(*args: Any, **kwargs: Any) -> Any: ...
def _clickhouse_database_precreated(*args: Any, **kwargs: Any) -> Any: ...
def _postgres_database_precreated(*args: Any, **kwargs: Any) -> Any: ...
def _wait_for_clickhouse_table(*args: Any, **kwargs: Any) -> Any: ...
def _wait_for_clickhouse_database(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_postgres_database(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_postgres_runtime_permissions(*args: Any, **kwargs: Any) -> Any: ...
def _run_migrations(*args: Any, **kwargs: Any) -> Any: ...
def _assert_required_simulation_metadata_tables(*args: Any, **kwargs: Any) -> Any: ...
def _remove_appledouble_sidecars(*args: Any, **kwargs: Any) -> Any: ...
def _supersede_stale_simulation_progress_rows(*args: Any, **kwargs: Any) -> Any: ...
def _reset_postgres_runtime_state(*args: Any, **kwargs: Any) -> Any: ...
def _seed_simulation_trade_cursor(*args: Any, **kwargs: Any) -> Any: ...
def _upsert_simulation_runtime_context(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_sessionmaker(*args: Any, **kwargs: Any) -> Any: ...
def _capture_cluster_state(*args: Any, **kwargs: Any) -> Any: ...
def _clickhouse_jdbc_url_for_database(*args: Any, **kwargs: Any) -> Any: ...
def _configure_ta_for_simulation(*args: Any, **kwargs: Any) -> Any: ...
def _desired_ta_simulation_config(*args: Any, **kwargs: Any) -> Any: ...
def _ta_runtime_reconfigure_required(*args: Any, **kwargs: Any) -> Any: ...
def _restart_ta_deployment(*args: Any, **kwargs: Any) -> Any: ...
def _configure_torghut_service_for_simulation(*args: Any, **kwargs: Any) -> Any: ...
def _torghut_service_env_for_simulation(*args: Any, **kwargs: Any) -> Any: ...
def _torghut_service_reconfigure_required(*args: Any, **kwargs: Any) -> Any: ...
def _restore_ta_configuration(*args: Any, **kwargs: Any) -> Any: ...
def _restore_ta_configuration_required(*args: Any, **kwargs: Any) -> Any: ...
def _restore_torghut_env(*args: Any, **kwargs: Any) -> Any: ...
def _restore_torghut_env_required(*args: Any, **kwargs: Any) -> Any: ...
def _condition_status(*args: Any, **kwargs: Any) -> Any: ...
def _deployment_replica_health(*args: Any, **kwargs: Any) -> Any: ...
def _fink_runtime_health(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_verify(*args: Any, **kwargs: Any) -> Any: ...
def _kafka_admin_client(*args: Any, **kwargs: Any) -> Any: ...
def _source_topic_partition_counts(*args: Any, **kwargs: Any) -> Any: ...
def _kafka_available_broker_count(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_topics(*args: Any, **kwargs: Any) -> Any: ...
def _simulation_schema_registry_subject_specs(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_schema_registry_schema_path(*args: Any, **kwargs: Any) -> Any: ...
def _load_schema_registry_schema_literal(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_simulation_schema_subjects(*args: Any, **kwargs: Any) -> Any: ...
def _consumer_for_dump(*args: Any, **kwargs: Any) -> Any: ...
def _producer_for_replay(*args: Any, **kwargs: Any) -> Any: ...
def _bytes_to_b64(*args: Any, **kwargs: Any) -> Any: ...
def _b64_to_bytes(*args: Any, **kwargs: Any) -> Any: ...
def _headers_to_json(*args: Any, **kwargs: Any) -> Any: ...
def _json_to_headers(*args: Any, **kwargs: Any) -> Any: ...
def _offset_for_time_lookup(*args: Any, **kwargs: Any) -> Any: ...
def _dump_topics(*args: Any, **kwargs: Any) -> Any: ...
def _pacing_delay_seconds(*args: Any, **kwargs: Any) -> Any: ...
def _dump_format_for_path(*args: Any, **kwargs: Any) -> Any: ...
def _open_dump_reader(*args: Any, **kwargs: Any) -> Any: ...
def _compress_dump_file(*args: Any, **kwargs: Any) -> Any: ...
def _count_lines(*args: Any, **kwargs: Any) -> Any: ...
def _dump_sha256_for_replay(*args: Any, **kwargs: Any) -> Any: ...
def _producer_flush_with_retry(*args: Any, **kwargs: Any) -> Any: ...
def _replay_dump(*args: Any, **kwargs: Any) -> Any: ...
def _verify_isolation_guards(*args: Any, **kwargs: Any) -> Any: ...
def _apply(*args: Any, **kwargs: Any) -> Any: ...
def _teardown(*args: Any, **kwargs: Any) -> Any: ...
def _prepare_argocd_for_run(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_argocd_manual_before_runtime_mutation(*args: Any, **kwargs: Any) -> Any: ...
def _restore_argocd_after_run(*args: Any, **kwargs: Any) -> Any: ...
def _analysis_run_name(*args: Any, **kwargs: Any) -> Any: ...
def _analysis_run_args(*args: Any, **kwargs: Any) -> Any: ...
def _render_analysis_run_spec(*args: Any, **kwargs: Any) -> Any: ...
def _wait_for_analysis_run(*args: Any, **kwargs: Any) -> Any: ...
def _wait_for_runtime_verify(*args: Any, **kwargs: Any) -> Any: ...
def _torghut_service_revision_ready(*args: Any, **kwargs: Any) -> Any: ...
def _wait_for_torghut_service_revision_ready(*args: Any, **kwargs: Any) -> Any: ...
def _run_rollouts_analysis(*args: Any, **kwargs: Any) -> Any: ...
def _report_simulation(*args: Any, **kwargs: Any) -> Any: ...
def _doc29_simulation_gate_ids(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_or_zero(*args: Any, **kwargs: Any) -> Any: ...
def _has_decimal_value(*args: Any, **kwargs: Any) -> Any: ...
def _build_fill_price_error_budget_payload(*args: Any, **kwargs: Any) -> Any: ...
def _build_strategy_proof_artifact(*args: Any, **kwargs: Any) -> Any: ...
def _build_performance_report(*args: Any, **kwargs: Any) -> Any: ...
def _build_run_summary(*args: Any, **kwargs: Any) -> Any: ...
def _build_gate_input(*args: Any, **kwargs: Any) -> Any: ...
def _existing_artifact_refs(*args: Any, **kwargs: Any) -> Any: ...
def _completion_trace_coverage_ratio(*args: Any, **kwargs: Any) -> Any: ...
def _build_simulation_completion_trace(*args: Any, **kwargs: Any) -> Any: ...
def _run_full_lifecycle(*args: Any, **kwargs: Any) -> Any: ...
def _render_report(*args: Any, **kwargs: Any) -> Any: ...

_monitor_run_completion: Any
_monitor_snapshot: Any
_signal_snapshot: Any

def main(*args: Any, **kwargs: Any) -> Any: ...
