from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import argparse
import json
import os
import shutil
import subprocess
from base64 import b64encode
from dataclasses import dataclass
from typing import Any, Mapping
from urllib.error import URLError
from urllib.request import Request, urlopen
import yaml

TA_CONFIGMAP: Any
TA_DEPLOYMENT: Any
APPLY_CONFIRMATION_PHRASE: Any
SUPPORTED_NAMESPACE: Any
FAILED_RUN_STATES: Any
MILLISECONDS_PER_DAY: Any
DEFAULT_KAFKA_RETENTION_TOPICS: Mapping[str, str]
RAW_REPLAY_SOURCE_TOPIC_ROLES: Any
DERIVED_TA_TOPIC_ROLES: Any
CLICKHOUSE_TA_TTL_DAYS: Mapping[str, int]

class ReplayState:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    namespace: str
    ta_group_id: str
    ta_auto_offset_reset: str
    flink_job_state: str | None
    flink_restart_nonce: int
    flink_status_state: str | None

def _require_kubectl(*args: Any, **kwargs: Any) -> Any: ...
def _require_supported_namespace(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_binary(*args: Any, **kwargs: Any) -> Any: ...
def _run_kubectl(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_get_ta_config_json(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_get_ta_deployment_json(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_get_kafka_topics_json(*args: Any, **kwargs: Any) -> Any: ...
def _kubectl_merge_patch(*args: Any, **kwargs: Any) -> Any: ...
def _parse_int(*args: Any, **kwargs: Any) -> Any: ...
def _load_state(*args: Any, **kwargs: Any) -> Any: ...
def _plan_command(*args: Any, **kwargs: Any) -> Any: ...
def _validate_plan_args(*args: Any, **kwargs: Any) -> Any: ...
def _validate_apply_preconditions(*args: Any, **kwargs: Any) -> Any: ...
def _build_plan_report(*args: Any, **kwargs: Any) -> Any: ...
def _print_plan_text(*args: Any, **kwargs: Any) -> Any: ...
def _clickhouse_basic_auth(*args: Any, **kwargs: Any) -> Any: ...
def _clickhouse_query(*args: Any, **kwargs: Any) -> Any: ...
def _parse_tsv_with_names(*args: Any, **kwargs: Any) -> Any: ...
def _parse_int_field(*args: Any, **kwargs: Any) -> Any: ...
def _table_coverage_query(*args: Any, **kwargs: Any) -> Any: ...
def _day_gap_query(*args: Any, **kwargs: Any) -> Any: ...
def _load_clickhouse_coverage(*args: Any, **kwargs: Any) -> Any: ...
def _required_calendar_days_from_trading_days(*args: Any, **kwargs: Any) -> Any: ...
def _parse_kafka_retention_topic_overrides(*args: Any, **kwargs: Any) -> Any: ...
def _kafka_topic_items_by_name(*args: Any, **kwargs: Any) -> Any: ...
def _kafka_topic_ready_status(*args: Any, **kwargs: Any) -> Any: ...
def _kafka_topic_config(*args: Any, **kwargs: Any) -> Any: ...
def _parse_retention_ms(*args: Any, **kwargs: Any) -> Any: ...
def _retention_days(*args: Any, **kwargs: Any) -> Any: ...
def _topic_role_has_blocker(*args: Any, **kwargs: Any) -> Any: ...
def _load_kafka_retention(*args: Any, **kwargs: Any) -> Any: ...
def _append_unique(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _string_list(*args: Any, **kwargs: Any) -> Any: ...
def _summary_int(*args: Any, **kwargs: Any) -> Any: ...
def _role_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _build_replay_feasibility(*args: Any, **kwargs: Any) -> Any: ...
def _apply_plan(*args: Any, **kwargs: Any) -> Any: ...
def _verify_state(*args: Any, **kwargs: Any) -> Any: ...
def _final_status(*args: Any, **kwargs: Any) -> Any: ...
def _handle_plan_mode(*args: Any, **kwargs: Any) -> Any: ...
def _handle_verify_mode(*args: Any, **kwargs: Any) -> Any: ...
def _handle_apply_mode(*args: Any, **kwargs: Any) -> Any: ...
def parse_args(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
