from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import argparse
import json
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, cast
from urllib.request import urlopen

SCHEMA_VERSION: Any
ROUTE_REACQUISITION_BOARD_SCHEMA_VERSION: Any
ROUTE_REACQUISITION_BOOK_SCHEMA_VERSION: Any
NEXT_PAPER_ROUTE_TARGET_PLAN_SCHEMA_VERSION: Any
RUNTIME_LEDGER_PROOF_PACKET_SCHEMA_VERSION: Any
TIGERBEETLE_RUNTIME_LEDGER_PARITY_SCHEMA_VERSION: Any
TIGERBEETLE_PARITY_STATUS_PASS: Any
DOC29_LIVE_SCALE_GATE: Any
REQUIRED_RUNTIME_WINDOW_TARGET_PLAN_FLAGS: Any
_RUNTIME_LEDGER_TRADING_DAY_KEYS: Any
_MISSING_QUANT_REASONS: Any

def _text(*args: Any, **kwargs: Any) -> Any: ...
def _bool(*args: Any, **kwargs: Any) -> Any: ...
def _health_gate_bool(*args: Any, **kwargs: Any) -> Any: ...
def _int(*args: Any, **kwargs: Any) -> Any: ...
def _decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_positive(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _sequence(*args: Any, **kwargs: Any) -> Any: ...
def _text_list(*args: Any, **kwargs: Any) -> Any: ...
def _load_json_object(*args: Any, **kwargs: Any) -> Any: ...
def _load_status_url(*args: Any, **kwargs: Any) -> Any: ...
def _load_optional_json_object(*args: Any, **kwargs: Any) -> Any: ...
def _dimension_by_name(*args: Any, **kwargs: Any) -> Any: ...
def _dimension_is_required(*args: Any, **kwargs: Any) -> Any: ...
def _market_session_open(*args: Any, **kwargs: Any) -> Any: ...
def _add_check(*args: Any, **kwargs: Any) -> Any: ...
def _expected_floor_states(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_probe_summary(*args: Any, **kwargs: Any) -> Any: ...

_QUOTE_FILLABILITY_REASON_TOKENS: Any
_QUOTE_FILLABILITY_REPAIR_ACTIONS: Mapping[str, str]

def _quote_fillability_reason(*args: Any, **kwargs: Any) -> Any: ...
def _quote_fillability_repair_action(*args: Any, **kwargs: Any) -> Any: ...
def _append_unique_text(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_quote_fillability_summary(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_target_plan_summary(*args: Any, **kwargs: Any) -> Any: ...
def _proofs_target_plan_summary(*args: Any, **kwargs: Any) -> Any: ...

_PAPER_ROUTE_PREOPEN_SOFT_CHECKS: Any

def _paper_route_preopen_evidence_collection_ready(
    *args: Any, **kwargs: Any
) -> Any: ...
def _apply_paper_route_preopen_evidence_collection(
    *args: Any, **kwargs: Any
) -> Any: ...
def _completion_gate(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_summary(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_refs(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_trading_day_count(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_daily_net_pnl(*args: Any, **kwargs: Any) -> Any: ...
def _add_runtime_ledger_proof_packet_check(*args: Any, **kwargs: Any) -> Any: ...
def _add_tigerbeetle_parity_check(*args: Any, **kwargs: Any) -> Any: ...
def _readiness_next_action(*args: Any, **kwargs: Any) -> Any: ...
def _add_runtime_ledger_profit_proof_checks(*args: Any, **kwargs: Any) -> Any: ...
def _execution_tca_lineage_summary(*args: Any, **kwargs: Any) -> Any: ...
def _add_execution_tca_lineage_check(*args: Any, **kwargs: Any) -> Any: ...
def evaluate_trading_readiness(*args: Any, **kwargs: Any) -> Any: ...
def _parser(*args: Any, **kwargs: Any) -> Any: ...
def main(*args: Any, **kwargs: Any) -> Any: ...
