apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
- server-upgrade-backup.yaml
- kargo-upgrade-backup.yaml
- postgres-upgrade-backup.yaml
- admin-sealedsecret.yaml
- postgres-cluster.yaml
- ingressroute-forgejo-k8s-private.yaml
helmCharts:
- name: forgejo
  repo: oci://code.forgejo.org/forgejo-helm
  version: 17.1.5
  releaseName: forgejo
  namespace: forgejo
  valuesFile: values.yaml
configMapGenerator:
- name: forgejo-kargo-16-0-3-rehearsal
  files:
  - upgrade-db-rehearsal.sh
  - upgrade-app-rehearsal.sh
  - upgrade-repository-refs.sh
  options:
    annotations:
      argocd.argoproj.io/sync-wave: "-25"
generatorOptions:
  disableNameSuffixHash: true
patches:
- path: kargo-upgrade-quiesce.patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: forgejo
images:
- name: code.forgejo.org/forgejo/forgejo
  newName: registry.ide-newton.ts.net/lab/forgejo
  digest: sha256:354184ad49824f28e84574519a50bb11974528a6746fb24d1786a87ba6e1c62c
