apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tengri
resources:
- crd.yaml
- sealed-secret.yaml
- service-account.yaml
- auth-nonces.yaml
- rbac.yaml
- spire-admission.yaml
- deployment.yaml
- services.yaml
- ingressroute.yaml
- resource-quota.yaml
- pod-disruption-budget.yaml
- network-policies.yaml
configMapGenerator:
- name: tengri-release
  literals:
  - NANOAGENT_IMAGE=registry.ide-newton.ts.net/lab/nanoagent@sha256:3b7013c180a11cc06910179c3780d8d043bc6e94a0dbccaf92d9fb2f6ee35d46
configurations:
- kustomizeconfig.yaml
images:
- name: registry.ide-newton.ts.net/lab/tengri
  digest: sha256:56b04da8fe7074e63356d093f287621b742dd5bcba73cda5bc72f0be658fbf22
