apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tengri
resources:
  - crd.yaml
  - external-secret.yaml
  - service-account.yaml
  - auth-nonces.yaml
  - rbac.yaml
  - deployment.yaml
  - services.yaml
  - ingressroute.yaml
  - resource-quota.yaml
  - pod-disruption-budget.yaml
  - network-policies.yaml
configMapGenerator:
  - name: tengri-release
    literals:
      - NANOAGENT_IMAGE=registry.ide-newton.ts.net/lab/nanoagent@sha256:042f84e2c587e047ce1cd99ca3c2ffb00382d8ced042f46eb65f6cb2a0dfacee
images:
  - name: registry.ide-newton.ts.net/lab/tengri
    newName: registry.ide-newton.ts.net/lab/tengri
    digest: sha256:0ac97bea95ecc9916352fce56f0809f12dbf50e941430e756e60b255d751992f
