apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tengri
resources:
- crd.yaml
- sealed-secret.yaml
- service-account.yaml
- auth-nonces.yaml
- rbac.yaml
- deployment.yaml
- services.yaml
- ingressroute.yaml
- resource-quota.yaml
- pod-disruption-budget.yaml
- network-policies.yaml
configMapGenerator:
- name: tengri-release
  literals:
  - NANOAGENT_IMAGE=registry.ide-newton.ts.net/lab/nanoagent@sha256:2e64aefeaa1b1453961b65c5f4ac66e6de6e044961920251281676ef4e0f00b3
configurations:
- kustomizeconfig.yaml
images:
- name: registry.ide-newton.ts.net/lab/tengri
  digest: sha256:05d12e341140bd643bc564baf5bb09c32b0f6491de586cd3810d63d571c4559c
