---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tengri-runtime
  namespace: tengri
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  encryptedData:
    TENGRI_INTERNAL_HMAC_SECRET: AgDHPs19spcWiLH+U92t+F2G8v9ku9tv6l9PrkzyXpSKPCvqGbpG/xuAo7+YC19jOZGUUa5VxfyCUFvzKGNCo5dBWhyYSNMgOnB3dfdmvPCH2d0EAzRpgNYigb+YXo8/XbSC8SsesFxKs+83RfAw1KogfPKVaYksOfmZDBnl2W+uj/1npCr6S3qL8IvmwZmFYlloz8p5StWMahILL5Obt1gjf46pPn4IEyt4yyWXwim+S/5x3b+gRLPdEpDnzuJRmRrEmIzDm9rdRZXbLb/cx4YIW+e5PUZusXvVvzHdQt4Y8yAK7TT4gJ6c2hSV2RI5jaXRuTgG7O4P6EFmNA5H/9iORYbVI6vf34bXMT+/Tc8ccrsIA6liJrPiguI+QqywHg+R/D3eIHPmtobE7oDu2Sdw3NyzBTiioqScs2NHZQg89KUb4fD7tYpvGiBL44Rd/zL9YLZWrxl8epXuYJZW+3yym74vgrd9Mzl6cYDRlPVFKlAGvrVeHOfRDiwP3tLoXcgY/gaFIJqwU0mYpdsK6fBEL+WJwCZtMCRrVQxYtAFdD9TRE6AxvACcwM6uLSKL10DkF2zEU0zIhN+EpozVCBv+tR0x+IfcruOAY//u3lCh8BIUA/awi6Hx5R97btI/17LMBaxoD7TrnUDD5OTXfFuGwQztcZZf/BClwWI8tr7aWqFa9WAUVmWhutvDaN0ezpODlxL8MijluXk1vSHkbIw49ptfKoE2cca83Osn7xVbegmO4gNml5CMBmHkxFnS0QtQniP6EQszq3VacVMhmWTD
    TENGRI_TICKET_SIGNING_SECRET: AgB53p0hH9eEtQ2kZw+xLvfaFfV6GxSCYzstxugyh3dnuQ8Zv4dwaIxTInDSnS2HRp3CDuL3UxRBIeze1UehNMocMqnOQ06qBStMukt3LcCzeNWglGtaL7KqXNocIHcyxgUV/Fcu2+NEsUJZ+yOQqozV582nzLxWOmBYRwqklTDp8mNVZUGkBfuA0UI7LJUHy62CQTyL/fKnwALyiTlYY19lViw1WvUjjqw/+pVfoyK72/JbR+T3n2qo2MktXPX9mrS+2rKz0t9AFSrdT4Lz04jCV0035fg8vgjBCqX6Xjq5AGKnV1gj16N7pasvU00yvqpIF623cO5JqGqejA0dC6VivJfAAiUTgry3GY4BzFjc5NyGnToJQqS4aq+OzSg6jcesN5RcTRu5dVfTYgdF3VVxsbCQ0Llm4/KNgln/unF3s+81KnXE8xwVWQXB3GWknECZx+5iNJIqFlSNdp5av0FI7FshONijHbkd4oFMQx6y0XgR60U5VYY/gS1ZPpkFEZU4b9gjRWdOQFEO8Wh79iu0Y6lI3lStPS4c7sKoayJse/BcffyOcXLvyJshGQvcK9/JxUCdZ0njNCOiFWI15/gn/43vgRD96G0hOzM5RFbisTghdEa443CS71jBliw1Cchn3LPiSSS/A26n6X8CX5nk7cIr3tLC4O1Yq7R1M46oEdmEgytOkVRGYPZn9I/ycrxOvGP14ps79PYScSC2NJI7AtjO3dkVJ1yuuwCCcTjuiJydiM13u+yUmBDRlEssso+yNYgVRekhd4RMgZ91baAI
  template:
    metadata:
      name: tengri-runtime
      namespace: tengri
    type: Opaque
