{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tengri-spicedb-key",
    "namespace": "tengri",
    "annotations": {
      "argocd.argoproj.io/sync-wave": "-1"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tengri-spicedb-key",
        "namespace": "tengri"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "preshared_key": "AgAM+faJ9+mpDx++ZlaIB7adfXhDXJ4GN6ceOuA21el18/qSbLy/344v6ZQp8uaNs4MQGytSO7X0BF8fu/YQKkKvQoBUO52BwGcfPLrmJoFpCXEAjIZAL4r0xvzUwMARjfkKZBEUfBSWp9JHpZGI5Xbe2NNYqEX/tgldvFcf8Ez/h6OoBZNrzxW+ssb0k0gHGv9z43wBFUuLUYAOPPeHU/gziXPb/Neo7Sr/eb6GX1/OCZPUugrptqHMdJOz1FMFmex6JZkVTMTtK+S//hhw/yp7N9sB93Z1ifm3o/qwZKP2DHjMvxsR0LvAzRwPyfA4tvqk6j+D4VUp2WxVxHL4d9brf0oY97vtUU/hAfUoOirIZrNrDWXOpb1myKpeoXP3KZ07y+cQKdBXUAQQndHo4KU8zerecnEQ+skQM9DlXCyUt2pvqfGP3Di7LFWWgI5vl+e9sR6tfb/T33oxgu2F3ANXQzikh+Qb9Do0kGBMsPtalR6D665UFhe+KG+x5HW2WDMJrpYIeMPdUtyEd4ZG7cX+aGI2xZCGXyK/q6IfyN3MA36+BYdUZbO0fa3nhWuRDBA/dncPdTf0cSGGbJCNPG0cU6qA313ms6R426XbAQrouxg4A1W7wtCvM8G+zvIGvcM6bAl5iHEth9sXRBBdRI8OBXTFBBg/Vu2piTL01wjy67R6c1ypQ4+PyWB8xNX8ogTHXcIJDm+JuvRomDzrR8rZsSGiH1E6SikIA8Vy7ac5g9oH2hCp3O7PyH+r9dM3QJwQn/zH8Rq0Wj2j8r319yH0"
    }
  }
}
