apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: attic-secrets
  namespace: attic
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-infra
  target:
    name: attic-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token-rs256-secret-base64
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: attic-cache
        property: token-rs256-secret-base64
        metadataPolicy: None
        nullBytePolicy: Ignore
