apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attic
resources:
- postgres-upgrade-backup.yaml
- objectbucketclaim.yaml
- postgres-cluster.yaml
- externalsecret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- tailscale-ingress.yaml
- gc-cronjob.yaml
images:
- name: registry.ide-newton.ts.net/lab/attic
  digest: sha256:2d519d97fd3cccae2e89d6bb4e38ea0485c87999593d524b526e428eb6d99529
