apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attic
resources:
- postgres-upgrade-backup.yaml
- objectbucketclaim.yaml
- postgres-cluster.yaml
- externalsecret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- tailscale-ingress.yaml
- gc-cronjob.yaml
images:
- name: registry.ide-newton.ts.net/lab/attic
  digest: sha256:45e591bf32738b2a4a696a540fd74941081445fcac68420b1e9f30b9fdceeb04
