// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewTarget } from "./ReviewTarget";

export type ReviewStartParams = { threadId: string, target: ReviewTarget, 
/**
 * When true, also append the final review message to the original thread.
 */
appendToOriginalThread: boolean, };
