-- +goose Up
-- +goose NO TRANSACTION

CREATE SCHEMA IF NOT EXISTS codex_kb AUTHORIZATION facteur;

GRANT USAGE ON SCHEMA codex_kb TO facteur;
ALTER DEFAULT PRIVILEGES IN SCHEMA codex_kb
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO facteur;

-- +goose Down
-- +goose NO TRANSACTION
ALTER DEFAULT PRIVILEGES IN SCHEMA codex_kb
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM facteur;
REVOKE USAGE ON SCHEMA codex_kb FROM facteur;
DROP SCHEMA IF EXISTS codex_kb;
