apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-next
resources:
  - rbac.yaml
  - kafka-cluster.yaml
  - source-credential-reflections.yaml
  - kafka-users.yaml
  - mirror-maker-2.yaml
