apiVersion: v1
kind: Secret
metadata:
  name: user1-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    reflector.v1.k8s.emberstack.com/reflects: kafka/user1
---
apiVersion: v1
kind: Secret
metadata:
  name: karapace-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    reflector.v1.k8s.emberstack.com/reflects: kafka/karapace
---
apiVersion: v1
kind: Secret
metadata:
  name: facteur-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    reflector.v1.k8s.emberstack.com/reflects: kafka/facteur
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-codex-credentials-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    reflector.v1.k8s.emberstack.com/reflects: kafka/kafka-codex-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: froussard-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    reflector.v1.k8s.emberstack.com/reflects: kafka/froussard
---
apiVersion: v1
kind: Secret
metadata:
  name: flink-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    reflector.v1.k8s.emberstack.com/reflects: kafka/flink
---
apiVersion: v1
kind: Secret
metadata:
  name: torghut-hyperliquid-feed-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    reflector.v1.k8s.emberstack.com/reflects: kafka/torghut-hyperliquid-feed
---
apiVersion: v1
kind: Secret
metadata:
  name: torghut-options-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    reflector.v1.k8s.emberstack.com/reflects: kafka/torghut-options
---
apiVersion: v1
kind: Secret
metadata:
  name: torghut-ws-source
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    reflector.v1.k8s.emberstack.com/reflects: kafka/torghut-ws
