{{- if and .Values.devShell.enabled .Values.devShell.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.devShell.tunnel.secretName }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "agents.labels" . | nindent 4 }}
    app.kubernetes.io/component: dev-shell
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  refreshPolicy: {{ .Values.devShell.externalSecret.refreshPolicy }}
  refreshInterval: {{ .Values.devShell.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.devShell.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.devShell.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.devShell.tunnel.secretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: {{ .Values.devShell.tunnel.secretKey }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.devShell.externalSecret.remoteRef.key }}
        metadataPolicy: None
        nullBytePolicy: Ignore
{{- end }}
