apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo-runners
resources:
  - serviceaccount.yaml
  - service-headless.yaml
  - configmap-runner.yaml
  - sealedsecret-runner-token.yaml
  - statefulset-forgejo-runners-amd64.yaml
  - statefulset-forgejo-runners-arm64.yaml
  - pdb-forgejo-runners-amd64.yaml
  - pdb-forgejo-runners-arm64.yaml
