apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: forgejo-runners-amd64
  labels:
    app.kubernetes.io/name: forgejo-runners
    app.kubernetes.io/instance: forgejo-runners-amd64
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo-runners
      app.kubernetes.io/instance: forgejo-runners-amd64
