apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-runners
  labels:
    app.kubernetes.io/name: forgejo-runners
    app.kubernetes.io/part-of: forgejo-runners
automountServiceAccountToken: false
