apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: torghut
spec:
  encryptedData:
    token: AgBeulVHuQAwUY3Uz8NDDttRcprF7uZzfKPh7IefvsPG8+SaZ/1mNuW62GP50LNcZm5T+n516yB9eAaqpff9I4PEoQWTjmsZw22IQFXk6ful2WTFepbz+sktXHv0kmRMP7fHbpNWPoPxG6ZDGl6rx3KmJzPc5d/++9DhQ12ojcePPSWwWMt6cN7x3e98xkyj6QZwzXbdipCGA1+17v25FUiGC9pkc6JFUvK1T9tMe/Yaj1L3cjp0FDlZZEFiPrT5pE0h70+3ci4bynec/yEgFk/af5WO/jG/7V87pGeKJI80vULZCIQ5w6HNshBCUsj8JGslY425brhOBTCYlySnDBRCpAN5coOEAUr/MHx77vJ/MM/12p7nrltNY3C7pKAbGUgEEfaD6o53BpKvJa2kwwVF81NCHAOgoT1Z+vb1j/+u/5O4K1Qx+GI52D66OQ1OBmPq885GBC5HTAEpJW3/3xf09J0kaj48uvATra5dwacxl2JQLGQZJ21p4GXCkP/PzmfyTXvWYLAhUTlk83HpTpFYvtCVSItQHQtakaHwBnhg1FyScnOxAR/HEA/01F1MrRhSK3nohXtcYvBP27JeX9WyXRY47lwrCXVV170LjmeKU98E6+Deno8S+zsbie+ImNP01cn38Z0ed1Q2JMETve1CYErQmbp7e06n2BlP7uXu60fDNCoQlUa+NnUq70XwxUHKa1rQAE9WfEQo/PjzJlVdxP8Oaw0x3GtBWDuBlL1fD8tydYDTu//J
  template:
    metadata:
      name: github-token-torghut
      namespace: torghut
