---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: symphony-posthog-torghut
  namespace: torghut
spec:
  encryptedData:
    POSTHOG_API_KEY: AgAbEeO2mZhQGlL5MtA5vtwjIR9vESyqBMjVJXtzwSOBhcwELmjyevUu65HN34x4ZNKKzL8mkXyskq9hr8bWXx7lTO7In/+CEd0h7dOfcgYgWy5ulyH1qB7wFxPZxIWzKMuTveFALNsqfsmRtKyIjg4TtV2pJhkpW2VR+Hjo/70FvBkqZJVfu1YlGZ8Mi7Xyhfl4YSrAm2Ivo3DQsYYeUkLwxFBxcgpV2gL15iRaAVkbdoVo4EtpE8oBcZxw3zNxhgQYDgvY0jMdYe31hDYBNGqG9wX1PM7iXA/8DbLIGfclkpLo9ul28DDjYNqLxPxB5bFD9MNltvwFfhUlCHJac3A2KWdjCo2OLgZ36OMHS4b1PDMfiATvR7aEF4OC73b9/wCBuxBJTfbQmifWkNdH9e+BoMD+clqpA/ONjfcQMViKCReiKD+h/glz7/GICrhv8T707GhjV+S9lrSLz4P6PuqaXRZ9CqyAmr95oXcv/gslDNabitLGp6ywb3vVbgCk9ct/c53zzg4MfUABJsHQkY2hKLXvPHiirZDHrV72SV1JcEehuMPZHIQ79Rt6Ydbl/lT0d1mfGznldx7rfIOxxeIIl9L986UH5RUzTlMbIjTioG77FRDAxborfoxTe0OPCY9TzC3vZp4c7VfId51ht/Tut72lHZM0HO7ncRaEOp3QGOAUdYOJ3YXuidXMaP7kwbjao2ZrKb04MXC6Fl+SLNzGrqxeq1w6Kr/trpNww39kYpuUGfTywXF/JcEI6S9ybg==
    POSTHOG_PROJECT_ID: AgAefeHTJfqMZRNMfKF3YC8dwLqzvhs0M+4lrOZR19+oPXWx5epaUvBnouXbp5Y50i7NUbD8+vgFTh3zWKjfdfU9BrTMw9tqcxNUFhKBh2EJwQVt3Kh1iW9K9zVnpykiw0Ru/gEyXyKf76YTiBUa5XNOcRjZ2EjH+B2ZRrxAqxhh5cTbCv+1BT0KFgKKYrZipEpAhi5Jz9yOjk5Mxz9D36+w1g8oxtfVIMpObzYTaEHcurPpZN4OuBjIwes+yP0I25djJRN6zmSWro5MfnvB9vVir7ftpSk/U1cgFc69IpdAxv6naiRzThkUknWi5zrYYqDwTDM1RAvtQjNTHExwAGwJbL3v43Nwx47S2HEg1yVVFXlZ3vL3WfVkabv2sbg8oL4EPPcxe3LnlcnENeg6BUm3SEPpPm1icSNH8Ka1ElfbrZ6mSoqQDdt8YPGLBAw+ifTdRsM/Oe+iCleyYNDL53T50Icyn5eviiLEalwozNrEXdKPbkubsOdIAlLpzS5yE0l04AQqAUQrsvwLSTBoFIQObMBcJnT66syGmwhbMWc0/xQAcU0BxXQ3EgAScVACbkfm4a7fUedJQO731eV4a2/Vn3Uy8OQCNhcX+8PeNxNGpFup/Wq+w5ocVgbBAQauCJoYqOyx6sPnxRjDsfMEIrfLNv4SgsXt0A3mdupeAiBd+ICCnsT9EvJl8wLGOsfepaEO
  template:
    metadata:
      name: symphony-posthog-torghut
      namespace: torghut
    type: Opaque
