---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: symphony-posthog-torghut
  namespace: torghut
spec:
  encryptedData:
    POSTHOG_API_KEY: AgDXtrDO4Ny86A2Mw/IRO7HV2ZK5AOLs0V5cJubEp4SZoFHAaRaLoX0dUzWURR/SL74e7a2p8YGtasEQS1cxqmdtcrQsnZ/PWitSTRG4UzaRsXJJ3K6lyVVhvAzOikmDY8pxeXNhFdEcGpia4GDjm+6V11FiMAoxeQ1iiaukw1HMLGwI6IpcDnvvAFKSGA6EL0lpVIStFEdTzMF3qeSzBe6Pzz0FBVxB9Q4TkmEubY5znK8DXIF4Gxk/MFAAVjQpxp4rhpVPaa3gWvdtiAal1wZDt4awaFWZZd0cUtR4v1lEqN1LVe//K4j8pZS0FTGmiG9utlnUhDme1oHhxFrDcZRB1pGikYThQ9wojqxRNZZvUvW0gSnd3osdmpU2WEa3n1mjpPeLfjijryXFuo4y3DBKzw8D239B7YuMPP6myr6r8uUau9LaUKlrG40va97VngtMZxqOxT1bXR9XOJQvOZ6DA7JcCg99eBf56dFp7xmTAFzLLSOYqqFDeCG4XkLqZ5ruXv2P/pomCD38vh0qk2/NpYVP8hV5Im2nqVA7K/sWEFK+JEGdJgd9AQ2QLJyra0p9+ym+kQo2EhjdqjyPPOpy1dikHrXKNE3ewcHDgg+rVjoxewX7d1n4AjjRbqzhpnWUDSyaMSbM25taY6Q8D0EYltFQgeoYB0Migj34sIKUcllYTpTz9tIRSFuoNpmNEjY8J0ZbDVT5OtthT1ht6jne1/99l6IZS0F2hHrawLbi9kaSyDnli5rV/HSG+llFsA==
    POSTHOG_PROJECT_ID: AgATqj+eqTcuaWdckqBD60tsldfwsNBqyoVtD70HMevVO/DsroTIkqupVdt/tu2YH9cDIw0ur9aQocIQgoBjelCW+dRDvrG1RaMQf5b8nBaIOiKvn54GkxlW6tP/suNpYVUSQianbjvWi5vi9edIyvMFapbs66VaYpr7FOt3lF24arptIP1w9C0EqB/ycjPOzxsY6AYYUE6euHlOUpvg74DOQxH75NbjCbPMMb7vdhnOxe2IbrHPR+uWBrk7sTOtNoahL4Rgh8Ppvz+Sv6ySt/pGLwwytjXVQMglYUpA0koqr8nBmoBUGODLrbE3s4mxrtrlUZCno+gmQM3iFjKfOuLpZupthC0oYuEkwYt2WvXROOGPGiIWaNeqn8mwkoFH7CjQ4vtFsWRohQc5lDuba9Yjjhu2tmsXAwAK3LO5hCdEUV+iZWZPDXZKU3tBDif93oCMipdkxwcClfDN0Y58/dbzrW31FMzMvMMPw4Y2z/h6URrP7IV/+sQ312oZS1DcrbPrDcJ7iN1L+dc8olxEjqXbK77WsIhUfZHhNeIl3RfPNM3GHjGL2ZrWg6/z1sFUHfePRck4uzAxN9RIe7JrbLcZRIZOj25PaAcyTKQfluT8HlUYBFBbtLYodEBVT9OVZLYQQ9LIl1KI05FYPMKEDOu3+kizH60aoPLjSFrg9ugom2z081ge7VnwrtAtQacqdsDF
  template:
    metadata:
      name: symphony-posthog-torghut
      namespace: torghut
