---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: codex-auth
  namespace: jangar
spec:
  encryptedData:
    auth.json: AgBW6y7jovK3nbCyvdR+9KqXWQvVPttywvYGPScUUjXpnMspaselPs2ah0WAuUZ5fcYsWj8H8JJlLYbW7wc5jDmHhzCwI3skD7CuMNjMvNql3I3iGdp/p7IyVV2QHlG/Wq2fPTJTO2Gr1wOlxdgOm9BYtW5eGr7t/gIxRtwj2RiyuZkZZMFtCjYv8oX15XQzzJrNfsC6hCoDA+r8TlMF+ntlJoRD4kI6Xc6YrEa0AXxWSHogqSocDR+dHSTV4HSPUpGOemKAI+LzfdsLhXURtBbEjWkBULv233H+RDTR7pzFaDFfCcpGwiTVvi42GBuVvuf0/ZeFza334sfbMKGwHfd6Ba2ZEOLG61NXR1MLjPL4k6nM4LHyHUQJtnf8QBfHIz16GleEzXruhivOkytE7tKJeTlSBOpgb0wVD/U+Wl7B3bxtAhYlExDm+NXtaMGF0IG/Evj7ap0dXAx3+89VW0U23O14LBHjkrYivgdTkHXg0UE2jWL7mVJO2eaYw88Txoz/ABWAGiXYZUHPHS64JkbBkK2lvOKz9JJIxqlkoHdg7jRpHy1biEBXEoMavQZpeRQKAGkwggrd7vovBxCLP50ZsjL8bgpobmSt1LkJpoxTjfDtMopw6a+Jfv3re2ndyfJ6x/0gJT/tC/Ob0QV4FMfc8/EVOyztDxcuX6QxLADAFGx6Rn9IqFEIrQ4NNySA4/dMdi84uDdB0JmluyTj7sD/x3z67Kz3LM1H/BNLvtzb+y9i+SkY+lmld2QFhegnxhkzAruidlsMxmepg3IbDniMSct/UEbuSj2ysRL3HbGkqSZox/ZuVPJTaWKt0zE9dp8POLBMm3GGbwVIYhk9NpLZDNH7N4dJ0iTprp3ovT9KGlZbj4qn26apkqGHxnnS2COXbFfb91upe5d2DJa6Wk9zsLcbTM65CjvYLzyQpZNyrhAbd0smPms3vBadW90w+NPGWplQUKZ+0wUbj4ZT3m+n1rfr5QjT/YE=
  template:
    metadata:
      name: codex-auth
      namespace: jangar
