apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: torghut-command-auth
  namespace: jangar
  labels:
    app.kubernetes.io/name: jangar
    app.kubernetes.io/component: torghut-command-auth
spec:
  encryptedData:
    token: AgCcHf8RspEzhBMoWL59WgTRJVll2Qjb4GvK0gPY0W3fKyzEQ1rhH3SbXEcZug0QoZb/pA3B2qmJlRGU+Lw6wKutI41rwQrnoSEGIC7729trKH8MJt6v/MILoJlHxdc9XMuvD91n8I7gujI+AUMHve507/Az2f7obUjHYz6k53i2Wc52zGB9sdA47bonVN6lNL9XX7AR/pHz2fdDAPuDgc/RiFiQEt79GEyz5rSNqC4FgQT/UH8wqdRaBlU1xPgcybQwF/d6Ns/aeJlXZfu/CbX3IyeTw7EwCWphpn6lxAcXhOJKXpnmX+yXEcrBURsmMIKRi4OO/Q6wZyQ2akz4ebmyUtT7kTUpk2aODgr1KQ3W+P1hPZrpbM8sNIlaXOM1nj5p8dzK/VqDh18QWU107pQSt4Npq1lCOZmiirJnIRBLcxJ74PnRSPj8ZzwilWlhQwl1IPaZ/9pM2QqJUy04fiQmv/vXaUw49Y7+RaPR4uJhVwSnrZFA6N2w6xA7BcnDKNsK5M56rDcSgbpdmK5rWNbONmH8gGzYUJMMHZjm9yin6wwuDPIOBBPQHlKbnW5ZQDcl8CRVyAxde0UXO8r/nBS/7QCNB3c7o4C0Mbuv66QtUq8zY6Xv3qkaTXEi/KuEPwLyvrNhDefP07EZo4x0AgXSXekYUuFU17W83zXSB1PpMQxIqHx0kpC8rU5OkUeS7anZ63QpI1NYZKX4rkf4/yDpxmI2O3jYRcVAYhJ/FnI0FCB1M8Px0QcgnwPWLlkpncAygiZFKtE1Sh4k67Ai4aNb
  template:
    metadata:
      name: torghut-command-auth
      namespace: jangar
      labels:
        app.kubernetes.io/name: jangar
        app.kubernetes.io/component: torghut-command-auth
