apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
resources:
  - torghut-db-ca-sealedsecret.yaml
  - rook-ceph-rgw-jangar-sealedsecret.yaml
  - cnpg-jangar-db-objectbucketclaim.yaml
  - deployment.yaml
  - service.yaml
  - github-token.yaml
  - codex-auth-externalsecret.yaml
  - discord-codex-bot-sealedsecret.yaml
  - discord-success-channel-sealedsecret.yaml
  - app-tailscale-service.yaml
  - tailscale-service.yaml
  - ingressroute-jangar-k8s-private.yaml
  - ingressroute-openwebui-k8s-private.yaml
  - postgres-cluster.yaml
  - postgres-scheduled-backup.yaml
  - openwebui-redis.yaml
  - pvc-rwo.yaml
  - vscode-tailscale-service.yaml
  - alloy-rbac.yaml
  - alloy-configmap.yaml
  - alloy-service.yaml
  - alloy-deployment.yaml
  - serviceaccount.yaml
  - post-deploy-verifier-rbac.yaml
  - clusterrolebinding.yaml
  - limitrange-defaults.yaml
helmCharts:
  - name: open-webui
    repo: https://helm.openwebui.com
    version: 15.2.0
    releaseName: jangar-openwebui
    namespace: jangar
    valuesFile: openwebui-values.yaml
images:
  - name: registry.ide-newton.ts.net/lab/jangar
    newTag: sha-3c56efdb18dd108c8bf884f209f3d9de8aa52a2d
    digest: sha256:cd113cb0d7f8b0741db969d282b96c164d29ac596d11aef79741d1b03d3079df
