apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jangar
resources:
  - torghut-db-ca-sealedsecret.yaml
  - rook-ceph-rgw-jangar-sealedsecret.yaml
  - cnpg-jangar-db-objectbucketclaim.yaml
  - deployment.yaml
  - service.yaml
  - github-token.yaml
  - codex-auth-sealedsecret.yaml
  - discord-codex-bot-sealedsecret.yaml
  - discord-success-channel-sealedsecret.yaml
  - app-tailscale-service.yaml
  - tailscale-service.yaml
  - ingressroute-jangar-k8s-private.yaml
  - ingressroute-openwebui-k8s-private.yaml
  - postgres-cluster.yaml
  - postgres-scheduled-backup.yaml
  - openwebui-redis.yaml
  - pvc-rwo.yaml
  - vscode-tailscale-service.yaml
  - alloy-rbac.yaml
  - alloy-configmap.yaml
  - alloy-service.yaml
  - alloy-deployment.yaml
  - serviceaccount.yaml
  - post-deploy-verifier-rbac.yaml
  - clusterrolebinding.yaml
  - limitrange-defaults.yaml
helmCharts:
  - name: open-webui
    repo: https://helm.openwebui.com
    version: 14.2.0
    releaseName: jangar-openwebui
    namespace: jangar
    valuesFile: openwebui-values.yaml
images:
  - name: registry.ide-newton.ts.net/lab/jangar
    newTag: 84300aed
    digest: sha256:6d80d9481cfb17b6aded045e092fcc8e5cc3ca79c8c60ed1658b431b05d3e15b
