---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: torghut-db-ca
  namespace: jangar
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  encryptedData:
    ca.crt: AgB2k4cORDvI+quqm9f5D06VOv53+BMZfeR0Yzhsw24S3ZzMF6pZHrENOt83FrEfp+DQyKkx17Wwygdyi8K7dYBYhMHdzCJ7uVATvtAFi+w8XXUzyvsxbUhCRJAJVo82NIYq6YKXMedvM3D5/2NZfoH4qCO0CZL5zb+TgQ7Y7spsGmIey7T6/BVt0wHrYq297pvQNVYCX34XwquaIVbdwryfVljkHX6/Jj3xSlYFE1jTDWe5NV6QbLajjjMq3+b4xGgDZjWs6hTaTrV4fzU2zyWzB4cXMGBSPHAo2NZ2SQXNwORZBeFYgGqTPR9hXR0xFcWETCAKejHR3PgJMyxXXOOZYy95qHmfH8bqBU8hzoiFDXZE1efHUVL+DSL6G1xKTiRGkTZs2TZN7ZosVwL7Yvb2/wpcbRemGv2lrh9Ld5t73wEKwxWsOV0NmjKLfVWCBlRaoFRBoBw27UzB1QHmrdj87yOYJl+vp/GT36lfR98LbtGQdqQWgE2BRajqGRMrHN4cwbHI1kCaJ5TOm2wO2ULxGZY/6EHq4es/SgtTXBABgoj2HSfO+lZeIsPfd+9VOgCmUjm8bNn/EVc5+gCdaXpVJHGkqeEu04wQSUeBP041EJ2vPsDGwgZMhhAhHzyu6FWeWnZqzx2yHqGxj8l+wwNqb9smHjVPjCY+S+UkdSfU/NoGeKoOYRcpEpPi9J3FE2qmdizoE43pRSUsKudU+lKOGTPFJCiaqjwDhpddJjA/4vsLZkvouYT/OrNJrE2u7LNxvZbqrGCYsVf+vdj3o0/F4vQwkQ4d4R0SSTRru+3RXA7LPEVs3RigQ4fuPy3oLBfvn3zhM8nBhTpoor7pwgJbhMJw1hx2iAkyG4pRT2zvmW0jncFUfOPPU5EdIDFyiSHWsaIKcKuT+Wt8AqZ8QR4mx2iIYZy3NMmA3yku6PD/08Vl+qmeglPapH7Ics0oZ5yUQBiuUhpkmXr9bu91BMioJPqEncux82WqTWLkUjvb7AU8AGfTK6DR9zXEadiwTSlJvtBVogMAmE6OXV9fZ/P3MQHJW90r74Lm/uLu6XWeFWeL68qbLNp8CBiK916+rS1lwpaepwx3mEjsr+H+X/VfEe/8RhHHLvp+3Q8umFW3KFRRu/EEA8jXypsNMFXbkjTIjY0xTNMGCwbQq/YoE5kEqcy7Zpj0/ciGOvIrfEhs7TNDVUKWgh/eigVCiqqtNg4Oin5knJeHCTixEo/brBXDz9IN+A8kUmTFa8E1BrNJiydlLyML0DazQOFrUgniA94BtDStGvLpCI3q3FJA7urhV3jxMhFA2ph8qyIHUap2hhvoqP2ZGUDRIYnIGpLL4/7ij6L0/K2ymeryeCBjVqn5WyQTh4KTusHrCHRFM9fDknV2KTDgjjQMARcI35/Zczdcry4AMOV25c3Epe0w85x2YUXHYHjU1xVpLOuz+QuIR1rEdFlpBePjAPsRalIM4CCQfALb/G5gwkvgf2vYDq0kToJGaM8gIppYdDI=
  template:
    metadata:
      name: torghut-db-ca
      namespace: jangar
    type: Opaque
