---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: codex-devbox-access
  namespace: codex-devbox
spec:
  encryptedData:
    authorized_keys: AgAdWVjROFegTg6sZZpHrq/XDY2X5SxIjD5CZPS4oI/XzSWD/pCS7ywOLLKj1DM+LiFUZyn88k/WJw1KL0ZBCqjx1uyS5dKYNf2FbDbS0zWRuT53RQd/XdxQAy0z2mtXlYPJUznyfpDYDh8/vAbfIFl6KVestOfBmGSidlL4Boi+PTzBcCY67Gv4/7K571XEIzHw9t2Gh4XEULLs6fg5F7UbrF3uzk+ET80ybqhpUC4wehbazgPrslOOAmI79iH/CjDqAo5G2StYC9wpq6ZIX6FgJuZ+xqCSkdfOOBRZwNcOpThUfxMGF7cXrpz6iJTyChypBEG28t5UhkSTb6VmSqXP1TWAIH1Nekxj1NhQqph+2wXq9NamqyPILHWGNFFR/h2FL8wgfVby24gSWTz8PaNBF1aSjAyxwYfDxxoSNpuRCRK9gCi08LU/+NWH0+6QA8Efe1Bf4QS+LAqhbjHVSx0/CBiVzf50oGA4JG/3WDbuLIhWRuwN/aG6ydm6lnLhQgHZ3qkdYjkgP59TFmAL8P3+khLYt/QsW3naypB761Dktb3jUiqp9jzFWAGdn8MfgOppNmVlsv5rPhMwPi5UtOByzKpYFuer/by9+Alip1WxdzGiKoKUaNlxNq+s/2b0WMWLYe57s2NkT5QPQc4wViJpKmfKhZi8s6yuC6TBh/aaPy+IlSPTPR20FCPCcVHrazI2XT154uQ0c3c4kBvWLGV9zScE0+ehFF7zwCmmUY/rQLSfv4GgIUSSk0hTrFde5dbw8pqQgQrzUGSYIDpFvNdR7eL9assG1+sM+qJ8wWn/Yw==
  template:
    metadata:
      name: codex-devbox-access
      namespace: codex-devbox
