apiVersion: v1
kind: Service
metadata:
  name: codex-turin
  annotations:
    metallb.io/loadBalancerIPs: 100.100.244.183
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: codex-devbox
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
      protocol: TCP
