apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codex-turin
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes: [ReadWriteOnce]
  volumeMode: Block
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 500Gi
