apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: restate
resources:
  - serviceaccount.yaml
  - request-identity-sealedsecret.yaml
  - service-cluster.yaml
  - service.yaml
  - statefulset.yaml
  - networkpolicy.yaml
