apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restate-request-identity
  namespace: restate
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.proompteng.ai/wait-for-sealed-secret: "true"
spec:
  encryptedData:
    private.pem: AgB7g3ggr2bx8roXihBBQAicPTpuVHvercfNI9ImKtYhc2/x+K+FXbZIYWPV6rRqEfACM4zS9o18bUi5Enf23/rPpTLRASQtXiN6h0t4nwjhHb7wWI6Gyg8vSTA1YkZbalvqet8kMUcL9zpZ0UQGJrVYgzSm6ZZ7/zg20onA2mAoov36Np7LqN8Y3m3NTcrzFTnElIUBqKeCSUx0nn8nMsszqt4O7NkJRp5/dRTz/DHgojDav96htF7vtFL73TbhuaSnaQaJMxdUoWN9VaXAjmRXaDS63Ln5CmKiUURSoDX84JZ5mItmKAlQNJMZxeKwUnMQ6Rd6nDwMQksg38VxXsdG1W0p5CoxGUAZIOB/wikAVRzE2os3vB1r8peOGteP66/ET09wUcQVmEjK6asZWHhdV3DPs7zusxJo2rCovLw9KOtqIe8wd2Iygpaz2rn5juNGV65R47nmOtHjte4g4WPIGEGKpfpehDcVtKGL+svX+PQqJE+rI2aAQ1a6zf7fnMEx6sN9VieL+wispRFUdwN0DMFZMzTSlmdbvf0xmKt+KTeUu6guwAttfHmCu0Ql4Q7S7/zE9N4mZJAyrAcoQdxMUNR7p8Lwz2j92milfCSO1q5tVN5OCFgl1hvH6mWxAiFgHpNfL1QamvDhJVMpK2WwX/rPOSwFUCPoCBK1/xe0oOsayp2G8j41Zz/a5xImWpxLZ1aIrevMb7QH1PTR/UpjoXCG8X/y/6g3q1dUbB31xH/Efqh6LCRemViHNKmMz97CBSoPOBILP0ioaVXfjKFnRaBF+GKKxT4StYUsFNMcG4cTuW+H26Jg/pCtku1dyXXqH2p7s1pZcSsBJEcsWunBL9xR7TLusA==
  template:
    metadata:
      name: restate-request-identity
      namespace: restate
    type: Opaque
