---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agents-artifacts
  namespace: synthesis
  labels:
    app.kubernetes.io/part-of: synthesis
    app.kubernetes.io/component: autonomous-trader
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB/hnlPGSkR2jcYYSCnhViNtuC1VmwfAn4oQjfFWTIOVdyTqD2e/3w3BZtwrvljTm+yPNwFg+5WpdR749E5c3ED5FfmSHYGdxZESuONiindTq9gySBOStRJzQLNP5bof0eIcbTRafDdLzWyWDEAIWP5FjYTQkQ1ftNRGsdw/f4q540yZoynYkl9fbpFyDODcmB/glo9aWb3JyMk4vTO9ddKbnodBReVIJPhDNJRtpbObPqWTMXy9NeoIxsv9TxtxBgr8bbaGpxhOqOuifyRvJiIDwzv2INu0CnIslgbllytixLmbi+FcMC5pIw1qXMLDqaoeWCNdQDhd4rMlNQTbkTVbDbpAKS65uiIFrUpv/BUEsYE40ZRVUAv/O9JrygcNCK3wsbByllM8BJkDf/FQe/+CIzkJGr3H04yYN1cHh1xTDkJ9ebXC9fRvwkGUY1cYtC3NZhz4xqK5mziCbQIaV2k1LSR7WPq4sQ75A2laO0S40dJuGCYIrjMO31amVzjoAOmSbhi5d3A9IoThbdwtaX/QVGrm5mSiNIa2S2SAAOUiRhQAgqpKLCUrJ8HTF+1M0VqipjQgct0incSgzQrBlT8hJ83ao8s0tjxxajj1NRcEdXhpe0aGj0vVXISudkEDqLQHnP54yZE+Ecf12op23JHAs0f36N7gZ9UwENknL+erhQfZdsMSxnjqsFv1a77reGo8s6wEgHFJECiIUvAFWf1dDaE2A==
    AWS_SECRET_ACCESS_KEY: AgCM9lmHGxgwruzWtW3GUxVBnu0azSE79U0Wdm1yXI0h7axpgbRzXAjSGHyJ3/tUYCwMeQjyeSpJAoRDzr5IHWJERuu73OXWJCf7cAkpS8RDWjKqKk+//fguMP9YfPVUUAZh3NJkRaZfQt0Z3tNIRGex8U4F5hzXU0dWXnyyeiYXKWLFXKtglsDkrr2qYgMomZLtJ1TpfaAkblxjwO5NOyiIssslrc5N1CJOZ8FrtfHg7cBBpqTjoRgSuVdYVXkUkUKe4czXE1rX7t2Fj7esKHCBfOGuZ8qkP4TLDIvdsn23QzgfKQS8LkO78S+izi2PcXbyBA9bxPm5rI8BmVrgvU6Z5Dpy62R17+oJRq90hBOajj1uIrDLcYsRkqKv3lr5bBgGNo6Ao4uTSVOFZiSGFrQXQoi2qIcGlHoKhD8/4h06fLvTFCH8zTx3H8UXSaORAiuhuWB6/mMOG9j0FfSGuwUO5KuwMbbDgPYkgoqBEuLWvgWbZMXReH7oz7HqStqaKDn73SZamR9SmngfxUkuprNh5KfZwrHhIxqEWa80PTuGwbjg3TlogikGbo8nAD38aWk1J0NtG8jfF6JiTRj+nHziM4/cwEmQelypDoYVyrWE2DPKhHv6wvPdjqhiN6Gze870dl7doSerHtiVcouB908QcgtlrwuJH9BgpxqEYGrre8vOUyXAawLJK+7X4y1qCRwiyOIyM0hrU72v8ToyYE2KJpNytIQyLPD2EKyiuAUi7wPQajVi4lHO
  template:
    metadata:
      name: agents-artifacts
      namespace: synthesis
    type: Opaque
