---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: synthesis
  labels:
    app.kubernetes.io/part-of: synthesis
    app.kubernetes.io/component: autonomous-trader
spec:
  encryptedData:
    token: AgAl/ztdhzzQOJzpieY+vCVYxC3DfKgLDsZFW2QBe3ZVJo7rOegqdGl/bv7xWbEQXCnEl5gBlBOUx+uCJy8eMZHBMZu/BIPUqyEvZly83Xxj4PFBwM0XPcCXZKoz3HXOPTUbgF7xpVHd5EvZ8BkQVgckGi/HyLvIe8mVFaQmeK8hAqRPPpb5h9JJSu0HrJsmZ4gGgzkcxQG5r87X8RqgzAtv76UKvafbTm4KCJkaLvYvjGCbbxyViJEHWCViyV+FrYQwTZTzn0UjjAr3ozpQ419I8ObfmAXiG1s0AA3tyytaM6GjmC57Zn/WUMS57iSS2sNxKLj+sO9ilcExacORMI8YcuNeaEN3rwkkNv5fHHBjOiW9HZds/yysoE5fg8s0csF4ANqIjcYomomA/4wUqsbvqZUxvYU8B3DmnmwbJEVz0RxXJxTlJS7TndnyluJaoPVbqHtsTjvR+u6D7JV7tloKbRmlYxxQ1UsQNZRUI53LflDHG/xDopCSU8vuRB9G/1I4sinyNjlH7Cy8VOzh+k9G5+4VqOvW9MVaugAl+ZpD/zP2WxWaUK3eBFIKeSvlnPhWWBnJQTas/gJ9Io4drLDUBr546RbcSXERBjFLGJFgK3W7tlHsP8YexrlakWeH9BLaosqGCJYY3NR+tYh2sQqzgV/4bORBrq/xVV9EaNANf0+dxLc2GABrEOhyBTO38w1OFCvPVee6ajue8X+qP9Dbxev1WUoij7bd7IEas4Kb6IVIIx1B76YS
  template:
    metadata:
      name: github-token
      namespace: synthesis
    type: Opaque
