apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agents
resources:
  - torghut-swarm-implspecs.yaml
  - torghut-swarm-agentrun-templates.yaml
  - torghut-swarm-instances.yaml
  - codex-whitepaper-secretbinding.yaml
  - codex-whitepaper-agent.yaml
  - codex-spark-whitepaper-agentprovider.yaml
  - codex-whitepaper-agent-system-prompt-configmap.yaml
  - codex-research-secretbinding.yaml
  - codex-research-agent.yaml
  - codex-research-agent-system-prompt-configmap.yaml
  - torghut-health-agentprovider.yaml
  - torghut-health-agent.yaml
  - torghut-health-secretbinding.yaml
  - torghut-market-context-agentprovider.yaml
  - torghut-news-agent.yaml
  - torghut-news-agent-system-prompt-configmap.yaml
  - torghut-agentruns.yaml
  - torghut-market-context-batch.yaml
  - torghut-market-context-priorityclass.yaml
