apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oirat
resources:
  - configmap.yaml
  - discord-sealedsecret.yaml
  - deployment.yaml
  - alloy-rbac.yaml
  - alloy-configmap.yaml
  - alloy-deployment.yaml
images:
  - name: registry.ide-newton.ts.net/lab/oirat
    digest: sha256:01e5f0ea021d4f37b4164cfe9807c6ed13d2afe873b00a3ab2c0717950ec72bf
