apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oirat
resources:
- configmap.yaml
- discord-sealedsecret.yaml
- deployment.yaml
- alloy-rbac.yaml
- alloy-configmap.yaml
- alloy-deployment.yaml
images:
- name: registry.ide-newton.ts.net/lab/oirat
  digest: sha256:e022e4b0e64e3b9fd2feacd6a4972208e285c523a37f72a281f7fab0f6f74764
