apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nack
helmCharts:
  - name: nack
    repo: https://nats-io.github.io/k8s/helm/charts
    version: 0.31.1
    releaseName: nack
    namespace: nack
    includeCRDs: true
    valuesFile: ./values.yaml

images:
  - name: natsio/jetstream-controller
    newName: docker.io/natsio/jetstream-controller
    digest: sha256:940b1bc0ac23ea62b7daf1c26568acca6e606351d0950902d5e76e36dffc91cd
