apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-github-auth
  namespace: hermes
  labels:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/component: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  encryptedData:
    GH_TOKEN: AgCJE66p94JDeeHmk+K+0IFffTTnqvNno/nkcKzu4YdemiJs92+WUMwbhHs6FU8RQSIYiLl2hVoB7QvyeE0Nlc6y0RCuQAxPW1111wkFZ+NKoGvvNpFrTVr/y9ETE/3LIRMf5qpzWSLke+DZUv6+bQ+usrK4kuR+EMmLCl5bkgk2cis/wm29iFioGLU/bE5xvqKapsevcB/AO997aliOdkG0NWWBfGRqd/mzRZlcYBPLylOEsbdDhu4A4g6qdeUjpGSlr7dQ8OvPsZKSqIBCe/EJwLVyC63pTfmo0fVHuikyUqaLiiJwt8X2blil1mDpyak7A9WQYUqWOBVIn2YOx2ldM9W4/DnFJhAUkcTdCbJiNWbLIr/9ZaFcVCI/Lllo4K1e9ACkCVSME/KnsQDsDzZJj7Mj9h+9e+/uN3PKacTyQsVGbYxLqZR9ZcgW5QOR4du4M3iU7a5FwF8Q+aV6ShlN243GMrXkrSKgDoE7ZVA1u+fVanmRmw5yihS3ZKXDCg5NQnB5DWcC0YkFdA+pA0P9Lxi5v9oxASTYAjOeOBmGlhgz3aeg+aFbwpaQOqSvghOJy/nj6eWGbKjC4k109PuJ+jOvz2Vv2D9xEYlMSmioiIijnubcPhxswA8ngF0c06iIFYshOcopGqHTQKAzAUExPoMOCOQ3iGe3yoY+/NwEOkvPU3rv6XhMJw/gopkp+ewU80Ftw62BO5zCh3Jm53X1wHxJP6i9YgAUymOHmpIq/J1FLyJZ/acp
  template:
    metadata:
      name: hermes-github-auth
      namespace: hermes
      labels:
        app.kubernetes.io/name: hermes
        app.kubernetes.io/component: gateway
    type: Opaque
