apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hermes

configMapGenerator:
  - name: hermes-config
    files:
      - config.yaml
  - name: hermes-bootstrap
    files:
      - bootstrap.sh
      - backup-loop.sh
      - AGENTS.md=bootstrap/AGENTS.md
      - HEARTBEAT.md=bootstrap/HEARTBEAT.md
      - IDENTITY.md=bootstrap/IDENTITY.md
      - SOUL.md=bootstrap/SOUL.md
      - TOOLS.md=bootstrap/TOOLS.md
      - USER.md=bootstrap/USER.md
  - name: hermes-egress-proxy
    files:
      - squid.conf

resources:
  - serviceaccount.yaml
  - external-secret.yaml
  - service.yaml
  - egress-proxy.yaml
  - network-policy.yaml
  - statefulset.yaml
  - pdb.yaml
