http_port 3128

acl SSL_ports port 443
acl CONNECT method CONNECT
acl allowed_discord dstdomain .discord.com
acl allowed_discord dstdomain .discord.gg
acl allowed_discord dstdomain .discordapp.com
acl allowed_discord dstdomain .discordapp.net
acl allowed_discord dstdomain .discordcdn.com
acl allowed_discord dstdomain .discord.media
acl allowed_github dstdomain .github.com

http_access deny !CONNECT
http_access deny CONNECT !SSL_ports
http_access allow CONNECT allowed_discord
http_access allow CONNECT allowed_github
http_access deny all

cache deny all
cache_mem 32 MB
maximum_object_size 0 KB

access_log stdio:/dev/stdout
cache_log /dev/stderr
pid_filename /run/squid/squid.pid
coredump_dir /tmp
