from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F811,F821
from typing import Any
import os
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from functools import lru_cache
from pathlib import Path
from typing import Any, Mapping, Sequence, cast
from zoneinfo import ZoneInfo
import yaml
from sqlalchemy import select
from sqlalchemy.orm import Session
from ..models import (
    StrategyHypothesisMetricWindow,
    StrategyPromotionDecision,
    StrategyRuntimeLedgerBucket,
    VNextCompletionGateResult,
    VNextEmpiricalJobRun,
)
from .empirical_jobs import EMPIRICAL_JOB_TYPES, build_empirical_jobs_status
from .hypotheses import HypothesisManifest, load_hypothesis_registry
from .runtime_cost_authority import (
    cost_basis_counts_have_non_promotion_grade_costs,
    is_non_promotion_grade_runtime_cost_basis,
)
from .runtime_ledger import POST_COST_PNL_BASIS
from .runtime_ledger_source_authority import (
    build_runtime_ledger_profit_distance_readback,
    runtime_ledger_promotion_source_authority_blockers,
)

def _runtime_matrix_path(*args: Any, **kwargs: Any) -> Any: ...
def _doc_matrix_path(*args: Any, **kwargs: Any) -> Any: ...

DOC29_COMPLETION_MATRIX_RUNTIME_PATH: Any
DOC29_COMPLETION_MATRIX_DOC_PATH: Any
DOC29_COMPLETION_ENDPOINT: Any
TRACE_STATUS_SATISFIED: Any
TRACE_STATUS_BLOCKED: Any
TRACE_STATUS_STALE: Any
TRACE_STATUS_REGRESSED: Any
TRACE_STATUSES: Any
DOC29_SIMULATION_SMOKE_GATE: Any
DOC29_SIMULATION_FULL_DAY_GATE: Any
DOC29_EMPIRICAL_MANIFEST_GATE: Any
DOC29_EMPIRICAL_JOBS_GATE: Any
DOC29_PAPER_GATE: Any
DOC29_LIVE_CANARY_GATE: Any
DOC29_LIVE_SCALE_GATE: Any
US_EQUITIES_REGULAR_TIMEZONE: Any

def _as_dict(*args: Any, **kwargs: Any) -> Any: ...
def _as_list(*args: Any, **kwargs: Any) -> Any: ...
def _as_text(*args: Any, **kwargs: Any) -> Any: ...
def _safe_int(*args: Any, **kwargs: Any) -> Any: ...
def _safe_float(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_trading_day_key(*args: Any, **kwargs: Any) -> Any: ...
def _median_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _p10_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _gate_policy_parameters(*args: Any, **kwargs: Any) -> Any: ...
def _policy_int(*args: Any, **kwargs: Any) -> Any: ...
def _load_hypothesis_manifests_by_id(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_hypothesis_manifests(*args: Any, **kwargs: Any) -> Any: ...
def _manifest_runtime_session_threshold(*args: Any, **kwargs: Any) -> Any: ...
def _load_yaml_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_gate_definition(*args: Any, **kwargs: Any) -> Any: ...
def validate_doc29_completion_matrix(*args: Any, **kwargs: Any) -> Any: ...
def load_doc29_completion_matrix(*args: Any, **kwargs: Any) -> Any: ...
def runtime_and_doc_completion_matrices_match(*args: Any, **kwargs: Any) -> Any: ...
def build_completion_trace(*args: Any, **kwargs: Any) -> Any: ...
def upsert_completion_gate_result(*args: Any, **kwargs: Any) -> Any: ...
def persist_completion_trace(*args: Any, **kwargs: Any) -> Any: ...
def _latest_completion_rows(*args: Any, **kwargs: Any) -> Any: ...
def _latest_completion_rows_filtered(*args: Any, **kwargs: Any) -> Any: ...
def _latest_empirical_rows(*args: Any, **kwargs: Any) -> Any: ...
def _latest_hypothesis_windows(*args: Any, **kwargs: Any) -> Any: ...

_PromotionDecisionKey: Any

def _promotion_decision_key(*args: Any, **kwargs: Any) -> Any: ...
def _promotion_decision_key_for_window(*args: Any, **kwargs: Any) -> Any: ...
def _promotion_decision_key_for_decision(*args: Any, **kwargs: Any) -> Any: ...
def _promotion_decision_keys_for_windows(*args: Any, **kwargs: Any) -> Any: ...
def _promotion_decision_blocked_reason(*args: Any, **kwargs: Any) -> Any: ...
def _windows_with_allowed_promotion_decisions(*args: Any, **kwargs: Any) -> Any: ...

_RUNTIME_LEDGER_BUCKET_SCHEMAS: Any

def _utc(*args: Any, **kwargs: Any) -> Any: ...
def _positive_hash_count(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_promotion_payload(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_existing_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_matches_window(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_window_match_key(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_is_promotion_grade(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_summary(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_daily_summary(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_persisted_daily_summary(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_refs_for_windows(*args: Any, **kwargs: Any) -> Any: ...
def _window_gate_summary(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_empirical_jobs_gate(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_paper_gate(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_live_canary_gate(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_live_scale_gate(*args: Any, **kwargs: Any) -> Any: ...
def _effective_row_status(*args: Any, **kwargs: Any) -> Any: ...
def build_doc29_completion_status(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
