from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import hashlib
import json
import logging
import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from decimal import Decimal, ROUND_HALF_UP
from typing import Any, Iterable, Literal, Optional, cast
from ..config import settings
from ..models import Strategy
from ..strategies.catalog import extract_catalog_metadata
from .features import (
    FeatureVectorV3,
    FeatureNormalizationError,
    SignalFeatures,
    extract_signal_features,
    normalize_feature_vector_v3,
    optional_decimal,
)
from .microstructure import parse_microstructure_state
from .evaluation_trace import StrategyTrace
from .forecasting import ForecastRoutingTelemetry, build_default_forecast_router
from .models import SignalEnvelope, StrategyDecision
from .regime_hmm import (
    HMM_UNKNOWN_REGIME_ID,
    resolve_hmm_context,
    resolve_regime_route_label,
)
from .prices import MarketSnapshot, PriceFetcher
from .quote_quality import QuoteQualityPolicy
from .quantity_rules import (
    min_qty_for_symbol,
    quantize_qty_for_symbol,
    resolve_quantity_resolution,
)
from .session_context import SessionContextTracker
from .simulation import resolve_simulation_context
from .strategy_runtime import (
    AggregatedIntent,
    RuntimeErrorRecord,
    RuntimeDecision,
    RuntimeEvaluation,
    RuntimeObservation,
    StrategyRegistry,
    StrategyRuntime,
)

logger: Any
_SHORT_ENTRY_BELOW_MIN_QTY_REASON: Any
_SAME_DIRECTION_REENTRY_REASON: Any
_EXIT_ONLY_SELL_FLAT_REASON: Any
_EXIT_ONLY_BUY_FLAT_REASON: Any
_RUNTIME_TRADE_POLICY_SHARED_OWNER: Any
_SELL_EXIT_ONLY_STRATEGY_TYPES: Any
_BUY_EXIT_ONLY_STRATEGY_TYPES: Any
_MICROBAR_PAIR_EXIT_RATIONALE: Any

def _feature_vector_with_runtime_position(*args: Any, **kwargs: Any) -> Any: ...

class DecisionRuntimeTelemetry:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    mode: str
    runtime_enabled: bool
    fallback_to_legacy: bool
    errors: tuple[RuntimeErrorRecord, ...]
    observation: RuntimeObservation | None
    traces: tuple[StrategyTrace, ...]

def _runtime_position_side(*args: Any, **kwargs: Any) -> Any: ...
def _feature_vector_with_positions(*args: Any, **kwargs: Any) -> Any: ...
def _merge_runtime_counter(*args: Any, **kwargs: Any) -> Any: ...
def _merge_runtime_evaluations(*args: Any, **kwargs: Any) -> Any: ...

class _RuntimeTradePolicySessionState:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    session_day: date
    entry_count: int
    stop_loss_exit_count: int
    negative_exit_count: int
    cumulative_negative_exit_bps: Decimal
    last_stop_loss_exit_at: datetime | None
    last_negative_exit_at: datetime | None

class DecisionEngine:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def evaluate(*args: Any, **kwargs: Any) -> Any: ...
    def consume_runtime_telemetry(*args: Any, **kwargs: Any) -> Any: ...
    def consume_forecast_telemetry(*args: Any, **kwargs: Any) -> Any: ...
    def observe_signal(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_with_runtime(*args: Any, **kwargs: Any) -> Any: ...
    def _sync_position_peak_price(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_legacy(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_legacy_strategy(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_price_and_snapshot(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_forecast_payload(*args: Any, **kwargs: Any) -> Any: ...

def _build_params(*args: Any, **kwargs: Any) -> Any: ...
def _has_explicit_regime_context(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_regime_context(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_microstructure_state_payload(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_execution_advice_payload(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_execution_feature_payload(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_fragility_snapshot_payload(*args: Any, **kwargs: Any) -> Any: ...
def _snapshot_payload(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_qty(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_qty_for_aggregated(*args: Any, **kwargs: Any) -> Any: ...
def _skip_non_executable_decision_qty(*args: Any, **kwargs: Any) -> Any: ...
def _build_runtime_position_exit_overlay(*args: Any, **kwargs: Any) -> Any: ...
def _blocks_same_direction_reentry(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_uses_position_isolation(*args: Any, **kwargs: Any) -> Any: ...
def _supports_runtime_position_exit_overlay(*args: Any, **kwargs: Any) -> Any: ...
def _position_state_scope_key(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_trade_policy_key(*args: Any, **kwargs: Any) -> Any: ...
def _positions_for_strategy_action(*args: Any, **kwargs: Any) -> Any: ...
def _is_pending_entry_position(*args: Any, **kwargs: Any) -> Any: ...
def _actual_positions_only(*args: Any, **kwargs: Any) -> Any: ...
def _treats_sell_as_exit_only(*args: Any, **kwargs: Any) -> Any: ...
def _treats_buy_as_exit_only(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_exit_semantics_type(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_catalog_runtime_type(*args: Any, **kwargs: Any) -> Any: ...
def _blocks_same_direction_reentry_any(*args: Any, **kwargs: Any) -> Any: ...
def _treats_sell_as_exit_only_any(*args: Any, **kwargs: Any) -> Any: ...
def _treats_buy_as_exit_only_any(*args: Any, **kwargs: Any) -> Any: ...
def _is_entry_action_for_strategies(*args: Any, **kwargs: Any) -> Any: ...
def _is_exit_action_for_strategies(*args: Any, **kwargs: Any) -> Any: ...
def _exit_position_side_for_strategies(*args: Any, **kwargs: Any) -> Any: ...
def _same_direction_reentry_exists(*args: Any, **kwargs: Any) -> Any: ...
def _cap_requested_qty_by_symbol_cap(*args: Any, **kwargs: Any) -> Any: ...
def _cap_requested_qty_by_portfolio_gross_cap(*args: Any, **kwargs: Any) -> Any: ...
def _max_requested_qty_with_symbol_cap(*args: Any, **kwargs: Any) -> Any: ...
def _position_qty_for_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _position_qty_from_payload(*args: Any, **kwargs: Any) -> Any: ...
def _portfolio_gross_exposure(*args: Any, **kwargs: Any) -> Any: ...
def _position_value_for_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _position_avg_entry_price_for_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_min_positive_strategy_param(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_max_nonnegative_strategy_param(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_dynamic_exit_threshold_bps(*args: Any, **kwargs: Any) -> Any: ...
def _volatility_to_bps(*args: Any, **kwargs: Any) -> Any: ...
def _signal_spread_bps(*args: Any, **kwargs: Any) -> Any: ...
def _reference_exit_price(*args: Any, **kwargs: Any) -> Any: ...
def _realized_exit_bps(*args: Any, **kwargs: Any) -> Any: ...
def _passes_exit_profit_policy(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_bool_strategy_param(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_symbol_notional_cap(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_portfolio_gross_cap(*args: Any, **kwargs: Any) -> Any: ...
def _has_legacy_indicator_inputs(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_legacy_action(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_aggregated_notional_budget(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_runtime_trade_policy(*args: Any, **kwargs: Any) -> Any: ...
def _passes_runtime_trade_policy(*args: Any, **kwargs: Any) -> Any: ...
def _decision_position_exit_type(*args: Any, **kwargs: Any) -> Any: ...
def _position_exit_bypasses_min_hold(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_strategy_time_in_force(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_trade_policy_owner(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_runtime_trade_policy_session_state(*args: Any, **kwargs: Any) -> Any: ...
def _record_runtime_trade_policy_decision(*args: Any, **kwargs: Any) -> Any: ...
def _passes_signal_exit_policy(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_intent_exit_side(*args: Any, **kwargs: Any) -> Any: ...
def _default_trailing_stop_requires_structure_loss(
    *args: Any, **kwargs: Any
) -> Any: ...
def _trailing_stop_structure_loss_confirmed(*args: Any, **kwargs: Any) -> Any: ...
def _signal_spread(*args: Any, **kwargs: Any) -> Any: ...
def _signal_decimal_feature_bps(*args: Any, **kwargs: Any) -> Any: ...
def _near_touch_exit_price(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_exit_price(*args: Any, **kwargs: Any) -> Any: ...
def _position_opened_at_for_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _position_age_seconds_for_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _count_open_long_positions(*args: Any, **kwargs: Any) -> Any: ...
def _count_open_short_positions(*args: Any, **kwargs: Any) -> Any: ...
def _int_param(*args: Any, **kwargs: Any) -> Any: ...
def _bool_param(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_signal_timeframe(*args: Any, **kwargs: Any) -> Any: ...
def _coerce_timeframe(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_enabled(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
