from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import hashlib
import json
from collections import Counter
from collections.abc import Mapping, Sequence
from datetime import datetime, timedelta, timezone
from typing import Any, Literal, cast
from .runtime_ledger import POST_COST_PNL_BASIS

CAPITAL_REPLAY_BOARD_SCHEMA_VERSION: Any
EXECUTABLE_ALPHA_RECEIPTS_SCHEMA_VERSION: Any
EXECUTABLE_ALPHA_REPAIR_RECEIPT_SCHEMA_VERSION: Any
EXECUTABLE_ALPHA_REPAIR_RECEIPTS_SCHEMA_VERSION: Any
EXECUTABLE_ALPHA_SETTLEMENT_SLOT_SCHEMA_VERSION: Any
EXECUTABLE_ALPHA_SETTLEMENT_SLOTS_SCHEMA_VERSION: Any
EXECUTABLE_ALPHA_SETTLEMENT_SLOTS_REF_SCHEMA_VERSION: Any
_EXECUTABLE_ALPHA_REPAIR_DESIGN_REF: Any
_EXECUTABLE_ALPHA_SETTLEMENT_DESIGN_REF: Any
_EXECUTABLE_ALPHA_REPAIR_ROLLBACK_TARGET: Any
_EXECUTABLE_ALPHA_SETTLEMENT_ROLLBACK_TARGET: Any
_NO_DELTA_RELEASE_CONDITIONS: Any
GraduationState: Any
_DEFAULT_FRESHNESS_SECONDS: Any
_LIVE_AAPL_HYPOTHESIS: Any
_SIM_NVDA_HYPOTHESIS: Any
_BREADTH_HYPOTHESIS: Any
_REPAIR_REASON_CLASSES: Any
_REPAIR_CLASS_RANK: Any
_VALIDATION_COMMANDS_BY_CLASS: Any
_FEATURE_OR_DRIFT_REPAIR_REASONS: Any
_POST_COST_REPAIR_REASONS: Any
_CLOSED_SESSION_REPAIR_REASONS: Any
_ALPHA_RUNTIME_REPLAY_CLASS: Any
_RUNTIME_LEDGER_ECONOMIC_REPAIR_CLASS: Any
_RUNTIME_LEDGER_PAPER_PROBATION_REASON: Any
_RUNTIME_LEDGER_PAPER_PROBATION_ALLOWED_REASONS: Any
_ZERO_RUNTIME_EVIDENCE_REASONS: Any
_HARD_ALPHA_ECONOMIC_REASONS: Any
_ALPHA_RUNTIME_REPAIR_REASONS: Any

def _text(*args: Any, **kwargs: Any) -> Any: ...
def _int(*args: Any, **kwargs: Any) -> Any: ...
def _float(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _sequence(*args: Any, **kwargs: Any) -> Any: ...
def _string_list(*args: Any, **kwargs: Any) -> Any: ...
def _stable_hash(*args: Any, **kwargs: Any) -> Any: ...
def _route_records(*args: Any, **kwargs: Any) -> Any: ...
def _route_board_rows(*args: Any, **kwargs: Any) -> Any: ...
def _find_by_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _first_with_state(*args: Any, **kwargs: Any) -> Any: ...
def _proof_window(*args: Any, **kwargs: Any) -> Any: ...
def _reason_list_from_target(*args: Any, **kwargs: Any) -> Any: ...
def _repair_class_for_target(*args: Any, **kwargs: Any) -> Any: ...
def _top_alpha_repair(*args: Any, **kwargs: Any) -> Any: ...
def _receipt_by_hypothesis(*args: Any, **kwargs: Any) -> Any: ...
def _targets_from_alpha_readiness(*args: Any, **kwargs: Any) -> Any: ...
def _expected_gate_delta(*args: Any, **kwargs: Any) -> Any: ...
def _required_input_refs(*args: Any, **kwargs: Any) -> Any: ...
def _receipt_revenue_lane_rank(*args: Any, **kwargs: Any) -> Any: ...
def _receipt_target_key(*args: Any, **kwargs: Any) -> Any: ...
def _executable_alpha_repair_receipt(*args: Any, **kwargs: Any) -> Any: ...
def build_executable_alpha_repair_receipts(*args: Any, **kwargs: Any) -> Any: ...
def _zero_notional(*args: Any, **kwargs: Any) -> Any: ...
def _top_queue_item(*args: Any, **kwargs: Any) -> Any: ...
def _repair_receipt_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _selected_repair_receipt(*args: Any, **kwargs: Any) -> Any: ...
def _parse_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _routeable_candidate_count_from_evidence(*args: Any, **kwargs: Any) -> Any: ...
def _alpha_target_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _required_after_receipts(*args: Any, **kwargs: Any) -> Any: ...
def _before_routeable_candidate_count(*args: Any, **kwargs: Any) -> Any: ...
def _settlement_state(*args: Any, **kwargs: Any) -> Any: ...
def _build_executable_alpha_settlement_slot(*args: Any, **kwargs: Any) -> Any: ...
def _no_delta_debt_from_settlement_slot(*args: Any, **kwargs: Any) -> Any: ...
def _primary_remaining_blocker(*args: Any, **kwargs: Any) -> Any: ...
def build_executable_alpha_settlement_slots(*args: Any, **kwargs: Any) -> Any: ...
def compact_executable_alpha_settlement_slots(*args: Any, **kwargs: Any) -> Any: ...
def _graduation_state(*args: Any, **kwargs: Any) -> Any: ...
def _market_context_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _quant_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _empirical_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _tca_guardrail_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _capital_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _before_refs(*args: Any, **kwargs: Any) -> Any: ...
def _required_after_refs(*args: Any, **kwargs: Any) -> Any: ...
def _guardrails(*args: Any, **kwargs: Any) -> Any: ...
def _live_gate_evaluated_hypotheses(*args: Any, **kwargs: Any) -> Any: ...
def _alpha_runtime_repair_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _alpha_runtime_replay_key(*args: Any, **kwargs: Any) -> Any: ...
def _top_alpha_runtime_replay_target(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_repair_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_repair_key(*args: Any, **kwargs: Any) -> Any: ...
def _top_runtime_ledger_economic_repair_candidate(*args: Any, **kwargs: Any) -> Any: ...
def _alpha_runtime_confidence(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_paper_probation_eligible(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_economic_repair_item(*args: Any, **kwargs: Any) -> Any: ...
def _alpha_runtime_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _alpha_runtime_replay_item(*args: Any, **kwargs: Any) -> Any: ...
def _replay_item(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_replays(*args: Any, **kwargs: Any) -> Any: ...
def _receipt_for_replay(*args: Any, **kwargs: Any) -> Any: ...
def build_capital_replay_projection(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
