from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401, F811
from typing import Any
import json
import logging
import time
from datetime import datetime, timezone
from collections.abc import Mapping
from decimal import Decimal
from http.client import HTTPConnection, HTTPSConnection
from typing import Any, Optional, Protocol, cast
from urllib.parse import quote, urlencode
from urllib.parse import urlsplit
from uuid import uuid4
from ..alpaca_client import TorghutAlpacaClient
from ..config import settings
from .firewall import OrderFirewall
from .simulation_progress import active_simulation_runtime_context
from .time_source import trading_now

logger: Any

class ExecutionAdapter(Protocol):
    def name(*args: Any, **kwargs: Any) -> Any: ...
    def submit_order(*args: Any, **kwargs: Any) -> Any: ...
    def cancel_order(*args: Any, **kwargs: Any) -> Any: ...
    def cancel_all_orders(*args: Any, **kwargs: Any) -> Any: ...
    def get_order(*args: Any, **kwargs: Any) -> Any: ...
    def get_order_by_client_order_id(*args: Any, **kwargs: Any) -> Any: ...
    def list_orders(*args: Any, **kwargs: Any) -> Any: ...
    def list_positions(*args: Any, **kwargs: Any) -> Any: ...

class AlpacaExecutionAdapter:
    name: Any
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def submit_order(*args: Any, **kwargs: Any) -> Any: ...
    def cancel_order(*args: Any, **kwargs: Any) -> Any: ...
    def cancel_all_orders(*args: Any, **kwargs: Any) -> Any: ...
    def get_order(*args: Any, **kwargs: Any) -> Any: ...
    def get_order_by_client_order_id(*args: Any, **kwargs: Any) -> Any: ...
    def list_orders(*args: Any, **kwargs: Any) -> Any: ...
    def list_positions(*args: Any, **kwargs: Any) -> Any: ...

class SimulationExecutionAdapter:
    name: Any
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def _sync_runtime_context(*args: Any, **kwargs: Any) -> Any: ...
    def seed_positions_snapshot(*args: Any, **kwargs: Any) -> Any: ...
    def seed_missing_position_snapshot(*args: Any, **kwargs: Any) -> Any: ...
    def submit_order(*args: Any, **kwargs: Any) -> Any: ...
    def cancel_order(*args: Any, **kwargs: Any) -> Any: ...
    def cancel_all_orders(*args: Any, **kwargs: Any) -> Any: ...
    def get_order(*args: Any, **kwargs: Any) -> Any: ...
    def get_order_by_client_order_id(*args: Any, **kwargs: Any) -> Any: ...
    def list_orders(*args: Any, **kwargs: Any) -> Any: ...
    def list_positions(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_fill_to_positions(*args: Any, **kwargs: Any) -> Any: ...
    def _build_producer(*args: Any, **kwargs: Any) -> Any: ...
    def _publish_trade_update(*args: Any, **kwargs: Any) -> Any: ...

class LeanExecutionAdapter:
    name: Any
    _required_order_keys: Any
    _required_read_order_keys: Any
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def submit_order(*args: Any, **kwargs: Any) -> Any: ...
    def cancel_order(*args: Any, **kwargs: Any) -> Any: ...
    def cancel_all_orders(*args: Any, **kwargs: Any) -> Any: ...
    def get_order(*args: Any, **kwargs: Any) -> Any: ...
    def get_order_by_client_order_id(*args: Any, **kwargs: Any) -> Any: ...
    def list_orders(*args: Any, **kwargs: Any) -> Any: ...
    def list_positions(*args: Any, **kwargs: Any) -> Any: ...
    def get_account(*args: Any, **kwargs: Any) -> Any: ...
    def get_asset(*args: Any, **kwargs: Any) -> Any: ...
    def _request_json_with_headers(*args: Any, **kwargs: Any) -> Any: ...
    def _request_json(*args: Any, **kwargs: Any) -> Any: ...
    def _with_fallback(*args: Any, **kwargs: Any) -> Any: ...
    def evaluate_strategy_shadow(*args: Any, **kwargs: Any) -> Any: ...
    def get_observability_snapshot(*args: Any, **kwargs: Any) -> Any: ...
    def _record_observability_success(*args: Any, **kwargs: Any) -> Any: ...
    def _record_observability_failure(*args: Any, **kwargs: Any) -> Any: ...
    def _fallback_submit(*args: Any, **kwargs: Any) -> Any: ...
    def _fallback_cancel(*args: Any, **kwargs: Any) -> Any: ...
    def _fallback_cancel_all(*args: Any, **kwargs: Any) -> Any: ...
    def _fallback_get_order(*args: Any, **kwargs: Any) -> Any: ...
    def _fallback_get_order_by_client_id(*args: Any, **kwargs: Any) -> Any: ...
    def _fallback_list_orders(*args: Any, **kwargs: Any) -> Any: ...
    def _coerce_order_dict(*args: Any, **kwargs: Any) -> Any: ...
    def _validate_submit_payload(*args: Any, **kwargs: Any) -> Any: ...
    def _validate_read_order_payload(*args: Any, **kwargs: Any) -> Any: ...
    def _request_and_validate_order_list(*args: Any, **kwargs: Any) -> Any: ...

def build_execution_adapter(*args: Any, **kwargs: Any) -> Any: ...
def _build_simulation_execution_adapter(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_simulated_fill_price(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_simulated_filled_qty(*args: Any, **kwargs: Any) -> Any: ...
def _first_nonnegative_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _simulated_order_status(*args: Any, **kwargs: Any) -> Any: ...
def _simulated_trade_update_event(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_simulation_event_ts(*args: Any, **kwargs: Any) -> Any: ...
def _float_to_order_text(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_to_order_text(*args: Any, **kwargs: Any) -> Any: ...
def _signed_decimal_to_text(*args: Any, **kwargs: Any) -> Any: ...
def _optional_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _positive_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _signed_position_market_value(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_simulation_context_payload(*args: Any, **kwargs: Any) -> Any: ...
def _error_summary(*args: Any, **kwargs: Any) -> Any: ...
def _is_http_status_error(*args: Any, **kwargs: Any) -> Any: ...
def _classify_fallback_reason(*args: Any, **kwargs: Any) -> Any: ...
def _classify_failure_taxonomy(*args: Any, **kwargs: Any) -> Any: ...
def _http_request_text(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
