from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
from dataclasses import dataclass, replace
from datetime import timezone
from decimal import Decimal, ROUND_HALF_UP
from typing import Any, Iterable, Mapping, Optional, cast
from ..config import settings
from ..models import Strategy
from .costs import CostModelConfig, CostModelInputs, OrderIntent, TransactionCostModel
from .microstructure import (
    MicrostructureStateV5,
    is_microstructure_stale,
    parse_execution_advice,
    parse_microstructure_state,
)
from .models import StrategyDecision
from .prices import MarketSnapshot, resolve_execution_reference_price
from .quantity_rules import (
    min_qty_for_symbol,
    qty_has_valid_increment,
    quantize_qty_for_symbol,
    resolve_quantity_resolution,
)
from .tca import AdaptiveExecutionPolicyDecision

DEFAULT_EXECUTION_SECONDS: Any
ADAPTIVE_PARTICIPATION_RATE_FLOOR: Any
ADAPTIVE_EXECUTION_SECONDS_MIN: Any
ADAPTIVE_EXECUTION_SECONDS_MAX: Any
MICROSTRUCTURE_PARTICIPATION_FLOOR: Any
MICROSTRUCTURE_EXECUTION_SCALE_MIN: Any
MICROSTRUCTURE_EXECUTION_SCALE_MAX: Any
MICROSTRUCTURE_SPREAD_BPS_PRESSURE: Any
MICROSTRUCTURE_DEPTH_USD_PRESSURE: Any
MICROSTRUCTURE_HAZARD_PRESSURE: Any
MICROSTRUCTURE_CRUMBLING_QUOTE_PROBABILITY_PRESSURE: Any
MICROSTRUCTURE_LATENCY_PRESSURE_MS: Any
MICROSTRUCTURE_STRESSED_RATE_SCALE: Any
MICROSTRUCTURE_COMPRESSED_RATE_SCALE: Any
MICROSTRUCTURE_HIGH_SPREAD_RATE_SCALE: Any
MICROSTRUCTURE_HAZARD_RATE_SCALE: Any
MICROSTRUCTURE_CRUMBLING_QUOTE_RATE_SCALE: Any
MICROSTRUCTURE_LOW_DEPTH_RATE_SCALE: Any
MICROSTRUCTURE_STRESS_EXECUTION_SCALE: Any
MICROSTRUCTURE_PRESSURE_EXECUTION_SCALE: Any
MICROSTRUCTURE_CRUMBLING_QUOTE_EXECUTION_SCALE: Any
MICROSTRUCTURE_EXECUTION_SCALE_EPSILON: Any
HIGH_CONVICTION_MARKET_SPREAD_BPS_MAX: Any
HIGH_CONVICTION_BREAKOUT_CONTINUATION_RANK_MIN: Any
HIGH_CONVICTION_BREAKOUT_MICROPRICE_BPS_MIN: Any
HIGH_CONVICTION_WASHOUT_REVERSAL_RANK_MIN: Any
HIGH_CONVICTION_WASHOUT_MICROPRICE_BPS_MIN: Any
_SIZING_LIMITING_CONSTRAINT_REASONS: frozenset[str]

class ExecutionPolicyConfig:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    min_notional: Optional[Decimal]
    max_notional: Optional[Decimal]
    max_participation_rate: Decimal
    allow_shorts: bool
    kill_switch_enabled: bool
    prefer_limit: bool
    max_retries: int
    backoff_base_seconds: float
    backoff_multiplier: float
    backoff_max_seconds: float

class AdaptiveExecutionApplication:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    decision: AdaptiveExecutionPolicyDecision
    applied: bool
    reason: str
    def as_payload(*args: Any, **kwargs: Any) -> Any: ...

class ExecutionPolicyOutcome:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    approved: bool
    decision: StrategyDecision
    reasons: list[str]
    notional: Optional[Decimal]
    participation_rate: Optional[Decimal]
    retry_delays: list[float]
    impact_assumptions: dict[str, Any]
    selected_order_type: str
    adaptive: AdaptiveExecutionApplication | None
    advisor_metadata: dict[str, Any]
    microstructure_metadata: dict[str, Any]
    def params_update(*args: Any, **kwargs: Any) -> Any: ...

class ExecutionPolicy:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def evaluate(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_allocator_participation_override(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_qty_and_notional(*args: Any, **kwargs: Any) -> Any: ...
    def _estimate_execution_costs(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_adaptive_application(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_microstructure_state(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_microstructure_config(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_microstructure_order_type(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_adaptive_config(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_advisor(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_advisor_order_type(*args: Any, **kwargs: Any) -> Any: ...
    def _sanitize_config(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_config(*args: Any, **kwargs: Any) -> Any: ...
    def _select_order_type(*args: Any, **kwargs: Any) -> Any: ...

def _should_keep_market_order_for_high_conviction_entry(
    *args: Any, **kwargs: Any
) -> Any: ...
def _should_keep_market_order_for_pair_runtime_exit(
    *args: Any, **kwargs: Any
) -> Any: ...
def _decision_strategy_runtime_types(*args: Any, **kwargs: Any) -> Any: ...
def _decision_execution_features(*args: Any, **kwargs: Any) -> Any: ...
def _decision_spread_bps(*args: Any, **kwargs: Any) -> Any: ...
def _decision_rationale_tokens(*args: Any, **kwargs: Any) -> Any: ...
def _near_touch_limit_price(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_price_for_trading(*args: Any, **kwargs: Any) -> Any: ...
def _tick_size_for_price(*args: Any, **kwargs: Any) -> Any: ...
def _build_retry_delays(*args: Any, **kwargs: Any) -> Any: ...
def should_retry_order_error(*args: Any, **kwargs: Any) -> Any: ...
def _build_impact_inputs(*args: Any, **kwargs: Any) -> Any: ...
def _combined_execution_seconds_scale(*args: Any, **kwargs: Any) -> Any: ...
def _build_impact_assumptions(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_price(*args: Any, **kwargs: Any) -> Any: ...
def _position_summary(*args: Any, **kwargs: Any) -> Any: ...
def _is_short_increasing(*args: Any, **kwargs: Any) -> Any: ...
def _is_position_reducing(*args: Any, **kwargs: Any) -> Any: ...
def _prechecked_reducing_position_qty(*args: Any, **kwargs: Any) -> Any: ...
def _quantity_resolution_matches_decision(*args: Any, **kwargs: Any) -> Any: ...
def _coerce_optional_bool(*args: Any, **kwargs: Any) -> Any: ...
def _optional_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _allocator_payload(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_qty_below_min_reason(*args: Any, **kwargs: Any) -> Any: ...
def _stringify_decimal(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
