from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import json
from collections import Counter
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from threading import Lock
from typing import Any, Literal, cast
from urllib.request import Request, urlopen
import yaml
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator
from ..config import settings
from .runtime_ledger import EXACT_REPLAY_LEDGER_SCHEMA_VERSION, POST_COST_PNL_BASIS

HypothesisState: Any
CapitalStage: Any
DependencyQuorumDecision: Any
_KNOWN_DEPENDENCY_CAPABILITIES: Any
_JANGAR_QUORUM_CACHE_LOCK: Any
_JANGAR_QUORUM_CACHE: dict[str, object]

def _stable_string_list(*args: Any, **kwargs: Any) -> Any: ...
def _coerce_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _optional_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _sequence(*args: Any, **kwargs: Any) -> Any: ...
def _optional_int(*args: Any, **kwargs: Any) -> Any: ...
def _optional_bool(*args: Any, **kwargs: Any) -> Any: ...
def _first_matching_reason(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_route_evidence_collection_readiness(*args: Any, **kwargs: Any) -> Any: ...
def _parse_iso8601(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_to_string(*args: Any, **kwargs: Any) -> Any: ...

_CAPITAL_STAGE_RANK: Any
_KNOWN_RUNTIME_LEDGER_SCHEMA_VERSIONS: Any
_RUNTIME_LEDGER_PROVENANCE_REASONS: Any
_EVIDENCE_REFRESH_REASONS: Any
_SAMPLE_REASONS: Any
_EDGE_OR_COST_REASONS: Any
_DEPENDENCY_REASONS: Any

def _normalize_dependency_capability(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_required_dependency_capabilities(*args: Any, **kwargs: Any) -> Any: ...
def _is_dependency_required(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_blocker_class(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_blocker_rank(*args: Any, **kwargs: Any) -> Any: ...
def _ranked_candidate_dossiers(*args: Any, **kwargs: Any) -> Any: ...
def hypothesis_registry_requires_dependency_capability(
    *args: Any, **kwargs: Any
) -> Any: ...
def resolve_hypothesis_dependency_quorum(*args: Any, **kwargs: Any) -> Any: ...

class HypothesisEntryRequirements(BaseModel):
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    model_config: Any
    max_signal_lag_seconds: int | None
    max_no_signal_streak: int | None
    max_market_context_freshness_seconds: int | None
    max_evidence_age_minutes: int | None
    min_feature_batch_rows: int
    require_feature_rows: bool
    require_drift_checks: bool
    require_evidence_continuity: bool
    require_delay_adjusted_depth_stress: bool
    min_delay_adjusted_depth_stress_checks: int
    max_delay_adjusted_depth_stress_age_minutes: int | None
    required_dependency_quorum: Literal["allow", "allow_or_delay"]

class HypothesisManifest(BaseModel):
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    model_config: Any
    schema_version: Literal["torghut.hypothesis-manifest.v1"]
    hypothesis_id: str
    lane_id: str
    strategy_family: str
    candidate_id: str | None
    paper_probation_candidate_ids: list[str]
    strategy_id: str | None
    dataset_snapshot_ref: str | None
    initial_state: Literal["shadow", "blocked"]
    market_regimes: list[str]
    required_feature_sets: list[str]
    required_dependency_capabilities: list[str]
    segment_dependencies: list[str]
    evidence_universe_symbols: list[str]
    require_pair_balance: bool
    expected_gross_edge_bps: Decimal
    max_allowed_slippage_bps: Decimal
    min_sample_count_for_live_canary: int
    min_sample_count_for_scale_up: int
    max_rolling_drawdown_bps: Decimal
    rollback_triggers: list[str]
    promotion_gates: list[str]
    entry_requirements: HypothesisEntryRequirements
    def _normalize_list(*args: Any, **kwargs: Any) -> Any: ...
    def _require_text(*args: Any, **kwargs: Any) -> Any: ...
    def _normalize_optional_text(*args: Any, **kwargs: Any) -> Any: ...
    def _normalize_symbol_universe(*args: Any, **kwargs: Any) -> Any: ...

class HypothesisRegistryLoadResult:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    path: str | None
    loaded: bool
    items: list[HypothesisManifest]
    errors: list[str]

def _empty_payload_dict(*args: Any, **kwargs: Any) -> Any: ...
def _empty_payload_dict_list(*args: Any, **kwargs: Any) -> Any: ...

class JangarDependencyQuorumStatus:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    decision: DependencyQuorumDecision
    reasons: list[str]
    message: str
    stage_trust: dict[str, object]
    stage_renewal_bonds: list[dict[str, object]]
    controller_ingestion_settlement: dict[str, object]
    verify_trust_foreclosure_board: dict[str, object]
    repair_slot_escrow: dict[str, object]
    stage_debt_repair_admission: dict[str, object]
    foreclosure_carry_rollout_witness: dict[str, object]
    generated_at: str | None
    def as_payload(*args: Any, **kwargs: Any) -> Any: ...

def _as_payload_dict(*args: Any, **kwargs: Any) -> Any: ...
def _as_payload_dict_list(*args: Any, **kwargs: Any) -> Any: ...
def _extract_stage_trust(*args: Any, **kwargs: Any) -> Any: ...
def _extract_stage_renewal_bonds(*args: Any, **kwargs: Any) -> Any: ...
def _extract_controller_ingestion_settlement(*args: Any, **kwargs: Any) -> Any: ...
def _extract_verify_trust_foreclosure_board(*args: Any, **kwargs: Any) -> Any: ...
def _extract_repair_slot_escrow(*args: Any, **kwargs: Any) -> Any: ...
def _extract_stage_debt_repair_admission(*args: Any, **kwargs: Any) -> Any: ...
def _extract_foreclosure_carry_rollout_witness(*args: Any, **kwargs: Any) -> Any: ...

class _TcaReadinessInputs:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    order_count: int
    avg_abs_slippage_bps: Decimal
    avg_realized_shortfall_bps: Decimal
    last_computed_at: datetime | None
    route_filter_applied: bool
    routeable_symbols: tuple[str, ...]
    route_repair_symbols: tuple[str, ...]
    route_excluded_symbol_count: int
    route_missing_symbol_count: int
    route_blocking_reason_codes: tuple[str, ...]
    route_symbol_diagnostics: tuple[dict[str, object], ...]

_NON_AUTHORITY_TCA_SOURCE_KINDS: Any
_NON_AUTHORITY_TCA_DECISION_MODES: Any

class _RuntimeLedgerReadinessInputs:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    proof_present: bool
    candidate_id: str | None
    observed_stage: str | None
    runtime_strategy_name: str | None
    strategy_family: str | None
    fill_count: int
    submitted_order_count: int
    closed_trade_count: int
    open_position_count: int
    filled_notional: Decimal
    net_strategy_pnl_after_costs: Decimal
    post_cost_expectancy_bps: Decimal | None
    bucket_started_at: datetime | None
    bucket_ended_at: datetime | None
    blockers: tuple[str, ...]
    execution_policy_hash_count: int
    cost_model_hash_count: int
    lineage_hash_count: int
    ledger_schema_version: str | None
    pnl_basis: str | None

class _DelayAdjustedDepthStressInputs:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    check_count: int
    passed: bool | None
    checked_at: datetime | None
    report_id: str | None

def _weighted_decimal_average(*args: Any, **kwargs: Any) -> Any: ...
def _latest_tca_timestamp(*args: Any, **kwargs: Any) -> Any: ...
def _normalized_route_token(*args: Any, **kwargs: Any) -> Any: ...
def _route_tca_text(*args: Any, **kwargs: Any) -> Any: ...
def _route_tca_bool(*args: Any, **kwargs: Any) -> Any: ...
def _manifest_pair_contract_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _route_tca_target_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _route_tca_authority_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _route_tca_adverse_slippage(*args: Any, **kwargs: Any) -> Any: ...
def _route_tca_diagnostic(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_delay_adjusted_depth_stress_inputs(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_tca_readiness_inputs(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_rows_for_hypothesis(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_text(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_target_token(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_target_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_row_rank(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_latest_row(*args: Any, **kwargs: Any) -> Any: ...
def _hash_count(*args: Any, **kwargs: Any) -> Any: ...
def _dedupe_runtime_ledger_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_provenance_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_window_bound_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_runtime_ledger_readiness_inputs(*args: Any, **kwargs: Any) -> Any: ...
def resolve_hypothesis_registry_path(*args: Any, **kwargs: Any) -> Any: ...
def _load_manifest_payload(*args: Any, **kwargs: Any) -> Any: ...
def load_hypothesis_registry(*args: Any, **kwargs: Any) -> Any: ...
def validate_hypothesis_registry_from_settings(*args: Any, **kwargs: Any) -> Any: ...
def _fallback_quorum_from_legacy_status(*args: Any, **kwargs: Any) -> Any: ...
def load_jangar_dependency_quorum(*args: Any, **kwargs: Any) -> Any: ...
def compile_hypothesis_runtime_statuses(*args: Any, **kwargs: Any) -> Any: ...
def summarize_hypothesis_runtime_statuses(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
