from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Literal, Mapping

class IntradayTsmomThresholdProfile:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    bullish_hist_min: Decimal
    bullish_hist_cap: Decimal | None
    bearish_hist_min: Decimal
    min_bull_rsi: Decimal
    max_bull_rsi: Decimal
    min_bear_rsi: Decimal | None
    max_bear_rsi: Decimal | None
    vol_floor: Decimal | None
    vol_ceil: Decimal | None
    bearish_hist_cap: Decimal | None
    low_vol_bonus_threshold: Decimal | None
    max_price_above_ema12_bps: Decimal | None
    min_price_below_ema12_bps: Decimal | None
    max_price_below_ema12_bps: Decimal | None

class IntradayTsmomEvaluation:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    direction: Literal["long", "short"]
    confidence: Decimal
    rationale: tuple[str, ...]
    macd_hist: Decimal
    thresholds: IntradayTsmomThresholdProfile

_ONE_SECOND_PROFILE: Any
_DEFAULT_PROFILE: Any

def validate_intraday_tsmom_params(*args: Any, **kwargs: Any) -> Any: ...
def resolve_intraday_tsmom_thresholds(*args: Any, **kwargs: Any) -> Any: ...
def evaluate_intraday_tsmom_signal(*args: Any, **kwargs: Any) -> Any: ...
def _price_within_entry_band(*args: Any, **kwargs: Any) -> Any: ...
def _profile_for_timeframe(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_timeframe(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_param(*args: Any, **kwargs: Any) -> Any: ...
def _optional_decimal_param(*args: Any, **kwargs: Any) -> Any: ...
def _decimal(*args: Any, **kwargs: Any) -> Any: ...
def _minute_param(*args: Any, **kwargs: Any) -> Any: ...
def _validate_optional_minute_param(*args: Any, **kwargs: Any) -> Any: ...
def _within_entry_window(*args: Any, **kwargs: Any) -> Any: ...
def _validate_optional_decimal_param(*args: Any, **kwargs: Any) -> Any: ...
def _validate_optional_rsi_param(*args: Any, **kwargs: Any) -> Any: ...
def _volatility_within_budget(*args: Any, **kwargs: Any) -> Any: ...
def _spread_bps(*args: Any, **kwargs: Any) -> Any: ...
def _rsi_within_bearish_bounds(*args: Any, **kwargs: Any) -> Any: ...
def _optional_min_threshold(*args: Any, **kwargs: Any) -> Any: ...
def _optional_max_threshold(*args: Any, **kwargs: Any) -> Any: ...
def _weighted_average_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _session_minutes_elapsed(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_live_continuation_rank(*args: Any, **kwargs: Any) -> Any: ...
def _decayed_minimum(*args: Any, **kwargs: Any) -> Any: ...
def _isolated_continuation_strength_confirmed(*args: Any, **kwargs: Any) -> Any: ...
def _relax_floor_for_isolated_strength(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
