from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F811,F821
from typing import Any
import hashlib
import json
import logging
import uuid
from dataclasses import dataclass, replace
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Callable, Mapping, cast
from sqlalchemy import exists, func, or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session
from sqlalchemy.sql.elements import ColumnElement
from ..config import settings
from ..models import (
    Execution,
    ExecutionOrderEvent,
    OrderFeedConsumerCursor,
    OrderFeedSourceWindow,
    TradeDecision,
    coerce_json_payload,
)
from .tca import upsert_execution_tca_metric
from .tigerbeetle_journal import TigerBeetleLedgerJournal
from .tigerbeetle_reconcile import reconcile_tigerbeetle_transfers

logger: Any
ORDER_FEED_SOURCE_REVISION: Any
HISTORICAL_ORDER_EVENT_SOURCE_WINDOW_REVISION: Any
FILL_QUANTITY_BASIS_CUMULATIVE_TO_DELTA: Any
FILL_QUANTITY_BASIS_CUMULATIVE_NON_INCREASING: Any
_FILL_EVENT_TYPES: Any
EXECUTION_RAW_ORDER_SOURCE_WINDOW_REVISION: Any
EXECUTION_RAW_ORDER_SOURCE_TOPIC: Any
EXECUTION_RAW_ORDER_SOURCE_PARTITION: Any

class NormalizedOrderEvent:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    event_fingerprint: str
    source_topic: str
    source_partition: int | None
    source_offset: int | None
    alpaca_account_label: str
    feed_seq: int | None
    event_ts: datetime | None
    symbol: str | None
    alpaca_order_id: str | None
    client_order_id: str | None
    execution_correlation_id: str | None
    event_type: str | None
    status: str | None
    qty: Decimal | None
    filled_qty: Decimal | None
    filled_qty_delta: Decimal | None
    avg_fill_price: Decimal | None
    filled_notional_delta: Decimal | None
    fill_quantity_basis: str | None
    raw_event: dict[str, Any]

class NormalizationResult:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    event: NormalizedOrderEvent | None
    drop_reason: str | None
    account_label_explicit: bool

class _IngestRecordOutcome:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    durable: bool
    commit_allowed: bool

class _ExecutionLinkageResolution:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    execution: Execution | None
    blockers: tuple[str, ...]

class _TradeDecisionLinkageResolution:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    trade_decision: TradeDecision | None
    blockers: tuple[str, ...]

class OrderFeedIngestor:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def ingest_once(*args: Any, **kwargs: Any) -> Any: ...
    def _reconcile_tigerbeetle_if_enabled(*args: Any, **kwargs: Any) -> Any: ...
    def _new_counters(*args: Any, **kwargs: Any) -> Any: ...
    def _preconditions_met(*args: Any, **kwargs: Any) -> Any: ...
    def _poll_records(*args: Any, **kwargs: Any) -> Any: ...
    def _ingest_record(*args: Any, **kwargs: Any) -> Any: ...
    def close(*args: Any, **kwargs: Any) -> Any: ...
    def _ensure_consumer(*args: Any, **kwargs: Any) -> Any: ...
    def _manual_assignment_required(*args: Any, **kwargs: Any) -> Any: ...
    def _assign_manual_partitions(*args: Any, **kwargs: Any) -> Any: ...
    def _build_consumer(*args: Any, **kwargs: Any) -> Any: ...

def _source_topic_from_record(*args: Any, **kwargs: Any) -> Any: ...
def _create_order_feed_source_window(*args: Any, **kwargs: Any) -> Any: ...
def _broker_high_watermark_from_record(*args: Any, **kwargs: Any) -> Any: ...
def _classify_source_window_drop(*args: Any, **kwargs: Any) -> Any: ...
def _classify_source_window_unhandled_failure(*args: Any, **kwargs: Any) -> Any: ...
def _source_window_failure_reason(*args: Any, **kwargs: Any) -> Any: ...
def _increment_drop_counter(*args: Any, **kwargs: Any) -> Any: ...
def _classify_source_window_event(*args: Any, **kwargs: Any) -> Any: ...
def _source_window_source_identity_payload(*args: Any, **kwargs: Any) -> Any: ...
def _source_window_source_identity_payload_for_values(
    *args: Any, **kwargs: Any
) -> Any: ...
def _raw_record_source_evidence_payload(*args: Any, **kwargs: Any) -> Any: ...
def _order_event_evidence_payload(*args: Any, **kwargs: Any) -> Any: ...
def _raw_event_with_linkage_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _order_event_linkage_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _missing_linkage_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _order_event_account_label_alias(*args: Any, **kwargs: Any) -> Any: ...
def _mark_order_event_account_alias(*args: Any, **kwargs: Any) -> Any: ...
def _order_event_client_identity(*args: Any, **kwargs: Any) -> Any: ...
def _order_event_execution_correlation_identity(*args: Any, **kwargs: Any) -> Any: ...
def _execution_correlation_identity_from_payload(*args: Any, **kwargs: Any) -> Any: ...
def _order_identity_payload(*args: Any, **kwargs: Any) -> Any: ...
def _lifecycle_payload(*args: Any, **kwargs: Any) -> Any: ...
def _dedupe(*args: Any, **kwargs: Any) -> Any: ...
def _source_window_event_status_reason(*args: Any, **kwargs: Any) -> Any: ...
def normalize_order_feed_record(*args: Any, **kwargs: Any) -> Any: ...
def _event_with_default_account_label_if_in_scope(*args: Any, **kwargs: Any) -> Any: ...
def _fingerprint_normalized_order_event(*args: Any, **kwargs: Any) -> Any: ...
def _order_identity_matches_account_scope(*args: Any, **kwargs: Any) -> Any: ...
def persist_order_event(*args: Any, **kwargs: Any) -> Any: ...
def _journal_tigerbeetle_order_event(*args: Any, **kwargs: Any) -> Any: ...
def apply_order_event_to_execution(*args: Any, **kwargs: Any) -> Any: ...
def _fill_delta_fields(*args: Any, **kwargs: Any) -> Any: ...
def _is_fill_event(*args: Any, **kwargs: Any) -> Any: ...
def merge_execution_raw_order_update(*args: Any, **kwargs: Any) -> Any: ...
def latest_order_event_for_execution(*args: Any, **kwargs: Any) -> Any: ...
def link_order_events_to_execution(*args: Any, **kwargs: Any) -> Any: ...
def repair_order_feed_execution_links(*args: Any, **kwargs: Any) -> Any: ...
def repair_order_feed_execution_states(*args: Any, **kwargs: Any) -> Any: ...
def repair_order_feed_fill_deltas(*args: Any, **kwargs: Any) -> Any: ...
def backfill_order_feed_source_windows(*args: Any, **kwargs: Any) -> Any: ...
def backfill_order_feed_events_from_executions(*args: Any, **kwargs: Any) -> Any: ...
def _execution_order_event_exists_for_execution_clause(
    *args: Any, **kwargs: Any
) -> Any: ...
def _execution_activity_timestamp(*args: Any, **kwargs: Any) -> Any: ...
def _execution_activity_at(*args: Any, **kwargs: Any) -> Any: ...
def _order_event_identity_clauses(*args: Any, **kwargs: Any) -> Any: ...
def _event_precedes_order_event(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_source_window_for_event(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_execution_linkage_for_identity(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_trade_decision_linkage_for_identity(*args: Any, **kwargs: Any) -> Any: ...
def _find_existing_source_window_for_event(*args: Any, **kwargs: Any) -> Any: ...
def _create_historical_source_window_for_event(*args: Any, **kwargs: Any) -> Any: ...
def _create_execution_backfill_source_window(*args: Any, **kwargs: Any) -> Any: ...
def _execution_backfill_order_event(*args: Any, **kwargs: Any) -> Any: ...
def _execution_backfill_event_type(*args: Any, **kwargs: Any) -> Any: ...
def _execution_backfill_raw_event(*args: Any, **kwargs: Any) -> Any: ...
def _source_offset_in_use(*args: Any, **kwargs: Any) -> Any: ...
def _stable_execution_source_offset(*args: Any, **kwargs: Any) -> Any: ...
def _event_timestamp_for_source_window(*args: Any, **kwargs: Any) -> Any: ...
def _ensure_aware_utc(*args: Any, **kwargs: Any) -> Any: ...
def _isoformat_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _cross_dsn_linkage_counts_for_source_window(*args: Any, **kwargs: Any) -> Any: ...
def _refresh_source_window_linkage_counts(*args: Any, **kwargs: Any) -> Any: ...
def _order_event_has_failed_unhandled_source_window(
    *args: Any, **kwargs: Any
) -> Any: ...
def _retry_failed_duplicate_order_event_application(
    *args: Any, **kwargs: Any
) -> Any: ...
def _extract_trade_update_payload(*args: Any, **kwargs: Any) -> Any: ...
def _decode_json_payload(*args: Any, **kwargs: Any) -> Any: ...
def _decode_json_text_payload(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_decoded_payload(*args: Any, **kwargs: Any) -> Any: ...
def _flatten_poll_records(*args: Any, **kwargs: Any) -> Any: ...
def _order_feed_cursor_consumer_group(*args: Any, **kwargs: Any) -> Any: ...
def _kafka_consumer_group_id(*args: Any, **kwargs: Any) -> Any: ...
def _consumer_commit_enabled(*args: Any, **kwargs: Any) -> Any: ...
def _latest_persisted_source_offsets(*args: Any, **kwargs: Any) -> Any: ...
def _upsert_order_feed_consumer_cursor(*args: Any, **kwargs: Any) -> Any: ...
def _upsert_cursor_and_count(*args: Any, **kwargs: Any) -> Any: ...
def _upsert_order_feed_consumer_cursor_from_source(
    *args: Any, **kwargs: Any
) -> Any: ...
def _coerce_text(*args: Any, **kwargs: Any) -> Any: ...
def _coerce_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _coerce_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _coerce_int(*args: Any, **kwargs: Any) -> Any: ...
def _as_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _is_stale_by_seq(*args: Any, **kwargs: Any) -> Any: ...
def _is_stale_by_ts(*args: Any, **kwargs: Any) -> Any: ...
def _update_trade_decision_from_execution(*args: Any, **kwargs: Any) -> Any: ...
def _commit_consumer(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
