from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import json
import time
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from hashlib import sha256
from http.client import HTTPConnection, HTTPSConnection
from typing import Any, cast
from urllib.parse import urlsplit
from sqlalchemy import select
from sqlalchemy.orm import Session
from ..config import settings
from ..models import Strategy, TradeDecision, coerce_json_payload
from .runtime_decision_authority import (
    BOUNDED_PAPER_ROUTE_COLLECTION_SOURCE_DECISION_MODE,
    source_decision_mode_is_profit_proof_eligible,
)

PAPER_ROUTE_MATERIALIZATION_SCHEMA_VERSION: Any
PAPER_ROUTE_MATERIALIZATION_ACCOUNT_LABEL: Any
PAPER_ROUTE_MATERIALIZATION_STAGE: Any
PAPER_ROUTE_MATERIALIZATION_SOURCE: Any
PAPER_ROUTE_MATERIALIZATION_FINAL_PROMOTION_BLOCKERS: Any
PAPER_ROUTE_MATERIALIZATION_HPAIRS_HYPOTHESIS_ID: Any
PAPER_ROUTE_TARGET_NOTIONAL_SOURCE_DECISION_SEED_QTY: Any

def _to_str_map(*args: Any, **kwargs: Any) -> Any: ...
def mapping_items(*args: Any, **kwargs: Any) -> Any: ...
def paper_route_target_plan_targets(*args: Any, **kwargs: Any) -> Any: ...
def _target_plan_from_proofs_payload(*args: Any, **kwargs: Any) -> Any: ...
def _target_from_proof_identity(*args: Any, **kwargs: Any) -> Any: ...
def _probe_symbol_values_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _target_probe_symbol_values(*args: Any, **kwargs: Any) -> Any: ...
def _target_source_decision_ready(*args: Any, **kwargs: Any) -> Any: ...
def _target_identity_value(*args: Any, **kwargs: Any) -> Any: ...
def _target_identity_keys(*args: Any, **kwargs: Any) -> Any: ...
def _target_plan_selected_identity_match(*args: Any, **kwargs: Any) -> Any: ...
def _source_collection_marker(*args: Any, **kwargs: Any) -> Any: ...
def _target_plan_is_source_collection_only(*args: Any, **kwargs: Any) -> Any: ...
def _target_plan_selection_score(*args: Any, **kwargs: Any) -> Any: ...
def paper_route_target_plan_from_payload(*args: Any, **kwargs: Any) -> Any: ...
def fetch_paper_route_target_plan_url(*args: Any, **kwargs: Any) -> Any: ...
def _fetch_paper_route_target_plan_url_once(*args: Any, **kwargs: Any) -> Any: ...
def paper_route_target_plan_probe_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _safe_text(*args: Any, **kwargs: Any) -> Any: ...
def _safe_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _positive_decimal_from_fields(*args: Any, **kwargs: Any) -> Any: ...
def _text_items(*args: Any, **kwargs: Any) -> Any: ...
def _truthy(*args: Any, **kwargs: Any) -> Any: ...
def _target_symbol_actions(*args: Any, **kwargs: Any) -> Any: ...
def _target_symbol_quantities(*args: Any, **kwargs: Any) -> Any: ...
def _target_source_decision_quantities(*args: Any, **kwargs: Any) -> Any: ...
def _target_notional(*args: Any, **kwargs: Any) -> Any: ...
def _target_quantity(*args: Any, **kwargs: Any) -> Any: ...
def _configured_bounded_collection_limit(*args: Any, **kwargs: Any) -> Any: ...
def _clean_window_baseline_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _target_identity(*args: Any, **kwargs: Any) -> Any: ...
def _target_identity_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _hpairs_materialization_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _source_decision_readiness_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _target_materialization_blockers(*args: Any, **kwargs: Any) -> Any: ...
def paper_route_target_execution_capacity_blockers(
    *args: Any, **kwargs: Any
) -> Any: ...
def _blocked_target_readiness(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_decision_hash(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_source_materialization_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_source_decision_needs_refresh(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_decision_payload(*args: Any, **kwargs: Any) -> Any: ...
def materialize_bounded_paper_route_target_plan(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
