from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F811,F821
from typing import Any
from collections.abc import Mapping, Sequence
from datetime import datetime, timedelta, timezone
from decimal import Decimal, InvalidOperation
from hashlib import sha256
import json
from typing import Any, cast
from .market_context_domains import (
    active_market_context_mapping,
    active_market_context_reasons,
)

PROFIT_FRESHNESS_FRONTIER_SCHEMA_VERSION: Any
_FRESHNESS_SECONDS: Any
_CURRENT_STATES: Any
_ROUTE_SETTLED_ROW_STATES: Any
_BAD_STATES: Any
_DIMENSION_EXPECTED_BPS: Mapping[str, Decimal]
_DIMENSION_REPAIR_COST: Mapping[str, str]
_REPAIR_COST_PENALTY: Mapping[str, Decimal]
_DIMENSION_ACTION: Mapping[str, str]
_DIMENSION_REPAIR_CLASSES: Mapping[str, tuple[str, ...]]
_DAILY_NET_PNL_UNLOCK_KEYS: Any
_DIMENSION_SUCCESS: Mapping[str, str]
_REPAIRABLE_DIMENSIONS: Any
_ROUTEABILITY_ONLY_TCA_REASON_CODES: Any
_ROUTEABILITY_ONLY_TCA_REASON_PREFIXES: Any
_NONBLOCKING_JANGAR_RELIABILITY_REASONS: Any
_NONBLOCKING_QUANT_HEALTH_REASONS: Any
_ROUTEABILITY_TCA_REPAIR_LOT_TYPES: Any
_ROUTEABILITY_TCA_REPAIR_ACTION: Any
_ROUTEABILITY_TCA_REPAIR_REASON_PREFIXES: Any
_ROUTEABILITY_TCA_REPAIR_REASON_FRAGMENTS: Any
_ALPHA_FEATURE_REPLAY_REASON_CODES: Any
_ALPHA_FEATURE_REPLAY_PRIORITY_BONUS: Any
_ALPHA_FEATURE_ROUTEABILITY_PRIORITY_BONUS: Any
_ALPHA_READINESS_ROUTEABILITY_REASON_CODES: Any

def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _sequence(*args: Any, **kwargs: Any) -> Any: ...
def _text(*args: Any, **kwargs: Any) -> Any: ...
def _decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _int(*args: Any, **kwargs: Any) -> Any: ...
def _float(*args: Any, **kwargs: Any) -> Any: ...
def _bool(*args: Any, **kwargs: Any) -> Any: ...
def _unique(*args: Any, **kwargs: Any) -> Any: ...
def _strings(*args: Any, **kwargs: Any) -> Any: ...
def _symbols(*args: Any, **kwargs: Any) -> Any: ...
def _stable_ref(*args: Any, **kwargs: Any) -> Any: ...
def _timestamp(*args: Any, **kwargs: Any) -> Any: ...
def _state_from_reasons(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_items(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_summary(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_ids_for_reasons(*args: Any, **kwargs: Any) -> Any: ...
def _reason_total(*args: Any, **kwargs: Any) -> Any: ...
def _dimension(*args: Any, **kwargs: Any) -> Any: ...
def _proof_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _market_domain_states(*args: Any, **kwargs: Any) -> Any: ...
def _market_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _signal_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _empirical_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _route_rows(*args: Any, **kwargs: Any) -> Any: ...
def _route_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _routeability_only_tca_reason(*args: Any, **kwargs: Any) -> Any: ...
def _tca_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _route_readiness_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _is_routeability_tca_repair_reason(*args: Any, **kwargs: Any) -> Any: ...
def _route_readiness_action(*args: Any, **kwargs: Any) -> Any: ...
def _zero_notional_action(*args: Any, **kwargs: Any) -> Any: ...
def _schema_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _jangar_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _confidence_for_state(*args: Any, **kwargs: Any) -> Any: ...
def _routeability_confidence(*args: Any, **kwargs: Any) -> Any: ...
def _jangar_confidence(*args: Any, **kwargs: Any) -> Any: ...
def _packet_dimension(*args: Any, **kwargs: Any) -> Any: ...
def _packet_hypothesis_refs(*args: Any, **kwargs: Any) -> Any: ...
def _packet_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _daily_net_pnl_unlock(*args: Any, **kwargs: Any) -> Any: ...
def _expected_daily_net_pnl_unlock(*args: Any, **kwargs: Any) -> Any: ...
def _target_notional_rankings(*args: Any, **kwargs: Any) -> Any: ...
def _repair_lot(*args: Any, **kwargs: Any) -> Any: ...
def build_profit_freshness_frontier(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
