from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F811,F821
from typing import Any
import hashlib
import json
import math
import random
import shutil
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from statistics import NormalDist
from typing import Any, Mapping, Sequence, cast
import psycopg
import yaml
from sqlalchemy import select
from sqlalchemy.orm import Session
from ..models import VNextDatasetSnapshot
from .evidence_contracts import ArtifactProvenance

MARKET_DAY_INVENTORY_SCHEMA_VERSION: Any
EXECUTION_DAY_INVENTORY_SCHEMA_VERSION: Any
REPLAY_DAY_MANIFEST_SCHEMA_VERSION: Any
DATA_SUFFICIENCY_SCHEMA_VERSION: Any
TRIAL_LEDGER_SCHEMA_VERSION: Any
STATISTICAL_VALIDITY_SCHEMA_VERSION: Any
PROFITABILITY_CERTIFICATE_SCHEMA_VERSION: Any
SUFFICIENCY_STATUS_INSUFFICIENT_HISTORY: Any
SUFFICIENCY_STATUS_RESEARCH_ONLY: Any
SUFFICIENCY_STATUS_HISTORICAL_READY: Any
SUFFICIENCY_STATUS_PAPER_READY: Any
CERTIFICATE_STATUS_INSUFFICIENT_HISTORY: Any
CERTIFICATE_STATUS_RESEARCH_ONLY: Any
CERTIFICATE_STATUS_HISTORICAL_PROVEN: Any
CERTIFICATE_STATUS_PAPER_PROVEN: Any
CERTIFICATE_STATUS_LIVE_CAPPED: Any
CERTIFICATE_STATUS_LIVE_FULL: Any
ARCHIVE_STATUS_ARCHIVED: Any
ARCHIVE_STATUS_PARTIAL: Any
ARCHIVE_STATUS_INSUFFICIENT: Any
_UTC: Any
_NORMAL_DIST: Any
_REALITY_CHECK_BOOTSTRAP_REPLICATES: Any
_REALITY_CHECK_MIN_SAMPLE_DAYS: Any
_DSR_MIN_SAMPLE_DAYS: Any
_COPYABLE_ARTIFACTS: tuple[str, ...]

class ArchiveWalkForwardFold:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    name: str
    train_days: list[str]
    validation_days: list[str]
    test_days: list[str]
    embargo_days: list[str]
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

class ArchivedTradingDayBundle:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    trading_day: str
    candidate_id: str
    run_id: str
    archived_run_dir: Path
    original_run_dir: Path
    market_day_inventory: dict[str, Any]
    execution_day_inventory: dict[str, Any]
    replay_day_manifest: dict[str, Any]
    def net_pnl_estimated(*args: Any, **kwargs: Any) -> Any: ...
    def estimated_cost_total(*args: Any, **kwargs: Any) -> Any: ...
    def replayable_market_day(*args: Any, **kwargs: Any) -> Any: ...
    def execution_day_eligible(*args: Any, **kwargs: Any) -> Any: ...

def _as_dict(*args: Any, **kwargs: Any) -> Any: ...
def _as_list(*args: Any, **kwargs: Any) -> Any: ...
def _as_text(*args: Any, **kwargs: Any) -> Any: ...
def _as_int(*args: Any, **kwargs: Any) -> Any: ...
def _as_float(*args: Any, **kwargs: Any) -> Any: ...
def _as_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _json_default(*args: Any, **kwargs: Any) -> Any: ...
def _stable_hash(*args: Any, **kwargs: Any) -> Any: ...
def _write_json(*args: Any, **kwargs: Any) -> Any: ...
def _load_json(*args: Any, **kwargs: Any) -> Any: ...
def _load_manifest(*args: Any, **kwargs: Any) -> Any: ...
def _simulation_report_path(*args: Any, **kwargs: Any) -> Any: ...
def _manifest_trading_day(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_id(*args: Any, **kwargs: Any) -> Any: ...
def _source_topics_for_manifest(*args: Any, **kwargs: Any) -> Any: ...
def _source_roles_for_manifest(*args: Any, **kwargs: Any) -> Any: ...
def _artifacts_for_copy(*args: Any, **kwargs: Any) -> Any: ...
def copy_archive_artifacts(*args: Any, **kwargs: Any) -> Any: ...
def collect_simulation_postgres_counts(*args: Any, **kwargs: Any) -> Any: ...
def build_market_day_inventory(*args: Any, **kwargs: Any) -> Any: ...
def build_execution_day_inventory(*args: Any, **kwargs: Any) -> Any: ...
def build_replay_day_manifest(*args: Any, **kwargs: Any) -> Any: ...
def upsert_dataset_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def _resolve_manifest_path(*args: Any, **kwargs: Any) -> Any: ...
def archive_historical_simulation_run(*args: Any, **kwargs: Any) -> Any: ...
def _parse_optional_timestamp(*args: Any, **kwargs: Any) -> Any: ...
def load_archived_trading_day_bundles(*args: Any, **kwargs: Any) -> Any: ...
def summarize_data_sufficiency(*args: Any, **kwargs: Any) -> Any: ...
def build_trial_ledger(*args: Any, **kwargs: Any) -> Any: ...
def generate_archive_walkforward_folds(*args: Any, **kwargs: Any) -> Any: ...
def _proof_eligible_bundles(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_daily_net_pnl_by_day(*args: Any, **kwargs: Any) -> Any: ...
def _fold_selection_rows(*args: Any, **kwargs: Any) -> Any: ...
def _estimate_pbo(*args: Any, **kwargs: Any) -> Any: ...
def _fit_slope(*args: Any, **kwargs: Any) -> Any: ...
def _sample_stddev(*args: Any, **kwargs: Any) -> Any: ...
def _daily_sharpe_ratio(*args: Any, **kwargs: Any) -> Any: ...
def _skewness_and_kurtosis(*args: Any, **kwargs: Any) -> Any: ...
def _estimate_deflated_sharpe_ratio(*args: Any, **kwargs: Any) -> Any: ...
def _moving_block_bootstrap_indices(*args: Any, **kwargs: Any) -> Any: ...
def _estimate_reality_check_p_value(*args: Any, **kwargs: Any) -> Any: ...
def build_statistical_validity_report(*args: Any, **kwargs: Any) -> Any: ...
def build_profitability_certificate(*args: Any, **kwargs: Any) -> Any: ...
def _min_retention_days(*args: Any, **kwargs: Any) -> Any: ...
def _missing_business_days(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_mean(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_median(*args: Any, **kwargs: Any) -> Any: ...
def _safe_decimal_ratio(*args: Any, **kwargs: Any) -> Any: ...
def _mean_optional_floats(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
