from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
from collections import Counter
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from typing import Any, cast
from .discovery.promotion_contract import (
    final_authority_parameter_contract,
    probation_evidence_collection_contract,
)
from .risk import target_sizing_payload
from .route_reacquisition import build_route_reacquisition_book

_BLOCKING_STATES: Any
_LIVE_MICRO_STAGES: Any
_LIVE_SCALE_STAGES: Any

def _text(*args: Any, **kwargs: Any) -> Any: ...
def _bool(*args: Any, **kwargs: Any) -> Any: ...
def _int(*args: Any, **kwargs: Any) -> Any: ...
def _decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _parse_timestamp(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _sequence(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_summary(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_items(*args: Any, **kwargs: Any) -> Any: ...
def _strings(*args: Any, **kwargs: Any) -> Any: ...
def _truthy(*args: Any, **kwargs: Any) -> Any: ...
def _first_decimal_from(*args: Any, **kwargs: Any) -> Any: ...
def _target_sizing_source_for_item(*args: Any, **kwargs: Any) -> Any: ...
def _target_notional_parameter_summary(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_repair_target_summary(*args: Any, **kwargs: Any) -> Any: ...
def _reason_counts(*args: Any, **kwargs: Any) -> Any: ...
def _slippage_guardrails(*args: Any, **kwargs: Any) -> Any: ...
def _tca_symbol_routes(*args: Any, **kwargs: Any) -> Any: ...
def _route_universe_adverse_slippage_clear(*args: Any, **kwargs: Any) -> Any: ...
def _route_symbol_filter_enabled(*args: Any, **kwargs: Any) -> Any: ...
def _add_repair(*args: Any, **kwargs: Any) -> Any: ...
def build_profitability_proof_floor_receipt(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
