from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import logging
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, time, timedelta, timezone
from decimal import Decimal
from typing import Any, Mapping, Sequence, cast
from uuid import UUID
from zoneinfo import ZoneInfo
from sqlalchemy import and_, delete, or_, select
from sqlalchemy.orm import Session
from sqlalchemy.sql.elements import ColumnElement
from ..config import settings
from ..models import (
    StrategyCapitalAllocation,
    StrategyHypothesis,
    StrategyHypothesisMetricWindow,
    StrategyHypothesisVersion,
    StrategyPromotionDecision,
    StrategyRuntimeLedgerBucket,
    TigerBeetleAccountRef,
    TigerBeetleTransferRef,
    VNextDatasetSnapshot,
)
from .hypotheses import (
    HypothesisManifest,
    HypothesisRegistryLoadResult,
    load_hypothesis_registry,
)
from .runtime_ledger import EXACT_REPLAY_LEDGER_SCHEMA_VERSION, POST_COST_PNL_BASIS
from .runtime_cost_authority import (
    cost_basis_counts_have_non_promotion_grade_costs,
    is_non_promotion_grade_runtime_cost_basis,
)
from .runtime_decision_authority import (
    SOURCE_DECISION_MODE_NOT_PROFIT_PROOF_ELIGIBLE_BLOCKER,
    SOURCE_DECISION_MODE_PROFIT_PROOF_MISSING_BLOCKER,
    normalize_source_decision_mode,
    source_decision_mode_counts_have_non_profit_proof_modes,
    source_decision_mode_counts_have_profit_proof_modes,
    source_decision_mode_is_profit_proof_eligible,
)
from .runtime_ledger_proof_policy import runtime_ledger_proof_policy_from_env
from .runtime_ledger_source_authority import (
    build_runtime_ledger_profit_distance_readback,
    runtime_ledger_promotion_source_authority_blockers as _base_runtime_ledger_promotion_source_authority_blockers,
)
from .tigerbeetle_journal import (
    TIGERBEETLE_BLOCKER_JOURNAL_DISABLED,
    TIGERBEETLE_BLOCKER_JOURNAL_ENTRY_UNAVAILABLE,
    TIGERBEETLE_BLOCKER_JOURNAL_ERROR,
    TIGERBEETLE_RUNTIME_LEDGER_JOURNAL_STATUS_NON_AUTHORITY_BLOCKED,
    TIGERBEETLE_RUNTIME_LEDGER_JOURNAL_STATUS_PASS,
    TigerBeetleLedgerJournal,
    tigerbeetle_runtime_ledger_journal_payload,
)

logger: Any
US_EQUITIES_REGULAR_TIMEZONE: Any
US_EQUITIES_REGULAR_OPEN: Any
US_EQUITIES_REGULAR_CLOSE: Any
PROMOTION_GRADE_POST_COST_BASES: Any
RUNTIME_LEDGER_PROOF_POLICY: Any
_RUNTIME_LEDGER_PROOF_SATISFIED_METADATA_BLOCKERS: Any
_RUNTIME_WINDOW_IMPORT_CAPITAL_ONLY_BLOCKERS: Any
RUNTIME_LEDGER_BUCKET_SCHEMAS: Any
RUNTIME_LEDGER_AUTHORITY_CLASS_MISSING_BLOCKER: Any
EXECUTION_TCA_MISSING_BLOCKER: Any
RUNTIME_LEDGER_EXECUTION_TCA_REFS_MISSING_BLOCKER: Any
_RUNTIME_LEDGER_PROMOTION_GRADE_AUTHORITY_MARKERS: Any

class ObservedRuntimeBucket:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    window_started_at: datetime
    window_ended_at: datetime
    market_session_count: int
    decision_count: int
    trade_count: int
    order_count: int
    decision_alignment_ratio: Decimal
    avg_abs_slippage_bps: Decimal
    post_cost_expectancy_bps: Decimal
    post_cost_promotion_sample_count: int
    post_cost_basis_counts: dict[str, int]
    continuity_ok: bool
    drift_ok: bool
    dependency_quorum_decision: str
    payload_json: dict[str, Any]

class _NormalizedTcaRow:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    computed_at: datetime
    bucketed_at: datetime
    abs_slippage_bps: Decimal | None
    post_cost_expectancy_bps: Decimal | None
    post_cost_expectancy_basis: str
    post_cost_promotion_eligible: bool
    runtime_ledger_bucket: dict[str, Any]
    source_decision_mode: str | None

def _utc(*args: Any, **kwargs: Any) -> Any: ...
def _optional_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_family_matches(*args: Any, **kwargs: Any) -> Any: ...
def _text(*args: Any, **kwargs: Any) -> Any: ...
def _promotion_grade_runtime_ledger_authority_marker_present(
    *args: Any, **kwargs: Any
) -> Any: ...
def runtime_ledger_promotion_source_authority_blockers(
    *args: Any, **kwargs: Any
) -> Any: ...
def _post_cost_expectancy_basis(*args: Any, **kwargs: Any) -> Any: ...
def _post_cost_basis_is_promotion_grade(*args: Any, **kwargs: Any) -> Any: ...
def _parse_observation_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _observation_bool(*args: Any, **kwargs: Any) -> Any: ...
def _observation_int(*args: Any, **kwargs: Any) -> Any: ...
def _observation_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _string_list(*args: Any, **kwargs: Any) -> Any: ...

_EXECUTION_TCA_REF_KEYS: Any

def _runtime_ledger_tca_ref_texts(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_execution_tca_metric_refs(*args: Any, **kwargs: Any) -> Any: ...
def _mapping(*args: Any, **kwargs: Any) -> Any: ...
def _hash_count(*args: Any, **kwargs: Any) -> Any: ...
def _positive_count_mapping_present(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_explicit_costs_present(*args: Any, **kwargs: Any) -> Any: ...
def _persisted_runtime_ledger_bucket_evidence_grade(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_ledger_bucket_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_payload(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_row_is_promotion_grade(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_post_cost_from_rows(*args: Any, **kwargs: Any) -> Any: ...
def _paper_probation_blocking_reasons(*args: Any, **kwargs: Any) -> Any: ...
def _delay_adjusted_depth_stress_blocking_reasons(*args: Any, **kwargs: Any) -> Any: ...
def _delay_adjusted_depth_stress_summary(*args: Any, **kwargs: Any) -> Any: ...
def _capital_stage_for_runtime_import(*args: Any, **kwargs: Any) -> Any: ...
def _capital_multiplier_for_stage(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_proof_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_evidence_blocking_reasons(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_ledger_authority_gate_targets(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_summary_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_promotion_blocking_reasons(*args: Any, **kwargs: Any) -> Any: ...
def resolve_hypothesis_manifest(*args: Any, **kwargs: Any) -> Any: ...
def build_regular_session_buckets(*args: Any, **kwargs: Any) -> Any: ...
def build_observed_runtime_buckets(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_payload_interval(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_payload_bucketed_at(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_payload_is_readback(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_payload_identity_values(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_payload_dedupe_key(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_payloads_overlap(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_payload_preference_key(*args: Any, **kwargs: Any) -> Any: ...
def _dedupe_runtime_ledger_bucket_payloads(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_payloads(*args: Any, **kwargs: Any) -> Any: ...
def _row_ref(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_readback_from_rows(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_replacement_scopes(*args: Any, **kwargs: Any) -> Any: ...
def _delete_replaced_runtime_ledger_buckets(*args: Any, **kwargs: Any) -> Any: ...
def _delete_current_runtime_ledger_buckets(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_post_cost_from_observed_buckets(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_ledger_trading_day_key(*args: Any, **kwargs: Any) -> Any: ...
def _median_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _p10_decimal(*args: Any, **kwargs: Any) -> Any: ...

_RUNTIME_LEDGER_EQUITY_DENOMINATOR_KEYS: Any
_RUNTIME_LEDGER_SYMBOL_KEYS: Any
_RUNTIME_LEDGER_SYMBOL_PNL_KEYS: Any

def _runtime_ledger_equity_denominator(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_symbol_pnl_items(*args: Any, **kwargs: Any) -> Any: ...
def _uuid_values(*args: Any, **kwargs: Any) -> Any: ...
def _tigerbeetle_transfer_account_ids(*args: Any, **kwargs: Any) -> Any: ...
def _tigerbeetle_account_refs_for_ids(*args: Any, **kwargs: Any) -> Any: ...
def _tigerbeetle_account_refs_for_transfer_ref(*args: Any, **kwargs: Any) -> Any: ...
def _tigerbeetle_refs_for_ledger_payload(*args: Any, **kwargs: Any) -> Any: ...
def _ledger_payload_with_tigerbeetle_refs(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_tigerbeetle_proof_refs(*args: Any, **kwargs: Any) -> Any: ...
def _journal_tigerbeetle_runtime_ledger_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _mark_runtime_ledger_bucket_tigerbeetle_journal(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_ledger_daily_summary_from_observed_buckets(
    *args: Any, **kwargs: Any
) -> Any: ...
def persist_observed_runtime_windows(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
