from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401, F811
from typing import Any
from collections import deque
from dataclasses import dataclass, field
from datetime import date, datetime, time, timedelta, timezone
from decimal import Decimal
from typing import Any
from zoneinfo import ZoneInfo
from .features import (
    extract_price,
    nested_payload_value,
    optional_decimal,
    payload_value,
)
from .models import SignalEnvelope
from .quote_quality import QuoteQualityPolicy, assess_signal_quote_quality

US_EQUITIES_TIMEZONE: Any
REGULAR_OPEN_LOCAL: Any
REGULAR_CLOSE_LOCAL: Any
DEFAULT_OPENING_RANGE_MINUTES: Any
DEFAULT_RECENT_WINDOW: Any
DEFAULT_PRICE_HISTORY_WINDOW: Any
DEFAULT_POSITION_IN_RANGE: Any
_MARKET_TZ: Any

def nyse_full_day_holidays(*args: Any, **kwargs: Any) -> Any: ...
def is_regular_equities_session_date(*args: Any, **kwargs: Any) -> Any: ...
def iter_regular_equities_session_dates(*args: Any, **kwargs: Any) -> Any: ...
def most_recent_regular_equities_session_date(*args: Any, **kwargs: Any) -> Any: ...
def _easter_date(*args: Any, **kwargs: Any) -> Any: ...
def _nth_weekday(*args: Any, **kwargs: Any) -> Any: ...
def _last_weekday(*args: Any, **kwargs: Any) -> Any: ...
def _observed_fixed_holiday(*args: Any, **kwargs: Any) -> Any: ...
def regular_session_open_utc_for(*args: Any, **kwargs: Any) -> Any: ...
def regular_session_close_utc_for(*args: Any, **kwargs: Any) -> Any: ...
def _regular_session_boundary_utc_for(*args: Any, **kwargs: Any) -> Any: ...
def regular_session_minutes_elapsed(*args: Any, **kwargs: Any) -> Any: ...
def _extract_price(*args: Any, **kwargs: Any) -> Any: ...
def _extract_spread_bps(*args: Any, **kwargs: Any) -> Any: ...
def _extract_imbalance_pressure(*args: Any, **kwargs: Any) -> Any: ...
def _extract_microprice_bias_bps(*args: Any, **kwargs: Any) -> Any: ...
def _bps_delta(*args: Any, **kwargs: Any) -> Any: ...
def _recent_return_bps(*args: Any, **kwargs: Any) -> Any: ...
def _mean_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _max_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _average_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _ratio_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _rank_universe_size(*args: Any, **kwargs: Any) -> Any: ...
def _percentile_rank(*args: Any, **kwargs: Any) -> Any: ...
def _session_minutes_elapsed(*args: Any, **kwargs: Any) -> Any: ...

class _SymbolSessionState:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    session_day: date
    session_open_price: Decimal
    prev_session_close_price: Decimal | None
    session_high_price: Decimal
    session_low_price: Decimal
    opening_range_high: Decimal
    opening_range_low: Decimal
    opening_window_close_price: Decimal
    spread_bps_window: deque[Decimal]
    imbalance_pressure_window: deque[Decimal]
    quote_validity_window: deque[Decimal]
    quote_jump_bps_window: deque[Decimal]
    microprice_bias_bps_window: deque[Decimal]
    above_opening_range_high_window: deque[Decimal]
    above_opening_window_close_window: deque[Decimal]
    above_vwap_w5m_window: deque[Decimal]
    price_history: deque[tuple[datetime, Decimal]]
    latest_price_vs_session_open_bps: Decimal | None
    latest_price_vs_prev_session_close_bps: Decimal | None
    latest_price_position_in_session_range: Decimal | None
    latest_recent_15m_return_bps: Decimal | None
    latest_microbar_volume: Decimal | None
    latest_clusterlob_directional_ofi: Decimal | None
    latest_price_vs_vwap_w5m_bps: Decimal | None
    latest_opening_window_return_bps: Decimal | None
    latest_opening_window_return_from_prev_close_bps: Decimal | None
    latest_recent_imbalance_pressure_avg: Decimal | None
    latest_recent_quote_invalid_ratio: Decimal | None
    latest_recent_quote_jump_bps_avg: Decimal | None
    latest_recent_quote_jump_bps_max: Decimal | None
    latest_recent_microprice_bias_bps_avg: Decimal | None
    latest_vwap_w5m_stretch_bps: Decimal | None
    latest_rsi14: Decimal | None
    latest_macd_hist: Decimal | None
    latest_executable_metric_ts: datetime | None
    last_valid_quote_price: Decimal | None
    opening_45_return_bps: Decimal | None
    opening_60_return_bps: Decimal | None

class SessionContextTracker:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def enrich_signal_payload(*args: Any, **kwargs: Any) -> Any: ...
    def _roll_forward_completed_sessions(*args: Any, **kwargs: Any) -> Any: ...
    def _rank_latest_metric(*args: Any, **kwargs: Any) -> Any: ...
    def _positive_ratio_latest_metric(*args: Any, **kwargs: Any) -> Any: ...
