from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import hashlib
import json
import logging
import os
from collections.abc import Mapping, Sequence
from datetime import datetime, timedelta, timezone
from decimal import Decimal, InvalidOperation
from threading import Lock
from typing import Any, NamedTuple, cast
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit
from urllib.request import Request, urlopen
from sqlalchemy import func, select, text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session
from ..config import settings
from ..models import (
    AutoresearchCandidateSpec,
    AutoresearchEpoch,
    AutoresearchPortfolioCandidate,
    AutoresearchProposalScore,
    ResearchCandidate,
    ResearchPromotion,
    StrategyHypothesis,
    StrategyHypothesisMetricWindow,
    StrategyPromotionDecision,
    StrategyRuntimeLedgerBucket,
    TradeDecision,
    VNextDatasetSnapshot,
    VNextPromotionDecision,
)
from .hypotheses import (
    compile_hypothesis_runtime_statuses,
    load_hypothesis_registry,
    resolve_hypothesis_dependency_quorum,
    summarize_hypothesis_runtime_statuses,
)
from .market_context_domains import (
    active_market_context_mapping,
    active_market_context_reasons,
)
from .discovery.profit_target_oracle import evaluate_profit_target_oracle
from .profit_windows import build_profit_window_contract
from .profit_leases import build_profit_lease_projection
from .runtime_ledger import POST_COST_PNL_BASIS
from .runtime_ledger_source_authority import (
    RUNTIME_LEDGER_AUTHORITY_CLASS_MISSING_BLOCKER,
    RUNTIME_LEDGER_EXECUTION_ORDER_EVENT_REFS_MISSING_BLOCKER,
    RUNTIME_LEDGER_EXECUTION_REFS_MISSING_BLOCKER,
    RUNTIME_LEDGER_SOURCE_MATERIALIZATION_MISSING_BLOCKER,
    RUNTIME_LEDGER_SOURCE_OFFSETS_MISSING_BLOCKER,
    RUNTIME_LEDGER_SOURCE_REFS_MISSING_BLOCKER,
    RUNTIME_LEDGER_SOURCE_WINDOW_IDS_MISSING_BLOCKER,
    RUNTIME_LEDGER_SOURCE_WINDOW_MISSING_BLOCKER,
    RUNTIME_LEDGER_TRADE_DECISION_REFS_MISSING_BLOCKER,
    runtime_ledger_promotion_source_authority_blockers,
    runtime_ledger_promotion_source_authority_present,
)
from .runtime_strategy_resolution import (
    derived_strategy_name_from_strategy_id,
    explicit_runtime_strategy_name_or_family_harness,
    strategy_names_from_strategy_id,
)
from .session_context import regular_session_close_utc_for, regular_session_open_utc_for
from .tca import build_tca_gate_inputs

logger: Any
_CAPITAL_STAGE_ORDER: Any
_LIVE_SUBMISSION_BLOCKING_TOGGLE_MISMATCHES: Any
_TYPED_QUANT_HEALTH_PATH: Any
_QUANT_HEALTH_CACHE_LOCK: Any
_QUANT_HEALTH_CACHE: dict[str, object]
_STALE_SEGMENT_STATES: Any
_TA_CORE_REASON_CODES: Any
_AUTORESEARCH_PORTFOLIO_READY_STATUSES: Any
_RUNTIME_LEDGER_REPAIR_SCAN_LIMIT: Any
_RUNTIME_LEDGER_REPAIR_CANDIDATE_LIMIT: Any
_RUNTIME_LEDGER_STATUS_QUERY_TIMEOUT_DEFAULT_MS: Any
_RUNTIME_LEDGER_STATUS_QUERY_TIMEOUT_MIN_MS: Any
_RUNTIME_LEDGER_STATUS_QUERY_TIMEOUT_MAX_MS: Any
_RUNTIME_LEDGER_STATUS_QUERY_TIMEOUT_ENV: Any
_RUNTIME_LEDGER_SUMMARY_PER_HYPOTHESIS_LIMIT: Any
_PROMOTION_TABLE_COUNT_SCAN_LIMIT: Any
_PROMOTION_PORTFOLIO_READY_SCAN_LIMIT: Any
_CERTIFICATE_EVIDENCE_PER_HYPOTHESIS_LIMIT: Any
_CERTIFICATE_EVIDENCE_WINDOW_LIMIT: Any
_CERTIFICATE_EVIDENCE_RUNTIME_LEDGER_LIMIT: Any
_PROMOTION_SCALAR_COUNT_LIMIT: Any
_PROMOTION_PORTFOLIO_SAMPLE_LIMIT: Any

class _PortfolioPromotionRow(NamedTuple):
    status: str
    portfolio_candidate_id: str
    source_candidate_ids_json: Any
    target_net_pnl_per_day: Decimal
    objective_scorecard_json: Any

_RUNTIME_WINDOW_IMPORT_CONTINUITY_READY_STATES: Any

def _maybe_set_runtime_ledger_status_statement_timeout(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_ledger_status_query_timeout_ms(*args: Any, **kwargs: Any) -> Any: ...
def _rollback_runtime_ledger_status_session(*args: Any, **kwargs: Any) -> Any: ...
def _sqlalchemy_error_indicates_statement_timeout(*args: Any, **kwargs: Any) -> Any: ...
def _unavailable_certificate_evidence_rows(*args: Any, **kwargs: Any) -> Any: ...
def _certificate_evidence_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _empty_profit_promotion_table_counts(*args: Any, **kwargs: Any) -> Any: ...
def _load_profit_promotion_bounded_row_count(*args: Any, **kwargs: Any) -> Any: ...
def _fresh_clickhouse_signal_continuity(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_continuity_signal(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_drift_signal(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_window_import_health_gate_inputs(*args: Any, **kwargs: Any) -> Any: ...
def _autoresearch_portfolio_current_oracle_passed(*args: Any, **kwargs: Any) -> Any: ...
def _safe_int(*args: Any, **kwargs: Any) -> Any: ...
def _safe_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_paper_route_probe_notional(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_paper_route_probe_collection_payload(*args: Any, **kwargs: Any) -> Any: ...
def _safe_bool(*args: Any, **kwargs: Any) -> Any: ...
def _safe_text(*args: Any, **kwargs: Any) -> Any: ...
def _safe_attr_text(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _stage_rank(*args: Any, **kwargs: Any) -> Any: ...
def _derive_quant_health_url(*args: Any, **kwargs: Any) -> Any: ...
def resolve_quant_health_url(*args: Any, **kwargs: Any) -> Any: ...
def _build_quant_health_request_url(*args: Any, **kwargs: Any) -> Any: ...
def load_quant_evidence_status(*args: Any, **kwargs: Any) -> Any: ...
def critical_trading_toggle_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def build_shadow_first_toggle_parity(*args: Any, **kwargs: Any) -> Any: ...
def resolve_active_capital_stage(*args: Any, **kwargs: Any) -> Any: ...
def build_hypothesis_runtime_summary(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_payload(*args: Any, **kwargs: Any) -> Any: ...

_RUNTIME_LEDGER_BUCKET_INT_TOTAL_KEYS: Any
_RUNTIME_LEDGER_BUCKET_DECIMAL_TOTAL_KEYS: Any
_RUNTIME_LEDGER_BUCKET_COUNT_MAP_KEYS: Any
_RUNTIME_LEDGER_BUCKET_SEQUENCE_KEYS: Any
_RUNTIME_LEDGER_BUCKET_COMMON_TEXT_KEYS: Any

def _runtime_ledger_candidate_group_key(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_latest_payloads_per_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_merge_count_maps(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_unique_sequence(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_common_text(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_aggregate_candidate_payloads(*args: Any, **kwargs: Any) -> Any: ...

_RUNTIME_LEDGER_SOURCE_EVIDENCE_KEYS: Any

def _runtime_ledger_source_evidence_payload(*args: Any, **kwargs: Any) -> Any: ...
def _normalized_strategy_family(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_hash_count(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_payload_from_runtime_item(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_within_metric_window(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_matches_metric_window(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_bucket_window_reason_code(*args: Any, **kwargs: Any) -> Any: ...
def _certificate_runtime_ledger_payload(*args: Any, **kwargs: Any) -> Any: ...
def _certificate_runtime_ledger_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _mark_runtime_certificate_rejected(*args: Any, **kwargs: Any) -> Any: ...
def _load_latest_runtime_ledger_summary(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_selection_score(*args: Any, **kwargs: Any) -> Any: ...
def _certificate_evidence_authority_score(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_target_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_manifest_candidate_ids(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_repair_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_repair_score(*args: Any, **kwargs: Any) -> Any: ...

_RUNTIME_LEDGER_PAPER_PROBATION_REASON: Any
_RUNTIME_LEDGER_PAPER_PROBATION_ALLOWED_REASONS: Any
_RUNTIME_LEDGER_PAPER_PROBATION_IMPORT_SCHEMA_VERSION: Any
_RUNTIME_LEDGER_PAPER_PROBATION_SOURCE_KIND: Any
_RUNTIME_LEDGER_PAPER_PROBATION_SOURCE_DSN_ENV: Any
_RUNTIME_LEDGER_PAPER_PROBATION_PROMOTION_BLOCKERS: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_SOURCE_KIND: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_SOURCE_DSN_ENV: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_TARGET_DSN_ENV: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_BUCKET_SOURCE: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_BUCKET_SOURCE_DSN_ENVS: Any
_RUNTIME_LEDGER_PAPER_PROBATION_TARGET_DSN_ENV: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_TRIGGER_REASONS: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_PROMOTION_BLOCKERS: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_LIVE_PAPER_EVIDENCE_REQUIREMENTS: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_SAFE_EVIDENCE_COLLECTION_PATH: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_PROFIT_TARGET_NET_PNL_AFTER_COSTS: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_PROFIT_TARGET_BLOCKER: Any
_RUNTIME_LEDGER_SOURCE_COLLECTION_PROFIT_TARGET_SELECTION_REASON: Any
_HPAIRS_BOUNDED_COLLECTION_HYPOTHESIS_ID: Any
_HPAIRS_BOUNDED_COLLECTION_CANDIDATE_ID: Any
_BOUNDED_PAPER_ROUTE_COLLECTION_SOURCE_KIND: Any
_BOUNDED_PAPER_ROUTE_COLLECTION_SCOPE: Any
_BOUNDED_PAPER_ROUTE_COLLECTION_PROMOTION_BLOCKERS: Any
_RUNTIME_LEDGER_PAPER_PROBATION_MIN_CLOSED_ROUND_TRIPS: Any

def _runtime_ledger_paper_probation_payload(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_paper_probation_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_paper_probation_eligible(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_paper_probation_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_source_collection_candidate(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_source_collection_profit_target_candidate(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_ledger_source_collection_target_progress_payload(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_ledger_source_collection_profit_target_metadata(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_ledger_source_collection_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_lookup_names(*args: Any, **kwargs: Any) -> Any: ...
def _hypothesis_manifest_ref(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_paper_probation_strategy_name(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_paper_probation_bucket_ref(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_source_collection_source_dsn_env(
    *args: Any, **kwargs: Any
) -> Any: ...
def _runtime_ledger_source_collection_import_candidate(
    *args: Any, **kwargs: Any
) -> Any: ...
def _bounded_source_collection_probe_window(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_paper_probation_import_plan(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_import_plan_has_target(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_paper_route_manifest_collection_targets(
    *args: Any, **kwargs: Any
) -> Any: ...
def _with_bounded_paper_route_manifest_collection_targets(
    *args: Any, **kwargs: Any
) -> Any: ...
def _paper_probation_eligible_total_with_runtime_ledger(
    *args: Any, **kwargs: Any
) -> Any: ...
def _load_runtime_ledger_repair_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _certificate_evidence_selection_key(*args: Any, **kwargs: Any) -> Any: ...
def _extract_runtime_summary(*args: Any, **kwargs: Any) -> Any: ...
def _refresh_runtime_summary_totals(*args: Any, **kwargs: Any) -> Any: ...
def build_submission_gate_market_context_status(*args: Any, **kwargs: Any) -> Any: ...
def _load_latest_certificate_evidence(*args: Any, **kwargs: Any) -> Any: ...
def _window_evidence_issued_at(*args: Any, **kwargs: Any) -> Any: ...
def _certificate_evidence_is_fresh(*args: Any, **kwargs: Any) -> Any: ...
def _certificate_capital_stage(*args: Any, **kwargs: Any) -> Any: ...
def _metric_window_activity_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _promotion_decision_blocking_reason_codes(*args: Any, **kwargs: Any) -> Any: ...
def _merge_runtime_certificate_evidence(*args: Any, **kwargs: Any) -> Any: ...
def _segment_summary(*args: Any, **kwargs: Any) -> Any: ...
def _evaluate_certificate_candidates(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_hypothesis_ids_for_gate_scope(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_hypothesis_ids_for_gate_scope(*args: Any, **kwargs: Any) -> Any: ...
def _candidate_reason_codes_for_gate_scope(*args: Any, **kwargs: Any) -> Any: ...
def _default_lineage_ref(*args: Any, **kwargs: Any) -> Any: ...
def _attach_lineage_refs(*args: Any, **kwargs: Any) -> Any: ...
def _load_profit_promotion_table_counts(*args: Any, **kwargs: Any) -> Any: ...
def _coerce_aware_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _build_profit_data_readiness_summary(*args: Any, **kwargs: Any) -> Any: ...
def _load_persisted_profit_rejection_summary(*args: Any, **kwargs: Any) -> Any: ...
def _build_profit_rejection_summary(*args: Any, **kwargs: Any) -> Any: ...
def _build_profit_live_controls(*args: Any, **kwargs: Any) -> Any: ...
def build_live_submission_gate_payload(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
