from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401, F811
from typing import Any
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from typing import Any, cast
from uuid import UUID
from sqlalchemy import func, or_, select
from sqlalchemy.orm import Session
from sqlalchemy.sql.elements import ColumnElement
from app.config import Settings, settings
from app.models import (
    Execution,
    ExecutionOrderEvent,
    ExecutionTCAMetric,
    StrategyRuntimeLedgerBucket,
    TigerBeetleAccountRef,
    TigerBeetleReconciliationRun,
    TigerBeetleTransferRef,
    coerce_json_payload,
)
from app.trading.tigerbeetle_client import (
    TigerBeetleClientProtocol,
    create_tigerbeetle_client,
)
from app.trading.tigerbeetle_ids import stable_ref_u128, u128_decimal
from app.trading.tigerbeetle_journal import (
    SOURCE_TYPE_EXECUTION,
    SOURCE_TYPE_EXECUTION_ORDER_EVENT,
    SOURCE_TYPE_EXECUTION_TCA_METRIC,
    SOURCE_TYPE_RUNTIME_LEDGER_BUCKET,
    execution_tca_metric_source_id,
    build_order_event_transfer_plan,
    build_runtime_ledger_bucket_transfer_plan,
    runtime_ledger_amount_source,
)
from app.trading.tigerbeetle_ledger_model import (
    TRANSFER_KIND_EXECUTION_COST,
    TRANSFER_KIND_EXECUTION_FILL,
    TRANSFER_KIND_RUNTIME_NET_PNL,
    decimal_usd_to_nearest_micros,
)

def create_tigerbeetle_client(settings: Settings) -> TigerBeetleClientProtocol: ...

SCHEMA_VERSION: Any
BLOCKER_TRANSFER_MISSING: Any
BLOCKER_AMOUNT_MISMATCH: Any
BLOCKER_CODE_MISMATCH: Any
BLOCKER_LEDGER_MISMATCH: Any
BLOCKER_DEBIT_ACCOUNT_MISMATCH: Any
BLOCKER_CREDIT_ACCOUNT_MISMATCH: Any
BLOCKER_POSTGRES_REF_MISMATCH: Any
BLOCKER_UNLINKED_EVENT: Any
BLOCKER_UNLINKED_EXECUTION: Any
BLOCKER_UNLINKED_COST: Any
BLOCKER_UNLINKED_RUNTIME_LEDGER: Any
BLOCKER_SOURCE_ROW_MISSING: Any
BLOCKER_SOURCE_AMOUNT_MISMATCH: Any
BLOCKER_RUNTIME_LEDGER_DIRECTION_MISMATCH: Any
BLOCKER_RUNTIME_LEDGER_METADATA_MISMATCH: Any
BLOCKER_RUNTIME_LEDGER_SIGNED_REFS_MISSING: Any
BLOCKER_RUNTIME_LEDGER_ACCOUNT_REFS_MISSING: Any
BLOCKER_STABLE_REF_PAYLOAD_MISMATCH: Any
BLOCKER_CLIENT_UNAVAILABLE: Any
BLOCKER_RECONCILIATION_STALE: Any
SAMPLE_LIMIT: Any
REF_COUNT_FIELD_NAMES: Any
COMPACT_REF_COUNT_KEYS: Any
COMPACT_REF_COUNT_FLAG_KEYS: Any

def _attr(*args: Any, **kwargs: Any) -> Any: ...
def _payload_value(*args: Any, **kwargs: Any) -> Any: ...
def _u128_text(*args: Any, **kwargs: Any) -> Any: ...
def _account_payload_matches(*args: Any, **kwargs: Any) -> Any: ...
def _payload_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _stable_ref_payload(*args: Any, **kwargs: Any) -> Any: ...
def _stable_ref_matches(*args: Any, **kwargs: Any) -> Any: ...
def _stable_ref_archives_event_transfer(*args: Any, **kwargs: Any) -> Any: ...
def _ref_matches_expected_event(*args: Any, **kwargs: Any) -> Any: ...
def _ref_sample(*args: Any, **kwargs: Any) -> Any: ...
def _append_sample(*args: Any, **kwargs: Any) -> Any: ...
def _transfer_lookup_key(*args: Any, **kwargs: Any) -> Any: ...
def _order_event_ref_exists(*args: Any, **kwargs: Any) -> Any: ...
def _source_ref_exists(*args: Any, **kwargs: Any) -> Any: ...
def _payload_int(*args: Any, **kwargs: Any) -> Any: ...
def _payload_string_list(*args: Any, **kwargs: Any) -> Any: ...
def _source_materialization_payload(*args: Any, **kwargs: Any) -> Any: ...
def _compact_reconciliation_ref_counts(*args: Any, **kwargs: Any) -> Any: ...
def _as_aware_utc(*args: Any, **kwargs: Any) -> Any: ...
def _uuid_or_none(*args: Any, **kwargs: Any) -> Any: ...
def _usd_to_micros(*args: Any, **kwargs: Any) -> Any: ...
def _execution_amount_micros(*args: Any, **kwargs: Any) -> Any: ...
def _cost_amount_micros(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_amount_micros(*args: Any, **kwargs: Any) -> Any: ...
def _archived_runtime_ledger_amount_micros(*args: Any, **kwargs: Any) -> Any: ...
def _archived_source_amount_micros(*args: Any, **kwargs: Any) -> Any: ...
def _legacy_unversioned_source_ref(*args: Any, **kwargs: Any) -> Any: ...
def _expected_source_amount_micros(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_ref_is_signed(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_payload_account_ids(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_ref_coverage(*args: Any, **kwargs: Any) -> Any: ...
def _runtime_ledger_ref_matches_expected_bucket(*args: Any, **kwargs: Any) -> Any: ...
def _reconciliation_transfer_refs(*args: Any, **kwargs: Any) -> Any: ...
def tigerbeetle_ref_counts(*args: Any, **kwargs: Any) -> Any: ...
def _latest_run_payload(*args: Any, **kwargs: Any) -> Any: ...
def _latest_run_compact_status_payload(*args: Any, **kwargs: Any) -> Any: ...
def latest_tigerbeetle_reconciliation_status_payload(
    *args: Any, **kwargs: Any
) -> Any: ...
def latest_tigerbeetle_reconciliation_payload(*args: Any, **kwargs: Any) -> Any: ...
def reconcile_tigerbeetle_transfers(*args: Any, **kwargs: Any) -> Any: ...
