from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from decimal import Decimal
import hashlib
import json
from types import TracebackType
from typing import Any, Self, cast
from sqlalchemy import or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session
from app.config import Settings, settings
from app.models import (
    Execution,
    ExecutionOrderEvent,
    ExecutionTCAMetric,
    StrategyRuntimeLedgerBucket,
    TigerBeetleAccountRef,
    TigerBeetleTransferRef,
    coerce_json_payload,
)
from app.trading.tigerbeetle_client import (
    TigerBeetleClientProtocol,
    create_tigerbeetle_client,
)
from app.trading.tigerbeetle_ids import stable_ref_u128, stable_u128, u128_decimal
from app.trading.tigerbeetle_ledger_model import (
    ACCOUNT_CODE_CASH_CONTROL,
    ACCOUNT_CODE_EVIDENCE_CONTROL,
    ACCOUNT_CODE_EXECUTION_COST,
    ACCOUNT_CODE_EXECUTION_EVIDENCE,
    ACCOUNT_CODE_FILL_NOTIONAL,
    ACCOUNT_CODE_ORDER_HOLD,
    ACCOUNT_CODE_REALIZED_PNL,
    ACCOUNT_CODE_RUNTIME_LEDGER_EVIDENCE,
    LEDGER_USD_MICRO,
    PNL_DIRECTION_LOSS,
    PNL_DIRECTION_PROFIT,
    TRANSFER_KIND_CANCEL_VOID,
    TRANSFER_KIND_EXECUTION_COST,
    TRANSFER_KIND_EXECUTION_FILL,
    TRANSFER_KIND_FILL_POST,
    TRANSFER_KIND_REJECT_VOID,
    TRANSFER_KIND_RUNTIME_NET_PNL,
    TRANSFER_KIND_SUBMITTED_PENDING,
    TigerBeetleAccountSpec,
    TigerBeetleTransferSpec,
    decimal_usd_to_nearest_micros,
    transfer_code_for_kind,
    transfer_kind_for_event,
)

SOURCE_TYPE_EXECUTION: Any
SOURCE_TYPE_EXECUTION_ORDER_EVENT: Any
SOURCE_TYPE_EXECUTION_TCA_METRIC: Any
SOURCE_TYPE_RUNTIME_LEDGER_BUCKET: Any
TIGERBEETLE_RUNTIME_LEDGER_JOURNAL_PARITY_SCHEMA_VERSION: Any
TIGERBEETLE_STABLE_REF_SCHEMA_VERSION: Any
TIGERBEETLE_STABLE_REF_NAMESPACE: Any
TIGERBEETLE_RUNTIME_LEDGER_JOURNAL_STATUS_PASS: Any
TIGERBEETLE_RUNTIME_LEDGER_JOURNAL_STATUS_NON_AUTHORITY_BLOCKED: Any
TIGERBEETLE_BLOCKER_JOURNAL_DISABLED: Any
TIGERBEETLE_BLOCKER_JOURNAL_ENTRY_UNAVAILABLE: Any
TIGERBEETLE_BLOCKER_JOURNAL_ERROR: Any
TIGERBEETLE_BLOCKER_TRANSFER_REF_CONFLICT: Any
TIGERBEETLE_AUTHORITY_BLOCKER_ACCOUNTING_ONLY: Any
TIGERBEETLE_AUTHORITY_BLOCKER_RUNTIME_LEDGER_SOURCE_REFS_MISSING: Any
TIGERBEETLE_AUTHORITY_BLOCKER_RUNTIME_LEDGER_SOURCE_WINDOW_REFS_MISSING: Any

def _official_status_name(*args: Any, **kwargs: Any) -> Any: ...
def _normalize_result_status(*args: Any, **kwargs: Any) -> Any: ...
def _result_status(*args: Any, **kwargs: Any) -> Any: ...
def _result_index(*args: Any, **kwargs: Any) -> Any: ...
def _result_statuses_by_index(*args: Any, **kwargs: Any) -> Any: ...
def _transfer_attr(*args: Any, **kwargs: Any) -> Any: ...
def _lookup_payload_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _nested_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _stable_ref_source_signature(*args: Any, **kwargs: Any) -> Any: ...
def _stable_ref_account_label(*args: Any, **kwargs: Any) -> Any: ...
def _payload_account_ids(*args: Any, **kwargs: Any) -> Any: ...
def tigerbeetle_stable_ref_payload(*args: Any, **kwargs: Any) -> Any: ...
def _payload_text_list(*args: Any, **kwargs: Any) -> Any: ...
def runtime_ledger_bucket_source_authority_blockers(
    *args: Any, **kwargs: Any
) -> Any: ...
def _positive_payload_count(*args: Any, **kwargs: Any) -> Any: ...
def tigerbeetle_runtime_ledger_journal_payload(*args: Any, **kwargs: Any) -> Any: ...

FILL_POST_EVENT_TYPES: Any

def _event_amount_usd(*args: Any, **kwargs: Any) -> Any: ...
def _explicit_fill_delta_notional_usd(*args: Any, **kwargs: Any) -> Any: ...
def _event_cumulative_amount_usd(*args: Any, **kwargs: Any) -> Any: ...
def _prior_cumulative_fill_notional_usd(*args: Any, **kwargs: Any) -> Any: ...
def _is_fill_post_event(*args: Any, **kwargs: Any) -> Any: ...
def _order_event_precedes(*args: Any, **kwargs: Any) -> Any: ...
def _account_id(*args: Any, **kwargs: Any) -> Any: ...

class TigerBeetleOrderEventTransferPlan:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    account_specs: tuple[TigerBeetleAccountSpec, ...]
    transfer_spec: TigerBeetleTransferSpec
    transfer_kind: str
    pending_mode: str

class TigerBeetleRuntimeLedgerTransferPlan:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    account_specs: tuple[TigerBeetleAccountSpec, ...]
    transfer_spec: TigerBeetleTransferSpec
    amount_source: Decimal
    signed_amount_micros: int
    pnl_direction: str
    runtime_key: str

class TigerBeetleSourceTransferPlan:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    account_specs: tuple[TigerBeetleAccountSpec, ...]
    transfer_spec: TigerBeetleTransferSpec
    amount_source: Decimal

class _PreparedTigerBeetleTransferWrite:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    account_specs: tuple[TigerBeetleAccountSpec, ...]
    transfer_spec: TigerBeetleTransferSpec
    trade_decision_id: object | None
    execution_id: object | None
    execution_order_event_id: object | None
    execution_tca_metric_id: object | None
    runtime_ledger_bucket_id: object | None
    event_fingerprint: str | None
    source_type: str
    source_id: str
    payload_json: Mapping[str, object]

def _submitted_pending_key(*args: Any, **kwargs: Any) -> Any: ...
def _economic_decimal_text(*args: Any, **kwargs: Any) -> Any: ...
def _economic_text(*args: Any, **kwargs: Any) -> Any: ...
def _source_revision_id(*args: Any, **kwargs: Any) -> Any: ...
def execution_economic_event_key(*args: Any, **kwargs: Any) -> Any: ...
def execution_source_id(*args: Any, **kwargs: Any) -> Any: ...
def execution_tca_metric_economic_event_key(*args: Any, **kwargs: Any) -> Any: ...
def execution_tca_metric_source_id(*args: Any, **kwargs: Any) -> Any: ...
def submitted_pending_transfer_id(*args: Any, **kwargs: Any) -> Any: ...
def event_transfer_id(*args: Any, **kwargs: Any) -> Any: ...
def execution_transfer_id(*args: Any, **kwargs: Any) -> Any: ...
def execution_cost_transfer_id(*args: Any, **kwargs: Any) -> Any: ...
def runtime_ledger_transfer_id(*args: Any, **kwargs: Any) -> Any: ...
def runtime_ledger_amount_source(*args: Any, **kwargs: Any) -> Any: ...
def _account_specs(*args: Any, **kwargs: Any) -> Any: ...
def _evidence_account_specs(*args: Any, **kwargs: Any) -> Any: ...
def _transfer_flag(*args: Any, **kwargs: Any) -> Any: ...
def _transfer_spec(*args: Any, **kwargs: Any) -> Any: ...
def _pending_transfer_ref_for_event(*args: Any, **kwargs: Any) -> Any: ...
def build_order_event_transfer_plan(*args: Any, **kwargs: Any) -> Any: ...
def _persist_account_refs(*args: Any, **kwargs: Any) -> Any: ...
def _dedupe_account_specs(*args: Any, **kwargs: Any) -> Any: ...
def _transfer_matches(*args: Any, **kwargs: Any) -> Any: ...
def _transfer_ref_mismatches(*args: Any, **kwargs: Any) -> Any: ...
def _assert_transfer_ref_matches(*args: Any, **kwargs: Any) -> Any: ...
def _find_transfer_ref(*args: Any, **kwargs: Any) -> Any: ...
def _merge_existing_transfer_ref(*args: Any, **kwargs: Any) -> Any: ...
def _source_transfer_spec(*args: Any, **kwargs: Any) -> Any: ...
def _execution_notional_usd(*args: Any, **kwargs: Any) -> Any: ...
def _amount_to_micros(*args: Any, **kwargs: Any) -> Any: ...
def build_runtime_ledger_bucket_transfer_plan(*args: Any, **kwargs: Any) -> Any: ...
def build_execution_transfer_plan(*args: Any, **kwargs: Any) -> Any: ...
def build_execution_tca_metric_transfer_plan(*args: Any, **kwargs: Any) -> Any: ...

class TigerBeetleLedgerJournal:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def __enter__(*args: Any, **kwargs: Any) -> Any: ...
    def __exit__(*args: Any, **kwargs: Any) -> Any: ...
    def _client_for_write(*args: Any, **kwargs: Any) -> Any: ...
    def client_for_reconciliation(*args: Any, **kwargs: Any) -> Any: ...
    def close(*args: Any, **kwargs: Any) -> Any: ...
    def _payload_with_stable_ref(*args: Any, **kwargs: Any) -> Any: ...
    def _persist_written_transfer_ref(*args: Any, **kwargs: Any) -> Any: ...
    def _persist_transfer_batch(*args: Any, **kwargs: Any) -> Any: ...
    def _persist_transfer(*args: Any, **kwargs: Any) -> Any: ...
    def backfill_stable_ref_payloads(*args: Any, **kwargs: Any) -> Any: ...
    def journal_order_events(*args: Any, **kwargs: Any) -> Any: ...
    def journal_executions(*args: Any, **kwargs: Any) -> Any: ...
    def journal_execution_tca_metrics(*args: Any, **kwargs: Any) -> Any: ...
    def journal_runtime_ledger_buckets(*args: Any, **kwargs: Any) -> Any: ...
    def journal_order_event(*args: Any, **kwargs: Any) -> Any: ...
    def journal_execution(*args: Any, **kwargs: Any) -> Any: ...
    def journal_execution_tca_metric(*args: Any, **kwargs: Any) -> Any: ...
    def journal_runtime_ledger_bucket(*args: Any, **kwargs: Any) -> Any: ...
