export const MAX_DESKTOP_WINDOWS = 20
export const MAX_CODE_WATCH_DIRECTORIES = 16
export const EVENT_STREAM_RECONNECT_OVERLAP = 2
export const MAX_EVENT_STREAMS_PER_SUBJECT =
  MAX_DESKTOP_WINDOWS * MAX_CODE_WATCH_DIRECTORIES * EVENT_STREAM_RECONNECT_OVERLAP
