from __future__ import annotations

# ruff: noqa: F401,F403,F405
__test__ = False
from tests.runtime_ledger.test_closed_round_trip_pnl_uses_net_after_explicit_costs import (
    test_carry_in_non_promotion_cost_basis_blocks_bucket,
    test_closed_round_trip_pnl_uses_net_after_explicit_costs,
    test_explicit_costs_are_deducted_from_gross_pnl,
    test_grouped_buckets_preserve_runtime_identity_fields,
    test_grouped_positions_carry_across_bucket_boundaries,
    test_invalid_bucket_range_is_rejected_before_profit_proof,
    test_invalid_runtime_fill_fields_fail_closed,
    test_missing_price_notional_and_cost_basis_are_blockers,
    test_order_feed_source_fill_requires_delta_basis,
    test_partial_unclosed_positions_report_realized_pnl_but_block_expectancy,
    test_positions_carry_across_bucket_boundaries,
    test_post_cost_expectancy_is_notional_weighted_across_closed_trips,
    test_reversal_closes_long_then_realizes_short_pnl_after_costs,
    test_sell_without_carry_in_stays_fail_closed,
    test_source_backed_carry_in_closes_position_opened_before_bucket,
    test_tca_shortfall_rows_do_not_count_as_strategy_pnl,
    test_tigerbeetle_execution_cost_journal_failure_blocks_authority,
)
from tests.runtime_ledger.test_order_feed_lifecycle_fill_without_execution_economics_is_not_pnl_proof import (
    test_execution_economics_requires_matching_order_feed_fill_lifecycle,
    test_execution_economics_with_linked_order_feed_lifecycle_satisfies_runtime_inputs,
    test_linked_order_feed_fill_accepts_structured_source_offsets_mapping,
    test_linked_order_feed_fill_materializes_fill_economics_lineage,
    test_linked_order_feed_fill_without_explicit_costs_stays_non_authority,
    test_non_promotion_source_marker_strings_block_fill_authority,
    test_order_feed_lifecycle_fill_without_execution_economics_is_not_pnl_proof,
    test_order_feed_source_fill_accepts_authority_class_marker,
    test_order_feed_source_fill_requires_positive_delta_quantity,
    test_order_feed_source_fill_uses_delta_not_cumulative_quantity,
    test_probe_route_order_feed_fill_remains_non_promotion_authority,
    test_source_authority_lifecycle_rows_can_be_clean_evidence_candidate,
    test_source_materialized_fill_requires_execution_refs_for_authority,
)
from tests.runtime_ledger.test_source_authority_unfilled_order_keeps_realized_expectancy_blocked import (
    test_aggregate_only_source_bucket_remains_blocked_from_authority,
    test_exact_replay_ledger_does_not_use_idempotency_key_as_policy_hash,
    test_exact_replay_ledger_requires_order_lifecycle_and_hash_lineage,
    test_execution_reconstruction_rows_do_not_become_runtime_authority,
    test_fill_quantity_basis_aliases_are_normalized,
    test_promotion_authority_class_also_requires_source_materialization,
    test_promotion_authority_class_requires_source_refs_without_lifecycle_gate,
    test_runtime_ledger_blocks_non_promotion_grade_cost_basis_at_builder,
    test_runtime_ledger_cost_hash_belongs_to_fill_economics_not_lifecycle,
    test_source_authority_extra_submitted_order_does_not_block_closed_trip,
    test_source_authority_missing_closed_round_trip_blocks_bucket,
    test_source_authority_missing_notional_and_cost_basis_block_expectancy,
    test_source_authority_open_position_blocks_final_expectancy,
    test_source_authority_requires_closed_lifecycle_even_without_lifecycle_gate,
    test_source_authority_unfilled_order_keeps_realized_expectancy_blocked,
    test_source_decision_collection_mode_is_not_profit_proof_eligible,
)
from tests.runtime_ledger.test_runtime_ledger_defensively_blocks_usable_non_promotion_grade_cost_basis import (
    test_cancelled_zero_fill_order_does_not_remain_unfilled,
    test_exact_replay_ledger_accepts_multiple_partial_fills_for_one_order,
    test_exact_replay_ledger_blocks_fill_only_profit_proof,
    test_exact_replay_ledger_blocks_unfilled_or_unhashed_order_lifecycle,
    test_runtime_ledger_defensively_blocks_usable_non_promotion_grade_cost_basis,
)
