from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401, F811
from typing import Any
import json
import logging
import os
import tempfile
from collections.abc import Mapping, Sequence
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any, Literal, Optional, cast
from ...config import settings
from ..autonomy import (
    DriftThresholds,
    DriftTriggerPolicy,
    decide_drift_action,
    detect_drift,
    evaluate_live_promotion_evidence,
    evaluate_evidence_continuity,
    run_autonomous_lane,
    upsert_autonomy_no_signal_run,
)
from ..autonomy.phase_manifest_contract import (
    build_phase_manifest_payload_with_runtime_and_rollback,
    coerce_path_strings,
)
from ..feature_quality import FeatureQualityThresholds, evaluate_feature_batch_quality
from ..ingest import SignalBatch
from ..models import SignalEnvelope
from ..time_source import trading_now
from .pipeline import TradingPipeline
from .state import TradingState

logger: Any
_FRESH_TAIL_NO_SIGNAL_REASONS: Any
_coerce_recovery_reason_sequence: Any
_is_market_session_open: Any
_is_recoverable_emergency_stop_reason: Any
_latch_signal_continuity_alert_state: Any
_merge_emergency_stop_reasons: Any
_record_signal_continuity_recovery_cycle: Any
_signal_bootstrap_grace_active: Any
_signal_tail_is_fresh: Any
_split_emergency_stop_reasons: Any

def _resolve_autonomy_artifact_root(*args: Any, **kwargs: Any) -> Any: ...
def _int_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _incident_payload_complete(*args: Any, **kwargs: Any) -> Any: ...
def _parse_iso_datetime(*args: Any, **kwargs: Any) -> Any: ...

class TradingSchedulerGovernanceMixin:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    state: TradingState
    _pipeline: Optional[TradingPipeline]
    _pipelines: list[TradingPipeline]
    def _emit_autonomy_domain_telemetry(*args: Any, **kwargs: Any) -> Any: ...
    def _drift_thresholds(*args: Any, **kwargs: Any) -> Any: ...
    def _drift_trigger_policy(*args: Any, **kwargs: Any) -> Any: ...
    def _current_drift_gate_evidence(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_drift_governance(*args: Any, **kwargs: Any) -> Any: ...
    def _drawdown_from_gate_payload(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_safety_controls(*args: Any, **kwargs: Any) -> Any: ...
    def _collect_emergency_stop_reasons(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_emergency_stop_recovery(*args: Any, **kwargs: Any) -> Any: ...
    def _clear_emergency_stop(*args: Any, **kwargs: Any) -> Any: ...
    def _is_market_session_open(*args: Any, **kwargs: Any) -> Any: ...
    def _load_latest_drawdown_from_gate(*args: Any, **kwargs: Any) -> Any: ...
    def _governance_now(*args: Any, **kwargs: Any) -> Any: ...
    def _trigger_emergency_stop(*args: Any, **kwargs: Any) -> Any: ...
    def _load_last_gate_provenance(*args: Any, **kwargs: Any) -> Any: ...
    def _run_evidence_continuity_check(*args: Any, **kwargs: Any) -> Any: ...
    def _run_autonomous_cycle(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_autonomy_config_paths(*args: Any, **kwargs: Any) -> Any: ...
    def _build_autonomy_execution_context(*args: Any, **kwargs: Any) -> Any: ...
    def _record_autonomy_batch_state(*args: Any, **kwargs: Any) -> Any: ...
    def _refresh_autonomy_universe_state(*args: Any, **kwargs: Any) -> Any: ...
    def _handle_autonomy_no_signal_cycle(*args: Any, **kwargs: Any) -> Any: ...
    def _prepare_autonomy_signal_artifacts(*args: Any, **kwargs: Any) -> Any: ...
    def _next_autonomy_iteration(*args: Any, **kwargs: Any) -> Any: ...
    def _iteration_notes_path(*args: Any, **kwargs: Any) -> Any: ...
    def _write_autonomy_iteration_notes(*args: Any, **kwargs: Any) -> Any: ...
    def _reset_autonomy_signal_state(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_autonomy_promotion_target(*args: Any, **kwargs: Any) -> Any: ...
    def _execute_autonomous_lane(*args: Any, **kwargs: Any) -> Any: ...
    def _clear_autonomy_result_state(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_autonomy_lane_result(*args: Any, **kwargs: Any) -> Any: ...
    def _append_runtime_governance_to_phase_manifest(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _update_autonomy_recommendation_state(*args: Any, **kwargs: Any) -> Any: ...
    def _update_autonomy_throughput_state(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
