from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import hashlib
import json
import inspect
import logging
import os
from collections.abc import Callable, Mapping
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any, Optional, Sequence, cast
from sqlalchemy import select
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session
from ...alpaca_client import TorghutAlpacaClient
from ...config import settings
from ...db import SessionLocal
from ...models import (
    Execution,
    LLMDecisionReview,
    PositionSnapshot,
    RejectedSignalOutcomeEvent,
    Strategy,
    TradeDecision,
    coerce_json_payload,
)
from ...observability import capture_posthog_event
from ...snapshots import snapshot_account_and_positions
from ...strategies import StrategyCatalog
from ..autonomy.phase_manifest_contract import AUTONOMY_PHASE_ORDER
from ..decisions import DecisionEngine
from ..empirical_jobs import build_empirical_jobs_status
from ..execution import OrderExecutor
from ..execution_adapters import ExecutionAdapter
from ..execution_policy import ExecutionPolicy
from ..feature_quality import (
    REASON_STALENESS,
    FeatureQualityThresholds,
    evaluate_feature_batch_quality,
)
from ..features import extract_executable_price, optional_decimal, payload_value
from ..firewall import OrderFirewall, OrderFirewallBlocked
from ..ingest import ClickHouseSignalIngestor, SignalBatch
from ..lean_lanes import LeanLaneManager
from ..llm import LLMReviewEngine, apply_policy
from ..llm.dspy_programs.runtime import (
    DSPyReviewRuntime,
    DSPyRuntimeUnsupportedStateError,
)
from ..llm.guardrails import evaluate_llm_guardrails
from ..llm.policy import allowed_order_types
from ..llm.schema import MarketContextBundle
from ..llm.schema import MarketSnapshot as LLMMarketSnapshot
from ..market_context import (
    MarketContextClient,
    MarketContextStatus,
    evaluate_market_context,
)
from ..market_context_domains import (
    active_market_context_domain_states,
    active_market_context_reasons,
)
from ..models import SignalEnvelope, StrategyDecision
from ..order_feed import OrderFeedIngestor
from ..paper_route_evidence import (
    PAPER_ROUTE_ACCOUNT_PRE_SESSION_READINESS_SECONDS,
    PAPER_ROUTE_ACCOUNT_START_SNAPSHOT_AFTER_START_GRACE_SECONDS,
)
from ..portfolio import (
    AllocationResult,
    PortfolioSizingResult,
    allocator_from_settings,
    sizer_from_settings,
)
from ..prices import ClickHousePriceFetcher, MarketSnapshot, PriceFetcher
from ..quote_quality import (
    QuoteQualityPolicy,
    QuoteQualityStatus,
    SignalQuoteQualityTracker,
    assess_signal_quote_quality,
)
from ..quantity_rules import (
    min_qty_for_symbol,
    quantize_qty_for_symbol,
    resolve_quantity_resolution,
)
from ..reconcile import Reconciler
from ..regime_hmm import (
    HMMRegimeContext,
    resolve_hmm_context,
    resolve_regime_context_authority_reason,
)
from ..risk import RiskEngine
from ..session_context import regular_session_open_utc_for
from ..tca import derive_adaptive_execution_policy
from ..time_source import trading_now
from ..universe import UniverseResolver
from ..submission_council import (
    build_hypothesis_runtime_summary,
    build_live_submission_gate_payload,
    build_submission_gate_market_context_status,
    load_quant_evidence_status,
)
from .pipeline_helpers import (
    _allocator_rejection_reasons,
    _apply_projected_position_decision,
    _attach_dspy_lineage,
    _autonomy_gate_report_is_saturated_fail_sentinel,
    _build_committee_veto_alignment_payload,
    _build_llm_policy_resolution,
    _build_portfolio_snapshot,
    _classify_llm_error,
    _clone_positions,
    _coerce_bool,
    _coerce_json,
    _coerce_runtime_uncertainty_gate_action,
    _coerce_strategy_symbols,
    _committee_trace_has_veto,
    _extract_json_error_payload,
    _format_order_submit_rejection,
    _hash_payload,
    _is_runtime_risk_increasing_entry,
    _llm_guardrail_controls_snapshot,
    _load_recent_decisions,
    _normalize_rollout_stage,
    _optional_decimal,
    _optional_int,
    _price_snapshot_payload,
    _project_open_orders_onto_positions,
    _resolve_decision_regime_label_with_source,
    _resolve_llm_review_error_reject_reason,
    _resolve_llm_unavailable_reject_reason,
    _resolve_signal_regime,
    _select_strictest_runtime_uncertainty_gate,
    _uncertainty_gate_staleness_reason,
)
from .safety import (
    _FRESH_TAIL_NO_SIGNAL_REASONS,
    _is_market_session_open,
    _latch_signal_continuity_alert_state,
    _record_signal_continuity_recovery_cycle,
    _signal_bootstrap_grace_active,
    _signal_tail_is_fresh,
)
from .state import (
    RuntimeUncertaintyGate,
    RuntimeUncertaintyGateAction,
    TradingState,
    _normalize_reason_metric,
)

logger: Any
_REJECTED_SIGNAL_OUTCOME_FOLLOWUP_HORIZON: Any
_REJECTED_SIGNAL_OUTCOME_LABEL_LIMIT: Any
_AUTONOMY_PHASE_ORDER: tuple[str, ...]
_RUNTIME_UNCERTAINTY_DEGRADE_QTY_MULTIPLIER: Any
_RUNTIME_UNCERTAINTY_DEGRADE_MAX_PARTICIPATION_RATE: Any
_RUNTIME_UNCERTAINTY_DEGRADE_MIN_EXECUTION_SECONDS: Any
_RUNTIME_REGIME_CONFIDENCE_DEFAULT_THRESHOLDS: Any
_STRATEGY_POSITION_TAG_TOLERANCE: Any
_STRATEGY_POSITION_TAG_LOOKBACK: Any

def _normalized_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _aware_utc(*args: Any, **kwargs: Any) -> Any: ...

class TradingPipeline:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def run_once(*args: Any, **kwargs: Any) -> Any: ...
    def _prepare_run_once(*args: Any, **kwargs: Any) -> Any: ...
    def _warm_session_context_from_open(*args: Any, **kwargs: Any) -> Any: ...
    def _capture_runtime_window_account_snapshot_if_due(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _record_ingest_window(*args: Any, **kwargs: Any) -> Any: ...
    def _prepare_batch_for_decisions(*args: Any, **kwargs: Any) -> Any: ...
    def _quality_gate_signals(*args: Any, **kwargs: Any) -> Any: ...
    def _relevant_signal_symbols(*args: Any, **kwargs: Any) -> Any: ...
    def _build_run_context(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_execution_context_positions(*args: Any, **kwargs: Any) -> Any: ...
    def _attach_current_session_strategy_position_tags(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _same_side_position_exposure(*args: Any, **kwargs: Any) -> Any: ...
    def _attach_strategy_position_tag(*args: Any, **kwargs: Any) -> Any: ...
    def _attach_strategy_position_tags(*args: Any, **kwargs: Any) -> Any: ...
    def _split_strategy_position_tags(*args: Any, **kwargs: Any) -> Any: ...
    def _strategy_tagged_position(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_execution_context_open_orders(*args: Any, **kwargs: Any) -> Any: ...
    def _process_batch_signals(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_signal_decisions(*args: Any, **kwargs: Any) -> Any: ...
    def _record_rejected_signal_outcome_event(*args: Any, **kwargs: Any) -> Any: ...
    def _rejected_signal_outcome_event_id(*args: Any, **kwargs: Any) -> Any: ...
    def _persist_rejected_signal_outcome_event(*args: Any, **kwargs: Any) -> Any: ...
    def _label_mature_rejected_signal_outcome_events(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _build_rejected_signal_outcome_payload(*args: Any, **kwargs: Any) -> Any: ...
    def _ensure_signal_executable_price(*args: Any, **kwargs: Any) -> Any: ...
    def _feature_quality_failure_payload(*args: Any, **kwargs: Any) -> Any: ...
    def _record_quantity_resolution_metrics(*args: Any, **kwargs: Any) -> Any: ...
    def _position_qty_for_symbol(*args: Any, **kwargs: Any) -> Any: ...
    def _sell_inventory_context(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_allocation_results(*args: Any, **kwargs: Any) -> Any: ...
    def _ingest_order_feed(*args: Any, **kwargs: Any) -> Any: ...
    def record_no_signal_batch(*args: Any, **kwargs: Any) -> Any: ...
    def _is_actionable_no_signal_reason(*args: Any, **kwargs: Any) -> Any: ...
    def _is_market_session_open(*args: Any, **kwargs: Any) -> Any: ...
    def reconcile(*args: Any, **kwargs: Any) -> Any: ...
    def _handle_decision(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_strategy_context(*args: Any, **kwargs: Any) -> Any: ...
    def _decision_row_age_seconds(*args: Any, **kwargs: Any) -> Any: ...
    def _dspy_runtime_gate_status(*args: Any, **kwargs: Any) -> Any: ...
    def _live_submission_gate(*args: Any, **kwargs: Any) -> Any: ...
    def _submission_capital_stage(*args: Any, **kwargs: Any) -> Any: ...
    def _submission_control_plane_snapshot(*args: Any, **kwargs: Any) -> Any: ...
    def _decision_lifecycle_metadata(*args: Any, **kwargs: Any) -> Any: ...
    def _block_decision_submission(*args: Any, **kwargs: Any) -> Any: ...
    def _ensure_pending_decision_row(*args: Any, **kwargs: Any) -> Any: ...
    def _expire_stale_planned_decision(*args: Any, **kwargs: Any) -> Any: ...
    def _prepare_decision_for_submission(*args: Any, **kwargs: Any) -> Any: ...
    def _record_runtime_uncertainty_gate_result(*args: Any, **kwargs: Any) -> Any: ...
    def _persist_runtime_uncertainty_gate_payload(*args: Any, **kwargs: Any) -> Any: ...
    def _should_degrade_runtime_uncertainty_fail(*args: Any, **kwargs: Any) -> Any: ...
    def _should_degrade_runtime_uncertainty_fail_from_payload(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _degrade_runtime_uncertainty_gate_decision(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _recheck_runtime_uncertainty_gate_after_llm(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _record_decision_rejection(*args: Any, **kwargs: Any) -> Any: ...
    def _emit_domain_telemetry(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_execution_policy_outcome(*args: Any, **kwargs: Any) -> Any: ...
    def _passes_risk_verdict(*args: Any, **kwargs: Any) -> Any: ...
    def _is_trading_submission_allowed(*args: Any, **kwargs: Any) -> Any: ...
    def _submit_decision_execution(*args: Any, **kwargs: Any) -> Any: ...
    def _maybe_record_lean_strategy_shadow(*args: Any, **kwargs: Any) -> Any: ...
    def _submit_order_with_handling(*args: Any, **kwargs: Any) -> Any: ...
    def _record_simulation_position_state(*args: Any, **kwargs: Any) -> Any: ...
    def _handle_execution_fallback(*args: Any, **kwargs: Any) -> Any: ...
    def _record_lean_shadow_from_execution(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_runtime_uncertainty_gate_components(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _resolve_runtime_uncertainty_gate(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_runtime_uncertainty_degrade_profile(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _resolve_runtime_uncertainty_gate_from_inputs(
        *args: Any, **kwargs: Any
    ) -> Any: ...
    def _resolve_runtime_regime_gate(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_runtime_regime_confidence_gate(*args: Any, **kwargs: Any) -> Any: ...
    def _extract_top_regime_posterior_probability(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_regime_confidence_thresholds(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_runtime_uncertainty_gate(*args: Any, **kwargs: Any) -> Any: ...
    def _execution_client_for_symbol(*args: Any, **kwargs: Any) -> Any: ...
    def _execution_client_name(*args: Any, **kwargs: Any) -> Any: ...
    def _sync_lean_observability(*args: Any, **kwargs: Any) -> Any: ...
    def _evaluate_lean_canary_guard(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_portfolio_sizing(*args: Any, **kwargs: Any) -> Any: ...
    def _load_strategies(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_llm_review(*args: Any, **kwargs: Any) -> Any: ...
    def _record_llm_policy_resolution_metrics(*args: Any, **kwargs: Any) -> Any: ...
    def _handle_llm_guardrail_block(*args: Any, **kwargs: Any) -> Any: ...
    def _handle_llm_circuit_open(*args: Any, **kwargs: Any) -> Any: ...
    def _handle_llm_dspy_live_runtime_block(*args: Any, **kwargs: Any) -> Any: ...
    def _classify_dspy_live_runtime_block(*args: Any, **kwargs: Any) -> Any: ...
    def _bounded_degraded_qty(*args: Any, **kwargs: Any) -> Any: ...
    def _degrade_llm_runtime_block_qty(*args: Any, **kwargs: Any) -> Any: ...
    def _run_llm_review_request(*args: Any, **kwargs: Any) -> Any: ...
    def _maybe_handle_market_context_block(*args: Any, **kwargs: Any) -> Any: ...
    def _record_market_context_observation(*args: Any, **kwargs: Any) -> Any: ...
    def _record_llm_verdict_counter(*args: Any, **kwargs: Any) -> Any: ...
    def _build_llm_response_json(*args: Any, **kwargs: Any) -> Any: ...
    def _record_llm_committee_metrics(*args: Any, **kwargs: Any) -> Any: ...
    def _record_llm_token_metrics(*args: Any, **kwargs: Any) -> Any: ...
    def _apply_llm_policy_verdict(*args: Any, **kwargs: Any) -> Any: ...
    def _finalize_llm_review_outcome(*args: Any, **kwargs: Any) -> Any: ...
    def _handle_llm_review_error(*args: Any, **kwargs: Any) -> Any: ...
    def _handle_llm_unavailable(*args: Any, **kwargs: Any) -> Any: ...
    def _build_market_snapshot(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_pre_llm_executability_reject(*args: Any, **kwargs: Any) -> Any: ...
    def _ensure_decision_price(*args: Any, **kwargs: Any) -> Any: ...
    def _resolve_llm_fallback(*args: Any, **kwargs: Any) -> Any: ...
    def _llm_runtime_model_identifier(*args: Any, **kwargs: Any) -> Any: ...
    def _llm_runtime_prompt_identifier(*args: Any, **kwargs: Any) -> Any: ...
    def _fetch_market_context(*args: Any, **kwargs: Any) -> Any: ...
    def _get_account_snapshot(*args: Any, **kwargs: Any) -> Any: ...
    def _persist_llm_review(*args: Any, **kwargs: Any) -> Any: ...
    def _persist_llm_adjusted_decision(*args: Any, **kwargs: Any) -> Any: ...

__all__: Any
