from __future__ import annotations

# pyright: reportMissingImports=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false
# ruff: noqa: F401, F811
from typing import Any
import logging
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Literal, TypeAlias, cast
from ...config import settings
from ...models import Strategy
from ...strategies.catalog import extract_catalog_metadata
from ..autonomy import DriftThresholds
from ..feature_quality import FeatureQualityThresholds
from ..models import StrategyDecision
from ..runtime_decision_authority import (
    BOUNDED_PAPER_ROUTE_COLLECTION_SOURCE_DECISION_MODE,
    ROUTE_ACQUISITION_SOURCE_DECISION_MODE,
    STRATEGY_SIGNAL_PAPER_SOURCE_DECISION_MODE,
    normalize_source_decision_mode,
)
from ..runtime_strategy_resolution import strategy_names_from_strategy_id
from ..simple_risk import position_qty_for_symbol

logger: Any
_SIMPLE_ALLOWED_REJECT_REASONS: Any
_PAPER_ROUTE_PROBE_REASONS: Any
_PaperRouteRetryKind: TypeAlias
_PAPER_ROUTE_RETRY_KINDS: frozenset[_PaperRouteRetryKind]
_PROFITABILITY_PROOF_FLOOR_TCA_MAX_AGE_SECONDS: Any
_SIMPLE_MARKET_CONTEXT_RETRY_INTERVAL: Any
_PAPER_ROUTE_PROBE_QTY_STEP: Any
_REGULAR_SESSION_MINUTES: Any
_PAPER_ROUTE_TARGET_PLAN_FETCH_ATTEMPTS: Any
_PAPER_ROUTE_TARGET_PLAN_CACHE_SECONDS: Any
_PAPER_ROUTE_TARGET_PLAN_STALE_SUCCESS_SECONDS: Any
_PAPER_ROUTE_TARGET_PROFIT_PROOF_EXPOSURE_LOOKBACK: Any
_PAPER_ROUTE_TARGET_OPEN_EXPOSURE_EPSILON: Any
_SIGNAL_INGEST_UNAVAILABLE_REASONS: Any
_BOUNDED_SIM_COLLECTION_ACCOUNT_LABEL: Any
_BOUNDED_SIM_COLLECTION_SOURCE_KIND: Any
_BOUNDED_SIM_COLLECTION_SOURCE_KINDS: Any
_BOUNDED_SIM_COLLECTION_SCOPE: Any
_BOUNDED_SIM_COLLECTION_BLOCKER_FIELDS: Any
_BOUNDED_SIM_COLLECTION_RESERVATION_BLOCKERS: Any
_PAPER_ROUTE_TARGET_ACCOUNT_AUDIT_UNAVAILABLE_BLOCKER: Any
_BOUNDED_PAPER_ROUTE_DEFAULT_CLOSEOUT_BUFFER_MINUTES: Any
_PAPER_ROUTE_PROBE_EXIT_PENDING_GRACE_SECONDS: Any
_BOUNDED_SIM_COLLECTION_ALLOWED_HEALTH_GATE_BLOCKERS: Any
_BOUNDED_SIM_COLLECTION_SOURCE_AUTHORIZED_SUPERSEDED_BLOCKERS: Any
_BOUNDED_SIM_COLLECTION_LINEAGE_KEYS: Any
_BOUNDED_SIM_COLLECTION_LINEAGE_BOOL_KEYS: Any
_BOUNDED_SIM_COLLECTION_LINEAGE_MAPPING_KEYS: Any
_FLATTEN_CLOSE_DECISION_SCHEMA_VERSION: Any
_BOUNDED_SIM_COLLECTION_RUNTIME_ACCOUNT_ALIAS_FIELDS: Any
_BOUNDED_SIM_COLLECTION_SOURCE_AUTHORIZATION_SCOPES: Any

class _PaperRouteRetryTransition:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    kind: _PaperRouteRetryKind
    metadata: dict[str, object]

def _safe_int(*args: Any, **kwargs: Any) -> Any: ...
def _safe_text(*args: Any, **kwargs: Any) -> Any: ...
def _symbols_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _target_symbols(*args: Any, **kwargs: Any) -> Any: ...
def _target_plan_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _target_lineage_strategy_names(*args: Any, **kwargs: Any) -> Any: ...
def _target_has_bounded_source_collection_authorization(
    *args: Any, **kwargs: Any
) -> Any: ...
def _target_bounded_collection_authorized(*args: Any, **kwargs: Any) -> Any: ...
def _target_has_bounded_sim_collection_source_kind(
    *args: Any, **kwargs: Any
) -> Any: ...
def _bounded_sim_collection_blockers(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_sim_collection_account_audit_blockers(
    *args: Any, **kwargs: Any
) -> Any: ...
def _without_lineage_text_values(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_sim_collection_target_with_runtime_account_audit(
    *args: Any, **kwargs: Any
) -> Any: ...
def _bounded_sim_collection_runtime_account_aliases(
    *args: Any, **kwargs: Any
) -> Any: ...
def _bounded_sim_collection_authorized(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_sim_collection_reserves_account(*args: Any, **kwargs: Any) -> Any: ...
def _target_owns_bounded_sim_collection_account(*args: Any, **kwargs: Any) -> Any: ...
def _target_runtime_account_matches(*args: Any, **kwargs: Any) -> Any: ...
def _target_active_in_window(*args: Any, **kwargs: Any) -> Any: ...
def _target_plan_has_active_bounded_sim_collection_owner(
    *args: Any, **kwargs: Any
) -> Any: ...
def _target_requires_bounded_sim_collection_gate(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_sim_collection_metadata_from_decision(
    *args: Any, **kwargs: Any
) -> Any: ...
def _target_lookup_names(*args: Any, **kwargs: Any) -> Any: ...
def _strategy_lookup_names(*args: Any, **kwargs: Any) -> Any: ...
def _parse_target_datetime(*args: Any, **kwargs: Any) -> Any: ...
def _mapping_value(*args: Any, **kwargs: Any) -> Any: ...
def _decimal_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _text_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _target_metadata_quote_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def _quote_snapshot_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _quote_snapshot_matches_symbol(*args: Any, **kwargs: Any) -> Any: ...
def _snapshot_has_executable_quote(*args: Any, **kwargs: Any) -> Any: ...
def _target_probe_window(*args: Any, **kwargs: Any) -> Any: ...
def _target_missing_explicit_probe_window(*args: Any, **kwargs: Any) -> Any: ...
def _target_probe_action(*args: Any, **kwargs: Any) -> Any: ...
def _target_probe_cap(*args: Any, **kwargs: Any) -> Any: ...
def _target_probe_exit_minute_after_open(*args: Any, **kwargs: Any) -> Any: ...
def _target_strategy_family_tokens(*args: Any, **kwargs: Any) -> Any: ...
def _target_requires_balanced_pair_legs(*args: Any, **kwargs: Any) -> Any: ...
def _target_probe_symbol_actions(*args: Any, **kwargs: Any) -> Any: ...
def _target_probe_symbol_quantities(*args: Any, **kwargs: Any) -> Any: ...

class _TargetProbeQuantityResolution:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    qty: Decimal
    audit: dict[str, Any]
    price_params: dict[str, Any]

def _target_probe_symbol_notional_budget(*args: Any, **kwargs: Any) -> Any: ...
def _quote_snapshot_reference_price(*args: Any, **kwargs: Any) -> Any: ...
def _target_pair_balance_state(*args: Any, **kwargs: Any) -> Any: ...
def _target_truthy(*args: Any, **kwargs: Any) -> Any: ...
def _target_bool(*args: Any, **kwargs: Any) -> Any: ...
def _lineage_text_values(*args: Any, **kwargs: Any) -> Any: ...
def _merge_unique_texts(*args: Any, **kwargs: Any) -> Any: ...
def _single_lineage_text(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_probe_lineage_from_params(*args: Any, **kwargs: Any) -> Any: ...
def _paper_route_probe_entry_metadata(*args: Any, **kwargs: Any) -> Any: ...
def _target_notional_sizing_audit_from_params(*args: Any, **kwargs: Any) -> Any: ...
def _bounded_collection_decision_requires_target_notional_sizing(
    *args: Any, **kwargs: Any
) -> Any: ...
def _bounded_paper_route_collection_entry_metadata(
    *args: Any, **kwargs: Any
) -> Any: ...
def _strategy_signal_paper_entry_metadata(*args: Any, **kwargs: Any) -> Any: ...
def _lineage_target_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
def _lineage_target_key(*args: Any, **kwargs: Any) -> Any: ...
def _merge_paper_route_probe_lineage(*args: Any, **kwargs: Any) -> Any: ...
def _optional_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _first_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _executable_bid_ask_present(*args: Any, **kwargs: Any) -> Any: ...
def _min_optional_decimal(*args: Any, **kwargs: Any) -> Any: ...
def _simple_drift_feature_thresholds(*args: Any, **kwargs: Any) -> Any: ...
def _simple_drift_thresholds(*args: Any, **kwargs: Any) -> Any: ...
def _pct_cap_to_notional(*args: Any, **kwargs: Any) -> Any: ...
def _simple_decision_notional(*args: Any, **kwargs: Any) -> Any: ...
def _simple_buying_power_consumption(*args: Any, **kwargs: Any) -> Any: ...

PAPER_ROUTE_PROBE_QTY_STEP: Any

class TargetProbeQuantityResolution:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    qty: Decimal
    audit: dict[str, Any]
    price_params: dict[str, Any]

def bounded_collection_decision_requires_target_notional_sizing(
    *args: Any, **kwargs: Any
) -> Any: ...
def bounded_paper_route_collection_entry_metadata(*args: Any, **kwargs: Any) -> Any: ...
def bounded_sim_collection_metadata_from_decision(*args: Any, **kwargs: Any) -> Any: ...
def decimal_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
def executable_bid_ask_present(*args: Any, **kwargs: Any) -> Any: ...
def first_decimal(*args: Any, **kwargs: Any) -> Any: ...
def mapping_value(*args: Any, **kwargs: Any) -> Any: ...
def min_optional_decimal(*args: Any, **kwargs: Any) -> Any: ...
def optional_decimal(*args: Any, **kwargs: Any) -> Any: ...
def paper_route_probe_entry_metadata(*args: Any, **kwargs: Any) -> Any: ...
def parse_target_datetime(*args: Any, **kwargs: Any) -> Any: ...
def pct_cap_to_notional(*args: Any, **kwargs: Any) -> Any: ...
def quote_snapshot_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
def quote_snapshot_reference_price(*args: Any, **kwargs: Any) -> Any: ...
def safe_int(*args: Any, **kwargs: Any) -> Any: ...
def safe_text(*args: Any, **kwargs: Any) -> Any: ...
def simple_buying_power_consumption(*args: Any, **kwargs: Any) -> Any: ...
def simple_decision_notional(*args: Any, **kwargs: Any) -> Any: ...
def snapshot_has_executable_quote(*args: Any, **kwargs: Any) -> Any: ...
def target_metadata_quote_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def target_notional_sizing_audit_from_params(*args: Any, **kwargs: Any) -> Any: ...
def target_plan_symbols(*args: Any, **kwargs: Any) -> Any: ...
def target_probe_cap(*args: Any, **kwargs: Any) -> Any: ...
def target_probe_symbol_actions(*args: Any, **kwargs: Any) -> Any: ...
def target_probe_symbol_notional_budget(*args: Any, **kwargs: Any) -> Any: ...
def target_probe_symbol_quantities(*args: Any, **kwargs: Any) -> Any: ...
def target_symbols(*args: Any, **kwargs: Any) -> Any: ...
def text_from_mapping(*args: Any, **kwargs: Any) -> Any: ...
