apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - generated
images:
  - name: registry.ide-newton.ts.net/lab/docs
    digest: sha256:1bf2e70c49012b4f60a6404aca12a52254559d700224fa3f574ea0a268f23cf1
    newName: registry.ide-newton.ts.net/lab/docs
