apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - generated
images:
  - name: registry.ide-newton.ts.net/lab/docs
    digest: sha256:6ec1bebaca80b5469c82f86bdb6f161a5465a4faa88641c743498f1874b6d666
    newName: registry.ide-newton.ts.net/lab/docs
