apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- generated
images:
- name: registry.ide-newton.ts.net/lab/docs
  digest: sha256:53b73dbb8c8d1a11bb18175bd44f4b23f2453c0f9c620c94565b9975b990edd5
