from __future__ import annotations

# pyright: reportMissingImports=false, reportMissingTypeStubs=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownParameterType=false, reportUnknownLambdaType=false, reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false, reportUndefinedVariable=false, reportUnsupportedDunderAll=false, reportAttributeAccessIssue=false, reportUntypedBaseClass=false, reportGeneralTypeIssues=false, reportInvalidTypeForm=false, reportReturnType=false, reportOptionalMemberAccess=false, reportArgumentType=false, reportCallIssue=false, reportPrivateUsage=false, reportUnnecessaryComparison=false, reportUnnecessaryCast=false
# ruff: noqa: F401,F403,F405,F811,F821
from typing import Any
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence, cast
from app.trading.discovery.hypothesis_cards import (
    HypothesisCard,
    build_hypothesis_cards,
)

MECHANISM_CLAIM_TYPES: Any
FEATURE_RECIPE_CLAIM_TYPES: Any
FEATURE_BLOCKER_CLAIM_TYPES: Any
FEATURE_FIELD_KEYS: Any
FEATURE_BLOCKER_RELATION_TYPES: Any
RISK_VALIDATION_CLAIM_TYPES: Any
RISK_VALIDATION_RELATION_TYPES: Any

class WhitepaperResearchSource:
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    run_id: str
    title: str
    source_url: str
    published_at: str
    claims: tuple[Mapping[str, Any], ...]
    claim_relations: tuple[Mapping[str, Any], ...]
    def to_payload(*args: Any, **kwargs: Any) -> Any: ...

RECENT_WHITEPAPER_SEEDS: tuple[WhitepaperResearchSource, ...]

def _string(*args: Any, **kwargs: Any) -> Any: ...
def _strings_from_value(*args: Any, **kwargs: Any) -> Any: ...
def _claim_type(*args: Any, **kwargs: Any) -> Any: ...
def _claim_text(*args: Any, **kwargs: Any) -> Any: ...
def _relation_type(*args: Any, **kwargs: Any) -> Any: ...
def _claim_feature_terms(*args: Any, **kwargs: Any) -> Any: ...
def _has_mechanism(*args: Any, **kwargs: Any) -> Any: ...
def _has_feature_recipe_or_blocker(*args: Any, **kwargs: Any) -> Any: ...
def _has_risk_validation_constraint(*args: Any, **kwargs: Any) -> Any: ...
def claim_subgraph_blockers(*args: Any, **kwargs: Any) -> Any: ...
def compile_sources_to_hypothesis_cards(*args: Any, **kwargs: Any) -> Any: ...
def source_from_payload(*args: Any, **kwargs: Any) -> Any: ...
def sources_from_jsonl(*args: Any, **kwargs: Any) -> Any: ...
