apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-ingress
resources:
  - external-gateway.yaml
helmCharts:
  - name: gateway
    repo: https://blob.istio.io/istio-release/charts
    version: 1.31.0
    releaseName: gateway
    namespace: istio-ingress
    valuesInline:
      service:
        loadBalancerIP: "100.100.244.182"
